### ISSUE TITLE
Azure: UnsupportedQueryParameter Error

### ISSUE THREAD

**Issue by dharmab** [vmware-tanzu/velero#516] opened 2018-05-24 18:09 UTC
I'm trying to get Ark running on Azure using the configuration documented [here](https://heptio.github.io/ark/v0.8.1/azure-config).

I get the following error in the Ark pod logs:

```
time="2018-05-24T18:07:04Z" level=error msg="error listing backups" error="rpc error: code = Unknown desc = storage: service returned error: StatusCode=400, ErrorCode=UnsupportedQueryParameter, ErrorMessage=One of the query parameters specified in the request URI is not supported.\nRequestId:240c2adc-201e-0019-5f8a-f3dcf5000000\nTime:2018-05-24T18:07:04.2800504Z, RequestInitiated=Thu, 24 May 2018 18:07:03 GMT, RequestId=240c2adc-201e-0019-5f8a-f3dcf5000000, API Version=2016-05-31, QueryParameterName=delimiter, QueryParameterValue=" logSource="pkg/controller/backup_sync_controller.go:78"
```

**Comment by jcrowthe** [comment] 2018-05-30 22:15
@skriss I think ark on Azure is currently broken due to this bug. Can I get an update on this too?

**Comment by ncdc** [comment] 2018-05-30 22:17
@jcrowthe we'll try to get some assistance from the Azure team and get back ASAP.

**Comment by squillace** [comment] 2018-05-30 22:39
@jimzim is defs the person to look, although he's with a customer at the moment. We'll follow up. We want this to work nicely. :-)

**Comment by jcrowthe** [comment] 2018-05-30 22:46
@squillace @skriss Thanks, much appreciated!

**Comment by ncdc** [comment] 2018-05-31 01:04
I've been testing the following:

```go
package andy

import (
	"os"
	"testing"

	"github.com/heptio/ark/pkg/cloudprovider/azure"
	"github.com/stretchr/testify/require"
)

func TestAzureDelimiter(t *testing.T) {
	o := azure.NewObjectStore()
	os.Setenv("AZURE_STORAGE_ACCOUNT_ID", "...")
	os.Setenv("AZURE_STORAGE_KEY", "...")
	err := o.Init(nil)
	require.NoError(t, err)

	prefixes, err := o.ListCommonPrefixes("ark", `/`)
	require.NoError(t, err)
	for _, p := range prefixes {
		t.Logf("prefix: %v", p)
	}
}
```

This is essentially what we're calling, and it's working for me. I did notice that the error message seems to indicate that instead of `/`, the delimiter is `"` (a quote). I have tried different values for the delimiter, including the empty string and `"`, and everything succeeds.

Still trying to figure out the root cause.

@jcrowthe @dharmab what location(s) are you using for your resource groups that have the blob storage container for Ark?

**Comment by ncdc** [comment] 2018-05-31 01:20
Oops, I misread the `"` as the value for delimiter, but that appears to be the closing quote for the `error` field in our structured log message. That would indicate the value is the empty string / missing, I imagine.

**Comment by jcrowthe** [comment] 2018-05-31 17:14
@ncdc `eastus2` is the primary region, although others may be affected as well, I'm not sure.

**Comment by ncdc** [comment] 2018-06-04 14:00
Just keeping everyone up to date - I have been unable to reproduce this, and I've chatted with @jcrowthe on Slack about it. He's going to retry and see if it works, or if we need to dig further.

**Comment by dharmab** [comment] 2018-06-04 20:43
Hmm, I'm consistently reproducing the error. I've run through the getting started guide again (to double check any formatting errors) and have also tried v0.8.2.

I'm starting to suspect that something about my specific cloud credentials is causing a problem, such as a special character.

**Comment by ncdc** [comment] 2018-06-04 20:44
@dharmab can you test the code snippet I pasted above?

**Comment by ncdc** [comment] 2018-06-26 14:00
@dharmab @jcrowthe any updates on this - were you able to get it working?

**Closed as completed** 2018-07-06 14:27 UTC
Labels: Area/Cloud/Azure
