### ISSUE TITLE
Data not getting restored on the web browser after restore

### ISSUE THREAD

**Issue by surekhakallam** [vmware-tanzu/velero#2417] opened 2020-04-11 13:38 UTC
we are trying to restore pods and pvs which we have on a vsphere vm's but they are not able to restore that back

we took backup after we added few data on to the browser and then after backup is completed successfully .. we added some data again on the browser ... and then we deleted the pod and respective pvc's and pv's .... and deleted the respective data files on the respective node where the pod is deployed... and then restored it .. the pods and respective pvc and pv have got restored successfully , but the data on the browser has not stored 

the status of both backup and restore is " completed" state as expected

anything else to be specially added in this case .. can you please guide me

**Comment by skriss** [comment] 2020-04-13 14:18
this looks like a dupe of #2418, closing this one out.

**Closed by skriss** 2020-04-13 14:18 UTC
Labels: Duplicate
