### ISSUE TITLE
Velero backup stays in progress after OOMkilled 

### ISSUE THREAD

**Issue by peterbosalliandercom** [vmware-tanzu/velero#4503] opened 2022-01-07 08:33 UTC
**What steps did you take and what happened:**
In our cluster the velero pod (Kubernetes) runs each night 0:00 hour a scheduled backup . We found that when the velero pod is restarting because of lack of memory (oomkilled) the backup never finishes, and stays in progress:

status:
  expiration: '2022-02-06T00:00:33Z'
  phase: InProgress
  startTimestamp: '2022-01-07T00:00:33Z'
  version: 1

values.yaml settings:
  backupsEnabled: true
    backupStorageLocation:
      name: aws
      bucket: xxxxxxxxxx
  schedules:
    mybackup:
      schedule: "0 0 * * *" # run at midnight
      template:
        ttl: "720h" # keep 30 days

**What did you expect to happen:**
We expect that velero fails the running job instead of keeping it in progress.

**Environment:**
- Velero version (use `velero version`): 1.3.0

**Comment by sseago** [comment] 2022-01-07 19:37
Currently, in-progress backups are never resumed on velero pod restart. A velero backup must run start to finish in a single pod run in order to complete. I"m not sure what the future plans are around this limitation, but at the moment, the only thing that can be done to work around it would be to delete the backup and screate a new one.

**Comment by reasonerjt** [comment] 2022-01-12 11:06
We may consider to fix it as we refactor the controller via kubebuilder, such that the controller can update the status on startup by comparing the actual and desired state.

**Comment by eleanor-millman** [comment] 2022-01-19 20:28
Additional explanation from a Velero dev that helped me understand this better: If a backup is in process and the Velero server pod is restarted (in this example, it ran out of memory and was killed and restarted), the backup stays in progress but Velero can’t continue to work on it because it can’t start work again on a backup already in progress.  Several possibilities to fix this. One is to make the backup tolerant of restarts. But simpler might be to mark the backup as failed.

**Comment by brnck** [comment] 2022-02-21 11:46
What makes the situation more difficult is that it is hard to automatically check when such behaviour happens. 

Let's say I have scheduled backups that run once a day. I don't know when OOM happens if don't monitor OOMs in general in my cluster. I thought about monitoring metrics exposed by Velero. Ideally, I would want to check how many backups are in state "InProgress" or perform calculations on several metrics to evaluate if there are any backups not in the completed state longer than they should. 

The problem is that OOM also clears some metrics as well. F.i.
* velero_backup_attempt_total
* velero_backup_success_total

Only **velero_backup_total** and **velero_backup_last_successful_timestamp** survives restarts.

Therefore, I need to check manually whether the pod had OOM and if yes, remove any InProgress backups and schedule a new one.

**Comment by cedricve** [comment] 2022-03-07 10:47
we are running scheduled backups every 6 hours, and we have them failing random. Some backups in the morning stay idle in InProgress, the next run was Completed, etc. We are using the latest Velero chart.

**Comment by sseago** [comment] 2022-03-07 13:54
I think this problem may have a quicker short-term fix and a longer-term more substantial change. Ideally we'd want Velero to be able to pick up a backup in-progress and finish it if the pod gets restarted. This is presumably a substantial undertaking which would make sense to look into as part of an overall controller refactoring. 

However, we may be able to put a shorter-term fix in place. Upon velero pod start, any "InProgress" backups or restores could be updated to "Failed" with a backup or restore error message indicating that it failed because the Velero pod was killed, so the user would need to recreate the backup or restore. This wouldn't completely solve the problem, but it would give a much more accurate view to the user, since the backup or restore is no longer in progress -- it actually failed to complete, but the status will never update to indicate that.

**Comment by ywk253100** [comment] 2022-04-28 01:03
The short-term fix is included in https://github.com/vmware-tanzu/velero/pull/4833 and is already merged. I'll move this issue out of scope v1.9.0

**Comment by kaovilai** [comment] 2023-09-21 21:08
This issue should close as issue title is no longer the case after https://github.com/vmware-tanzu/velero/pull/4833

For tracking resuming backup after restart we can use https://github.com/vmware-tanzu/velero/issues/6710

**Closed** 2023-11-17 02:16 UTC
Labels: limitation
