### ISSUE TITLE
Activity Logs in Storage Account for AKS installed in velero

### ISSUE THREAD

**Issue by hitesh1907nayyar** [vmware-tanzu/velero#4777] opened 2022-03-27 08:06 UTC
Hi, 

Installed velero on AKS with azure storage account plugin. Installation is successful but having issues after checking the activity logs of the storage account . 

Below logs are being published every minute. Functionality wise there is no impact but why these logs are published every min can someone please provide an answer. Right column is the name of service principal.

As per these activity logs,  service principal is listing azure storage  account details per minute. It this feature by design  or we can modify this

Event Initiated by 
![Activity log](https://user-images.githubusercontent.com/42111008/160272668-3f7b61be-a6ae-4a15-80dc-6735fef99866.png)

**Comment by ywk253100** [comment] 2022-03-28 01:41
It's by design. Velero tries to sync backups from the backup storage location every minute.

Every running of the syncing triggers once running of the Azure plugin, and the Azure plugin lists the storage account keys for auth

**Comment by ywk253100** [comment] 2023-01-04 08:26
I'm closing this issue as it is by design at this moment.
The behavior will change after https://github.com/vmware-tanzu/velero/issues/4267 is fixed.

**Closed by ywk253100** 2023-01-04 08:26 UTC
Labels: Area/Cloud/Azure, kind/question, 1.11-candidate
