### ISSUE TITLE
Http request is redirected to original NodePort after service is restored with a new NodePort

### ISSUE THREAD

**Issue by DanielXiao** [vmware-tanzu/velero#2689] opened 2020-07-04 00:35 UTC
**What steps did you take and what happened:**
1. Deploy wordpress with service type NodePort, and login it through NodePort to add some posts.
```
NAME                                   READY   STATUS    RESTARTS   AGE
pod/wordpress-9b7dfb89f-wcszk          1/1     Running   0          103s
pod/wordpress-mysql-67df859d84-ghqnp   1/1     Running   0          103s

NAME                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
service/wordpress         NodePort    100.65.89.248   <none>        80:32050/TCP   103s
service/wordpress-mysql   ClusterIP   None            <none>        3306/TCP       103s
```

2. Backup the whole namespace.
`velero backup create wordpress-1 --include-namespaces blog`

3. Restore wordpress-1 to another Kubernetes cluster.
`velero restore create --from-backup wordpress-1`

4. Check the new NodePort has changed from 32050 to 31783.
```
AME                                   READY   STATUS    RESTARTS   AGE
pod/wordpress-9b7dfb89f-wcszk          1/1     Running   0          107s
pod/wordpress-mysql-67df859d84-ghqnp   1/1     Running   0          107s

NAME                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
service/wordpress         NodePort    100.71.21.231   <none>        80:31783/TCP   107s
service/wordpress-mysql   ClusterIP   None            <none>        3306/TCP       107s
```

5. Send request to the wordpress serivce in the new cluster and it redirects to the port of the original NodePort 32050.
```
root@localhost:~/velero# curl -v http://10.199.17.22:31783
* Rebuilt URL to: http://10.199.17.22:31783/
*   Trying 10.199.17.22...
* Connected to 10.199.17.22 (10.199.17.22) port 31783 (#0)
> GET / HTTP/1.1
> Host: 10.199.17.22:31783
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Date: Fri, 03 Jul 2020 23:59:51 GMT
< Server: Apache/2.4.10 (Debian)
< X-Powered-By: PHP/5.6.32
< Location: http://10.199.17.22:32050/
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< 
* Connection #0 to host 10.199.17.22 left intact
```

6. Edit the service by changing Node Port to 32050 then it works well.

**What did you expect to happen:**
No redirection to the original NodePort.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

Logs: https://gist.github.com/DanielXiao/c58dba8331e62d8128823ca5197eae3a

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

According to the service backup resource file, nodePort is 32050. I guess velero is trying to restore the service with original port 32050 but fails, so Kubernetes allocates a new port 31783.
```
{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"wordpress\"},\"name\":\"wordpress\",\"namespace\":\"blog\"},\"spec\":{\"ports\":[{\"port\":80}],\"selector\":{\"app\":\"wordpress\",\"tier\":\"frontend\"},\"type\":\"NodePort\"}}\n"},"creationTimestamp":"2020-07-03T23:50:21Z","labels":{"app":"wordpress"},"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:externalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":80,\"protocol\":\"TCP\"}":{".":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{".":{},"f:app":{},"f:tier":{}},"f:sessionAffinity":{},"f:type":{}}},"manager":"kubectl","operation":"Update","time":"2020-07-03T23:50:21Z"}],"name":"wordpress","namespace":"blog","resourceVersion":"221297","selfLink":"/api/v1/namespaces/blog/services/wordpress","uid":"38fe084e-9c06-478e-8ffd-fef976a2dc5b"},"spec":{"clusterIP":"100.65.89.248","externalTrafficPolicy":"Cluster","ports":[{"nodePort":32050,"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"wordpress","tier":"frontend"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
```

**Environment:**

- Velero version (use `velero version`): 
```
Client:
        Version: v1.4.0
        Git commit: 5963650c9d64643daaf510ef93ac4a36b6483392
Server:
        Version: v1.4.0
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2+vmware.1", GitCommit:"9da25ece4c3bd1aa2e9c77ba28f92dbfe3945dcb", GitTreeState:"clean", BuildDate:"2020-05-08T00:46:39Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2+vmware.1", GitCommit:"9da25ece4c3bd1aa2e9c77ba28f92dbfe3945dcb", GitTreeState:"clean", BuildDate:"2020-05-07T18:49:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: Cluster API
- Cloud provider or hardware configuration: vSphere
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by nrb** [comment] 2020-07-15 22:42
Hi @DanielXiao, you're right that Velero makes an attempt to use the original NodePort if one is defined in the `last-applied-configuration` annotation, but it's not always successful.

I find it interesting that the new NodePort is doing redirection, though. I will give this a test as I haven't seen that behavior before - usually, when NodePort restore failure happens, the Service can't be restored at all.

**Comment by nrb** [comment] 2020-10-22 16:35
@DanielXiao After spending time inspecting the Kubernetes service code, I'm not seeing anything in Kubernetes itself that redirects remapped NodePorts. I also can't reproduce this on a GCP cluster.

Were you using a VMware distribution with NSX-T by any chance? Perhaps that cloud provider implementation is doing the redirect.

**Comment by carlisia** [comment] 2020-11-12 00:54
Since it's been a while, I'm closing this issue. @DanielXiao feel free to reopen with the information requested if you are still having issues.

**Closed by carlisia** 2020-11-12 00:54 UTC
Labels: Kubernetes Resources, Needs info, Needs investigation

**Comment by DanielXiao** [comment] 2020-11-12 02:11
@nrb Sorry for the late reply, I was not aware your reply. My test was performed on TKG multi-cloud v1.1.0 and Calico is the 
 deployed CNI. It can always reproduce.

**Comment by TheNewStellW** [comment] 2023-08-14 06:55
Sorry for the 3 year late reply here, but I think issue is with Wordpress image and its default configs. When you deploy Wordpress without specifying the Wordpress URL or Site Address URL the NodePort IP and Port will be embedded in the settings, that's why it continues redirecting.

As @nrb already mentioned, you need to modify the restored Service to use the original port that Wordpress is redirecting you to.
