### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by SergioTeco** [vmware-tanzu/velero#3874] opened 2021-06-15 00:45 UTC
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

https://velero.io/docs/master/api-types/volumesnapshotlocation/

PAGE NOT FOUND

**Comment by zubron** [comment] 2021-06-15 01:24
Hi 👋 where did you get this link? If some of our documentation has this broken link, we will need to know the location so we can fix it :)

**Comment by reasonerjt** [comment] 2021-07-06 01:59
I believe this is caused by branch renaming, this link works:
https://velero.io/docs/main/api-types/volumesnapshotlocation/

I'm closing this issue.

**Closed by reasonerjt** 2021-07-06 01:59 UTC
Labels: Needs info
