### ISSUE TITLE
allow for kustomize customizations before objects are restored

### ISSUE THREAD

**Issue by grozan** [vmware-tanzu/velero#2090] opened 2019-12-02 16:13 UTC
**Describe the problem/challenge you have**
let's take a cluster migration scenario. A workload is to be moved from clusterA to clusterB.
That workload uses "things" which are not available (or simply different) on clusterB.

Examples would be:
- pods with NFS volumes. The NFS paths are different between the DEV and TEST clusters
- private registries, which are different between DEV and TEST
This kind of things.

Basically a backup taken on clusterA cannot be restored on clusterB unless the restored YAML is edited first, to update those few fields. In velero the restore happens as being in progress. a `kubectl get pods` shows the restored pod cannot start.

**Describe the solution you'd like**
in the restore command, I'd like to be able to specify some customization to be applied to the YAML before it gets pushed to the cluster. Kustomize being kind of built-in, I guess it would be good candidate.
so the restore command would look something like
`velero restore create --from-backup <BACKUP-NAME> --kustomize /path/to/overlays/folder`

**Comment by skriss** [comment] 2019-12-02 17:37
xref #474

**Comment by debianmaster** [comment] 2020-01-09 04:16
@skriss    is this being worked on by anyone?   we would like to join hands and contribute to this.

**Comment by skriss** [comment] 2020-01-10 16:45
@debianmaster nobody's actively working on this right now - it would be great if you wanted to pick it up! Did you have any ideas about how to go about implementing yet?

Usually for a feature of this size, we write up a brief design doc first to make sure everyone's in agreement about the approach.  The document template is [here](https://github.com/vmware-tanzu/velero/blob/master/design/_template.md) and you can see some past docs in that directory as well.

**Comment by debianmaster** [comment] 2020-01-13 07:39
@skriss  we are currently exploring kustomize based approach like suggested in thread.   we will do some initial study and come up with doc

**Comment by sseago** [comment] 2020-01-14 00:01
It seems like there's a fair amount of overlap between the proposed --kustomize functionality and what's currently being done with plugins. We are currently doing similar things to this with plugins -- registry paths, PV differences on restore, etc. Maybe the difference is that you'd write a plugin if there's some sort of logic that will always apply in terms of what you want to change on restore, and the kustomize approach would be used when the changes are determined based on user input at restore time. We do need to make sure these two things don't step on each other. For example, would the kustomize changes be applied *after* plugins run (which means the kustomize user input would need to know about the post-plugin view of the resources), or *before* they run (in which case the plugins would need to understand that they're looking at post-kustomize resources?

**Comment by skriss** [comment] 2020-01-17 19:46
@sseago yeah, you make good points about the overlap and we'd definitely need to figure those things out. In my mind, the goal is to have a lighter-weight way to apply changes to the objects being restored, that doesn't require writing and deploying a containerized go binary.  But I'm guessing that for more complex scenarios, plugins may still be required.

**Comment by eleanor-millman** [comment] 2021-05-10 20:36
Closing because duplicate of #474

**Closed by eleanor-millman** 2021-05-10 20:36 UTC
Labels: Enhancement/User, P2 - Long-term important, Reviewed Q2 2021
