### ISSUE TITLE
podvolumerestore controller to handle different uploader-types

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#5096] opened 2022-07-05 08:36 UTC
Make sure the podvolumerestore controller will trigger different code path based on the uploader-type of the CR.

**Comment by Yggdrasil** [comment] 2022-07-30 23:28
Duplicate of https://github.com/vmware-tanzu/velero/issues/5095

**Closed** 2022-09-05 02:19 UTC
Labels: area/kopia-integration
