### ISSUE TITLE
⚠️ If you are running against the main branch

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#2747] opened 2020-07-22 14:57 UTC
There has been some changes to the Velero CRDs. Depending on when you installed Velero, you might not have picked up the changes. 

You may run the command below to update without any concern for messing up your install:

`velero install --crds-only --dry-run -o yaml | kubectl apply -f -`

**Comment by nrb** [comment] 2020-07-22 17:44
Is this a duplicate of #2717?

**Comment by carlisia** [comment] 2020-07-22 17:47
I didn't think so, this is meant as a temporary warning with a specific instruction of what to do until 1.5 is released, or maybe even longer than that for people who didn't upgrade.

**Comment by ashish-amarnath** [comment] 2020-08-25 23:15
Now that we've shipped the 1.5 beta. Should we close this out?

**Comment by nrb** [comment] 2020-08-26 17:13
This seems like it would be an ongoing concern against `main` whenever fields are added to the CRDs.

I think it's something we should add to developer documentation, but maybe not be a pinned issue. What do others think of that?

**Comment by ashish-amarnath** [comment] 2020-08-26 17:27
+1 for adding doc and not having it be a pinned issue.
Maybe just changing the background of this banner on our website should do?
![image](https://user-images.githubusercontent.com/22872138/91336399-ae0ddf00-e786-11ea-9da6-98379f9c9764.png)

**Comment by carlisia** [comment] 2020-08-26 17:29
Yes, good idea. I think adding this warning to the end of the text in the banner for "main" will be perfect.

**Comment by nrb** [comment] 2020-08-26 17:47
@ashish-amarnath I'm not sure I understand what you mean about the background - how does it relate to running this command?

I'm not sure about adding specific commands to the `main` banner...I was more thinking the https://velero.io/docs/v1.4/development/ page. My fear is we'll stuff the warning banner full of messages, and it will get super long.

**Comment by ashish-amarnath** [comment] 2020-08-26 17:51
My intention was to draw attention to the warning to convey to our users using the `main` version of the docs can result in a bumpy ride.
I believe your intention is to update the development doc w/ instructions on how to deploy from main.
I am +1 on updating the development docs too.

**Comment by nrb** [comment] 2020-10-22 17:18
Echoing my previous comment, this is something I would like to get in developer documentation and then close out this issue. I'm going to put a v1.6.0 milestone on it.

**Comment by a-mccarthy** [comment] 2021-04-22 14:55
to summarize, we want add a note to this page, https://velero.io/docs/main/development/, saying that if you are running/developing from the main branch there may be some inconstancies in Velero CRDs as changes are made during a release cycle and then recommend that folks run the command to install the new crds? 

`velero install --crds-only --dry-run -o yaml | kubectl apply -f -`

Do we want to add this to the 1.7 milestone?

**Comment by carlisia** [comment] 2021-04-27 16:42
@a-mccarthy yes please. Would you be able to take this on? At the very least we need to have an issue for it.

@eleanor-millman you may go ahead and close this.

**Comment by carlisia** [comment] 2021-04-27 16:43
Rather: we don''t need to close it. Let's reuse if for the doc change. But I think it can be unpinned.

**Closed** 2021-05-12 19:41 UTC
Labels: Area/Documentation, Public Announcement, Reviewed Q2 2021
