### ISSUE TITLE
Document known issue: Restore of resources with Admission Webhooks

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#4847] opened 2022-04-19 19:37 UTC
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
A frequently asked questions and notes around velero's limited ability to resolve admission webhook issues without support by the workload itself.

For example, Knative resources may not restore properly with velero.
https://github.com/knative/serving/issues/10926
IBM AppConnect may fail validating admission webhook upon restoring to a different version.
https://github.com/openshift/oadp-operator/issues/538
There have been [other closed issues](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+admission+webhook+is%3Aclosed) around the topic.

There are many other workloads which have an admission webhook actively working against velero restore. We cannot document them all but we should document that Velero cannot always handle these and a plugin or changes to the workload will be required. Setting expectation with what velero can and cannot do may reduce future issue volumes.

The solutions suggested in past issues include [creating a plugin](https://github.com/vmware-tanzu/velero/issues/4572).

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment] 2023-01-03 17:31
I think a challenge is that there can be arbitrary code in the admission webhook, and working around the issue is really a case-by-case thing.

It won't be very helpful if we just add a couple of sentences acknowledging this is known issue and let the user figure out themselves.

**Comment by kaovilai** [comment] 2023-01-03 18:09
> Shall we just add a couple of sentences acknowledging this is a known issue and let the user figure it out themselves?
That would work. And/or a table of known issues/resolutions that are either maintained (best-effort) by velero community or by the vendors of those workloads.

**Comment by kaovilai** [comment] 2023-01-03 18:10
Should probably be in troubleshooting or create a new known issue section.

**Comment by reasonerjt** [comment] 2023-01-10 08:19
@kaovilai sure I'll add another item in trouble shooting section on the website.

ideally we may want to run a script in github action or some script to generate the content of that page automatically

I'll make sure this issue is reflected on the website, and see the automation as a stretch goal for v1.11

**Comment by reasonerjt** [comment] 2023-04-07 02:37
Fixed via #6092

**Closed by reasonerjt** 2023-04-07 02:37 UTC
Labels: Area/Documentation, Needs Product, limitation, backlog
