### ISSUE TITLE
On a misconfigured backupstoragelocation, the velero pod goes into a crashloopbackoff

### ISSUE THREAD

**Issue by marccampbell** [vmware-tanzu/velero#2412] opened 2020-04-10 13:45 UTC
**What steps did you take and what happened:**
I deployed a misconfigured backupstoragelocation (the bucket name had a typo)

**What did you expect to happen:**
Backups destined to this BSL to fail. Or some other error.

But instead, the controller goes into a crashloopbackoff with

```
time="2020-04-10T13:39:23Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-aws kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2020-04-10T13:39:23Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:337" namespace=velero
time="2020-04-10T13:39:23Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:343" namespace=velero
time="2020-04-10T13:39:25Z" level=info msg="Checking existence of Velero custom resource definitions" logSource="pkg/cmd/server/server.go:372"
time="2020-04-10T13:39:25Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:406"
time="2020-04-10T13:39:25Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:413"
An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: rpc error: code = Unknown desc = NoSuchBucket: The specified bucket does not exist
        status code: 404, request id: 584D8BA932599A1C, host id: VT1dI...
```

This makes the issue pretty difficult to debug, and it also breaks backups that are using other backupstoragelocations in the same cluster.

Instead of returning an error and crashing, could velero manager log the error, and remaining running to continue to function for other backup storage locations?

**Comment by skriss** [comment] 2020-04-10 15:06
dupe of #1967 - @carlisia is planning to change how the server & BSL lifecycles work as part of #2202

**Comment by nrb** [comment] 2020-04-10 17:06
PR #2382 is one attempt at fixing this, too. It allows the server to start, but introduces an HTTP endpoint that could pair with a Kubernetes liveness check to see if the server has what it needs.

I don't know if 2382 will get merged ultimately, though.

**Comment by carlisia** [comment] 2020-04-10 19:26
@marccampbell thanks for reporting this. I'm going to close this issue but please follow https://github.com/vmware-tanzu/velero/issues/1967 for updates since this change is in our near term pipeline.

**Closed by carlisia** 2020-04-10 19:26 UTC
