### ISSUE TITLE
Can't disable Restic and use CSI Snapshotter instead - "Skipping snapshot of PVC because volume is being backed up with restic"

### ISSUE THREAD

**Issue by maarsaks** [vmware-tanzu/velero#3638] opened 2021-03-29 20:12 UTC
Hi, I have a problem that makes me sick cause I wasted a whole day on it and no more ideas what's happening.
How to DISABLE restic?

**What steps did you take and what happened:**
I'm trying to make a backup of PVC based on `BlockStorage` and `FilesystemStorage` (Rook-by-Ceph) using `velero-plugin-for-csi` to `ObjectStorage` (Rook-by-Ceph), but in logs of the Velero pod I can see the info:
```
time="2021-03-29T17:36:39Z" level=info msg=
"Skipping snapshot of persistent volume because volume is being backed up with restic."
backup=velero/test99 logSource="pkg/backup/item_backupper.go:423" name=pvc-xxx
namespace= persistentVolume=pvc-xxx resource=persistentvolumes
```
```
Skipping PVC monitoring/data-zabbix-postgresql-0, PV will be backed up using restic%! (EXTRA string=pvc-xxx)"
backup=velero/test cmd=/plugins/velero-plugin-for-csi 
logSource="/go/src/velero-plugin-for-csi/internal/backup/pvc_action.go:92" pluginName=velero-plugin-for-csi.
```
(Here's the code source from the last message: [.../velero-plugin-for-csi/internal/backup/pvc_action.go](https://github.com/vmware-tanzu/velero-plugin-for-csi/blob/main/internal/backup/pvc_action.go))

**What did you expect to happen:**
The backup will be successfully created.

**The output of the following commands will help us better understand what's going on**:

`$ kubectl logs deployment/velero -n velero`
[click](https://gist.github.com/maarsaks/af1a0b8bccda01a8e0fbfb336a01278e)

`$ velero backup describe test99 --details`
[click](https://gist.github.com/maarsaks/3003dc472b0456a1371f8d6aa19478f0)

```
$ velero backup logs test99
Logs for backup "test99" are not available until it's finished processing. 
Please wait until the backup has a phase of Completed or Failed and try again.
```

**Anything else you would like to add:**
- I tried manually:
```
$ velero install \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.0.0,velero/velero-plugin-for-csi:v0.1.0 \
    --bucket backup-storage-0bb9e3c3-f9eb-4cf7-bb66-dcfb17ad2a30 \
    --secret-file ./credentials-velero \
    --use-volume-snapshots=false \
    --backup-location-config region=us-east-1,s3ForcePathStyle="true",s3Url=http://rook-ceph-rgw-my-store.rook-ceph.svc \
    --features=EnableCSI
```
- I tried with Helm:
```
helm install velero vmware-tanzu/velero \
--namespace velero \
--create-namespace \
--set-file credentials.secretContents.cloud=/home/maar/temp/velero/credentials-velero \
--set configuration.provider=aws \
--set configuration.backupStorageLocation.config.s3Url=http://rook-ceph-rgw-my-store.rook-ceph.svc \
--set configuration.backupStorageLocation.config.s3ForcePathStyle=true \
--set configuration.backupStorageLocation.bucket=backup-storage-xxxx \
--set configuration.backupStorageLocation.config.region=us-east-1 \
--set configuration.volumeSnapshotLocation.name=default \
--set configuration.volumeSnapshotLocation.config.region=us-east-1 \
--set configuration.snapshotsEnabled=false \
--set configuration.deployRestic=false \
--set initContainers[0].name=velero-plugin-for-aws \
--set initContainers[0].image=velero/velero-plugin-for-aws:v1.0.0 \
--set initContainers[0].volumeMounts[0].mountPath=/target \
--set initContainers[0].volumeMounts[0].name=plugins \
--set initContainers[1].name=velero-plugin-for-csi \
--set initContainers[1].image=velero/velero-plugin-for-csi:v0.1.0 \
--set initContainers[1].volumeMounts[0].mountPath=/target \
--set initContainers[1].volumeMounts[0].name=plugins
```
- I'm using a correct secret and the bucket name.
- There's no restic deamon or pod after installing Velero with above configs.
- Kubernetes VolumeSnapshots are creating successfully.
- PV doesn't have any restic annotations.

**Environment:**

```
$ velero version
Client:
	Version: v1.5.3
	Git commit: 123109a3bcac11dbb6783d2758207bac0d0817cb
Server:
	Version: v1.5.3
```
```
$ velero client config get features
features: EnableCSI
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
```
- Kubernetes installer & version: `v1.20.4-rancher1-1`
- Cloud provider or hardware configuration: five virtual machine nodes.

**SOME CONFIGS:**
- CSI Snapshotter:
[crds.yaml](https://gist.github.com/maarsaks/050bd5214105f4d1b684d6f29febcd63)
[rbac-csi-snapshotter.yaml](https://gist.github.com/maarsaks/7c11741fe60c8d709a1110c0724ee18a)
[rbac-external-provisioner.yaml](https://gist.github.com/maarsaks/076e793baee5ed47e360e23a59494370)
[setup-csi-snapshotter.yaml](https://gist.github.com/maarsaks/171969ec3a85a200b1b20c5fcc4b8ae2)
[rbac-snapshot-controller.yaml](https://gist.github.com/maarsaks/b7a49918a1821f57d5d663cba5050944)
[snapshot-controller-deployment.yaml](https://gist.github.com/maarsaks/c60734f87ea5e76db5e972d60fa15655)
- Object Storage:
[ceph-object-store-and-storageclass.yaml](https://gist.github.com/maarsaks/6e37427360f8e518c604f1dda38a76e5)
[object-bucket-claim.yaml](https://gist.github.com/maarsaks/eb27b113cdc44576ea8bd315fac6936a)

I have no idea where to even look. Anyway, tommorrow round number two.

**UPDATE_1:**
I exposed the `rook-ceph-rgw-my-store.rook-ceph.svc:80` and now after `velero backup describe test99 --details` there's only `Resource List:  <backup resource list not found> instead of the error.`
But the main problem still exists.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by zubron** [comment] 2021-04-19 16:09
Hi @maarsaks - Sorry you're having issues with this. Can you try running Velero with the versions of the [AWS](https://github.com/vmware-tanzu/velero-plugin-for-aws#compatibility) and [CSI](https://github.com/vmware-tanzu/velero-plugin-for-csi#compatibility) plugins that are compatible with v1.5? For AWS this will be v1.1.0 or later, and for CSI, v0.1.2. I don't know if that is the cause of this issue, but I'd like to verify if it's still an issue with those versions. Thanks!

**Comment by ashish-amarnath** [comment] 2021-04-28 20:56
@maarsaks Can you please share the annotations on the pod that is causing this issue?
The incompatible version of the velero-plugin-for-csi is most likely the reason for the error you are seeing. The incompatibility arising from this change https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/70 that was made.
Sharing the annotations on the pod will be helpful in confirming the root cause.

Upgrading the velero-plugin-for-csi to version `v0.1.2` compatible with Velero `v1.5` should resolve the issue you are seeing.

I am going to close this issue. Please reach out or reopen if you need further assistance.

**Closed by ashish-amarnath** 2021-04-28 20:56 UTC
Labels: Area/CSI, Needs info, Needs investigation, Restic
