### ISSUE TITLE
Velero backup getting stuck "InProgress" 

### ISSUE THREAD

**Issue by viswaselvamazure** [vmware-tanzu/velero#7287] opened 2024-01-08 12:00 UTC
**What steps did you take and what happened:**
Velero backups, whether scheduled or manually triggered, sometimes get stuck in the in progress phase. When I ran velero backup describe I realized that the values of Estimated total items to be backed up: and Items backed up so far: are same, Kopia backup failed. The below command is used for velero install on the cluster.
```
velero install --provider azure \
  --plugins velero/velero-plugin-for-microsoft-azure:v1.8.0 \
  --bucket velero \
  --secret-file credentials-velero.yaml \
  --backup-location-config resourceGroup=,storageAccount= \
  --use-volume-snapshots=false \
  --velero-pod-cpu-limit="0" \
  --velero-pod-mem-limit="0" \
  --velero-pod-mem-request="0" \
  --velero-pod-cpu-request="0" \
  --use-node-agent \
  --privileged-node-agent \
  --default-volumes-to-fs-backup
```

If I open the azure storage account container to verify the backed up files, and check the velero-backup.json file, I can see the below status.
```
"status": {
"version": 1,
"formatVersion": "1.1.0",
"expiration": "2024-02-06T11:21:58Z",
"phase": "FinalizingPartiallyFailed",
"startTimestamp": "2024-01-07T11:21:59Z",
"errors": 1,
"progress": {
"totalItems": 48,
"itemsBackedUp": 48
}
```
But, when I run "Velero get backups" getting the status as InProgress only.

**What did you expect to happen:**

1. Velero should backup all manifests and volumes.

**The following information will help us better understand what's going on**:

[bundle-2024-01-08-06-20-47.tar.gz](https://github.com/vmware-tanzu/velero/files/13859619/bundle-2024-01-08-06-20-47.tar.gz)

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):  1.12.2
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`): Client Version: v1.27.2
                                                                       Kustomize Version: v5.0.1
                                                                       Server Version: v1.27.3
```
Name: veletotest
Namespace: velero
Labels: velero.io/storage-location=default
Annotations: velero.io/resource-timeout=10m0s
velero.io/source-cluster-k8s-gitversion=v1.25.12+26bab08
velero.io/source-cluster-k8s-major-version=1
velero.io/source-cluster-k8s-minor-version=25
Phase: InProgress

Namespaces:
Included: pvc-test2
Excluded:

Resources:
Included: *
Excluded:
Cluster-scoped: auto

Label selector:

Or label selector:

Storage Location: default

Velero-Native Snapshot PVs: auto
Snapshot Move Data: auto
Data Mover: velero

TTL: 720h0m0s

CSISnapshotTimeout: 10m0s
ItemOperationTimeout: 0s

Hooks:

Backup Format Version: 1.1.0

Started: 2023-12-14 10:45:40 +0300 +03
Completed: <n/a>

Expiration: 2024-01-13 10:45:40 +0300 +03

Estimated total items to be backed up: 34
Items backed up so far: 34

Velero-Native Snapshots:

velero backup logs <backupname>
An error occurred: logs for backup "veletotest" are not available until it's finished processing, please wait until the backup has a phase of Completed or Failed and try again 
```

- Kubernetes installer & version: 
- Cloud provider or hardware configuration: Azure Kubernetes Service

- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment] 2024-01-10 03:00
The PVB failed with node-agent "OOM", but the backup was not handled when the PVB was marked as failed.

**Comment by reasonerjt** [comment] 2024-01-15 06:38
> The PVB failed with node-agent "OOM", but the backup was not handled when the PVB was marked as failed.
In this case the backup SHOULD be marked as failed in v1.12.  
Let's double check the root cause.

**Comment by qiuming-best** [comment] 2024-01-15 08:00
@viswaselvamazure the backup `veletotest` you provided is `InProgress`, but I could not find related logs in the bundles.

For the `FinalizingPartiallyFailed` phase backup I find in the logs with the name `all-namespaces-20240103000021`, which is in `PartiallyFailed`.

So could you provide the logs just around the backup is stuck `InProgess`?

**Comment by blackpiglet** [comment] 2024-01-30 05:45
The backup indeed failed with PVB not completed and meet a server restart.
```
"get a podvolumebackup with status \"InProgress\" during the server starting, mark it as \"Failed\"",
```

But the backup should be updated into failed status. The reason it didn't is the kube-apiserver rejected the update request.
It looks like the reason is the Backup CRD was not up-to-date.

```
time="2024-01-07T14:22:13Z" level=error msg="error updating backup's final status" backuprequest=velero/aksbofanidstagingwe001backup controller=backup error="Backup.velero.io \"aksbofanidstagingwe001backup\" is invalid: status.phase: Unsupported value: \"FinalizingPartiallyFailed\": supported values: \"New\", \"FailedValidation\", \"InProgress\", \"Completed\", \"PartiallyFailed\", \"Failed\", \"Deleting\"" logSource="pkg/controller/backup_controller.go:311"
```

**Comment by qiuming-best** [comment] 2024-02-02 06:17
@blackpiglet @viswaselvamazure 
the error is `Unsupported value: \"FinalizingPartiallyFailed\"`
I think because @viswaselvamazure used CRD is older than Velero server version which lead to the patch action failed, then it will lead to `aksbofanidstagingwe001backup` stuck `InProgress`.

**Comment by reasonerjt** [comment] 2024-02-02 09:00
This is likely a usage error.

**Comment by reasonerjt** [comment] 2024-03-13 08:51
Close due to inactivity.

**Closed by reasonerjt** 2024-03-13 08:51 UTC
Labels: Needs info, area/fs-backup, 2024 Q1 reviewed
