### ISSUE TITLE
Concurrency for restic backup

### ISSUE THREAD

**Issue by hibbert** [vmware-tanzu/velero#2078] opened 2019-11-22 21:14 UTC
**Describe the problem/challenge you have**

Our restic backup is very slow. We are backing up over 40 volumes, with not a huge amount of data in. Upon watching the backup it seems like it is not running the volume backups concurrently, it looks like it is doing it one by one in lexicographical order. It's taking 12 hours to complete so we need to bump the timeout again ```--restic-timeout=14h```

**Describe the solution you'd like**
Quicker backups with concurrency

**Anything else you would like to add:**
We have just upgraded to v1.2.0, I don't think this has had a massive impact, it has been getting slower for some time. Are pods are static and don't restart and rename often

**Environment:**

- Velero version (use `velero version`): v1.2.0
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-e9b1d0", GitCommit:"e9b1d0551216e1e8ace5ee4ca50161df34325ec2", GitTreeState:"clean", BuildDate:"2019-09-21T08:33:01Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: EKS
- Cloud provider or hardware configuration: AWS Amazon Linux 2
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment] 2019-12-02 18:17
@hibbert I believe this is a duplicate of #1531 - I'm going to close this out in favor of that existing issue. Please subscribe there as desired!

**Closed by skriss** 2019-12-02 18:17 UTC
