### ISSUE TITLE
Velero 1.9.1 backup timed out waiting for all PodVolumeBackups to complete leaving process consuming 99% CPU running for >5 hours already

### ISSUE THREAD

**Issue by andy108369** [vmware-tanzu/velero#5251] opened 2022-08-26 14:58 UTC
```
$ velero version
Client:
	Version: v1.9.1
	Git commit: e4c84b7b3d603ba646364d5571c69a6443719bf2
Server:
	Version: v1.9.1
```

- Velero restic backup timed out:

```
time="2022-08-26T13:05:40Z" level=error msg="Error backing up item" backup=velero/velero-default-20220826090539 error="timed out waiting for all PodVolumeBackups to complete
```

Leaving a process consuming 99% CPU behind:

```
# ps -ef|grep 'restic backup'
root     2550974 2549993 99 09:05 ?        05:47:31 restic backup ...
```

Is running for more than 5 hours now.

That is the same restic PID which is running after I've lifted the memory limit from `1Gi` to `2Gi` here https://github.com/vmware-tanzu/velero/issues/2073#issuecomment-1228287647

Please advise.

**Comment by blackpiglet** [comment] 2022-08-27 03:38
The PodVolume timeout configuration 240 minutes.
If your backup data is pretty much, you can set the PodVolume timeout by two ways:
* Annotate the backup with "velero.io/pod-volume-timeout". This will take affect on the backup you annotate.
* Set the velero server parameter in Velero deployment with `--restic-timeout <duration>`. This will affect all the backups.

You may need to restart the Restic DaemonSet, if you don't want to wait for the Restic backup process.

Restic process can consume a lot of memory. There are some senarios that Restic would use more than 10G memory. This is one of the reason Velero team is working on integration with Kopia. By now, please only backup the data and volume you needs, and don't backup all volumes in cluster to avoid this situation.

**Comment by andy108369** [comment] 2022-08-27 07:25
Thanks, in my case the memory is not an issue. (it was resolved after I have increased the mem limit from `1Gi` to `2Gi`).

The issue I have is the `restic` process stopped doing anything after reading about `41Gi`, the  symptoms are following:
- no I/O activity - `cat /proc/$(pidof -s restic)/io` - read_bytes / write_bytes have not been changing;
- no network activity other than some attempts connecting to the GCP as seen via `nsenter -n -t $(pidof -s restic) ss -tulpan` -- can't really see the headers since it's TLS;
- process memory consumption significantly dropped below 600MiB (or even way less.. I remember seeing a number starting with 618...k);
- the CPU usage was around 99%;

The PVC it is trying to backup has 8 directories and 8 files:

```
# find /var/lib/kubelet/pods/REDACTED/volumes/kubernetes.io~csi/pvc-REDACTED/mount -type f -ls | awk '{print $7}' | numfmt --to=iec-i
1.2Gi
1.0Gi
29Gi
8.0Gi
772Mi
468Mi
3.9Ti
977Gi
```

The process is now gone, but I kept some traces from that day:

## strace

```
# strace -f -c -p 2550974
## running for about 10 seconds

% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 77.60   22.388267        2150     10409       312 futex           <<<<<<< as you can see most of the time was consumed by futex errors
  9.09    2.623728        1094      2397           read
  6.24    1.800919       30015        60           epoll_pwait
  6.12    1.765238         216      8142           nanosleep
  0.51    0.146219         108      1352         2 rt_sigreturn
  0.31    0.089510          65      1358           tgkill
  0.10    0.028221          20      1358           getpid
  0.02    0.006891          48       141           write
  0.01    0.001809          60        30           sched_yield
  0.00    0.000034          34         1           restart_syscall
------ ----------- ----------- --------- --------- ----------------
100.00   28.850836                 25248       314 total
```

## Locked files
```
# lsof -Pn -p 2550974
COMMAND     PID USER   FD      TYPE DEVICE      SIZE/OFF      NODE NAME
restic  2550974 root  cwd       DIR 252,16          4096         2 /host_pods/REDACTED/volumes/kubernetes.io~csi/pvc-REDACTED/mount
restic  2550974 root  rtd       DIR  0,272          4096  76289175 /
restic  2550974 root  txt       REG  0,272      18472960  76289144 /usr/bin/restic
restic  2550974 root    0r      CHR    1,3           0t0         7 /dev/null
restic  2550974 root    1w     FIFO   0,13           0t0 446326837 pipe
restic  2550974 root    2w     FIFO   0,13           0t0 446326838 pipe
restic  2550974 root    3u     sock    0,9           0t0 446567791 protocol: TCP
restic  2550974 root    4u  a_inode   0,14             0     13989 [eventpoll]
restic  2550974 root    5r     FIFO   0,13           0t0 446309006 pipe
restic  2550974 root    6w     FIFO   0,13           0t0 446309006 pipe
restic  2550974 root   16u      REG  0,272       1056483  76289146 /tmp/restic-temp-pack-1594035339 (deleted)
restic  2550974 root   55r      REG 252,16 1048576000000   4194306 /host_pods/REDACTED/volumes/kubernetes.io~csi/pvc-REDACTED/mount/history_index/shared_memory.bin
restic  2550974 root   69u      REG  0,272       2626494  76289164 /tmp/restic-temp-pack-496344882 (deleted)
restic  2550974 root   73r      REG 252,16 4194304000000   4980738 /host_pods/REDACTED/volumes/kubernetes.io~csi/pvc-REDACTED/mount/history/shared_memory.bin
```

Based on the locked files by the `restic` process, their sizes as well as the fact `restic` was attempting connecting to the google cloud, it seems to me that it had some issues uploading these large files, `shared_memory.bin` is 3.9 TiB.
OTOH, after uploading about 41Gi out of 48Gi, it just stalled with the symptoms mentioned above.

It'd be cool if it could do some more logging so we could figure what makes it stop.

But having that it was using 99% of CPU suggests that something went wrong / into a loop or so.

**Comment by andy108369** [comment] 2022-08-27 19:49
I've noticed `restic` process was still getting OOM killed, this time reaching `2Gi`.
Interesting part is that it seems* it left the process running at 99% CPU usage, no I/O nor network activity behind, with exactly same symptoms as described above. (it *seems - because I've had 1 process launched manually and another one on schedule, they might have collided making the new process OOM and the old one to still sit in memory).

I've set it to `10Gi` and re-run the backup to see if that somehow helps.

```
[Fri Aug 26 15:10:40 2022] Memory cgroup out of memory: Killed process 2550974 (restic) total-vm:2639028kB, anon-rss:1897248kB, file-rss:15116kB, shmem-rss:0kB, UID:0 pgtables:4004kB oom_score_adj:999
[Sat Aug 27 14:15:58 2022] Memory cgroup out of memory: Killed process 828591 (restic) total-vm:2638516kB, anon-rss:1794964kB, file-rss:15116kB, shmem-rss:0kB, UID:0 pgtables:3732kB oom_score_adj:999
```

While watching the `restic` process now, I am also wondering if having `cancelled_write_bytes` grow along with `write_bytes` is not a bad sign?
![image](https://user-images.githubusercontent.com/107317698/187045770-6a00993d-31c5-4e76-8c84-95fa037fb3b5.png)

**Comment by andy108369** [comment] 2022-08-28 21:56
> I've set it to `10Gi` and re-run the backup to see if that somehow helps.

Unfortunately, no difference.

It is running way longer than `240 minutes` (more than 11h52mins), taking 99% of CPU (having all the same symptoms as mentioned before):

```
# date
Sun Aug 28 21:54:03 UTC 2022
# ps -ef|grep resti
root     1429521 2215495  0 21:54 pts/0    00:00:00 grep --color=auto resti
root     2224814 2224746  0 Aug27 ?        00:04:11 /velero restic server
root     4076017 2224814 99 09:58 ?        11:52:46 restic backup --repo=gs:...
```

```
# cat /proc/$(pidof -s restic)/io | numfmt --to=iec-i --field=2
rchar:         4.1Ti
wchar:        14Gi
syscr:   8.4Mi
syscw:   1.4Mi
read_bytes:        35Gi
write_bytes:      6.8Gi
cancelled_write_bytes:      6.6Gi
```

Is there some way to determine where / why it gets stuck?

**Comment by Lyndon-Li** [comment] 2022-08-29 09:41
@andy108369 Could you help to share more details of the file data to be backed up, especially the 3.9T file and 997G file:

- Are there lots of "0" in the file?
- If so, how much (data size) of "0" in the file?

**Comment by andy108369** [comment] 2022-08-29 13:46
> @andy108369 Could you help to share more details of the file data to be backed up, especially the 3.9T file and 997G file:
> 
> * Are there lots of "0" in the file?
> * If so, how much (data size) of "0" in the file?

Bingo!

They do seem to have a lot of "0"'s in them, as it first appears to be large files:

```
# ls -lah history_index/shared_memory.bin history/shared_memory.bin 
-rw-r--r-- 1 systemd-resolve systemd-journal 3.9T Aug 29 13:44 history/shared_memory.bin
-rw-r--r-- 1 systemd-resolve systemd-journal 977G Aug 29 13:44 history_index/shared_memory.bin
```

In reality they are consuming only 4.5Gi and 10Gi each:

```
# du -smh history_index/shared_memory.bin history/shared_memory.bin 
4.5G	history_index/shared_memory.bin
10G	history/shared_memory.bin
```

Does it somehow affect the `restic` / confirms the `cancelled_write_bytes`?
Is there a way around it to make `restic` (velero) work with these kind of files?

**Comment by Lyndon-Li** [comment] 2022-08-29 15:10
Then I am afraid after you change the memory to 10G, everything goes to normal and Restic may finally complete its work merely it will take quite a long time since there are 3.9T for Restic. I say "may finally complete", because along the running, no one knows how much memory Restic will use, so 10G may not be enough.

let's first check the rchar vs. read_bytes:
 
- For the 1st statistic, rchar=33G, read_bytes=20G, it means, there are around 10G of data that the file system doesn't think it need to read from the storage, for example, zero data
- For the 2nd statistic, rchar=4.1T, read_bytes=35G, there much more data the file system returned directly, more than 3.9T

How's that happen? The most common case is the file data are all "0", so only the file system only allocates metadata to record them but not allocate any disk space.
What is the impacts:

- This will cause the read operation to the system returns very fast because on data need to read from disk. After the read returns, on data is actually uploaded because almost all the data will be deduplicated. As you can see, the CPU will not yield because any disk/network IO, that is why the CPU usage is almost 100%
- Even though the data doesn't occupy disk space, since Restic has no optimization, the "0"s are counted as normal data in Restic's deduplication system, so every KB of this data will take an index. The indexes are data structure in memory, this will lead to huge memory usage since there are 3.0TB of data. That is why OOM happens

Conclusively, since the code is in Restic and the current behavior of Velero integrating with Restic is just calling the Restic CLI and starting a Restic process, I don't think we have any way to optimize this from Velero side.

**Comment by andy108369** [comment] 2022-08-29 15:20
> Then I am afraid that after you change the memory to 10G

I'm already running with [that](https://github.com/vmware-tanzu/velero/issues/5251#issuecomment-1229255415) setting since 2 days ago.

The restic process is not getting OOM-killed.

The error now is this - as the new backup gets scheduled every once a day it hits the lock:

```
pod volume backup failed: running Restic backup, stderr=unable to create lock in backend: repository is already locked exclusively by PID 1673956 on velero-6df6454fb-h8v6j by nonroot (UID 65532, GID 65532)\nlock was created at 2022-08-29 08:38:50 (5m6.531202411s ago)\nstorage ID 8c5d6a8d\nthe `unlock` command can be used to remove stale locks\n: exit status 1
```

I have checked - the `restic` process is now gone.

> Conclusively, since the code is in Restic and the current behavior of Velero integrating with Restic is just calling the Restic CLI and starting a Restic process, I don't think we have any way to optimize this from Velero side.

Makes sense, I'll open an issue in [restic GH issues](https://github.com/restic/restic/issues)
Thank you!

**Comment by Lyndon-Li** [comment] 2022-08-29 15:26
> unable to create lock in backend
This means some Restic processes have left over an orphan file lock in the repository.
This may be normal since the current backup haven't finished in 1 day. So when a new Restic process is launched the second day, it is blocked

**Comment by MichaelEischer** [comment] 2022-08-29 19:31
> repository is already locked exclusively by PID 1673956

The `backup` command doesn't use exclusive locks. It must be a different command that left that lock behind.

> * Even though the data doesn't occupy disk space, since Restic has no optimization, the "0"s are counted as normal data in Restic's deduplication system, so every KB of this data will take an index.

4TB shouldn't require much more than 400MB for the index, if all chunks were different. However, as the file appears to largely consist of zeroes this will mean nearly perfect deduplication, thus the index size will probably only be a few MB. What requires a lot more memory is the directory metadata, with lots of zeros in it, the file will be cut into approx. 8 million chunks. The end result will be about 500MB directory metadata that will temporarily require at least 3 times as much memory (restic < 0.14.0 might require a bit more). Thus 2GB is definitely not enough, although 10GB might work, but that depends on the total number of files in the backed up folder.

Just processing the 4TB of zeros will take several hours, as apparently restic can only use a single CPU core, I'd expect it to manage something between 100-200MB/s.

**Comment by Lyndon-Li** [comment] 2022-09-01 06:24
I am closing this issue since we've known the cause of the CPU and memory usage and a Restic issue has been opened.
The lock problem will be handled in #5268 separately.

**Closed** 2022-09-01 06:25 UTC
Labels: Restic

**Comment by andy108369** [comment] 2022-09-02 22:40
@Lyndon-Li there is an idea of adding a `tar` which is able to detect holes in sparse files (`tar --sparse`).

Is it possible to somehow instruct Velero do `tar --sparse <target> | restic backup --stdin ...` and similar during restore?

Ref https://github.com/restic/restic/issues/3903#issuecomment-1235888813

cc @MichaelEischer

**Comment by Lyndon-Li** [comment] 2022-09-05 02:11
As a general Kubernetes backup tool, Velero always pursues general solutions instead of making solutions for very limited workaround. Therefore, we need to consider below things:

- Which files need `tar` is a question, the entire volume? some files or directories in the volume? We need a way for users to tell this.
- This is also true for the `--sparse `option, which also needs users to tell Velero.
- Velero needs to change the general backup and restore workflow to integrate with the new command `tar`
- By calling `tar --sparse`, we lay everything on the tar tool, whether it behaves as what we are expecting? how much cpu/memory it takes? will it change? We don't know, eventually the `tar --sparse` is not designed for this purpose

Therefore, there is quite a lot of work to make a general solution by Velero with your proposal, so it is not a quick fix; one the other hand, even if we have it, finally we may see the solution itself is not general enough.

On the other hand, Velero indeed aims to solve this kind of problem in future, but with another direction -- the block level data movement. Please keep tune in Velero's roadmap for this.

**Comment by Lyndon-Li** [comment] 2022-09-05 02:18
Finally, one more question for the user case:
From the files' name, I guess it is some kind of files to store the `share memory` data, it means the data is most probably ephemeral. Why do you want to persist it? Could you share more information of your user case?

**Comment by andy108369** [comment] 2022-09-06 11:31
> Finally, one more question for the user case: From the files' name, I guess it is some kind of files to store the `share memory` data, it means the data is most probably ephemeral. Why do you want to persist it? Could you share more information of your user case?

This is the customer data, normally we should not even look nor know what is there.
So, that's supposed to be a blackbox and we just want to backup the data so we can restore it if things catastrophically fail or get removed due to a an error (human or non-human).

**Comment by andy108369** [comment] 2022-09-06 11:34
> Therefore, there is quite a lot of work to make a general solution by Velero with your proposal,

@Lyndon-Li Should I open a feature request for this or that's going to be on your roadmap somewhere?

**Comment by Lyndon-Li** [comment] 2022-09-06 14:21
Though I totally agree with you that a backup tool should back up whatever data users give, I also believe this kind of share memory data is meaningless for users to back it up if they understand what the data is in the files.
Therefore, I believe if the customer fully understand what is happening, what the customer asks is not a way to back up these files, but a way to skip the files.

Now go back to the topic of backing up sparse file, I think the two of the most rational solutions are:

1. Be aware of the sparse files in the file system uploader and process them in an enlightened way, just as the Restic issue [3914](https://github.com/restic/restic/issues/3914). With this solution, the caller doesn't need to know the sparse files at all; otherwise, without this solution, even if the caller sets the --sparse flag, the uploader cannot make much optimization, because in order to optimize the backup, the uploader has to query the file system to get the extents of the zero data; also, it requires a special protocol to write the all zero data to the repository.
2. Back up the volume in block level

Solution 1 will not be in the scope of Velero, but of Restic because Restic itself is the file system uploader and repository.
Solution 2 will be in the future release of Velero, you don't need to open an issue, it has already been in our roadmap. But if you want to better track this on your own, yes, you can open an issue.

And as you can see, the aforementioned workaround that uses `tar` tool is not regarded as a general enough and ultimate solution, so I think we will not deliver it in Velero.

**Comment by andy108369** [comment] 2022-09-07 09:57
> Though I totally agree with you that a backup tool should back up whatever data users give, I also believe this kind of share memory data is meaningless for users to back up if they understand what the data is in the files.
Therefore, I believe if the customer fully understand what is happening, what the customer asks is not a way to back up these files anyway, but a way to skip the files.

It is very often the customer does not even know what are the files being used by the application they use.
All they really want is make sure things can start back up again as before without them needing to look what files their apps might be missing/depending on.
I understand the normal app would just recreate any temporary file such as a shared memory but sometimes this is not the case.
Hence, I'd prefer to be able restore everything intact 1:1 to avoid any surprises where the customer start asking questions such as why their app isn't starting or is missing something.

And even if we are right about telling what files the customer should or should not backup, in some cases we should not be even able to look at what data the customers store. This can be contract-based, promise-based, or design-based (say, through Secure Computing).
And again, even if we were right to tell them what to store or not to, that would incur a huge overhead for us managing the decentralized cloud go through each customer deployment, browse & analyse through the data they store and then find and talk to them about what to or not to backup. Whereas we do not even know who is storing the data in our case :-)

Hence, a working blackbox backup would be ideal for us, but here it fails on a large sparse file.

`tar` tool would be a perfect solution here since it handles sparse files and isn't using much of resources while is backing the data up.
As well as it is able to backup & preserve (on restore) ownership, permissions, POSIX ACLs, SELinux context, extended attributes (xattrs) all out of a box.

# Tests

I've made a few tests which do not show much of memory utilization, only a high CPU during the restore which is expected.
The restore itself was very fast.

## Archival: tar sparse

here is `tar --sparse -cf shared_memory.bin.tar shared_memory.bin` running, using only `2996 Ki` of RAM, no compression:

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                 
1180029 root      20   0    8684   2996   2792 R 100.0   0.0   0:06.65 tar --sparse -cf shared_memory.bin.tar shared_memory.bin
```

![image](https://user-images.githubusercontent.com/107317698/188843969-7bca816c-ca41-436c-881a-660d5fda925b.png)

```
# rm -vf shared_memory.bin.tar; time tar --sparse -cf shared_memory.bin.tar shared_memory.bin
removed 'shared_memory.bin.tar'

real	0m13.732s
user	0m1.052s
sys	0m12.463s

# du -shm shared_memory.bin*
10258	shared_memory.bin
10258	shared_memory.bin.tar

# ls -altrh shared_memory.bin*
-rw-r--r-- 1 root root 3.9T Sep  7 09:20 shared_memory.bin
-rw-r--r-- 1 root root  11G Sep  7 09:29 shared_memory.bin.tar

# tar tvf shared_memory.bin.tar
-rw-r--r-- root/root 4194304000000 2022-09-07 09:20 shared_memory.bin
```

Throughput is `829 MiB/s` during archive creation:

![image](https://user-images.githubusercontent.com/107317698/188844847-cdbc1c6c-1adf-45d4-b848-53d01efa48c7.png)

```
# tar --sparse -c shared_memory.bin 2>/dev/null | pv -petrafb -i 1 > shared_memory.bin.tar
10.0GiB 0:00:12 [ 829MiB/s] [ 829MiB/s] [                        <=>                                                                       ]
```

## Extraction: tar sparse

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
1188029 root      20   0    8684   2904   2700 R 100.0   0.0   0:05.35 tar xO 
```

![image](https://user-images.githubusercontent.com/107317698/188845533-e61ef503-25c2-47dd-bcd1-6a16d279d659.png)

> Note: can't `tar -xO -f shared_memory.bin.tar | pv -petrafb -i 1 > shared_memory.bin.extracted` here as all `0`'s will go through the `pv` tool which will take ages.

```
# pv < shared_memory.bin.tar | tar xO > shared_memory.bin.extracted
10.0GiB 0:00:28 [ 358MiB/s] [============================================================================================>] 100%  

# ls -la shared_memory.bin*
-rw-r--r-- 1 root root 4194304000000 Sep  7 09:20 shared_memory.bin
-rw-r--r-- 1 root root 4194304000000 Sep  7 09:36 shared_memory.bin.extracted
-rw-r--r-- 1 root root   10756106240 Sep  7 09:33 shared_memory.bin.tar
```

### md5sum check - OK

```
# tar --sparse -cf shared_memory.bin.tar.1 shared_memory.bin
# md5sum shared_memory.bin.tar*
0b3380836c34df7935a86e2e9b0b0fb9  shared_memory.bin.tar
0b3380836c34df7935a86e2e9b0b0fb9  shared_memory.bin.tar.1
```

## Archival: tar sparse + compression (pigz)

![image](https://user-images.githubusercontent.com/107317698/188847168-8d744a88-0a38-4adb-a0b9-db1f20df7634.png)

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                          
1195208 root      20   0 4803372  23900   2032 R  1292   0.0   1:37.18 pigz --fast                      
1195207 root      20   0    8684   3072   2868 R  90.2   0.0   0:06.53 tar --sparse -c shared_memory.bin
```

![image](https://user-images.githubusercontent.com/107317698/188847272-a90f7b9f-94ab-4f1f-a921-e451228f09b3.png)

```
root@k8s-node-8:~# tar --sparse -c shared_memory.bin 2>/dev/null | pigz --fast | pv -petrafb -i 1 > shared_memory.bin.tar.gz
2.45GiB 0:00:14 [ 170MiB/s] [ 170MiB/s] [                            <=>  
```

## Extraction: tar sparse + compression (pigz)

```
# pigz -cd shared_memory.bin.tar.gz | pv -petrafb -i 1 | tar xO > shared_memory.bin.extracted.2
5.13GiB 0:00:15 [ 341MiB/s] [ 350MiB/s] [                            <=>                                                                   ]
7.05GiB 0:00:21 [ 320MiB/s] [ 343MiB/s] [                                       <=>                                                        ]
10.0GiB 0:00:30 [ 340MiB/s] [ 340MiB/s] [                                                          <=>                                     ]
```

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                          
1201932 root      20   0   28904   2412   2132 R 149.0   0.0   0:40.72 pigz -cd shared_memory.bin.tar.gz
1201934 root      20   0    8684   3028   2824 R  91.2   0.0   0:26.04 tar xO                           
```
![image](https://user-images.githubusercontent.com/107317698/188848577-065e7204-9201-404e-82bd-45c20c1e7676.png)

```
# ls -la shared_memory.bin*
-rw-r--r-- 1 root root 4194304000000 Sep  7 09:20 shared_memory.bin
-rw-r--r-- 1 root root 4194304000000 Sep  7 09:36 shared_memory.bin.extracted
-rw-r--r-- 1 root root 4194304000000 Sep  7 09:49 shared_memory.bin.extracted.2
-rw-r--r-- 1 root root   10756106240 Sep  7 09:33 shared_memory.bin.tar
-rw-r--r-- 1 root root   10756106240 Sep  7 09:41 shared_memory.bin.tar.1
-rw-r--r-- 1 root root    2626875983 Sep  7 09:44 shared_memory.bin.tar.gz
```

**Comment by Lyndon-Li** [comment] 2022-09-07 11:01
I agree tar tool could solve the current problem perfectly, but it is true for the current issue only. 
Velero as a universal Kubernetes backup tool cannot take in changes that work only for a particular case, instead, we pursue universal and sophisticated solutions. Especially when we know the right directions (as the 2 solutions I've mentioned) to solve the current problem.
