### ISSUE TITLE
Restore of role-bindings to new namespace fails

### ISSUE THREAD

**Issue by alexander-demichev** [vmware-tanzu/velero#1954] opened 2019-10-09 17:41 UTC
Restore of role-bindings to new namespace(from 'foo' to 'bar') fails with following error:
```
time="2019-10-09T17:26:38Z" level=info msg="Attempting to restore RoleBinding: basic-role-binding" logSource="pkg/restore/restore.go:1031" restore=xxx/dcafd130-eab9-11e9-9840-73e49cdff9d1-8lggw
time="2019-10-09T17:26:38Z" level=info msg="error restoring basic-role-binding: invalid origin role binding basic-role-binding: attempts to reference role in namespace \"foo\" instead of current namespace \"bar\"" logSource="pkg/restore/restore.go:1094" restore=xxx/dcafd130-eab9-11e9-9840-73e49cdff9d1-8lggw
```
Referenced role is restored to new namespaced without problems. Is this a known issue?

**Comment by prydonius** [comment] 2019-10-09 22:04
Hi @alexander-demichev, this does seem like a bug. Just to clarify, are you remapping the namespace using `--namespace-mappings`?

**Comment by alexander-demichev** [comment] 2019-10-10 08:10
Yes, I was using namespace mappings

**Comment by alexander-demichev** [comment] 2019-10-10 10:57
I can open a PR with new role-binding restore action, if this is an appropriate fix.

**Comment by skriss** [comment] 2019-10-10 20:52
xref #80

**Comment by prydonius** [comment] 2019-10-10 23:54
@skriss should we close this out in favour of #80? It already mentions the issue with rolebindings.

**Comment by skriss** [comment] 2019-10-11 14:44
Yeah, that works. The only question is, if we add a restore item action that specifically fixes role bindings - does that close #80 or are there still other instances of it that will exist? Guessing there are still other instances (at a minimum, for cluster role bindings as mentioned in the issue).

**Comment by skriss** [comment] 2019-10-11 14:45
Closing as dupe of #80, @alexander-demichev let's continue discussion there

**Closed by skriss** 2019-10-11 14:45 UTC
Labels: Bug

**Comment by cszixin** [comment] 2025-08-08 03:06
Hi, I'm currently using Velero version 1.14. I encountered this same issue when restoring RoleBindings across namespaces. How can I resolve it?
