### ISSUE TITLE
Backups created by a schedule with useOwnerReferenceInBackup set do not get synced properly

### ISSUE THREAD

**Issue by luizrojo** [vmware-tanzu/velero#4093] opened 2021-09-01 17:00 UTC
**What steps did you take and what happened:**
I am trying to test and document the full restore process for my team.

Right now I have a few backups on S3, and I am spinning a new cluster with a fresh velero install (using the official helm) and trying to restore a backup available

Velero is finding the backups on S3, as shown in the POD logs:

```
time="2021-09-01T16:31:07Z" level=info msg="Found 24 backups in the backup location that do not exist in the cluster and need to be synced" backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:204"
time="2021-09-01T16:31:07Z" level=info msg="Attempting to sync backup into cluster" backup=velero-cluster-20210830215921 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:07Z" level=info msg="Backup storage location valid, marking as available" backup-storage-location=s3 controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:121"
time="2021-09-01T16:31:08Z" level=info msg="Successfully synced backup into cluster" backup=velero-cluster-20210830215921 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:08Z" level=info msg="Attempting to sync backup into cluster" backup=velero-kube-system-20210831061225 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:09Z" level=info msg="Successfully synced backup into cluster" backup=velero-kube-system-20210831061225 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:09Z" level=info msg="Attempting to sync backup into cluster" backup=velero-kube-system-20210831180036 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:09Z" level=info msg="Successfully synced backup into cluster" backup=velero-kube-system-20210831180036 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:09Z" level=info msg="Attempting to sync backup into cluster" backup=velero-cluster-20210901030146 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:09Z" level=info msg="Successfully synced backup into cluster" backup=velero-cluster-20210901030146 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:09Z" level=info msg="Attempting to sync backup into cluster" backup=velero-cluster-20210831061225 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:09Z" level=info msg="Successfully synced backup into cluster" backup=velero-cluster-20210831061225 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:09Z" level=info msg="Attempting to sync backup into cluster" backup=teste backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:09Z" level=info msg="Successfully synced backup into cluster" backup=teste backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:09Z" level=info msg="Attempting to sync backup into cluster" backup=velero-kube-system-20210831120036 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:09Z" level=info msg="Successfully synced backup into cluster" backup=velero-kube-system-20210831120036 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:09Z" level=info msg="Attempting to sync backup into cluster" backup=velero-kube-system-20210831060010 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:09Z" level=info msg="Successfully synced backup into cluster" backup=velero-kube-system-20210831060010 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:10Z" level=info msg="Attempting to sync backup into cluster" backup=velero-kube-system-20210830215735 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:10Z" level=info msg="Successfully synced backup into cluster" backup=velero-kube-system-20210830215735 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:10Z" level=info msg="Attempting to sync backup into cluster" backup=velero-kube-system-20210831023229 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:10Z" level=info msg="Successfully synced backup into cluster" backup=velero-kube-system-20210831023229 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:10Z" level=info msg="Attempting to sync backup into cluster" backup=velero-cluster-20210830210350 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:10Z" level=info msg="Successfully synced backup into cluster" backup=velero-cluster-20210830210350 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:10Z" level=info msg="Attempting to sync backup into cluster" backup=velero-kube-system-20210830215921 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:10Z" level=info msg="Successfully synced backup into cluster" backup=velero-kube-system-20210830215921 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:10Z" level=info msg="Attempting to sync backup into cluster" backup=velero-mybackup-20210830203606 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:10Z" level=info msg="Successfully synced backup into cluster" backup=velero-mybackup-20210830203606 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:10Z" level=info msg="Attempting to sync backup into cluster" backup=velero-kube-system-20210901120046 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:10Z" level=info msg="Successfully synced backup into cluster" backup=velero-kube-system-20210901120046 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:10Z" level=info msg="Attempting to sync backup into cluster" backup=velero-cluster-20210830215732 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:10Z" level=info msg="Successfully synced backup into cluster" backup=velero-cluster-20210830215732 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:11Z" level=info msg="Attempting to sync backup into cluster" backup=velero-kube-system-20210901030146 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:11Z" level=info msg="Successfully synced backup into cluster" backup=velero-kube-system-20210901030146 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:11Z" level=info msg="Attempting to sync backup into cluster" backup=velero-cluster-20210901120046 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:11Z" level=info msg="Successfully synced backup into cluster" backup=velero-cluster-20210901120046 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:11Z" level=info msg="Attempting to sync backup into cluster" backup=velero-kube-system-20210830205702 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:11Z" level=info msg="Successfully synced backup into cluster" backup=velero-kube-system-20210830205702 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:11Z" level=info msg="Attempting to sync backup into cluster" backup=velero-kube-system-20210830220222 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:11Z" level=info msg="Successfully synced backup into cluster" backup=velero-kube-system-20210830220222 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:11Z" level=info msg="Attempting to sync backup into cluster" backup=velero-cluster-20210830220219 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:11Z" level=info msg="Successfully synced backup into cluster" backup=velero-cluster-20210830220219 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:11Z" level=info msg="Attempting to sync backup into cluster" backup=velero-cluster-20210831120036 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:11Z" level=info msg="Successfully synced backup into cluster" backup=velero-cluster-20210831120036 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:11Z" level=info msg="Attempting to sync backup into cluster" backup=velero-kube-system-20210830210353 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:11Z" level=info msg="Successfully synced backup into cluster" backup=velero-kube-system-20210830210353 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:12Z" level=info msg="Attempting to sync backup into cluster" backup=velero-kube-system-20210901060046 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:12Z" level=info msg="Successfully synced backup into cluster" backup=velero-kube-system-20210901060046 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2021-09-01T16:31:12Z" level=info msg="Attempting to sync backup into cluster" backup=velero-kube-system-20210830223613 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2021-09-01T16:31:12Z" level=info msg="Successfully synced backup into cluster" backup=velero-kube-system-20210830223613 backupLocation=s3 controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
```

But it is not creating the objects in the cluster, so when I use the velero CLI to list the backups, none but one are shown:

```
velero get backups --show-labels
NAME    STATUS      ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR   LABELS
teste   Completed   0        0          2021-08-30 17:37:38 -0300 -03   28d       s3                 <none>     velero.io/storage-location=s3
```

One thing I noticed is that it only imported the "manual backup", the other backups were generated via schedule routine.

**What did you expect to happen:**

All backups found on S3 listed and available using the velero CLI

**Environment:**

- Velero version
```
Client:
	Version: v1.6.3
	Git commit: -
Server:
	Version: v1.6.3
```

- Velero features (use `velero client config get features`): 

```
features: <NOT SET>
```

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:56:19Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
```
Kubernetes kind instalation
Kubernetes is on v1.21.1
```
- Cloud provider or hardware configuration:
```
local kind cluster
```
- OS (e.g. from `/etc/os-release`):
```
Ubuntu 21.04
```

**Comment by luizrojo** [comment] 2021-09-01 21:03
After some tshoot, I found out that the schedules being created at helm deploy had the config `useOwnerReferencesInBackup` set to `true`.

Changing it to `false` solved the problem.

My main concern is that at the helm default [values yaml file](https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml) the property set to `true` on the example configurarion, but I could not find any reference of it on the [CLI schedule creation example here](https://velero.io/docs/v1.6/api-types/schedule/#use) or anywhere on the website.

What is the correct configuration, and what does this config really do?

**Comment by dsu-igeek** [comment] 2021-09-02 20:03
That flag was added to fix a problem when using Velero with Argo in PR #3127.  It shouldn't affect the backup syncing, but apparently it does.  It doesn't need to be on by default and the Helm chart shouldn't recommend it be set to true.  I'm converting this to a bug.  Would you put some examples of your schedule CRDs here?  Thanks!

**Comment by luizrojo** [comment] 2021-09-09 17:45
@dsu-igeek 

These are the schedules with the feature as on, passed on the values.yaml. This is from when I was having the issue.

```yaml
schedules:
  kube-system:
    disabled: false
    labels:
      cluster: "XXXXXXXXXXXXX"
      scheduled: "yes"
    annotations:
      cluster: "XXXXXXXXXXXXX"
      scheduled: "yes"
    schedule: "0 */6 * * *"
    useOwnerReferencesInBackup: true
    template:
      ttl: "168h"
      includedNamespaces:
        - kube-system
  cluster:
    disabled: false
    labels:
      cluster: "XXXXXXXXXXXXX"
      scheduled: "yes"
    annotations:
      cluster: "XXXXXXXXXXXXX"
      scheduled: "yes"
    schedule: "0 */12 * * * "
    useOwnerReferencesInBackup: true
    template:
      ttl: "168h"
      includedNamespaces:
        - "*"
      includedResources:
        - "*"
  ```

These are the configs right now, with the flag defined as false. With the configuration below, Velero is able to import de backups from S3 into the cluster

```yaml
schedules:
  kube-system:
    disabled: false
    labels:
      cluster: "XXXXXXXXXXXXX"
      scheduled: "yes"
    annotations:
      cluster: "XXXXXXXXXXXXX"
      scheduled: "yes"
    schedule: "0 * * * *"
    useOwnerReferencesInBackup: false
    template:
      ttl: "168h"
      includedNamespaces:
        - kube-system
  cluster:
    disabled: false
    labels:
      cluster: "XXXXXXXXXXXXX"
      scheduled: "yes"
    annotations:
      cluster: "XXXXXXXXXXXXX"
      scheduled: "yes"
    schedule: "0 * * * * "
    useOwnerReferencesInBackup: false
    template:
      ttl: "168h"
      includedNamespaces:
        - "*"
      includedResources:
        - "*"
```

And this is a backup crd from one of the clusters

```yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    cluster: XXXXXXXXXXXXX
    helm.sh/hook: post-install,post-upgrade,post-rollback
    helm.sh/hook-delete-policy: before-hook-creation
    scheduled: "yes"
    velero.io/source-cluster-k8s-gitversion: v1.20.6
    velero.io/source-cluster-k8s-major-version: "1"
    velero.io/source-cluster-k8s-minor-version: "20"
  creationTimestamp: "2021-09-08T17:00:39Z"
  generation: 10
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    cluster: XXXXXXXXXXXXX
    helm.sh/chart: velero-2.23.6
    scheduled: "yes"
    velero.io/schedule-name: velero-kube-system
    velero.io/storage-location: s3
  name: velero-kube-system-20210908170042
  namespace: kube-system
  resourceVersion: "259642287"
  uid: 95ed3945-21d9-44f5-bf2d-26aa7dcb3f11
spec:
  defaultVolumesToRestic: false
  hooks: {}
  includedNamespaces:
  - kube-system
  storageLocation: s3
  ttl: 168h0m0s
  volumeSnapshotLocations:
  - default
status:
  completionTimestamp: "2021-09-08T17:01:08Z"
  expiration: "2021-09-15T17:00:56Z"
  formatVersion: 1.1.0
  phase: Completed
  progress:
    itemsBackedUp: 860
    totalItems: 860
  startTimestamp: "2021-09-08T17:00:56Z"
  version: 1
```

**Comment by obeyler** [comment] 2021-09-15 16:11
same pb

**Comment by tricky42** [comment] 2021-09-16 09:25
I am also affected by this problem. E.g. missing owner references can lead to problems when restoring `certificates` which have been issued by `cert-manager` for an `ingress`: https://cert-manager.io/docs/tutorials/backup/#restoring-ingress-certificates

_Velero does not restore owner references, so it may be necessary to exclude Certificates created for Ingresses from the backup even when not re-creating the Ingress itself. See Restoring Ingress Certificates._

**Comment by jdheyburn** [comment] 2021-09-21 10:03
This looks to be the cause of my issue: https://github.com/vmware-tanzu/velero/issues/3963; changing/recreating a schedule can recreate a new UID, causing the Backup resource to be orphaned. This then leaves a load of garbage in places like AWS EBS snapshots where they have been lost. 

I don't believe `useOwnerReferencesInBackup` should be set to `true` in the helm chart as this is where I pulled it in from.

Notably as well, the application should give better feedback on when a Backup is being synced, when it has an owner that doesn't exist.

**Comment by chris-sanders** [comment] 2021-10-01 02:15
Today I've tried to restore a cluster and hit this same issue. I removed the reference, did another backup and now I can restore as long as the reference is removed. Just wanted to confirm this configuration option prevents restores. Seems to me the reference should be removed on import. I see it's marked as Needs Investigation, the merge that introduced this is almost 10 months old and backups for that time period from anyone using it don't work.

This is a pretty critical bug to be alive for almost a year considering it renders backups unusable. I understand this is open source, I don't have the time to try and fix this myself, I don't mean to be critical I just want to confirm the issue and the impact.

**Comment by obeyler** [comment] 2021-10-01 07:56
May I've done a mistake but if I also see that but if the K8S object is well restore by removing the ownerref, I also note the the restic backup hasn't been restored. could you check in your restore that the pv is also restored ?

**Comment by blackpiglet** [comment] 2022-02-17 02:07
Some analysis and proposal solution is written to this document. Please check:
https://docs.google.com/document/d/16AE370SDkxtaYEqJwCWEF6neLTPJ8mkC5jyLFjl1KPI

**Comment by blackpiglet** [comment] 2022-03-02 01:43
Fixed by
https://github.com/vmware-tanzu/velero/pull/4660
https://github.com/vmware-tanzu/helm-charts/pull/346

**Closed by blackpiglet** 2022-03-02 01:43 UTC
Labels: Needs info
