### ISSUE TITLE
Restore with existing resource policy as update doesn't work on pod resources

### ISSUE THREAD

**Issue by rnarenpujari** [vmware-tanzu/velero#6828] opened 2023-09-15 13:36 UTC
**What steps did you take and what happened:**

Taking a backup of a namespace with a pod and then trying to restore it with `--existing-resource-policy update` doesn't work well. Surprisingly the restore reaches the Completed phase in spite of the error.

```
time="2023-09-15T09:24:54Z" level=warning msg="patch attempt failed for /v1, Kind=Pod test-1/my-pod: Pod \"my-pod\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds`, `spec.tolerations` (only additions to existing tolerations) or `spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)\n\u00a0\u00a0core.PodSpec{\n\u00a0\u00a0\t... // 9 identical fields\n\u00a0\u00a0\tServiceAccountName:           \"default\",\n\u00a0\u00a0\tAutomountServiceAccountToken: nil,\n-\u00a0\tNodeName:                     \"aks-agentpool-38125718-vmss000002\",\n+\u00a0\tNodeName:                     \"\",\n\u00a0\u00a0\tSecurityContext:              &{},\n\u00a0\u00a0\tImagePullSecrets:             nil,\n\u00a0\u00a0\t... // 19 identical fields\n\u00a0\u00a0}\n" logSource="pkg/restore/restore.go:2207" restore=velero/rs-6
```
I see that this happens even if there is no change in the pod since the backup as well as if there is a change like a new annotation.

I've destroyed my cluster and didn't collect the debug bundle but you should be able to reproduce with any pod manifest, e.g.
```
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: public.ecr.aws/docker/library/nginx
```

```
velero create backup bk-5 --include-namespaces test-1
velero create restore rs-5 --from-backup bk-5 --existing-resource-policy update
```

**What did you expect to happen:**

Patch to succeed

**The following information will help us better understand what's going on**:

NA

**Anything else you would like to add:**

NA

**Environment:**

- Velero version (use `velero version`): 1.10.3 & 1.12 rc1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by sseago** [comment] 2023-09-19 21:45
"Surprisingly the restore reaches the Completed phase in spite of the error."

Warnings don't fail restores. It is expected that some resource update attempts will fail, since various resources have certain immutable fields, etc. Basically, if policy is "Update", then Velero first attempts to patch the resource to make it look exactly like the resource in the backup -- if this fails, the error message gets logged as a Restore warning, and Velero then attempts to only patch the backup/restore labels.

From the warning logged above, it looks like Velero attempted to modify one or more immutable fields in the Pod, so this failed.

Velero is working as expected here.

**Comment by blackpiglet** [comment] 2023-09-20 05:43
The pod failed due to one of the restore actions removing the pod's NodeName to make it re-scheduled.
https://github.com/vmware-tanzu/velero/blob/d3e5bb7451447b61ea9b985210d0a7c369ec73f8/pkg/restore/pod_action.go#L52 
The NodeName cannot be updated for a pod, that's the reason why Velero failed to update.

**Comment by rnarenpujari** [comment] 2023-09-20 08:52
> Velero is working as expected here.  

I'd agree if there was a difference in an immutable field between the existing resource and the resource that was backed up. But as mentioned in the description, this error occurs even if there is no change in the pod. So Velero generating a patch that modifies an immutable field when in reality there is zero diff sounds like a bug.

**Comment by blackpiglet** [comment] 2023-09-21 02:31
@rnarenpujari 
Do you have a preference for how to make a change to the existing behavior?

I agree this is a limitation of the `update` existing policy, but this policy works in a best-effort way to me. It has an assumption that if it cannot apply the modification to the already existing resource in the k8s cluster, it will fall back to the default non-destructive way in the restore.

Furthermore, the document already mentioned in the `Note` section that the pod resource cannot work with the existing resource policy.
https://velero.io/docs/v1.12/restore-reference/#restore-existing-resource-policy
Maybe this can be addressed by the `recreate` existing resource policy.

**Comment by rnarenpujari** [comment] 2023-09-21 06:49
> @rnarenpujari Do you have a preference for how to make a change to the existing behavior?
> 
> I agree this is a limitation of the `update` existing policy, but this policy works in a best-effort way to me. It has an assumption that if it cannot apply the modification to the already existing resource in the k8s cluster, it will fall back to the default non-destructive way in the restore.
> 

I see this as two parts

a) Is it ok to mark the restore phase as Completed if patch operations failed
IMO if it's documented as best effort then perhaps it's fine. But if someone just looks at the status, they may think everything worked as defined in the backup spec when actually some patch operations succeeded and some failed. And this may have left the cluster in an inconsistent state.


b) Does the pod resource behavior need to be fixed?
It looks like it's caused by velero's logic of manipulating `NodeName` and therefore should be fixable. But even if it is fixed, I may have overestimated the usefulness of this feature. I thought it could be used for reverting a namespace to the state at the backup time. But without also restoring volume data to that state, which this feature does not attempt to do, it's not very practical. Looks like the use case of this feature is more for simple resources like services and configmaps. cc @pradeepkchaturvedi

> Furthermore, the document already mentioned in the `Note` section that the pod resource cannot work with the existing resource policy. https://velero.io/docs/v1.12/restore-reference/#restore-existing-resource-policy Maybe this can be addressed by the `recreate` existing resource policy.

Missed that. Thanks for pointing out.

**Comment by blackpiglet** [comment] 2023-09-21 07:31
@rnarenpujari 
> a) Is it ok to mark the restore phase as Completed if patch operations failed
IMO if it's documented as best effort then perhaps it's fine.

It should be better if we document that the existing policy is supposed to work as best effort clearly the somewhere.
@sseago What do you think about that.

> b) Does the pod resource behavior with the update policy need to be fixed?

The first thought jump into my mind is maybe the action can skip the `NodeName` deletion, if the existing policy is set to `update`, but I'm not that is the expected behavior. The user may not know this limitation of the pod, and the pod is restored to unexpected node, or it's also possible the pod's NodeName changed after backup, then the restore would also failed to restore the pod.
Do you have any thought on how to fix the `NodeName` issue?

I also think the feature is not aimed to revert the k8s state without deletion the workload.

**Comment by rnarenpujari** [comment] 2023-09-21 09:46
> Do you have any thought on how to fix the `NodeName` issue?
> 
Maybe one quick fix would be to readd NodeName just before the patch: https://github.com/vmware-tanzu/velero/blob/d3e5bb7451447b61ea9b985210d0a7c369ec73f8/pkg/restore/restore.go#L2196C52-L2196C52
Maybe make a copy of `obj` and populate `NodeName` using the value from `fromCluster` and calculate the patch from that. But it makes the code a bit messy since you have to add resource specific logic just for pods and have to keep it in sync in case the pod action manipulates more fields in the future.

**Comment by sseago** [comment] 2023-09-21 14:51
"It should be better if we document that the existing policy is supposed to work as best effort clearly somewhere.
@sseago What do you think about that?"
So I know that the design doc did state that patch failures would result in Warnings rather than Errors. But maybe that's not mentioned in the user docs? If so, yes, that's an oversight and the doc on the Update policy should be clear that update failures will result in Restore warnings rather than restore Errors.

**Comment by blackpiglet** [comment] 2023-09-22 02:10
I agree with @sseago. The possible fix seems a bit hacky, and it is only useful for a specific case, even if this issue is resolved, we cannot guarantee that there are no other potential issues. 

The `recreate` existing resource policy should be a better solution.

**Comment by blackpiglet** [comment] 2023-09-22 03:02
@sseago @rnarenpujari 
I created a PR to add the best-effort description of the update existing resource policy. Please help to review.
https://github.com/vmware-tanzu/velero/pull/6856

**Closed** 2023-10-17 08:12 UTC
