### ISSUE TITLE
velero needs to support git feature

### ISSUE THREAD

**Issue by doronmak** [vmware-tanzu/velero#3104] opened 2020-11-22 08:49 UTC
today velero don't support backup the YAML file to the git server
I would like if it supports to add the backup to a repository
add support to the public git server and standalone server.
Bitbucket \ github \ gitlab and more
I think its a super feature and can add more users to the velero community

**Comment by carlisia** [comment] 2020-11-23 20:11
For ref: https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+gitop+is%3Aclosed

**Comment by dsu-igeek** [comment] 2020-11-24 23:01
Would you give a little more description of how you think this feature would work and what the use cases for it would be?  Do you see it copying the yamls in as a git tree?  We currently store all of the yamls together in a tar file.  Git has problems with large amounts of data so it won't work as a general purpose store.

**Comment by doronmak** [comment] 2020-11-29 19:13
as I think it should support and give an option to push and extracts files and be in folders by the type of the objects and namespaces. it gives more options when someone got to restore we can also edit configuration and more.
I think it could be super awesome!
btw maybe there are more ideas on how to enable editing file and let velero also be a tool for deployments.
thanks!

**Comment by nrb** [comment] 2020-11-30 20:21
@doronmak Thanks for your explanation! I don't think that's going to be a use case that Velero will support any time soon, as it's super specific. Rather, we'll likely support file system mounts first.

I'm going to close this as a duplicate of https://github.com/vmware-tanzu/velero/issues/238

**Closed by nrb** 2020-11-30 20:21 UTC
Labels: Enhancement/Dev, Needs Product, Needs info
