### ISSUE TITLE
Velero support for object name mapping as we have --namespace-mapping

### ISSUE THREAD

**Issue by abhinavsinha1991** [vmware-tanzu/velero#2044] opened 2019-11-05 13:24 UTC
**Describe the problem/challenge you have**

Currenlty, Velero doesn't support mapping restored Kubernetes objects with a different name, the way we have `--namespace-mapping old-ns:new-ns`

**Describe the solution you'd like**

It would  be good to have a feature like:

`velero restore create --from-backup my-ns-backup --mappings [{"pvcs":[{"old-pvc":"new-pvc"}]},{"secrets":[{"old-secret":"new-secret"}]}]`

**Anything else you would like to add:**

This way, I can restore an older version of a PVC on the existing namespace as a temp PVC, mount it to my application's pods and do file restorations by simple copying.

Suggestion welcome for the use-case.

**Environment:**

- Velero version (use `velero version`): `v1.2.0-beta.1`
- Kubernetes version (use `kubectl version`): 
```
   Client Version: v1.15.0
   Server Version: v1.14.6
```
- Kubernetes installer & version: `NA (using AKS)`
- Cloud provider or hardware configuration: `Azure`
- OS (e.g. from `/etc/os-release`): `Not sure`

**Comment by skriss** [comment] 2019-11-05 15:21
xref #474

**Comment by skriss** [comment] 2019-11-15 20:53
thanks for the request @abhinavsinha1991. You could use a plugin to implement this behavior today - the plugin could run during restores, and could use e.g. a `ConfigMap` to store mappings. It's certainly less convenient than having CLI flags/API fields, but maybe it's an option for you.

See https://velero.io/docs/v1.2.0/custom-plugins/ for more information if you're interested!

**Comment by bruce2409** [comment] 2020-02-21 16:53
We run stateful websites on our cluster, it would be handy to be able to restore the deployments under new names for automating staging environment creation.

**Comment by eleanor-millman** [comment] 2021-05-10 20:34
Closing because duplicate of #474

**Closed by eleanor-millman** 2021-05-10 20:34 UTC
Labels: Enhancement/User, Help wanted, P3 - Wouldn't it be nice if..., Reviewed Q2 2021
