### ISSUE TITLE
PVC disk are using the GCP project ID of the credential used

### ISSUE THREAD

**Issue by mayeco** [vmware-tanzu/velero#4806] opened 2022-04-01 18:36 UTC
What steps did you take and what happened:

**Create a Service account in a different project used to install the GKE with Velero and the backup failed partially**

What did you expect to happen:

**A setting to be able to change the project volumen location.**

The following information will help us better understand what's going on:

https://github.com/vmware-tanzu/velero-plugin-for-gcp/blob/main/velero-plugin-for-gcp/volume_snapshotter.go#L73

**There is not option to change the project ID, is set to the credential project id.**

**The volumeProject option is set directly from the credential project**

![image](https://user-images.githubusercontent.com/369490/161322568-9162e19a-85c5-413f-a5f9-e48e18cffc14.png)

**There are many issues related to this:** 
https://github.com/vmware-tanzu/velero/issues/4776

Anything else you would like to add:

`time="2022-04-01T16:00:32Z" level=error msg="Error backing up item" backup=velero/velero-drp-backup-20220401160027 error="error getting volume info: rpc error: code = Unknown desc = googleapi: Error 403: Required 'compute.disks.get' permission for 'projects/SERVICE_ACCOUNT_PROJECT_ID/zones/us-east1-d/disks/gke-gke-01-us-east1-uuid', forbidden" logSource="pkg/backup/backup.go:417" name=ubuntu
`

**Environment:**

- Velero version (use `velero version`): 

```
Client:
	Version: v1.8.1
	Git commit: 18ee078dffd9345df610e0ca9f61b31124e93f50
Server:
	Version: v1.8.1
```

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5-gke.1805", GitCommit:"6be6bf42dd3e740d8515b47dee3c9fc3ddf602b2", GitTreeState:"clean", BuildDate:"2022-02-18T05:04:07Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes installer & version:
`velero	velero   	1       	2022-04-01 00:02:47.286000243 +0000 UTC	deployed	velero-2.29.4	1.8.1`

**Comment by mayeco** [comment] 2022-04-01 19:21
@carlisia can you please check this. is happening to us. we have a global account (in project A) to deploy Velero and when we install velero in project (B,C...) the backup fail partially for the PVC.

**Comment by mayeco** [comment] 2022-04-01 19:31
https://github.com/vmware-tanzu/velero-plugin-for-gcp/pull/91

**Comment by reasonerjt** [comment] 2022-04-05 16:16
This is probably by design, that the project ID in your gcp credentials is the one you used to take snapshot.

**Comment by blackpiglet** [comment] 2022-04-06 01:54
I put some comments in the PR https://github.com/vmware-tanzu/velero-plugin-for-gcp/pull/91
I'm not sure whether this can work.

Is your case about backup cluster in project A and restore in project B? If so, I think GCP plugin still doesn't support this case yet. Maybe Restic can be used for this case.

**Comment by mayeco** [comment] 2022-04-06 22:33
> This is probably by design, that the project ID in your gcp credentials is the one you used to take snapshot.
@reasonerjt no is not that. is that you use credentials with ORG level permissions to deploy velero in many clusters, to backup and restore in the same project.

@blackpiglet In a big organization. you create a SA in project (services-account-project) then give permissions in the ORG level to this service account to GKE/Bucket then you deploy Velero in many projects (my-gke-app1 and my-gke-app2) using the same service account, this will try to locate the disk in the service account project (services-account-project) not in the projects velero is deployed (my-gke-app1 and my-gke-app2) this PR will give the option to configure the project (ej. my-gke-app1 or my-gke-app2) not from the credential, this is a real scenario in big companies using GCP and use a project only for service account is a Google recommendation in big setups.

the other option is to get the current project ID from the Google API. https://stackoverflow.com/a/56350074

(I'll copy this comment to the PR)

Please let me know I can explain the issue in detail.

**Comment by blackpiglet** [comment] 2022-04-07 02:47
@mayeco 
I haven't tried setting like this before, but if the permission is set correctly, it should work.

https://github.com/vmware-tanzu/velero-plugin-for-gcp/blob/main/velero-plugin-for-gcp/volume_snapshotter.go#L73

From this line, the project ID is read from the secret cloud-credentials. That file contents the information of ServiceAccount, so that doesn't work for your case. I think that should the project where the cluster is in.

Have you tested whether this modification make your environment work fine?
To me, there are some other cases need consideration, e.g. the snapshotProject setting.

https://github.com/vmware-tanzu/velero-plugin-for-gcp/blob/main/velero-plugin-for-gcp/volume_snapshotter.go#L77

And the object store also use project in some logic.

**Comment by mayeco** [comment] 2022-04-07 21:20
> I haven't tried setting like this before, but if the permission is set correctly, it should work.

@blackpiglet is not a permission issue. is a "not found" issue since Velero is trying to backup a disk in a gcp project where the disk not exist.

This is the main issue. setting the volume project_id from the credential and not be able to change it, the credential IS not a reliable source of the project id: https://github.com/vmware-tanzu/velero-plugin-for-gcp/blob/main/velero-plugin-for-gcp/volume_snapshotter.go#L73

- Velero is deployed in Cluster name: gke-01-us-east1
- GKE Cluster Live in project: my-app-dev
- Service account is created in project: sa-projects
- Service account permissions is OWNER in project my-app-dev

`time="2022-04-07T21:00:20Z" level=error msg="Error backing up item" backup=velero/velero-drp-backup-20220407210015 error="error getting volume info: rpc error: code = Unknown desc = googleapi: Error 403: Required 'compute.disks.get' permission for 'projects/sa-projects/zones/us-east1-d/disks/gke-gke-01-us-east1-8d-pvc-46a5aefc-a712-4bca-870d-65cc7fd1d35a', forbidden" logSource="pkg/backup/backup.go:417" name=pvc-demo`

- WRONG: projects/**sa-projects**/zones/us-east1-d/disks/gke-gke-01-us-east1-8d-pvc-46a5aefc-a712-4bca-870d-65cc7fd1d35a 
- GOOD: projects/**my-app-dev**/zones/us-east1-d/disks/gke-gke-01-us-east1-8d-pvc-46a5aefc-a712-4bca-870d-65cc7fd1d35a

**Comment by blackpiglet** [comment] 2022-04-08 15:33
@mayeco 
I understand. Maybe I didn't illustrate myself clearly in previous reply.
I agree with your request to modify how to set project ID in GCP plugin, but I think the current PR may not cover all code that needs project id.

For example.
https://github.com/vmware-tanzu/velero-plugin-for-gcp/blob/main/velero-plugin-for-gcp/volume_snapshotter.go#L77
This line reads project ID from BSL's config key projectKey. Perhaps reuse this key for volumeProject is an alternative solution.

**Comment by mayeco** [comment] 2022-04-11 22:27
does not work. the config setting used to locate the disk is volumeProject and is hard coded from the credential.

https://github.com/vmware-tanzu/velero-plugin-for-gcp/blob/main/velero-plugin-for-gcp/volume_snapshotter.go#L73

**Comment by jenting** [comment] 2022-05-19 15:40
Code merged, close this issue.
Waits for the next Velero GCP plugin release.

**Closed by jenting** 2022-05-19 15:40 UTC
Labels: Area/Cloud/GCP
