### ISSUE TITLE
Add possibility to backup resources in namespaces matching a label

### ISSUE THREAD

**Issue by lorenzofelletti** [vmware-tanzu/velero#8340] opened 2024-10-23 12:02 UTC
**Describe the problem/challenge you have**
On thing I need to do is to backup all resources in namespaces matching a certain label, e.g. all the namespaces having label `backup: true`, or something like that.

**Describe the solution you'd like**
New version of Schedule/Backup spec supporting this option. Something like:
```yaml
apiVersion: velero.io/v2alpha1
kind: Backup
metadata:
  name: a
  namespace: velero
spec:
  namespaceSelector:
    matchLabels:
      backup: "true"
```

Changing the `BackupSpec` type to something like:
```golang
type BackupSpec struct {
    // ...
    NamespaceSelector *metav1.LabelSelector `json:"namespaceSelector,omitempty"`
    // ...
}
```

**Anything else you would like to add:**

**Environment:**

- Velero version (use `v1.14.0`):
- Kubernetes version (use `v1.30.2`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by kaovilai** [comment] 2024-10-23 14:46
if the documentation are unclear please list the pages needing updating.

**Comment by lorenzofelletti** [comment] 2024-10-23 15:13
So labelSelector will backup any resource in the namespace with `backup: true`, regardless if individual resources in that namespace have such label in turn? If that's the current `labelSelector` field then I didn't know it

**Comment by lorenzofelletti** [comment] 2024-10-23 15:18
As per the docs [here](https://velero.io/docs/v1.15/api-types/backup/):
```
  # Individual objects must match this label selector to be included in the backup. Optional.
  labelSelector:
```

To be clear, that is not the behaviour I want to achieve. I'd like to set the label on the namespace object, and have all resources in that namespace backed up (regardless of individual objects labels)

**Comment by kaovilai** [comment] 2024-10-23 15:25
dupe of https://github.com/vmware-tanzu/velero/issues/7492 requirements then. We're saying the said requirements are not met?

**Comment by lorenzofelletti** [comment] 2024-10-23 15:34
Yes, it looks like it is. Closing this one.

**Closed** 2024-10-23 15:35 UTC
