### ISSUE TITLE
Cannot view logs

### ISSUE THREAD

**Issue by reddiablo85** [vmware-tanzu/velero#2537] opened 2020-05-14 14:55 UTC
**What steps did you take and what happened:**
velero installed and appears to be running correctly
executing "velero backup logs velero-hourly-20200514140009"  returns logs in unreadable format. Returns different if executed from powershell or directly from linux node (same kubeconfig env)

UPDATE: It seems to be that the logs are in compressed format. When downloaded and unpacked they can be viewed in notepad
However issue remains that they cannot be viewed directly in the console

**What did you expect to happen:**
Read logs

**The output of the following commands will help us better understand what's going on**:
Sample output:
▒d▒     ▒͠N▒▒▒I▒j▒n▒\)e▒Dߤ"b     ڐū▒J▒@R▒+u▒▒▒▒V▒+u▒eox$>)u▒d|▒Һ▒▒▒$▒▒▒▒=Nբ▒▒▒7▒@▒▒u▒N_*▒3"Tį>\@E▒z;▒5"▒▒\▒$▒▒▒j▒r▒      aA▒c▒&▒m▒▒▒op#▒{▒▒!1▒h٦▒▒▒▒k▒#▒▒@▒*▒͔▒▒t/hrH+L▒▒▒▒▒▒i""|▒<▒▒ǯ▒*▒▒٧~▒▒Z▒▒o▒t▒Q▒5L▒Ŀ▒Xg▒2▒▒d  ▒c▒!▒:▒yn▒lE▒c
▒7▒▒▒
     a▒;(▒▒▒▒
             J▒▒c▒▒▒▒X▒3▒֬j▒▒X▒▒ȿ▒怛ӿ?]▒qN▒(!Q▒PqިZa▒h▒▒▒▒Q+▒ѹe>qT▒▒+
                                                                   ▒▒▒uPu▒*Q▒}▒.>▒Bw▒▒GލBw▒n?v▒(▒s▒▒▒Oe@a▒▒▒,▒52▒▒▒[\▒dG%▒▒n▒▒O▒▒-#qW▒▒▒▒▒▒
▒/▒▒▒▒q▒5▒z▒▒▒▒▒j`▒{▒▒▒8qw▒
▒-Fh▒▒
/▒%▒c▒9▒▒▒x▒F▒
u▒▒%▒2:▒▒▒R▒q▒▒Y▒Bb▒▒QB9▒▒"J▒1▒2ֹb▒▒unKi▒
                                        ▒▒K▒▒r▒K▒Y_[▒▒m΀?▒Hw]~▒▒▒Q▒▒Z▒UV▒}▒$▒s▒▒▒dI▒,7+▒▒4▒▒▒wn▒▒D▒18?U▒▒P▒▒Z%F▒^▒▒▒{▒▒▒)̨▒▒▒}▒▒ؐ▒x7▒T▒#u▒rRW}~f▒?Ĩ?▒▒▒▒%V▒▒▒Ů▒+▒j▒NB▒4ڔ▒▒▒~O▒6▒▒▒▒▒▒▒hS1j▒▒h8b▒^_/ӫ▒SYm▒&▒▒k▒jC▒v▒7▒5Ԇ▒▒▒▒&1▒▒م▒H▒6▒▒▒▒xI▒▒Ń
▒4▒r:▒▒ac▒];▒.▒e▒!▒▒b▒Q▒Xp▒8Ec▒▒*▒▒w▒T#d'!▒z▒▒;▒▒3▒ܹ▒▒t▒▒Qa▒▒u▒Ĩ▒X▒4f▒k▒K▒▒w▒e▒w+▒▒▒Xe/o▒�▒긠    ▒
                                                                                                 ▒\▒▒8▒X0▒g▒▒C▒˱D▒▒▒▒Ҧ▒▒&1▒A▒s▒▒▒H]#b▒0▒▒Y▒▒▒▒FŎ▒▒S▒E▒89[o▒'▒▒▒m▒d▒dA}iYy,▒▒f
                         R▒Ŧ▒▒GNl▒▒QON▒8▒▒▒▒▒1▒~▒<l▒▒F▒▒r▒豶>͔x▒▒#LĘm̼▒!▒
Uj▒ Mu▒▒▒y▒▒b▒gn▒▒Kuu▒▒n~V▒▒▒6▒▒▒Mk͚▒B▒E▒▒-▒4ԩEg4
U▒)MC]֫▒▒$       ▒K~▒▒▒X▒F▒ێ'b/u▒▒▒▒▒s_▒▒▒֪▒X~▒▒F▒f)▒+▒▒S▒▒▒▒J▒▒▒]L       ▒t▒▒P▒t▒▒▒▒L▒▒|▒▒▒벰V▒F▒▒iVE▒▒▒a▒hZ▒7Y▒,▒▒▒|▒O-▒▒▒=(▒.▒F▒▒▒▒U▒▒▒i▒>▒▒▒L▒▒▒5T▒▒\R▒y▒▒▒d_x▒aԩ▒r▒▒{▒Q▒4#.J▒ m0
{▒f▒y▒n▒o▒▒▒▒u▒▒5▒▒▒(▒▒▒Ɇ▒,▒▒{▒!ڬ▒O*xD▒▒L|g|▒g▒▒91$▒(y▒▒▒▒▒▒ZEiz▒▒䣠▒@▒c▒n2:▒▒?▒▒Q▒,▒'_▒▒9▒▒s▒(M▒▒P2٤o▒ 4?▒▒0▒0;▒▒cd▒'ӱO▒1▒G:▒dx▒P▒▒*▒]rU▒i▒▒PP▒d▒*@I$▒hQ=Z▒}ʸ▒~▒Z[Z侳fI$▒N▒▒▒U
▒▒▒3▒5▒.▒a▒▒▒HT-ѯ|
                  ~▒▒▒▒▒▒
                         ▒      bĺ#ֽ▒|▒▒0uRH▒|▒▒▒~▒%▒P?▒b)▒P0▒$&▒▒▒E3p▒▒▒▒Q
▒D▒{=▒▒▒J▒▒8@>▒▒▒▒▒▒▒▒▒▒▒▒3D▒ե|▒▒r▒▒ <w0▒@▒▒▒▒&▒▒▒▒PI▒$▒Ftg▒)▒▒Uۈ% 4>(▒^▒▒3Z+B0▒0▒d/\▒▒▒r▒▒▒f▒▒▒-Z$Ǖ▒▒
                       ̚~[
▒,▒n▒ll▒ ▒t▒p▒Xǈ▒P▒c߱5M▒▒D▒2▒Ì▒ID▒▒▒E▒▒H▒OaB▒▒▒\Є▒▒6B6▒xe▒yÍ`▒▒"
                                                               R▒.▒}▒e4l▒▒▒m#_K▒Rʳ(▒{▒▒▒▒t▒ѱ▒▒▒▒▒▒Y▒my▒~▒cS▒▒!▒▒▒f▒▒)vT▒$▒ǆ     8▒▒▒]▒+▒▒6f▒▒▒▒▒▒C▒▒▒▒u▒Q▒▒▒
nb|▒▒(Dl▒k▒▒$ɌV▒bu▒▒H▒▒'0▒m2F▒▒▒0ʐ(▒lK▒bIaz▒5Jϱ:▒e2▒▒sA▒}▒a▒Rra^▒▒▒[▒
/)٘L$▒#▒▒4z▒;<2▒k*x▒▒▒E▒▒▒▒jT8▒3#▒D&8<▒▒(I▒▒▒*^▒▒9zY▒1▒u▒S▒▒٠8▒▒p▒▒▒'▒&▒▒s;1▒▒UmB▒▒▒"▒▒%ʹL#8▒:▒▒"▒4H     ▒`▒h▒▒
S▒J▒A▒▒m▒▒Q▒▒0▒▒?▒+du▒▒$▒.7▒8!▒▒▒V▒ӕ▒▒V▒▒▒Ҍ▒▒▒▒r▒▒▒▒.▒wa▒▒V▒
&▒蒹˵▒▒V▒m▒▒▒.7▒`G▒▒▒%Ķc▒▒]▒56▒▒▒▒▒▒^▒▒D▒4
!▒▒Ϛ^▒▒[▒▒Xpn▒ݢ.▒▒▒▒;S▒?▒▒▒▒▒▒▒_▒▒▒▒1▒▒qRF▒▒lYJ▒▒hVW▒▒+▒k▒h▒▒#YD▒▒▒e▒G▒▒▒%▒0▒▒▒%lс▒h▒w[x▒h_▒▒U▒%NM▒m▒w2m▒       4kx▒▒X▒Ck▒$▒▒y#▒▒▒`▒▒W▒▒▒▒▒Yo▒▒▒▒5▒▒▒▒M▒▒▒▒b▒/▒U▒Mȍq▒▒ڨ▒cch#▒▒C{jm▒▒[▒Ѳ▒▒▒F▒▒zGj!m▒짓▒ѱ߆▒F▒~▒J{h/mD▒˴▒▒▒f▒F▒^{N▒k=m▒▒▒▒▒▒F▒F▒▒▒QlKm▒▒;▒.▒▒]▒T▒W▒▒▒▒▒F▒;W{h`mDl▒▒▒H֥▒▒.       L▒&ź(Ҷ!▒V▒
0▒[▒▒]▒̸ܶ%▒.U▒3▒Nb▒n▒▒▒(-▒K▒"M▒.▒f<ο8▒▒3▒#[
                                         52▒8\▒g▒▒ٯ▒Gֽ▒:-#▒k▒f}m▒▒n▒-";]▒CZCQUu▒▒@▒}▒▒▒t▒D▒▒▒s▒▒{▒▒>Ia２▒ܑ
▒2▒L▒6▒t{F▒ET@  C▒ۮպ9▒▒▒▒▒Ҝ▒▒Ss▒xJ
                                  ▒ʾ▒m▒▒kq▒G[ʕ▒▒6HX]FgH▒Q▒E,▒te▒▒+▒3L▒▒▒Zi▒#▒▒▒h▒▒
▒$▒▒▒W▒֥▒N▒z▒▒▒z▒▒L▒z▒▒E▒7B'{▒Wk▒▒▒ВFt/hr▒▒d
)▒▒V"▒▒[▒▒/▒a▒D8]\ՉY/▒▒▒9gX▒▒L▒▒▒sX▒ ▒▒d▒r▒ob▒▒.▒▒▒a▒)▒▒0▒8▒J▒▒▒{k$Ͽ▒)▒m▒▒%x|▒`▒▒▒
2▒I▒0▒▒?▒▒)?\▒▒▒▒k▒G▒▒▒▒▒ߘ▒▒▒▒o▒▒▒T29֯IoQ▒?/▒E▒z▒音▒ӗ▒E▒▒▒▒D1▒▒k?▒n▒▒▒j▒(▒▒▒_▒▒▒u▒▒9yK9{▒X`G▒▒1^qv▒f.1N▒▒dM▒▒▒▒▒D▒=I ▒▒c▒J,c▒tBc*▒釜~lh&F▒▒ǽǪ▒▒^▒풘A2#▒xC▒▒pz'|D;:G▒▒S▒▒▒S▒▒L0NG▒G▒c▒▒x@▒▒ٚ▒%▒dtt▒~D▒0b▒▒?<▒▒&▒▒▒K▒R(▒}z▒!▒G▒ӔeǇ<▒L`<▒0N}▒▒▒cɁ▒e▒cQ▒▒{▒▒~>y▒v<?*Y▒▒▒j▒▒3▒3▒&▒▒▒H2~зD▒▒u       h\▒0b▒▒W▒▒▒▒▒,▒i▒dbT?▒▒#F,▒R▒▒▒▒S▒z▒▒9▒▒▒M▒9▒/▒▒▒▒
▒▒v▒Čq%▒▒▒▒▒댜1▒▒0{`▒2[▒\FJoP▒▒▒▒R▒▒ЃF:Y▒▒▒▒lV▒;v▒<▒▒▒▒o%7▒▒▒▒`▒▒;▒▒#▒▒c▒▒▒F▒▒I▒▒▒.▒r4▒▒u▒E▒C▒▒]A*s▒L}t▒▒▒U▒8v▒▒▒*{▒J▒▒ٍ▒▒▒,^[o▒T▒=▒▒▒p▒~▒hM▒▒|_▒L▒▒M▒hM▒▒▒8▒▒▒      ▒u▒,g#5ˮ▒=▒(▒▒▒▒M,ꂖ▒a▒▒b▒▒L`▒1AA▒▒_▒▒I▒C▒@▒▒▒2▒▒▒z▒y▒▒▒▒▒D1▒dtds
▒▒O▒▒▒▒lҷa,h>▒▒/▒ٸ@~▒O#▒q▒m▒▒?з▒▒▒▒tk▒▒=▒g
d;dL▒▒▒▒▒▒B▒xW▒▒▒]      ▒8▒▒}▒▒^▒▒▒▒▒▒!۠?▒^ER▒▒▒▒▒▒▒
▒▒:▒"B1▒▒▒▒▒▒b((▒▒S▒Y▒C!b4▒(▒D▒ٶ▒▒e▒d▒g▒▒▒▒3/▒▒▒▒▒▒▒֫▒ߓ▒5▒▒▒▒ ▒s2▒=▒hͰ▒b▒|Fؖj▒&ؖl▒X▒D!S▒▒7~▒▒▒▒▒&▒ҷ▒ۄ▒<▒jx▒▒▒▒▒▒RW▒▒▒▒▒T}8P?d▒▒$^▒▒▒v ▒cv▒Ɇ؁▒▒▒XC▒▒
.𕂔▒#▒}▒▒qt=̞▒b>▒▒g]▒▒%3g=X▒|,J~▒5▒P@▒c]▒F▒>e\P▒xCA▒_f▒|G▒▒P▒▒t:▒▒▒Y"8▒▒N0▒
                                                                         ʍnut▒
▒~▒▒▒W)▒ݎ▒▒▒6▒▒▒X▒▒o 0▒?▒▒%R▒▒<}▒A▒▒▒K▒ˎ2▒▒3b▒ɋ[▒>▒▒{|KAZa▒▒▒l▒2*▒*▒$,▒}uF▒▒u▒▒ݵ▒▒u▒▒Ɣ▒։D▒▒▒^▒ZST▒▒
                                                                                      w▒▒l̜▒▒▒4▒▒i▒▒5=▒▒▒
                                                                                                        z~▒▒5▒▒▒]▒▒▒L▒▒ImkI▒▒HmYR[SWGj-G3K▒▒▒▒r4▒▒▒▒▒▒L▒▒t>▒1▒▒ߠ▒#▒q4Ӎ▒▒r4▒▒▒▒'▒f▒0▒}Y▒▒|▒
▒ʷ▒뼤▒V▒▒▒n<▒\▒▒▒4*s;qd L▒%▒▒Z▒j▒▒▒Yoh^▒▒▒▒<▒▒}▒u▒&J▒f▒^.~▒▒tD▒▒ي▒▒ ▒`D▒▒5[uωk▒▒ˌ▒▒#Ƨ3p▒
                                                                                        ▒a
▒▒▒▒▒-▒H▒c▒▒▒hR▒▒▒w▒▒▒L;b[3b[▒▒▒▒
                                 `s▒▒?▒▒.V▒i[root@####### ~]# PuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTY
-bash: PuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTY: 

(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by ashish-amarnath** [comment] 2020-05-15 22:17
@reddiablo85 
I am assuming you are using minio for your backup storage location.
Can you please follow the instructions in the **Accessing logs with an HTTPS endpoint** section at https://velero.io/docs/v1.4-pre/contributions/minio/

**Comment by skriss** [comment] 2020-05-20 16:59
@reddiablo85 just checking in again to see if you were able to resolve this with ashish's pointer.

**Comment by reddiablo85** [comment] 2020-05-26 13:12
> @reddiablo85
> I am assuming you are using minio for your backup storage location.
> Can you please follow the instructions in the **Accessing logs with an HTTPS endpoint** section at https://velero.io/docs/v1.4-pre/contributions/minio/ and let us know if that fixes your problem?

Hi @ashish-amarnath we aren´t using minio....we are using Storage Grid by NetApp.

**Comment by ashish-amarnath** [comment] 2020-06-01 21:14
@reddiablo85 I am not super familiar with the Storage Grid. However, I think the steps in the "Accessing logs with an HTTPS endpoint" section of the document https://velero.io/docs/v1.4/contributions/minio/ can still be applicable to your scenario.

**Comment by skriss** [comment] 2020-06-09 19:28
@reddiablo85 were you able to get this sorted out using the instructions Ashish linked to?

**Comment by reddiablo85** [comment] 2020-06-09 20:20
@skriss no this isn´t the root of the issue unfortunately. I tried changing the the target of the S3 to its IP rather than its hostname and no improvement. We are currently backing up over HTTP anyway, at least until we have this resolved and can then implement HTTPS. We have a call early next week with our S3 provider to try and drill down the issue as it certainly seems to be on their end. Perhaps something to do with the headers / file-type they are applying to the files

**Comment by fvsqr** [comment] 2020-06-25 07:01
I was able to reproduce the issue @reddiablo85 described on my side with StorageGrid. 

It seems that the reason is because of this line https://github.com/vmware-tanzu/velero/blob/master/pkg/cmd/util/downloadrequest/downloadrequest.go#L144 
The request header Accept-Encoding is explicitly set to 'gzip' and that causes StorageGrid to encode the requested object with gzip. For me this sounds like the expected behaviour. In the specific situation of downloading the velero log file, which is already gzipped, this results in gzipping a second time. However on the client side, the object responded by the S3 storage is decompressed only once and outputted in binary format as we see in the issue description.

My workaround for now is to comment the appropriate line and recompile the velero binary - but of course I don't want to do this every time a new velero version is released.

I'd be more than happy to provide a Pull Request, but the Accept-Header setting seems - according to the comment - necessary for some S3 cloud providers. Again, I think the general behaviour of StorageGrid is correct. We can discuss. BTW: because of the second gzip run the transferred object also gets bigger in size.

Anyway, maybe we can find together a way to either check the content of the file before copying (and decompress again?) or check wether StorageGrid is the S3 storage, etc... I see a couple of options.

**Comment by carlisia** [comment] 2020-07-08 13:48
@fvsqr we would love it if you could add a PR for this. Thank you.

**Comment by fvsqr** [comment] 2020-07-10 14:40
sorry for the delayed response. Before I add a PR, I will check next week, whether the change have a negative impact on my minio setup.

However, I'm still concerned about the comment regarding the cloud providers (see my previous post). I don't think I have the resources to check whether it functions with GCP and Azure. Do you have a test setup for the cloud providers?

BTW: I'm not very into the velero development - do you have guidelines for PR? Or just a PR to the main branch?

**Comment by ashish-amarnath** [comment] 2020-07-17 18:06
@reddiablo85 Does @fvsqr 's PR #2712 fix the issue you are seeing?

**Comment by reddiablo85** [comment] 2020-07-20 07:53
> @reddiablo85 Does @fvsqr 's PR #2712 fix the issue you are seeing?

Yes, this adjustment in the executable solved the issue
Thanks

**Comment by ashish-amarnath** [comment] 2020-07-20 16:04
Thanks for confirming @reddiablo85 .

**Closed** 2020-07-20 17:11 UTC
Labels: Needs info, Needs investigation
