### ISSUE TITLE
AWS S3: Consider distributing objects across multiple prefixes

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#7278] opened 2024-01-05 13:56 UTC
To resolve or avoid 5xx status errors, try the following approaches:

- For the application that makes the requests, use a retry mechanism
- Configure your application to increase request rates gradually.
- Consider distributing objects across multiple prefixes
- Monitor the number of 5xx error responses.

[src](https://repost.aws/knowledge-center/http-5xx-errors-s3#:~:text=To%20resolve%20or,5xx%20error%20responses.)

_Originally posted by @kaovilai in https://github.com/vmware-tanzu/velero/issues/5856#issuecomment-1878699723_

**Comment by reasonerjt** [comment] 2024-01-08 02:25
@kaovilai 

To make it more self-contained,  could you provide more background about the problem in this issue?

I wish to understand more details about the requirement to have an opinion whether it's valid.

**Comment by kaovilai** [comment] 2024-01-08 02:36
The background for this issue is that aws s3 service could be throttled at times and to reduce the need to retry they suggested that multiple prefixes be used to spread out the load.

https://github.com/vmware-tanzu/velero/issues/5856

**Comment by reasonerjt** [comment] 2024-01-08 02:56
But that's for concurrent write situations, right?

Per my understanding different prefixes are needed when different users try to write content to the same location, but currently given a single BSL of velero can configure on prefix, we should ask velero user to use different BSLs for different backups. right?

I assume we don't wanna allow storing one backup into different BSLs or different prefixes?

**Comment by blackpiglet** [comment] 2024-01-08 03:21
The original issue is `Velero should retry backup bundle upload if fails due to some bucket related issues`.
It looks like that is not specific to resolving throttle caused by multiple prefixes scenario.

**Comment by reasonerjt** [comment] 2024-01-08 03:27
> The original issue is Velero should retry backup bundle upload if fails due to some bucket related issues.
> It looks like that is not specific to resolving throttle caused by multiple prefixes scenario

So is this issue needed?

**Comment by kaovilai** [comment] 2024-01-08 05:24
Reading https://stackoverflow.com/questions/52443839/s3-what-exactly-is-a-prefix-and-what-ratelimits-apply makes me think that this could be needed when we start solving for https://github.com/vmware-tanzu/velero/issues/2587 could start multiple uploads enough per second to trigger throttle.. especially if user and admins are doing per app schedule backups and also having a schedule for a whole cluster backup.

**Comment by kaovilai** [comment] 2024-01-08 05:24
It's not immediately needed. Just a note for future work.

**Comment by kaovilai** [comment] 2024-01-08 05:28
This issue could become unnecessary also should we implement retry mechanism #5856 .

**Comment by reasonerjt** [comment] 2024-01-08 05:40
To be honest I also think retrying on ratelimit issue is not the right approach, it may make velero tolerant for misconfiguration, but we exposing the issue more explicitly may be better for the end user.

**Closed** 2024-01-08 06:17 UTC
Labels: kind/requirement, repository

**Comment by kaovilai** [comment] 2024-01-08 06:19
The cause for throttling from the s3 service do not have to be caused by the velero user, it could be caused by external factors such as a black friday or 11/11 sale surging s3 usage
