### ISSUE TITLE
AWS Plugin v1.1.0: NotImplemented: A header you provided implies functionality that is not implemented

### ISSUE THREAD

**Issue by dperezro** [vmware-tanzu/velero#3313] opened 2021-01-20 22:16 UTC
**What steps did you take and what happened:**
I created an scheduled backup with:
`velero schedule create prod-daily --schedule="30 22 * * *" --ttl 168h0m0s --exclude-resources pods --kubecontext prod`

But with above schedule, after a while backing up, when trying to upload to a GCS bucket via Minio, it said the following:

```
time="2021-01-20T21:24:44Z" level=info msg="Found associated CRD machineconfigs.machineconfiguration.openshift.io to add to backup" backup=velero/prod-daily-20210120212309 logSource="pkg/backup/backup.go:476"
time="2021-01-20T21:24:44Z" level=info msg="Skipping item because it's already been backed up." backup=velero/prod-daily-20210120212309 logSource="pkg/backup/item_backupper.go:115" name=machineconfigs.machineconfiguration.openshift.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2021-01-20T21:24:44Z" level=info msg="Backed up a total of 13803 items" backup=velero/prod-daily-20210120212309 logSource="pkg/backup/backup.go:419" progress=
time="2021-01-20T21:24:44Z" level=info msg="Setting up backup store to persist the backup" backup=velero/prod-daily-20210120212309 logSource="pkg/controller/backup_controller.go:632"
time="2021-01-20T21:24:44Z" level=error msg="Error uploading log file" backup=prod-daily-20210120212309 bucket=ext-prod-config-backups error="rpc error: code = Unknown desc = error putting object backups/prod-daily-20210120212309/prod-daily-20210120212309-logs.gz: NotImplemented: A header you provided implies functionality that is not implemented\n\tstatus code: 501, request id: 165C0DBFCD9E855B, host id: " error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:257" error.function="main.(*ObjectStore).PutObject" logSource="pkg/persistence/object_store.go:203" prefix=
time="2021-01-20T21:24:44Z" level=info msg="Backup completed" controller=backup logSource="pkg/controller/backup_controller.go:642"
time="2021-01-20T21:24:44Z" level=error msg="backup failed" controller=backup error="rpc error: code = Unknown desc = error putting object backups/prod-daily-20210120212309/velero-backup.json: NotImplemented: A header you provided implies functionality that is not implemented\n\tstatus code: 501, request id: 165C0DBFCE0B99BB, host id: " key=velero/prod-daily-20210120212309 logSource="pkg/controller/backup_controller.go:279"
```

**What did you expect to happen:**
Backup should have completed and being uploaded.

**The output of the following commands will help us better understand what's going on**:

- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
```
Name:         prod-daily-20210120212309
Namespace:    velero
Labels:       velero.io/schedule-name=prod-daily
              velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.18.3
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=18+

Phase:  Failed (run `velero backup logs prod-daily-20210120212309` for more information)

Errors:    0
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        pods
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  168h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-01-20 22:23:09 +0100 CET
Completed:  2021-01-20 22:24:44 +0100 CET

Expiration:  2021-01-27 22:23:09 +0100 CET

Total items to be backed up:  13803
Items backed up:              13803

Velero-Native Snapshots: <none included>
```

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):  v1.5.3
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`): v1.18.3

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by carlisia** [comment] 2021-01-25 17:57
Hi. May I please have the output of `velero get backup-location -o yaml`?

**Comment by nrb** [comment] 2021-01-25 20:25
@dperezro This appears to be something being passed back from Minio; I'd suggest using the GCP plugin directly if you can.

**Comment by dperezro** [comment] 2021-01-26 10:35
> @dperezro This appears to be something being passed back from Minio; I'd suggest using the GCP plugin directly if you can.

Thing is, the hosts are run in Google but the intention is to be as much cloud agnostic as it can be, because the solution will be run in other clouds as well.

**Comment by dperezro** [comment] 2021-01-26 10:37
> velero get backup-location -o yaml

Sure!

```apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"velero.io/v1","kind":"BackupStorageLocation","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"component":"velero"},"name":"default","namespace":"velero"},"spec":{"config":{"region":"minio","s3ForcePathStyle":"true","s3Url":"https://minio.minio.svc:9000","serverSideEncryption":"AES256"},"objectStorage":{"bucket":"XXXXX"},"provider":"aws"}}
  creationTimestamp: "2021-01-20T16:56:38Z"
  generation: 2
  labels:
    component: velero
  managedFields:
  - apiVersion: velero.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:component: {}
      f:spec:
        .: {}
        f:config:
          .: {}
          f:region: {}
          f:s3ForcePathStyle: {}
          f:s3Url: {}
          f:serverSideEncryption: {}
        f:objectStorage:
          .: {}
          f:bucket: {}
        f:provider: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-01-20T16:56:38Z"
  - apiVersion: velero.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:objectStorage:
          f:caCert: {}
    manager: kubectl-patch
    operation: Update
    time: "2021-01-20T16:59:24Z"
  - apiVersion: velero.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:lastSyncedTime: {}
        f:lastValidationTime: {}
        f:phase: {}
    manager: velero-server
    operation: Update
    time: "2021-01-26T10:34:59Z"
  name: default
  namespace: velero
  resourceVersion: "83390629"
  selfLink: /apis/velero.io/v1/namespaces/velero/backupstoragelocations/default
  uid: aa9e087a-d639-4b9d-ae4d-5ee823c42731
spec:
  config:
    region: minio
    s3ForcePathStyle: "true"
    s3Url: https://minio.minio.svc:9000
    serverSideEncryption: AES256
  objectStorage:
    bucket: XXXXXX
    caCert: <CERTIFICATE>
  provider: aws
status:
  lastSyncedTime: "2021-01-26T10:34:58Z"
  lastValidationTime: "2021-01-26T10:34:59Z"
  phase: Available
```

**Comment by zubron** [comment] 2021-01-26 14:55
The only thing in your BSL config that would cause an additional header to be added is the `serverSideEncryption` but this is supported in the GCS gateway. You could try removing that part of the config though to verify that it is not the cause of the issue.

Otherwise, this seems like a limitation with Minio (see "Known Limitations" here: https://docs.min.io/docs/minio-gateway-for-gcs.html). I'd suggest looking at the [policies applied to your GCS bucket](https://cloud.google.com/storage/docs/access-control#choose_between_uniform_and_fine-grained_access) as it looks like the Minio GCS gateway only supports fine grained permissions: https://github.com/minio/minio/issues/11292

Given that this is most likely something within Minio and not something the Velero team can take action on, I'm going to close this issue. If you find something that would enable Velero to work around this though, feel free to reopen.

**Closed by zubron** 2021-01-26 14:55 UTC
Labels: Needs info, Needs investigation

**Comment by dperezro** [comment] 2021-01-27 13:32
After checking further, I think the problem is related to Minio. I will close this one, thanks!

**Comment by dperezro** [comment] 2021-02-17 10:00
Do you have any insight about this?
