### ISSUE TITLE
velero 1.9.1 unable to delete partially failed backup

### ISSUE THREAD

**Issue by vineetsingh5** [vmware-tanzu/velero#5354] opened 2022-09-17 17:27 UTC
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I have created a backup using velero 1.9.1 and NFS server s object-store. Backup got failed due to some CSI snapshot issue. 
I checked nfs server backup, no data was present so I tried to delete backup using the backup delete command. Now backup is stuck in Deleting state

> velero backup create <backup name>
>velero backup delete <backup name>

**What did you expect to happen:**
Velero should be able to delete partially failed backups. 
I can see some similar issues fixed here https://github.com/vmware-tanzu/velero/pull/4817 but i am seeing same issue with velero 1.9.1

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

`
t@server0 UiPath_Installer]# bin/velero backup describe manualbackup
Name:         manualbackup
Namespace:    velero
Labels:       velero.io/storage-location=objectstore
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.21.4+rke2r2
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=21

Phase:  Deleting

Errors:    0
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  redis-system, security-system, velero, rook-ceph, cattle-system, cattle-fleet-clusters-system, cattle-fleet-system, cattle-global-data, cattle-global-nt, cattle-impersonation-system, fleet-default, fleet-local, local

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  included

Label selector:  <none>

Storage Location:  objectstore

Velero-Native Snapshot PVs:  auto

TTL:  8760h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2022-09-17 16:18:54 +0000 UTC
Completed:  2022-09-17 17:01:59 +0000 UTC

Expiration:  2023-09-17 16:18:54 +0000 UTC

Total items to be backed up:  4822
Items backed up:              4822

Velero-Native Snapshots: <none included>

Deletion Attempts (1 failed):
  2022-09-17 17:08:11 +0000 UTC: Processed
  Errors:
    rpc error: code = Unknown desc = open /var/velero-local-volume-provider/asbackup/backups/manualbackup: no such file or directory
`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): v1.9.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4+rke2r2", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-29T22:29:54Z", GoVersion:"go1.16.6b7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4+rke2r2", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-29T22:29:54Z", GoVersion:"go1.16.6b7", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
RHEL 8.2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

[velero.log](https://github.com/vmware-tanzu/velero/files/9592265/velero.log)

[bundle-2022-09-17-17-22-30.tar.gz](https://github.com/vmware-tanzu/velero/files/9592267/bundle-2022-09-17-17-22-30.tar.gz)

**Comment by Lyndon-Li** [comment] 2022-11-15 03:36
@vineetsingh5 

> I checked nfs server backup, no data was present
How did this happen? Did you delete the backup data from nfs server manually, or the backup data failed to be saved due to some nfs server problem (i.e., nfs was unmounted suddenly), or Velero backup failed to save the data due to Velero's own problem?

**Comment by Lyndon-Li** [comment] 2022-11-15 03:39
The failure of deletion problem is basically clear:
When deleting a backup, Velero first tries to download the related backup metadata and delete all the related objects accordingly
If any problem happens during the download, the deletion process will abort

**Comment by vineetsingh5** [comment] 2022-12-07 05:55
@Lyndon-Li Velero failed to save the data due to some issue during cluster backup. I am not 100% sure if this is Valero's issue or a plugin that we use to copy backup metadata but I don't see any data available for this backup on NFS server

**Comment by reasonerjt** [comment] 2023-02-06 10:16
@vineetsingh5 

I don't reproduce this issue using the latest codebase, which should have identical logic in terms of backup deletion controller.

Additionally, from the log messages of velero pod:
```
 cat ./velero.log|grep "backup=manualbackup"|grep "controller=backup-deletion" | grep -v "level=debug"
time="2022-09-17T17:08:11Z" level=info msg="Removing existing deletion requests for backup" backup=manualbackup controller=backup-deletion deletebackuprequest=velero/manualbackup-7v2v8 logSource="pkg/controller/backup_deletion_controller.go:414"
time="2022-09-17T17:08:11Z" level=error msg="Unable to download tarball for backup manualbackup, skipping associated DeleteItemAction plugins" backup=manualbackup controller=backup-deletion deletebackuprequest=velero/manualbackup-7v2v8 error="error copying Backup to temp file: rpc error: code = Unknown desc = open /var/velero-local-volume-provider/asbackup/backups/manualbackup/manualbackup.tar.gz: no such file or directory" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/restore_controller.go:597" error.function=github.com/vmware-tanzu/velero/pkg/controller.downloadToTempFile logSource="pkg/controller/backup_deletion_controller.go:254"
time="2022-09-17T17:08:11Z" level=info msg="Removing PV snapshots" backup=manualbackup controller=backup-deletion deletebackuprequest=velero/manualbackup-7v2v8 logSource="pkg/controller/backup_deletion_controller.go:278"
time="2022-09-17T17:08:11Z" level=info msg="Removing restic snapshots" backup=manualbackup controller=backup-deletion deletebackuprequest=velero/manualbackup-7v2v8 logSource="pkg/controller/backup_deletion_controller.go:303"
time="2022-09-17T17:08:12Z" level=info msg="Removing backup from backup storage" backup=manualbackup controller=backup-deletion deletebackuprequest=velero/manualbackup-7v2v8 logSource="pkg/controller/backup_deletion_controller.go:311"
time="2022-09-17T17:08:12Z" level=info msg="Removing restores" backup=manualbackup controller=backup-deletion deletebackuprequest=velero/manualbackup-7v2v8 logSource="pkg/controller/backup_deletion_controller.go:317"
time="2022-09-17T17:08:12Z" level=info msg="Reconciliation done" backup=manualbackup controller=backup-deletion deletebackuprequest=velero/manualbackup-7v2v8 logSource="pkg/controller/backup_deletion_controller.go:383"
```

The backup should have been deleted successfully.

Therefore, this seems like a race condition that some other controller is making update to the backup CR making it not deleted.

Would you mind double checking you environment?

**Comment by reasonerjt** [comment] 2023-03-01 00:50
Closing as not-reproducible.

**Closed by reasonerjt** 2023-03-01 00:50 UTC
Labels: Needs info, status/not-reproducible
