### ISSUE TITLE
Invalid memory address on Velero restore operation

### ISSUE THREAD

**Issue by nikoshet** [vmware-tanzu/velero#7494] opened 2024-03-05 13:14 UTC
**What steps did you take and what happened:**
Hello,
Based on a scheduled backup that takes place every 3 days, I am trying to do an on-demand restore on a specific namespace using a resource modifier configmap so as to overwrite some annotations and the StorageClass name.

```bash
$ velero backup create data-backup --include-namespaces source-namespace --include-resources pv,pvc
```
After some time I get:
```bash
$ velero backup get
NAME          STATUS      ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
data-backup   Completed   0        0          2024-03-05 14:15:06 +0200 EET   29d       default            <none>
```
However, when I try to do a velero restore operation:
```bash
$ velero restore create data-restore-test-namespace-$(date +'%Y%m%d%H%M%S') --from-backup data-backup --namespace-mappings source-namespace:test-namespace --resource-modifier-configmap resource-modified-rule-ebs-test-namespace --existing-resource-policy update

$ velero restore get
NAME                                               BACKUP        STATUS      STARTED                         COMPLETED                       ERRORS   WARNINGS   CREATED                         SELECTOR
data-restore-test-namespace-20240305141714         data-backup   Failed   2024-03-05 14:17:15 +0200 EET   2024-03-05 14:17:16 +0200 EET   0        0          2024-03-05 14:17:15 +0200 EET   <none>
```

I am using the Helm Chart of Velero in Kubernetes, so the logs with the error are the following:
```bash
velero-597cc879d-5drjp velero time="2024-03-05T11:42:49Z" level=debug msg="received EOF, stopping recv loop" cmd=/plugins/velero-plugin-for-csi err="rpc error: code = Unavailable desc = error reading from server: EOF" logSource="pkg/plugin/clientmgmt/process/logrus_adapter.go:75" pluginName=stdio restore=velero/data-restore-test-namespace-20240305141714
velero-597cc879d-5drjp velero time="2024-03-05T11:42:49Z" level=debug msg="plugin process exited" cmd=/plugins/velero-plugin-for-csi logSource="pkg/plugin/clientmgmt/process/logrus_adapter.go:75" path=/plugins/velero-plugin-for-csi pid=134 restore=velero/data-restore-test-namespace-20240305141714
velero-597cc879d-5drjp velero time="2024-03-05T11:42:49Z" level=debug msg="plugin exited" cmd=/plugins/velero-plugin-for-csi logSource="pkg/plugin/clientmgmt/process/logrus_adapter.go:75" restore=velero/data-restore-test-namespace-20240305141714
velero-597cc879d-5drjp velero time="2024-03-05T11:42:49Z" level=info msg="Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference" controller=restore controllerGroup=velero.io controllerKind=Restore logSource="/go/pkg/mod/github.com/bombsimon/logrusr/v3@v3.0.0/logrusr.go:108" name=data-restore-test-namespace-20240305141714 namespace=velero reconcileID="\"494f8559-c6ee-418b-875f-b7b71ec1955e\"" restore="{\"name\":\"data-restore-test-namespace-20240305141714\",\"namespace\":\"velero\"}"
velero-597cc879d-5drjp velero panic: runtime error: invalid memory address or nil pointer dereference [recovered]
velero-597cc879d-5drjp velero 	panic: runtime error: invalid memory address or nil pointer dereference
velero-597cc879d-5drjp velero [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a512a8]
velero-597cc879d-5drjp velero
velero-597cc879d-5drjp velero goroutine 860 [running]:
velero-597cc879d-5drjp velero sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
velero-597cc879d-5drjp velero 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:118 +0x19c
velero-597cc879d-5drjp velero panic({0x1de0c60, 0x3bac510})
velero-597cc879d-5drjp velero 	/usr/local/go/src/runtime/panic.go:884 +0x1f4
velero-597cc879d-5drjp velero github.com/vmware-tanzu/velero/pkg/restore.hasCSIVolumeSnapshot(0x40007c0000, 0x400000fa50)
velero-597cc879d-5drjp velero 	/go/src/github.com/vmware-tanzu/velero/pkg/restore/restore.go:1979 +0xf8
```

After that, the Kubernetes Velero pod restarts, and this happens everytime I execute _velero restore_.

**_Important_**: The restore operation was working without any issues for 3 weeks straight using the same version and a few velero backup operations took place in the meantime.

**What did you expect to happen:**

Velero should be able to restore the backed up PV/PVCs to the target namespace.

**The following information will help us better understand what's going on**:

Apart from the above details, I can't provide any more insights since the backup operation is in Completed state, and there are no logs for the restore operation:
```bash
$ velero restore logs data-restore-test-namespace-20240305141714
An error occurred: file not found
```

**Anything else you would like to add:**

**Environment:**

- Velero version: 1.12.3
- Velero plugins: velero-plugin-for-csi:v0.6.3, velero-plugin-for-aws:v1.8.2
- Kubernetes version: 1.29
- Cloud provider or hardware configuration: AWS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by allenxu404** [comment] 2024-03-06 06:17
@blackpiglet can you help take a look?

The panic seems to result from the volumeSnapshot.spec.Source.PersistentVolumeClaimName being nil in this case.
https://github.com/vmware-tanzu/velero/blob/684f71306e9c2fda204a16cb012dc209523cfae1/pkg/restore/restore.go#L1979

**Comment by blackpiglet** [comment] 2024-03-06 07:59
@allenxu404 
Sure. I will work on the fix.

**Comment by blackpiglet** [comment] 2024-03-07 02:46
@nikoshet 
[There](https://github.com/vmware-tanzu/velero/blob/684f71306e9c2fda204a16cb012dc209523cfae1/pkg/restore/restore.go#L1979)

This piece of code didn't check the pointer before using it, but, I couldn't figure out a case that could trigger this issue.
Could you share more information about your scenario?
It's better to collect the debug bundle of the Velero backup. The command is `velero debug`.
And could you share the restore-resource modifier's content?

**Comment by nikoshet** [comment] 2024-03-08 14:02
@blackpiglet 
Hello,
Regarding the resource-modifer CM:
```
apiVersion: v1
data:
  resourcemodifierrule.yaml: |
    version: v1
    resourceModifierRules:
    - conditions:
        groupResource: persistentvolumeclaims
        resourceNameRegex: "ebs-mongo-claim"
        namespaces:
        - test-namespace
      patches:
      - operation: replace
        path: "/spec/storageClassName"
        value: "ebs-mongo-test-namespace-sc"
      - operation: replace
        path: "/metadata/labels/environment"
        value: "test-namespace"
      - operation: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "test-namespace"
kind: ConfigMap
``` 

The StorageClass already exists.
Regarding the bundle of velero backup json:

```
{
    "apiVersion": "velero.io/v1",
    "items": [
        {
            "apiVersion": "velero.io/v1",
            "kind": "Backup",
            "metadata": {
                "annotations": {
                    "velero.io/resource-timeout": "10m0s",
                    "velero.io/source-cluster-k8s-gitversion": "v1.29.0-eks-c417bb3",
                    "velero.io/source-cluster-k8s-major-version": "1",
                    "velero.io/source-cluster-k8s-minor-version": "29+"
                },
                "creationTimestamp": "2024-03-08T07:54:04Z",
                "generation": 10,
                "labels": {
                    "velero.io/storage-location": "default"
                },
                "managedFields": [
                    {
                        "apiVersion": "velero.io/v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:metadata": {
                                "f:annotations": {
                                    ".": {},
                                    "f:velero.io/resource-timeout": {},
                                    "f:velero.io/source-cluster-k8s-gitversion": {},
                                    "f:velero.io/source-cluster-k8s-major-version": {},
                                    "f:velero.io/source-cluster-k8s-minor-version": {}
                                },
                                "f:labels": {
                                    ".": {},
                                    "f:velero.io/storage-location": {}
                                }
                            },
                            "f:spec": {
                                "f:csiSnapshotTimeout": {},
                                "f:defaultVolumesToFsBackup": {},
                                "f:itemOperationTimeout": {},
                                "f:snapshotMoveData": {},
                                "f:storageLocation": {},
                                "f:ttl": {},
                                "f:volumeSnapshotLocations": {}
                            },
                            "f:status": {
                                "f:backupItemOperationsAttempted": {},
                                "f:backupItemOperationsCompleted": {},
                                "f:completionTimestamp": {},
                                "f:csiVolumeSnapshotsAttempted": {},
                                "f:csiVolumeSnapshotsCompleted": {},
                                "f:expiration": {},
                                "f:formatVersion": {},
                                "f:phase": {},
                                "f:progress": {
                                    ".": {},
                                    "f:itemsBackedUp": {},
                                    "f:totalItems": {}
                                },
                                "f:startTimestamp": {},
                                "f:version": {}
                            }
                        },
                        "manager": "velero-server",
                        "operation": "Update",
                        "time": "2024-03-08T08:03:20Z"
                    }
                ],
                "name": "data-backup",
                "namespace": "velero",
                "resourceVersion": "688856329",
                "uid": "084bb809-7c79-428e-9b63-4daa8dc7c619"
            },
            "spec": {
                "csiSnapshotTimeout": "10m0s",
                "defaultVolumesToFsBackup": false,
                "hooks": {},
                "includedNamespaces": [
                    "datacore"
                ],
                "includedResources": [
                    "pv",
                    "pvc"
                ],
                "itemOperationTimeout": "4h0m0s",
                "metadata": {},
                "snapshotMoveData": false,
                "storageLocation": "default",
                "ttl": "720h0m0s",
                "volumeSnapshotLocations": [
                    "aws"
                ]
            },
            "status": {
                "backupItemOperationsAttempted": 4,
                "backupItemOperationsCompleted": 4,
                "completionTimestamp": "2024-03-08T08:03:20Z",
                "csiVolumeSnapshotsAttempted": 2,
                "csiVolumeSnapshotsCompleted": 2,
                "expiration": "2024-04-07T07:54:04Z",
                "formatVersion": "1.1.0",
                "phase": "Completed",
                "progress": {
                    "itemsBackedUp": 9,
                    "totalItems": 9
                },
                "startTimestamp": "2024-03-08T07:54:04Z",
                "version": 1
            }
        }
    ],
    "kind": "BackupList",
    "metadata": {
        "continue": "",
        "resourceVersion": "689547952"
    }
}
```

**Comment by nikoshet** [comment] 2024-03-12 17:10
@blackpiglet 
No namespace is backed-up and no namespace is deleted. I only backup the PV/PVC in a specific namespace.

**Comment by blackpiglet** [comment] 2024-03-13 03:01
Got it. 
The scenario should be similar. The VolumeSnapshot created by the previous restore involves the next same-name backup.

**Comment by Miraj50** [comment] 2024-08-28 18:55
Hi @blackpiglet, even after the fix that you have checked in, we saw a nil pointer dereference error during restore in one of our customer's cluster. According to the stack trace, it still occurs in this line:
`if pv.Spec.ClaimRef.Name == *vs.Spec.Source.PersistentVolumeClaimName &&`

It's difficult to gather any more data on what is the seq of events in the customer's cluster that could lead to this. Wished to check with you if by any chance, `vs.Spec.Source` could be nil or anything else that we might have missed here.

**Comment by blackpiglet** [comment] 2024-08-29 03:08
@Miraj50 
I don't think `vs.Spec.Source` could be nil. It's not a pointer.
If there is still a crash caused by a nil pointer, the reason should be the `pv.Spec.ClaimRef`.
That means the PV doesn't have any PVC binding. I will check when that could happen.

https://github.com/kubernetes-csi/external-snapshotter/blob/533a2ee13a39cc4e568fb9181bdac4c2a7d03bd6/client/apis/volumesnapshot/v1/types.go#L74-L80

**Comment by blackpiglet** [comment] 2024-08-29 03:12
I will create a PR to address this issue.

**Closed** 2024-09-04 02:39 UTC
