### ISSUE TITLE
Backup partially fails for postgres-helm (ArgoCD) with Velero - VolumeSnapshot not found

### ISSUE THREAD

**Issue by dfourakis** [vmware-tanzu/velero#8346] opened 2024-10-24 13:08 UTC
**Issue Description:**
 When running a Velero backup for a PostgreSQL Helm deployment via ArgoCD, the backup process results in a PartiallyFailed status. The error indicates that a VolumeSnapshot cannot be found.

**Deploy PostgreSQL using Helm via ArgoCD.**

**Commands:**

- Create bucket:
```bash
velero backup create postgres-helm --include-namespaces postgres-helm  --wait --default-volumes-to-fs-backup=false -n velero
```

- Describe Backup:
```bash
velero backup describe postgres-helm -n velero
```

The error:
    
```
Velero: name: /postgres-postgresql-0 message: /Error backing up item error: /error executing custom action (groupResource=volumesnapshots.snapshot.storage.k8s.io, namespace=postgres-helm, name=velero-data-postgres-postgresql-0-qskk9): rpc error: code = Unknown desc = failed to get volumesnapshot postgres-helm/velero-data-postgres-postgresql-0-qskk9: volumesnapshots.snapshot.storage.k8s.io "velero-data-postgres-postgresql-0-qskk9" not found
```

****
**About Snapshots:**

```bash
kubectl get volumesnapshot -A
```
```
No resources found
```

```bash
kubectl get volumesnapshotcontents -A
```
```
NAME                                               READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER             VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT                              VOLUMESNAPSHOTNAMESPACE   AGE
snapcontent-0e43a509-d531-4f32-a355-0c807dee03c5   true         1073741824    Retain           csi.scaleway.com   scw-snapshot-retain   velero-data-postgres-postgresql-0-fptb8     postgres-helm             3h21m
snapcontent-10f338f0-61aa-4fd1-b80d-c544849f2fc1   true         1073741824    Retain           csi.scaleway.com   scw-snapshot-retain   velero-data-postgres-postgresql-0-z728v     postgres-helm             3h15m
```

```bash
kubectl get volumesnapshotclass
```
```
NAME                  DRIVER             DELETIONPOLICY   AGE
scw-snapshot          csi.scaleway.com   Delete           13d
scw-snapshot-retain   csi.scaleway.com   Retain           13d
```
****

Can someone help resolve the error?

****
**Environment**:

- **Velero version**:
    - Client: v1.15.0-rc.1
    - Server: v1.15.0-rc.1
- **Kubernetes version**:
    - v1.30.2
- **PostgreSQL deployment via**: Helm (with **ArgoCD**)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by weshayutin** [comment] 2024-10-24 13:27
@shubham-pampattiwar FYI

**Comment by kaovilai** [comment] 2024-10-25 14:50
duplicate of https://github.com/vmware-tanzu/velero/issues/7905, please follow there

**Comment by reasonerjt** [comment] 2024-10-28 06:33
Thanks @kaovilai I'm closing this one as a dup.

**Closed by reasonerjt** 2024-10-28 06:33 UTC
Labels: env/has/argocd
