### ISSUE TITLE
Update Azure plugin README to use latest version in install commands

### ISSUE THREAD

**Issue by amankohli** [vmware-tanzu/velero#3508] opened 2021-02-26 07:08 UTC
We followed the below steps:

i) Created velero credentials:
cat << EOF  > ./credentials-velero
AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
AZURE_CLOUD_NAME=AzureUsGovenmentCloud
EOF

ii)Installed Velero using the below command:
velero install \
    --provider azure \
    --plugins velero/velero-plugin-for-microsoft-azure:v1.1.0 \
    --bucket $BLOB_CONTAINER \
    --secret-file ./credentials-velero \
    --backup-location-config resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,storageAccount=$AZURE_STORAGE_ACCOUNT_ID[,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID] \
    --snapshot-location-config apiTimeout=<YOUR_TIMEOUT>[,resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID]

iii) Added the below label to velero deployment:
  labels:
    aadpodidbinding:${IdentityName}
    component: velero

We get the below error:
time="2021-02-26T06:55:50Z" level=info msg="Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:58"
time="2021-02-26T06:55:50Z" level=error msg="Error getting a backup store" backupstoragelocation=default controller=backupstoragelocation error="rpc error: code = Unknown desc = unable to get all required environment variables: the following keys do not have values: AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET" error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:178" error.function=main.getStorageAccountKey logSource="pkg/controller/backupstoragelocation_controller.go:87"
time="2021-02-26T06:55:50Z" level=i

Velero should just use AADPOD Identity and not look for client secret

**Comment by zubron** [comment] 2021-02-26 15:23
This looks like an issue with the README for the plugin. Support for AAD Pod Identity was released in [v1.1.1](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/releases/tag/v1.1.1) but the README gives instructions to install the v1.1.0 version.

Please try using v1.1.1, or the latest [v1.1.2](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/releases/tag/v1.1.2) release.

I am going to leave this issue open and change the title to track updating the README to reference the latest version of the plugin.

**Comment by da1rren** [comment] 2021-02-26 15:30
I can confirm using v1.2 works.  Just shipped my first backups after encountering the same issue.

**Comment by theok-nice** [comment] 2021-03-01 14:25
I tested the new plugin version (v1.1.2) on a AzureUsGovenmentCloud region and get the following

i) Created velero credentials:
cat << EOF > ./credentials-velero
AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
AZURE_CLOUD_NAME=AzureUsGovenmentCloud
EOF

ii)Installed Velero using the below command:
velero install
--provider azure
--plugins velero/velero-plugin-for-microsoft-azure:v1.1.2
--bucket $BLOB_CONTAINER
--secret-file ./credentials-velero
--backup-location-config resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,storageAccount=$AZURE_STORAGE_ACCOUNT_ID[,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID]
--snapshot-location-config apiTimeout=<YOUR_TIMEOUT>[,resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID]

iii) Added the below label to velero deployment:
labels:
aadpodidbinding:${IdentityName}
component: velero

time="2021-03-01T13:47:00Z" level=info msg="Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:58"
time="2021-03-01T13:47:01Z" level=error msg="Error getting a backup store" backupstoragelocation=default controller=backupstoragelocation error="rpc error: code = Unknown desc = storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code=\"InvalidAuthenticationTokenAudience\" Message=\"The access token has been obtained for wrong audience or resource 'https://management.azure.com/'. It should exactly match with one of the allowed audiences 'https://management.core.usgovcloudapi.net/','https://management.core.usgovcloudapi.net','https://management.usgovcloudapi.net/','https://management.usgovcloudapi.net'.\"" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:213" error.function=main.getStorageAccountKey logSource="pkg/controller/backupstoragelocation_controller.go:87"
time="2021-03-01T13:47:01Z" level=info msg="No backup locations were ready to be verified" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:120"
time="2021-03-01T13:47:01Z" level=error msg="Error getting backup store for this location" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code=\"InvalidAuthenticationTokenAudience\" Message=\"The access token has been obtained for wrong audience or resource 'https://management.azure.com/'. It should exactly match with one of the allowed audiences 'https://management.core.usgovcloudapi.net/','https://management.core.usgovcloudapi.net','https://management.usgovcloudapi.net/','https://management.usgovcloudapi.net'.\"" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:213" error.function=main.getStorageAccountKey logSource="pkg/controller/backup_sync_controller.go:168" 

I am not sure if there is bug or there is something more missing from the README for the plugin.

**Comment by carlisia** [comment] 2021-03-01 19:29
I think this needs some looking into. I'd start with this: https://stackoverflow.com/questions/34384409/azure-the-access-token-has-been-obtained-from-wrong-audience-or-resource.

**Comment by theok-nice** [comment] 2021-03-02 17:14
In line https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/1f34714a0ea78b1d0a57cc53ad317deb351042cf/velero-plugin-for-microsoft-azure/object_store.go#L207 

env.ResourceManagerEndpoint returns the correct endpoint for `AZURE_CLOUD_NAME=AzureUSGovernmentCloud`. 

I don't understand why code defaults to `resource 'https://management.azure.com/'` in the logs

**Comment by amankohli** [comment] 2021-03-11 12:22
@carlisia  Do we have an update on the issue?

We are blocked on our deliverables due to the MSI issue, please let us know if they is a workaround

**Comment by b-amkohl** [comment] 2021-07-23 08:10
any update on the change?

**Comment by zubron** [comment] 2022-01-24 17:21
The original issue with the Azure plugin documentation referencing the wrong version has been fixed. The follow up queries regarding the issues when using Azure Government cloud will be addressed in #4570 so I'm closing this issue.

**Closed by zubron** 2022-01-24 17:21 UTC
Labels: Area/Documentation, Area/Cloud/Azure, Needs investigation, Reviewed Q2 2021
