### ISSUE TITLE
New dependencies relates to aws and azure sdk on Velero 1.14

### ISSUE THREAD

**Issue by Frank51** [vmware-tanzu/velero#8157] opened 2024-08-28 16:23 UTC
**What steps did you take and what happened:**

Trying to use "install.VeleroOptions" to generate the velero option struct, then passing this as a parameter to the "install.Install" function. I was trying use the "install.Install" function to install Velero 1.14 on kubernetes cluster. 
https://github.com/vmware-tanzu/velero/blob/main/pkg/install/install.go

On the Velero 1.12, this method works for installing velero. But on Velero 1.14, it involves in lots of new dependency of "`github.com/aws/aws-sdk-go-v2`" and "`github.com/Azure/azure-sdk-for-go/sdk`". And the building does not work. Since we don't have this dependency on our repository yet.
https://github.com/vmware-tanzu/velero/blob/main/go.mod#L13

**What did you expect to happen:**
The Velero 1.14 server should install successfully using this package. 

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

Here is the reason I found. The install package has dependency with these sdk.
`go mod why github.com/aws/aws-sdk-go-v2/credentials`
   `github.com/aws/aws-sdk-go-v2/credentials`
   `github.com/vmware-tanzu/velero/pkg/install`
   `github.com/vmware-tanzu/velero/pkg/repository`
   `github.com/vmware-tanzu/velero/pkg/repository/provider`
   `github.com/vmware-tanzu/velero/pkg/repository/config`
   `github.com/aws/aws-sdk-go-v2/credentials`

I knew in this release, Velero 1.14 including new features relates to aws and azure sdk. But on our dev side, I don't want to add too many new dependencies relates to these sdk for now. Any way to fix it or temporarily workaround? Thanks.

**Environment:**

- Velero version (use `velero version`): v1.14.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): Kubernetes v1.27.0
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): SUSE Linux Enterprise Server 15 SP4

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by kaovilai** [comment] 2024-08-28 17:30
`"github.com/vmware-tanzu/velero/pkg/repository"` contains aws.go

user wants to import pkg/install without aws.go dependencies

currently repository.MaintenanceConfig is the only thing consumed by pkg/install.

We can avoid unnecessary imports by moving aws.go and other cloud specifics out of pkg/repository and into sub packages such as pkg/repository/aws/aws.go

**Comment by kaovilai** [comment] 2024-08-28 17:41
previously worked on similar thing at https://github.com/vmware-tanzu/velero/pull/6484, can assign me this issue.

**Comment by kaovilai** [comment] 2024-08-29 03:15
Although this PR might also fix this issue incidentally by removing `repository.MaintenanceConfig` from install pkg
https://github.com/vmware-tanzu/velero/pull/8145/files#diff-a8f6f486214a428136fecae53b9e1eb1da76c5f1c109e153443b20edc6ee3cb5

**Comment by kaovilai** [comment] 2024-08-29 22:39
Maybe something like this could work in the importing projects.
```
go mod edit -replace="github.com/vmware-tanzu/velero=github.com/blackpiglet/velero@7758_implement"
```

**Comment by Frank51** [comment] 2024-08-30 00:02
> could work in the importing projects.

Thanks. Let me try this way. And give feedback over here once test finish.

**Comment by kaovilai** [comment] 2024-08-30 04:20
looks like 8145 still has repository import in pkg/install under resources.go

**Comment by Frank51** [comment] 2024-08-30 13:21
https://gist.github.com/Frank51/2ca548e036c0cddee5f159be80642445
This is the building log for using forked velero repo name. Could you take a look?

**Comment by reasonerjt** [comment] 2024-09-02 06:21
Let's double check after #8145 is merged.

**Comment by kaovilai** [comment] 2024-09-03 14:38
Before 8145
```
go list -f {{.Deps}} ./pkg/install/... | sed 's/ /\n/g' | grep aws 
github.com/aws/aws-sdk-go-v2/aws
github.com/aws/aws-sdk-go-v2/aws/arn
github.com/aws/aws-sdk-go-v2/aws/defaults
github.com/aws/aws-sdk-go-v2/aws/middleware
github.com/aws/aws-sdk-go-v2/aws/middleware/private/metrics
github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream
github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream/eventstreamapi
github.com/aws/aws-sdk-go-v2/aws/protocol/query
github.com/aws/aws-sdk-go-v2/aws/protocol/restjson
github.com/aws/aws-sdk-go-v2/aws/protocol/xml
github.com/aws/aws-sdk-go-v2/aws/ratelimit
github.com/aws/aws-sdk-go-v2/aws/retry
github.com/aws/aws-sdk-go-v2/aws/signer/internal/v4
github.com/aws/aws-sdk-go-v2/aws/signer/v4
github.com/aws/aws-sdk-go-v2/aws/transport/http
github.com/aws/aws-sdk-go-v2/config
github.com/aws/aws-sdk-go-v2/credentials
github.com/aws/aws-sdk-go-v2/credentials/ec2rolecreds
github.com/aws/aws-sdk-go-v2/credentials/endpointcreds
github.com/aws/aws-sdk-go-v2/credentials/endpointcreds/internal/client
github.com/aws/aws-sdk-go-v2/credentials/processcreds
github.com/aws/aws-sdk-go-v2/credentials/ssocreds
github.com/aws/aws-sdk-go-v2/credentials/stscreds
github.com/aws/aws-sdk-go-v2/feature/ec2/imds
github.com/aws/aws-sdk-go-v2/feature/ec2/imds/internal/config
github.com/aws/aws-sdk-go-v2/feature/s3/manager
github.com/aws/aws-sdk-go-v2/internal/auth
github.com/aws/aws-sdk-go-v2/internal/auth/smithy
github.com/aws/aws-sdk-go-v2/internal/awsutil
github.com/aws/aws-sdk-go-v2/internal/configsources
github.com/aws/aws-sdk-go-v2/internal/context
github.com/aws/aws-sdk-go-v2/internal/endpoints
github.com/aws/aws-sdk-go-v2/internal/endpoints/awsrulesfn
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2
github.com/aws/aws-sdk-go-v2/internal/ini
github.com/aws/aws-sdk-go-v2/internal/rand
github.com/aws/aws-sdk-go-v2/internal/sdk
github.com/aws/aws-sdk-go-v2/internal/sdkio
github.com/aws/aws-sdk-go-v2/internal/shareddefaults
github.com/aws/aws-sdk-go-v2/internal/strings
github.com/aws/aws-sdk-go-v2/internal/sync/singleflight
github.com/aws/aws-sdk-go-v2/internal/timeconv
github.com/aws/aws-sdk-go-v2/internal/v4a
github.com/aws/aws-sdk-go-v2/internal/v4a/internal/crypto
github.com/aws/aws-sdk-go-v2/internal/v4a/internal/v4
github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding
github.com/aws/aws-sdk-go-v2/service/internal/checksum
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url
github.com/aws/aws-sdk-go-v2/service/internal/s3shared
github.com/aws/aws-sdk-go-v2/service/internal/s3shared/arn
github.com/aws/aws-sdk-go-v2/service/internal/s3shared/config
github.com/aws/aws-sdk-go-v2/service/s3
github.com/aws/aws-sdk-go-v2/service/s3/internal/arn
github.com/aws/aws-sdk-go-v2/service/s3/internal/customizations
github.com/aws/aws-sdk-go-v2/service/s3/internal/endpoints
github.com/aws/aws-sdk-go-v2/service/s3/types
github.com/aws/aws-sdk-go-v2/service/sso
github.com/aws/aws-sdk-go-v2/service/sso/internal/endpoints
github.com/aws/aws-sdk-go-v2/service/sso/types
github.com/aws/aws-sdk-go-v2/service/ssooidc
github.com/aws/aws-sdk-go-v2/service/ssooidc/internal/endpoints
github.com/aws/aws-sdk-go-v2/service/ssooidc/types
github.com/aws/aws-sdk-go-v2/service/sts
github.com/aws/aws-sdk-go-v2/service/sts/internal/endpoints
github.com/aws/aws-sdk-go-v2/service/sts/types
github.com/aws/smithy-go
github.com/aws/smithy-go/auth
github.com/aws/smithy-go/auth/bearer
github.com/aws/smithy-go/container/private/cache
github.com/aws/smithy-go/container/private/cache/lru
github.com/aws/smithy-go/context
github.com/aws/smithy-go/document
github.com/aws/smithy-go/encoding
github.com/aws/smithy-go/encoding/httpbinding
github.com/aws/smithy-go/encoding/json
github.com/aws/smithy-go/encoding/xml
github.com/aws/smithy-go/endpoints
github.com/aws/smithy-go/endpoints/private/rulesfn
github.com/aws/smithy-go/internal/sync/singleflight
github.com/aws/smithy-go/io
github.com/aws/smithy-go/logging
github.com/aws/smithy-go/middleware
github.com/aws/smithy-go/private/requestcompression
github.com/aws/smithy-go/ptr
github.com/aws/smithy-go/rand
github.com/aws/smithy-go/sync
github.com/aws/smithy-go/time
github.com/aws/smithy-go/transport/http
github.com/aws/smithy-go/transport/http/internal/io
github.com/aws/smithy-go/waiter
```

after 8145
```
❯ gh pr checkout 8145 
Switched to branch '7758_implement'

~/git/velero 7758_implement
❯ go list -f {{.Deps}} ./pkg/install/... | sed 's/ /\n/g' | grep aws
```

**Comment by Frank51** [comment] 2024-09-09 16:09
https://github.com/vmware-tanzu/velero/pull/8145
Looks like we are solving this at this PR. Does this fix will be included in Velero 1.14.1?

**Comment by sseago** [comment] 2024-09-09 18:26
@Frank51 1.14.1 has already been released. I don't think the the repo maintenance change you linked is one we would backport, unless there was some 1.14 bug that we really needed the fix for. If we do end up fixing the aws/azure deps as part of a larger PR in 1.15, then any future 1.14.x changes would need to be a separate commit. If it gets fixed separately, then it could be backported via cherry-pick.

**Comment by kaovilai** [comment] 2024-09-10 22:43
Looks like 8145 had some changes that I missed between initial check and merge.. there appears to be dependency even after 8145.

```
❯ gh pr checkout 8145 
Already on '7758_implement'
Your branch is up to date with 'blackpiglet/7758_implement'.
Already up to date.

~/git/velero 7758_implement
❯ go list -f {{.Deps}} ./pkg/install/... | sed 's/ /\n/g' | grep -E 'aws|azure|gcp|s3' 
github.com/Azure/azure-sdk-for-go/sdk/azcore
github.com/Azure/azure-sdk-for-go/sdk/azcore/arm
github.com/Azure/azure-sdk-for-go/sdk/azcore/arm/internal/resource
github.com/Azure/azure-sdk-for-go/sdk/azcore/arm/policy
github.com/Azure/azure-sdk-for-go/sdk/azcore/arm/runtime
...
```

**Comment by kaovilai** [comment] 2024-09-10 23:13
https://github.com/vmware-tanzu/velero/commit/337b796b5b4d11c0d8a840fc042d5287a0b64e14 this worked but not as of latest pr commit.. further digging reveals "github.com/vmware-tanzu/velero/internal/velero" is now the blocking file that imports aws deps

**Comment by kaovilai** [comment] 2024-09-10 23:46
This is now being solved as part of #8180

**Comment by kaovilai** [comment] 2024-09-11 02:57
#8208 solves the root cause of install pkg import issue by solving plugin framework deps directly. #8180 only just avoided importing plugin framework.

**Closed** 2024-09-13 02:21 UTC

**Comment by Frank51** [comment] 2024-09-14 21:56
Thanks @kaovilai @sseago @ywk253100 @blackpiglet for the work on this issue.
