### ISSUE TITLE
backup statefulset failed with "unable to upgrade connection: container not  found (\"fsfreeze\")"

### ISSUE THREAD

**Issue by liyan-su** [vmware-tanzu/velero#4412] opened 2021-11-30 13:57 UTC
**Describe the bug**
env: TKGI 1.13 + velero 1.6.3 + velero-plugin-for-vsphere:v1.3.0-rc4
backup items 696/696, but there are two error messages "unable to upgrade connection: container not  found (\"fsfreeze\")"

**To Reproduce**

    1.setup tkgi 1.13
    2.create a k8s cluster
    3.install velero and velero-plugin-for-vsphere:v1.3.0-rc4
    4.create 10 namespaces, 100 statefulsets with 1g pv each
    5.backup 10 namespaces, 2 namespaces each time
    6.backup result 
`bk7-100g-1      PartiallyFailed   2        20         2021-11-29 15:45:36 +0000 UTC   29d       default            <none>
bk7-100g-2      PartiallyFailed   8        20         2021-11-29 15:52:15 +0000 UTC   29d       default            <none>
bk7-100g-3      PartiallyFailed   8        20         2021-11-29 15:55:49 +0000 UTC   29d       default            <none>
bk7-100g-4      PartiallyFailed   8        20         2021-11-29 15:59:10 +0000 UTC   29d       default            <none>
bk7-100g-5      InProgress        0        0          2021-11-29 16:02:46 +0000 UTC   29d       default            <none>`
7.  velero backup describe bk7-100g-1
`root@7248d36844f0:~/1.13/velero/vsphere# velero backup describe bk7-100g-1
Name:         bk7-100g-1
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.22.2+vmware.1
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=22

Phase:  PartiallyFailed (run `velero backup logs bk7-100g-1` for more information)

Errors:    2
Warnings:  20

Namespaces:
  Included:  pv-ns-1, pv-ns-2
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  true

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-11-29 15:45:36 +0000 UTC
Completed:  2021-11-29 15:52:12 +0000 UTC

Expiration:  2021-12-29 15:45:36 +0000 UTC

Total items to be backed up:  696
Items backed up:              696

Velero-Native Snapshots: <none included>`

7. backup bk7-100g-1 error logs 
`time="2021-11-29T15:52:03Z" level=info msg="stdout: " backup=velero/bk7-100g-1 hookCommand="[/sbin/fsfreeze --unfreeze /var/lib/postgresql/data]" hookContainer=fsfreeze hookName="<from-annotation>" hookOnError=Fail hookPhase=post hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:171" name=postgres-wl-82-0 namespace=pv-ns-2 resource=pods
time="2021-11-29T15:52:03Z" level=info msg="stderr: " backup=velero/bk7-100g-1 hookCommand="[/sbin/fsfreeze --unfreeze /var/lib/postgresql/data]" hookContainer=fsfreeze hookName="<from-annotation>" hookOnError=Fail hookPhase=post hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:172" name=postgres-wl-82-0 namespace=pv-ns-2 resource=pods
time="2021-11-29T15:52:03Z" level=error msg="Error executing hook" backup=velero/bk7-100g-1 error="unable to upgrade connection: container not found (\"fsfreeze\")" hookPhase=post hookSource=annotation hookType=exec logSource="internal/hook/item_hook_handler.go:206" name=postgres-wl-82-0 namespace=pv-ns-2 resource=pods
time="2021-11-29T15:52:03Z" level=info msg="1 errors encountered backup up item" backup=velero/bk7-100g-1 logSource="pkg/backup/backup.go:427" name=postgres-wl-82-0
time="2021-11-29T15:52:03Z" level=error msg="Error backing up item" backup=velero/bk7-100g-1 error="unable to upgrade connection: container not found (\"fsfreeze\")" logSource="pkg/backup/backup.go:431" name=postgres-wl-82-0
time="2021-11-29T15:52:03Z" level=info msg="Backed up 57 items out of an estimated total of 714 (estimate will change throughout the backup)" backup=velero/bk7-100g-1 logSource="pkg/backup/backup.go:394" name=postgres-wl-82-0 namespace=pv-ns-2 progress= resource=pods
time="2021-11-29T15:52:03Z" level=info msg="Processing item" backup=velero/bk7-100g-1 logSource="pkg/backup/backup.go:354" name=postgres-wl-92-0 namespace=pv-ns-2 progress= resource=pods
time="2021-11-29T15:52:03Z" level=info msg="Backing up item" backup=velero/bk7-100g-1 logSource="pkg/backup/item_backupper.go:121" name=postgres-wl-92-0 namespace=pv-ns-2 resource=pods`
8. Some pods are ContainerCreating.
`pv-ns-1       postgres-wl-1-0                          2/2     Running             0          20h
pv-ns-1       postgres-wl-11-0                         2/2     Running             0          20h
pv-ns-1       postgres-wl-21-0                         0/2     ContainerCreating   0          19h
pv-ns-1       postgres-wl-31-0                         2/2     Running             0          20h
pv-ns-1       postgres-wl-41-0                         0/2     ContainerCreating   0          19h
pv-ns-1       postgres-wl-51-0                         2/2     Running             0          20h
pv-ns-1       postgres-wl-61-0                         0/2     ContainerCreating   0          19h
pv-ns-1       postgres-wl-71-0                         2/2     Running             0          20h
pv-ns-1       postgres-wl-81-0                         2/2     Running             0          20h
pv-ns-1       postgres-wl-91-0                         0/2     ContainerCreating   0          19h`

kubectl describe pod postgres-wl-21-0  -n pv-ns-1

`  Type     Reason       Age                        From     Message
  ----     ------       ----                       ----     -------
  Warning  FailedMount  2m11s (x463 over 21h)      kubelet  Unable to attach or mount volumes: unmounted volumes=[appdb], unattached volumes=[appdb kube-api-access-mmf7g]: timed out waiting for the condition
  Warning  FailedMount  <invalid> (x113 over 21h)  kubelet  Unable to attach or mount volumes: unmounted volumes=[appdb], unattached volumes=[kube-api-access-mmf7g appdb]: timed out waiting for the condition`
**Expected behavior**

no error msg

**Troubleshooting Information**
**Screenshots**

[If applicable, add screenshots to help explain your problem.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue]

**Comment by zubron** [comment] 2022-01-27 22:08
This is failing because the container to run the hook in does not exist. The fsfreeze example from [our documentation](https://velero.netlify.app/docs/v1.8/backup-hooks/#hook-example-with-fsfreeze) references a [container named fsfreeze](https://github.com/vmware-tanzu/velero/blob/main/examples/nginx-app/with-pv.yaml#L74-L85) to run the hook in. When specifying the container for the hook, it must match the name of a container in the pod. If no container name is specified, Velero will default to running the command in the first container.

I am going to close this as this is expected behaviour, but please let us know if you have further issues.

**Closed by zubron** 2022-01-27 22:08 UTC
