### ISSUE TITLE
Cannot create a velero backup multiple times of a persistent volume backed by AWS EFS

### ISSUE THREAD

**Issue by sumz95** [vmware-tanzu/velero#5452] opened 2022-10-17 16:33 UTC
**What steps did you take and what happened:**
I tried to create a velero backup of a persistent volume but it errored with:

``` 
time="2022-10-14T10:39:14Z" level=info msg="1 errors encountered backup up item" backup=velero/backup-test-5984 logSource="pkg/backup/backup.go:413" name=write-to-file-pod`
time="2022-10-14T10:39:14Z" level=error msg="Error backing up item" backup=velero/backup-test-5984 error="pod volume backup failed: running Restic backup, stderr=Fatal: Fatal: config cannot be loaded: ciphertext verification failed\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:199" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:417" name=write-to-file-pod 
```
I have installed velero with restic integrated into it. I have a efs backed volumes on a AWS cluster.

Steps taken:
1) Create a pod, with a pvc and pv: 
`kubectl apply -n backup-test -f kube-resources.yaml `
2) Save some data into the pv: 
`kubectl -n backup-test exec <pod> -- sh -c "echo -n "Hello world" > hello.txt" `
3) Run a velero backup: 
`velero backup create backup-1 --wait --snapshot-volumes --default-volumes-to-restic --include-namespaces backup-test`
4) Repeat step 3 a few more times and it will fail
`velero backup create backup-2 --wait --snapshot-volumes --default-volumes-to-restic --include-namespaces backup-test`

kube-resources.yaml :

``` 
apiVersion: v1
kind: Namespace
metadata:
  name: backup-test

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-test
spec:
  resources:
    requests:
      storage: 5G 
  accessModes:
    - ReadWriteMany
---

apiVersion: v1
kind: Pod
metadata:
  name: write-to-file-pod
spec:
  restartPolicy: OnFailure 
  volumes:
      - name: data
        persistentVolumeClaim:
            claimName: backup-test
  containers:
  - name: write-to-file-pod
    image: alpine
    command: [ "/bin/sh", "-c", "tail -f /dev/null"]  
    volumeMounts:
    - name: data
      mountPath: "/data"
```

**What did you expect to happen:**

I expected it to create a successful backup, without a "PartiallyFailed" status

**The following information will help us better understand what's going on**:
[bundle-2022-10-17-16-03-42.tar.gz](https://github.com/vmware-tanzu/velero/files/9809167/bundle-2022-10-17-16-03-42.tar.gz)

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

**Anything else you would like to add:**
The first backup is created successfully, with future backups often failing with the error message mentioned above. It works again once the controller restic pod in the velero namespace has been deleted and then recreated.

**Environment:**

- Velero version (use `velero version`):  `Version: v1.9.2`
- Velero features (use `velero client config get features`): `features: <NOT SET>`
- Kubernetes version (use `kubectl version`): `Client Version: v1.25.2.   Kustomize Version: v4.5.7.  Server Version: v1.21.14-eks-6d3986b`
- Kubernetes installer & version: `AWS EKS`
- Cloud provider or hardware configuration: `AWS and EFS as persistent volume`
- OS (e.g. from `/etc/os-release`): `Amazon Linux 2 `

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment] 2022-10-19 03:57
@sumz95 through the log in the bundle you provided, one of problem is velero could not handle restore hello.txt in volumes, `Lchown: lchown xxxx kubernetes.io~csi/pvc-6d1f5453-e6e2-4336-afad-a06f2aa4cd4d/mount/hello.txt  operation not permitted`, AWS EFS which is one nfs server backend, Is there some permission problem of restore one EFS mounted volume?

`config cannot be loaded: ciphertext verification failed`, it is reported by restic which velero integrated into, it store the repository config in S3 that you provided, it seems to be broken. Did you do some other operation during Repeat step 3?

**Comment by sumz95** [comment] 2022-10-19 13:57
@qiuming-best I am aware of the issue with restore, it is reported in issue #5403.

Regarding the "S3 config", I did not execute any other operations that could have broken it. I run some commands as part of a script (relevant bits below):

```
    test_identifier=${test_identifier:-$RANDOM}
    resources=($(kubectl create -k infrastructure/tests/storage-backup-restore -o jsonpath='{.metadata.name}{"\n"}'))
    ns="${resources[0]}" pvc="${resources[1]}" pod="${resources[2]}"
  
    
    kubectl wait -n $ns pod $pod --for=condition='Ready' --timeout 10m
    kubectl -n $ns exec $pod -- sh -c "echo -n $sample_text > $sample_text_file" \
        && debug "written $sample_text_file"

    backup=backup-test-$test_identifier
    velero backup create $backup --wait --snapshot-volumes --default-volumes-to-restic --include-namespaces $ns \
        && debug "taken $backup"
```

**Comment by Lyndon-Li** [comment] 2022-11-15 03:25
If the problem is on restore, this is duplicated with #5403

**Comment by sumz95** [comment] 2022-11-18 12:43
It's to do with the backup. I am aware of #5403 I already highlighted that in my previous comment

> @qiuming-best I am aware of the issue with restore, it is reported in issue https://github.com/vmware-tanzu/velero/issues/5403.

**Comment by reasonerjt** [comment] 2023-01-10 07:51
#5403 will not exist in kopia path.

As for the error `config cannot be loaded: ciphertext verification failed` this looks like an env issue and it should not block the release of v1.11

**Comment by Lyndon-Li** [comment] 2024-05-20 03:21
Closing this issue since there is no update for long time.

@sumz95 Feel free to reopen it if you have further clue and we recommend to use Kopia path over Restic path since Velero is planning to deprecate Restic path.

**Closed** 2024-05-20 03:22 UTC
Labels: Area/Cloud/AWS, Needs investigation, Restore, PodVolume
