### ISSUE TITLE
Restic backups when taking backups of pods not in "Running" state

### ISSUE THREAD

**Issue by amarshaw** [vmware-tanzu/velero#2395] opened 2020-04-03 07:57 UTC
Running schedule backup and it's getting PartiallyFailed.

```
TION   SELECTOR
daily-k8s-backup-120d-20200403020007   PartiallyFailed   2020-04-02 22:00:07 -0400 EDT   119d      default            !openebs.io/controller,!openebs.io/replica
daily-k8s-backup-120d-20200402020037   PartiallyFailed   2020-04-01 22:00:37 -0400 EDT   118d      default            !openebs.io/controller,!openebs.io/replica
```

By troubleshooting i found that restic is trying to take backup from Evicted pods.

**Failed Backup for namespace :**

```
    k8s-xxx-qa/xxx-85dbcc67b4-pdj6x: storage-0
    k8s-xxx/xxx-6859ffc4-mhrjl: storage-0
    k8s-qqq-qa/qqq-qa-6db8d5c876-5rfmd: storage-0
    k8s-qqq/qqq-5bc89bdfcc-qrjf6: storage-0
    k8s-www-qa/www-qa-65f5966c97-2jnhn: storage-0
    k8s-watcher/k8s-watcher-nfs-665cd5dbd9-rv4v4: storage-0
  Failed:
    k8s-ccc/ccc-64fcc6bccd-248zb: storage-0
```

**Statue of k8s-ccc namespace and pods ccc-64fcc6bccd-248zb.**

```
kubectl -n k8s-peoplefunction get pods
NAME                               READY   STATUS    RESTARTS   AGE
ccc-64fcc6bccd-248zb   0/1     Evicted   0          12h
ccc-64fcc6bccd-5lflt   1/1     Running   0          5d19h
ccc-64fcc6bccd-5sgc6   1/1     Running   0          12h

```

**Backup Error Log.**

```
velero backup  logs daily-k8s-backup-120d-20200403020007 | grep -i error
time="2020-04-03T02:13:40Z" level=info msg="1 errors encountered backup up item" backup=velero/daily-k8s-backup-120d-20200403020007 group=v1 logSource="pkg/backup/resource_backupper.go:283" name=ccc-64fcc6bccd-248zb namespace= resource=pods
time="2020-04-03T02:13:40Z" level=error msg="Error backing up item" backup=velero/daily-k8s-backup-120d-20200403020007 error="pod volume backup failed: error getting volume path on host: expected one matching path, got 0"error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:182" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" group=v1 logSource="pkg/backup/resource_backupper.go:287" name=ccc-64fcc6bccd-248zb namespace= resource=pods
```

Velero Version : 1.3.1
storage-0 is openebs NFS mount.

```
kubectl -n velero get deployment velero -o yaml | grep image
        image: artifacts.aaa.com/deployer-tools/velero:v1.3.1
        imagePullPolicy: IfNotPresent
      - image: openebs/velero-plugin:1.8.0-velero_1.0.0
        imagePullPolicy: IfNotPresent
      - image: velero/velero-plugin-for-aws:v1.0.0
        imagePullPolicy: IfNotPresent
```

**Velero Namespace Status :**

```
kubectl -n velero get pods
NAME                      READY   STATUS      RESTARTS   AGE
minio-setup-nfvh9         0/1     Completed   0          20h
restic-5czcv              1/1     Running     0          20h
restic-5pkqn              1/1     Running     0          20h
restic-6knq7              1/1     Running     0          20h
restic-7g57s              1/1     Running     0          20h
restic-8446z              1/1     Running     0          20h
restic-9lrrj              1/1     Running     0          20h
restic-9mcbv              1/1     Running     0          20h
restic-ddg5v              1/1     Running     0          20h
restic-f4bj8              1/1     Running     0          20h
restic-fh6q8              1/1     Running     0          20h
restic-ft4nx              1/1     Running     0          20h
restic-ftl9p              1/1     Running     0          20h
restic-g96g2              1/1     Running     0          20h
restic-hl9b5              1/1     Running     0          20h
restic-m4pwl              1/1     Running     0          20h
restic-ngmgc              1/1     Running     0          20h
restic-nhd98              1/1     Running     0          20h
restic-rn8hw              1/1     Running     0          20h
restic-rpnxd              1/1     Running     0          20h
restic-s7w79              1/1     Running     0          20h
restic-tcvhf              1/1     Running     0          20h
restic-tnvgz              1/1     Running     0          20h
restic-ttkfp              1/1     Running     0          20h
restic-tvz54              1/1     Running     0          20h
velero-6b696d6fb8-8qf9z   1/1     Running     0          20h 
```

**Backup Schedule**

```
kubectl -n velero get schedule daily-k8s-backup-120d  -o yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  creationTimestamp: "2020-04-02T11:04:25Z"
  generation: 4
  name: daily-k8s-backup-120d
  namespace: velero
  resourceVersion: "332594823"
  selfLink: /apis/velero.io/v1/namespaces/velero/schedules/daily-k8s-backup-120d
  uid: b7205264-74d1-11ea-bf21-0050569a4d16
spec:
  schedule: 00 02 * * *
  template:
    excludedNamespaces:
    - openebs
    includedNamespaces:
    - '*'
    labelSelector:
      matchExpressions:
      - key: openebs.io/controller
        operator: DoesNotExist
      - key: openebs.io/replica
        operator: DoesNotExist
    snapshotVolumes: true
    ttl: 2880h0m0s
status:
  lastBackup: "2020-04-03T02:00:07Z"
  phase: Enabled
```

**Comment by nrb** [comment] 2020-04-06 18:15
Thanks for reporting this @amarshaw, I've added it to our backlog.

**Comment by amarshaw** [comment] 2020-04-08 13:28
welcome

**Comment by ashish-amarnath** [comment] 2020-06-25 22:31
The phase of the pod is something that is external to Velero. Trying to think what would be an expected behavior when this happens? Putting out some options:
1. Check Pod status before creating the `PodVolumeBackup` objects [here](https://github.com/vmware-tanzu/velero/blob/master/pkg/restic/backupper.go#L160)
2. Check pod status in the pod_volume_backup controller [here](https://github.com/vmware-tanzu/velero/blob/master/pkg/controller/pod_volume_backup_controller.go#L193)

I think option 2 seems more right and is more just-in-time fashion. 
In either case, we would want to return an error indicating that it was caused by a pod not being in the `Running` phase.

**Comment by fredgate** [comment] 2021-03-03 08:45
Velero should ignore evicted pods since it will not be able to perform backup of their volumes. In addition, an evicted pod is generally replaced by an active pod, so backups should be performed only from `Running` pods.
For schedule backups we can not define which pod will be evicted.

**Comment by zubron** [comment] 2021-07-07 22:40
@eleanor-millman This issue has been reported quite a few times (I found a few duplicates). I'd like to propose that we remove the "Icebox" label and consider this for an upcoming release.

**Comment by eleanor-millman** [comment] 2021-07-15 15:05
@zubron Thanks for highlighting this! I took off the icebox tag, which means that we will consider it for the 1.8 release when we do that planning.

cc @dsu-igeek

**Comment by beegee1** [comment] 2022-01-19 16:53
@eleanor-millman 
Any updates on this? We need this feature for our backup-restore (clone) functionality of namespaces. As a workaround we have implemented a CronJob which deletes evicted pods just before creating the backup.

**Comment by eleanor-millman** [comment] 2022-01-19 19:46
Note to devs who might work on this, this fix would likely be in the same area as https://github.com/vmware-tanzu/velero/pull/3993/files

**Comment by eleanor-millman** [comment] 2022-01-19 19:52
when we back up a volume using restic, we need pod to be up and running to access the volume. Currently, if this is the case, the backup is marked as “PartiallyFailed”. It would be better to not try to back it up at all and so mark it as “cannot backup due to the pod not running” or something like that and log something like that as well.

**Comment by bynare** [comment] 2022-01-27 04:16
Thanks for your pointers @eleanor-millman - I've added a PR for this, which seems to solve our issues ;)

**Closed** 2022-02-15 21:34 UTC
Labels: Bug, Restic, Restic - GA, Reviewed Q2 2021
