### ISSUE TITLE
Support LetsEncrypt CA signed certificates for S3 storage

### ISSUE THREAD

**Issue by msnelling** [vmware-tanzu/velero#2080] opened 2019-11-25 12:06 UTC
**What steps did you take and what happened:**
Ran install command below for specifying a Minio S3 object store URL for the AWS plugin
```
velero install \
--provider aws \
--bucket velero.k8s.xmple.io \
--secret-file ./credentials-velero \
--use-volume-snapshots=false \
--backup-location-config region=minio,s3ForcePathStyle="true",s3Url=https://nas01.xmple.io9000 \
--plugins velero/velero-plugin-for-aws:v1.0.0
```

**What did you expect to happen:**
I expected the workload to successfully install

**The output of the following commands will help us better understand what's going on**:
* `kubectl logs deployment/velero -n velero`
```
time="2019-11-25T11:51:28Z" level=info msg="setting log-level to INFO" logSource="pkg/cmd/server/server.go:171"
time="2019-11-25T11:51:28Z" level=info msg="Starting Velero server v1.2.0 (5d008491bbf681658d3e372da1a9d3a21ca4c03c)" logSource="pkg/cmd/server/server.go:173"
time="2019-11-25T11:51:28Z" level=info msg="No feature flags enabled" logSource="pkg/cmd/server/server.go:177"
time="2019-11-25T11:51:28Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2019-11-25T11:51:28Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv
time="2019-11-25T11:51:28Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2019-11-25T11:51:28Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pv-from-pvc
time="2019-11-25T11:51:28Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pvc-from-pod
time="2019-11-25T11:51:28Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-storage-class
time="2019-11-25T11:51:28Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/cluster-role-bindings
time="2019-11-25T11:51:28Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job
time="2019-11-25T11:51:28Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2019-11-25T11:51:28Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic
time="2019-11-25T11:51:28Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/role-bindings
time="2019-11-25T11:51:28Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service
time="2019-11-25T11:51:28Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2019-11-25T11:51:28Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-aws kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2019-11-25T11:51:28Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-aws kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2019-11-25T11:51:28Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:337" namespace=velero
time="2019-11-25T11:51:28Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:343" namespace=velero
time="2019-11-25T11:51:31Z" level=info msg="Checking existence of Velero custom resource definitions" logSource="pkg/cmd/server/server.go:372"
time="2019-11-25T11:51:31Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:406"
time="2019-11-25T11:51:31Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:413"
An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: rpc error: code = Unknown desc = RequestError: send request failed
caused by: Get https://nas01.xmple.io:9000/velero.k8s.xmple.io?delimiter=%2F&list-type=2&prefix=: x509: certificate signed by unknown authority
```
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): v1.2.0
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`): v1.16.3
- Kubernetes installer & version: Rancher v2.3.2
- Cloud provider or hardware configuration: vSphere 6.7U3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.3

**Comment by skriss** [comment] 2019-12-02 22:34
@msnelling thanks for submitting the issue. This is a dupe of #1027 - I'm going to close this one out in favor of that existing issue.

**Closed by skriss** 2019-12-02 22:34 UTC
Labels: Duplicate
