### ISSUE TITLE
velero backup deletion is not working and ttl not working

### ISSUE THREAD

**Issue by mani-bca** [vmware-tanzu/velero#4113] opened 2021-09-08 06:58 UTC
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
velero schedule create firstbackup --schedule="@every 2m" --ttl 0h3m0s
in minio bucket the object are still there after the ttl expiration 
and velero backup delete firstbackup this command also not working

**What did you expect to happen:**
i expected to delete the pervious backup files are deleted in after TTL expire 

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
nothing

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment] 2021-09-08 07:59
Which version of velero are you using? Is there any error logs in the velero server about the cleaning up expired backups?

Could provide more information for `velero backup delete firstbackup this command also not working`? Does it report errors or not?

**Comment by mani-bca** [comment] 2021-09-08 08:32
hi,
using velero Version: v1.6.3.
no error logs in velero server about expired backup.

"velero backup delete firstbackup" firstbackup is backup name. if i execute this command that 'firstbackup' object is not deleting in the minio server

And i schedule the backup with TTL (velero schedule create k8s-backup --schedule="5 * * * *" --ttl 0h6m0s ) using this command  is working for backup only not deleting the object

**Comment by ywk253100** [comment] 2021-09-13 09:09
Dup of https://github.com/vmware-tanzu/velero/issues/3048

**Comment by ywk253100** [comment] 2021-09-13 09:11
@mani-bca I cannot reproduce the issue of `velero backup delete`

**Comment by ywk253100** [comment] 2021-09-13 23:28
Closing this issue, feel free to reopen it if you have any further question

**Closed by ywk253100** 2021-09-13 23:28 UTC
Labels: Needs info
