### ISSUE TITLE
LIST call performance suffers on very large clusters

### ISSUE THREAD

**Issue by dharmab** [vmware-tanzu/velero#3819] opened 2021-05-20 17:34 UTC
**What steps did you take and what happened:**

On very large clusters, such as clusters with many tens of thousands of resouce objects, Velero may time out when listing those objects with the log:

```
level=error msg="Error listing items" backup=velero/hourly-k8s-backup-20210518091554 error="stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 953119; INTERNAL_ERROR" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/backup/item_collector.go:294" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*itemCollector).getResourceItems" group=v1 logSource="pkg/backup/item_collector.go:294" namespace= resource=secret
```

(The above was on a cluster with around 25,000 Secrets and 75,000 active secret WATCH streams.)

This occurs when the latency of the cluster-scoped LIST Secrets call exceeds the apiserver's configured request timeout, causing the apiserver to close the connection (default 60 seconds).

Obviously, there are performance problems to address with the apiserver- however, Velero's performance can be drastically improved by using pagination to page through the cluster scoped resources instead of requesting all resources in a single request.

**What did you expect to happen:**

Velero should split the LIST calls into multiple shorter requests to improve performance.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`: See above for relevant log line
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 

```
[kube]$ velero version
Client:
	Version: v1.5.3
	Git commit: -
Server:
	Version: v1.5.1
```

- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
```
[kube]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:21:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by zubron** [comment] 2021-05-20 18:04
Thanks for reporting this, @dharmab! We currently have another issue opened for this: #262. I'm going to close this one as a duplicate of that so you may wish to follow that one instead.

**Closed** 2021-05-20 18:04 UTC
Labels: Duplicate
