### ISSUE TITLE
node-agent cpu & memory limitation parameters doesn't honored during   "velero install " script 

### ISSUE THREAD

**Issue by TzahiAshkenazi** [vmware-tanzu/velero#7423] opened 2024-02-13 14:02 UTC
**What steps did you take and what happened:**
when running the velero upstream installation script as follow :
```
./velero install \
  --provider aws \
  --image velero/velero:v1.12.3 \
  --plugins velero/velero-plugin-for-aws:latest,quay.io/konveyor/openshift-velero-plugin:latest,velero/velero-plugin-for-csi:main --bucket ${bucket_name} \
  --secret-file ${bucket_credentials_location} \
  --use-node-agent \
  --use-volume-snapshots=false \
  --namespace=${namespace} \
  --backup-location-config s3Url=${minio_url},insecureSkipTLSVerify=true,profile=default,region=minio=minio,s3ForcePathStyle=true \
  --features=EnableCSI --prefix "velero" \
  --velero-pod-cpu-limit "2000m" --velero-pod-mem-limit "2048Mi" \
  --node-agent-pod-cpu-limit "20000m" --node-agent-pod-mem-limit "32Gi" \
```
the node-agent cpu & memory limitation doesnt honored by the script
**What did you expect to happen:**
 node-agent cpu & memory limitation  will be honored 

**Anything else you would like to add:**
a workaround was edit the ds after the velero install completed 

**Environment:**
 
- Velero version (use `velero version`): 
  `[kni@f07-h27-000-r640 velero]$ ./velero version -nvelero-1-12
Client:
	Version:
	Git commit: -
Server:
	Version: v1.12.3
`
- Velero features (use `velero client config get features`): 
`
[kni@f07-h27-000-r640 velero]$ ./velero client config get features
features: <NOT SET>
`
- Kubernetes version (use `kubectl version`):
`
[kni@f07-h27-000-r640 velero]$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"dea6f474b21d4a33a76ca138fce4eba81ede2bee", GitTreeState:"clean", BuildDate:"2023-04-18T18:29:23Z", GoVersion:"go1.18.10", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.8+4fab27b", GitCommit:"c7a50586071278562f15130ff5ba194015aedee2", GitTreeState:"clean", BuildDate:"2023-12-01T15:11:39Z", GoVersion:"go1.20.10 X:strictfipsruntime", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.27) exceeds the supported minor version skew of +/-1
`

- Kubernetes installer & version:
- Cloud provider or hardware configuration:
   OCP running over BM servers
   3 masters & 12 workers nodes
- OS (e.g. from `/etc/os-release`):
sh-5.1# cat /etc/os-release
NAME="Red Hat Enterprise Linux CoreOS"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION="414.92.202312191502-0"
VERSION_ID="4.14"
VARIANT="CoreOS"
VARIANT_ID=coreos
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 414.92.202312191502-0 (Plow)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::coreos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://docs.openshift.com/container-platform/4.14/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.14"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.14"
OPENSHIFT_VERSION="4.14"
RHEL_VERSION="9.2"
OSTREE_VERSION="414.92.202312191502-0"

- deployment yaml 
```1
[kni@f07-h27-000-r640 velero]$ oc get deployment/velero -n velero-1-12 -oyaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2024-02-04T14:20:43Z"
  generation: 3
  labels:
    component: velero
  name: velero
  namespace: velero-1-12
  resourceVersion: "411255154"
  uid: c44b3239-2f95-4048-b2b0-0eb0635cf297
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deploy: velero
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8085"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        component: velero
        deploy: velero
    spec:
      containers:
      - args:
        - server
        - --features=EnableCSI
        - --uploader-type=kopia
        - --fs-backup-timeout=900m
        - --log-level=debug
        command:
        - /velero
        env:
        - name: VELERO_SCRATCH_DIR
          value: /scratch
        - name: VELERO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: LD_LIBRARY_PATH
          value: /plugins
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /credentials/cloud
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: AZURE_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: ALIBABA_CLOUD_CREDENTIALS_FILE
          value: /credentials/cloud
        image: velero/velero:v1.12.3
        imagePullPolicy: IfNotPresent
        name: velero
        ports:
        - containerPort: 8085
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /plugins
          name: plugins
        - mountPath: /scratch
          name: scratch
        - mountPath: /credentials
          name: cloud-credentials
      dnsPolicy: ClusterFirst
      initContainers:
      - image: velero/velero-plugin-for-aws:latest
        imagePullPolicy: IfNotPresent
        name: velero-velero-plugin-for-aws
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /target
          name: plugins
      - image: quay.io/konveyor/openshift-velero-plugin:latest
        imagePullPolicy: IfNotPresent
        name: konveyor-openshift-velero-plugin
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /target
          name: plugins
      - image: velero/velero-plugin-for-csi:main
        imagePullPolicy: IfNotPresent
        name: velero-velero-plugin-for-csi
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /target
          name: plugins
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: velero
      serviceAccountName: velero
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: plugins
      - emptyDir: {}
        name: scratch
      - name: cloud-credentials
        secret:
          defaultMode: 420
          secretName: cloud-credentials
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-02-04T14:20:43Z"
    lastUpdateTime: "2024-02-04T16:27:42Z"
    message: ReplicaSet "velero-674755865b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-02-11T08:50:12Z"
    lastUpdateTime: "2024-02-11T08:50:12Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by weshayutin** [comment] 2024-02-13 14:15
@TzahiAshkenazi can you please add the resulting deployment yaml so the incorrect values can be observed in the bug.

**Comment by ywk253100** [comment] 2024-02-15 03:38
Please make sure you are using the same version of Velero CLI with the server

**Comment by Lyndon-Li** [comment] 2024-02-19 02:08
@TzahiAshkenazi 
Please also attach the node-agent ds yaml, since you mentioned "the node-agent cpu & memory limitation doesnt honored by the script"

**Comment by TzahiAshkenazi** [comment] 2024-02-19 09:20
```
[root@f07-h27-000-r640 ~]# oc get  ds node-agent -n velero-1-12 -oyaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "4"
  creationTimestamp: "2024-02-04T14:20:43Z"
  generation: 4
  labels:
    component: velero
  name: node-agent
  namespace: velero-1-12
  resourceVersion: "404664959"
  uid: 1c8a98d3-7ec2-433c-bff1-fa3f953e8d51
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: node-agent
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: velero
        name: node-agent
    spec:
      containers:
      - args:
        - node-agent
        - server
        - --features=EnableCSI
        command:
        - /velero
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: VELERO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: VELERO_SCRATCH_DIR
          value: /scratch
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /credentials/cloud
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: AZURE_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: ALIBABA_CLOUD_CREDENTIALS_FILE
          value: /credentials/cloud
        image: velero/velero:v1.12.3
        imagePullPolicy: IfNotPresent
        name: node-agent
        ports:
        - containerPort: 8085
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: "20"
            memory: 32Gi
          requests:
            cpu: 500m
            memory: 512Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host_pods
          mountPropagation: HostToContainer
          name: host-pods
        - mountPath: /var/lib/kubelet/plugins
          mountPropagation: HostToContainer
          name: host-plugins
        - mountPath: /scratch
          name: scratch
        - mountPath: /credentials
          name: cloud-credentials
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      serviceAccount: velero
      serviceAccountName: velero
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/kubelet/pods
          type: ""
        name: host-pods
      - hostPath:
          path: /var/lib/kubelet/plugins
          type: ""
        name: host-plugins
      - emptyDir: {}
        name: scratch
      - name: cloud-credentials
        secret:
          defaultMode: 420
          secretName: cloud-credentials
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 12
  desiredNumberScheduled: 12
  numberAvailable: 12
  numberMisscheduled: 0
  numberReady: 12
  observedGeneration: 4
  updatedNumberScheduled: 12

```

**Comment by ywk253100** [comment] 2024-02-19 10:45
@TzahiAshkenazi The settings seems are correct:
```
        resources:
          limits:
            cpu: "20"
            memory: 32Gi
          requests:
            cpu: 500m
            memory: 512Mi
```

**Comment by ywk253100** [comment] 2024-02-19 10:47
And I also try in my local env, everything works as expected. I'm closing this issue, feel free to reopen it if you have any further questions.

**Closed by ywk253100** 2024-02-19 10:47 UTC
Labels: Needs info

**Comment by TzahiAshkenazi** [comment] 2024-02-19 12:42
@ywk253100 
those issues are correct since they were modified manually  after those setting didn't honored by the velero install 
as mention on the ticket 

```
Anything else you would like to add:
a workaround was edit the ds after the velero install completed

```

**Comment by ywk253100** [comment] 2024-02-20 01:41
Could you try again with the same version of CLI with the server(v1.12.3)? I saw your CLI version doesn't match with the server:
```
[kni@f07-h27-000-r640 velero]$ ./velero version -nvelero-1-12 Client: Version: Git commit: - Server: Version: v1.12.3 
```

I cannot reproduce the issue. If you get the same issue again, it's better to do some debugging and feel free to reopen this issue if you find any clue.

**Comment by TzahiAshkenazi** [comment] 2024-02-20 09:04
@ywk253100 
thanks for your comment 
currently the cluster  running this version is occupied with long run testing on upstream once it finish
i will check  with your request
