### ISSUE TITLE
volume-snapshots not work 

### ISSUE THREAD

**Issue by 631068264** [vmware-tanzu/velero#4852] opened 2022-04-21 07:40 UTC
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

install cmd
```sh
velero install \
   --plugins velero/velero-plugin-for-aws:v1.4.0 \
   --provider aws \
   --bucket velero \
   --namespace velero \
   --secret-file ./credentials-velero \
   --velero-pod-cpu-request 200m \
   --velero-pod-mem-request 200Mi \
   --velero-pod-cpu-limit 1000m \
   --velero-pod-mem-limit 1000Mi \
   --restic-pod-cpu-request 200m \
   --restic-pod-mem-request 200Mi \
   --restic-pod-cpu-limit 1000m \
   --restic-pod-mem-limit 1000Mi \
   --use-restic \
   --use-volume-snapshots=true \
   --snapshot-location-config region=minio \
   --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://xxxx:9000 \
   --wait
```

Use example from `kubectl apply -f examples/nginx-app/with-pv.yaml`
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/8144089/164405038-03e4870f-e41e-4c51-baf0-968c79cb7683.png">

Backup yaml
```yaml
{
   "apiVersion": "velero.io/v1",
   "kind": "Backup",
   "metadata": {
      "name": "nginx-backup-volume-test1",
      "namespace": "velero"
   },
   "spec": {
      "includedNamespaces": [
         "nginx-example"
      ],
      "snapshotVolumes":true
      
      
   }
}
```

restore.yaml
```yaml
{
   "apiVersion": "velero.io/v1",
   "kind": "Restore",
   "metadata": {
      "name": "nginx-backup-volume",
      "namespace": "velero"
   },
   "spec": {
      "backupName": "nginx-backup-volume-test1",
      "includedNamespaces": [
         "nginx-example"
      ],
      "restorePVs": true
   }
}
```

**After restore I can't find  any old log or old file under** `/var/log/nginx`.

All task is Completed without any error or warning.

**Environment:**

- Velero version (use `velero version`):  1.8
- Velero features (use `velero client config get features`):  features: <NOT SET>

- Kubernetes version (use `kubectl version`):   
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version: rke 
- Cloud provider or hardware configuration: 
- OS (e.g. from `/etc/os-release`): centos 7

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment] 2022-04-25 01:40
Is this issue the same with #4853, one is for backup and the other one is for restore?
**If this the same:**
Looks like you are using NFS for the PVC "nginx-logs". Velero's Volume Snapshotter doesn't support, you need to use Restic to backup this kind of Pod and PVC.
From the attached log in #4853, the Restic backup is not enabled: 
time="2022-04-21T08:58:56Z" level=info msg="Backing up all pod volumes using restic: false" backup=velero/nginx-backup-volume-test1 logSource="pkg/backup/backup.go:204"

If this is not the same, please provide more details, specifically, please provide the Velero logs.


Thanks.

**Comment by Lyndon-Li** [comment] 2022-05-24 02:36
@631068264 Is this problem solved? If not, please provide more information as mentioned above.

**Comment by Lyndon-Li** [comment] 2022-07-04 07:08
Closing this stable issue, if more help is needed, please reopen it. Thanks.

**Closed by Lyndon-Li** 2022-07-04 07:08 UTC
Labels: Needs info

**Comment by thedarkside** [comment] 2022-10-14 15:11
@Lyndon-Li i can reproduce it in one scenario: if you have a finished pod (a leftover triggered by a job) which shares the same pvc with a still running pod (the real app), velero will not backup that pvc.

The reason is because first velero skips the pvc because the first pod is not running and when it gets to the second running pod it says in the log "it was already backuped prior. skipping".

The result is that the underlying pv contents wont get backuped at all!

I worked around that issue by annotating all job pods with `velero.io/exclude-from-backup=true`.

**Comment by sseago** [comment] 2022-10-14 15:19
@thedarkside Is this with restic or with volume snapshots? If you're still using NFS volumes, I'm assuming this is with restic. I don't think the volume snapshotter should really depend on pods in any significant way (other than the annotations which determine when to use snapshots vs. restic), while restic backup and restore does depend on the pod the PVC is attached to. Either way, this sounds like a bug if completed job pods prevent PVC backup, but if you're using restic, then you should probably create a new issue with the current failing scenario described, since it's no longer related to the original volume-snapshot bug as reported.

**Comment by thedarkside** [comment] 2022-10-14 21:45
@sseago you are right! Its restic. My mistake, sorry! Will report it cause i think it is a bug too!
