### ISSUE TITLE
Add `velero status` command

### ISSUE THREAD

**Issue by ncdc** [vmware-tanzu/velero#1094] opened 2018-11-28 17:40 UTC
Expansion of #770. Add more details, such as "missing a BackupStorageLocation". More details TBD.

**Comment by nrb** [comment] 2019-09-18 16:48
Per https://github.com/heptio/velero/pull/1849#issuecomment-532370324, this could also report any feature flags enabled on the server.

**Comment by nrb** [comment] 2020-10-22 17:23
Closing as a duplicate of #979, which has more commentary.

**Closed by nrb** 2020-10-22 17:23 UTC
Labels: Duplicate, Enhancement/User, P2 - Long-term important
