### ISSUE TITLE
Unable to backup persistentvolumeclaims to multiple storage locations

### ISSUE THREAD

**Issue by a4nowgh** [vmware-tanzu/velero#2241] opened 2020-02-04 19:08 UTC
**What steps did you take and what happened:**
An annotated persistent volume claim mount volume fails to backup to a secondary storage location after successfully backing up to a primary storage location.  The same backup job to the primary storage location can be performed again successfully.

$ kubectl -n <NAMESPACE> annotate po <POD> backup.velero.io/backup-volumes=<PVC-MOUNT-VOLUME>
$ velero backup create backup-job-1 --include-namespace <NAMESPACE> --storage-location s3-bucket-1 (success)
$ velero backup create backup-job-2 --include-namespace <NAMESPACE> --storage-location s3-bucket-2 (PartiallyFailed (1 error))
$ velero backup describe backup create backup-job-2 --details | grep persistentvolumeclaims
time="2020-02-04T13:50:47Z" level=info msg="Skipping item because it's already been backup." backup=velero/backup-job-2 group=v1 logSource="pkg/backup/item_backupper.go:163" name=<NAME> namespace=<NAMESPACE> resource=persistentvolumeclaims

**What did you expect to happen:**
Backup persistentvolumeclaim to a second storage location after backing up to primary storage location.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version: v1.2.0
- Velero features: <NOT SET>
- Kubernetes Client version: v1.15.3
- Kubernetes Server version: v1.14.6
- Cloud provider or hardware configuration: aws
- OS: Ubuntu 18.04.3 LTS

**Comment by jenting** [comment] 2020-02-05 01:43
@a4nowgh, which case did you configure? Two backup-location and two snapshot-locations or two backup-locations and one snapshot-location?

In my usage, I could take 2 volume snapshots with two backup-locations (to different S3 bucket) and one snapshot-location on AWS. (Velero would create 2 snapshots in AWS EBS snapshots.)

**Comment by carlisia** [comment] 2020-02-05 21:45
Hey @a4nowgh would you please give us the output of: 

`kubectl describe backupstoragelocations`?

**Comment by a4nowgh** [comment] 2020-02-06 19:52
Hello,
Below is my output:

$ kubectl describe backupstoragelocations default
Spec:  Config:    Region:    us-east-1    s3ForcePathStyle: true    s3Url:    https://backupserver2.cloud.com
  Object Storage:    Bucket: bucketname  Provider: aws

$ kubectl describe backupstoragelocations default
Spec:  Config:    Region:    minio    s3ForcePathStyle: true    s3Url:    https://backupserver2.cloud.com
  Object Storage:    Bucket: bucketname  Provider: aws
 $ kubectl describe volumesnapshotlocation default
Spec:  Config:    Profile: default
    Region: us-east-1  Provider: velero.io/aws
$ kubectl describe volumesnapshotlocation minio
Spec:  Config:    Profile: minio
    Region: minio  Provider: velero.io/aws

    On Wednesday, February 5, 2020, 4:45:04 PM EST, Carlisia Campos <notifications@github.com> wrote:  
 
 
Hey @a4nowgh would you please give us the output of:

kubectl describe backupstoragelocations?

**Comment by skriss** [comment] 2020-02-11 20:41
@a4nowgh couple of questions:

1. I see you're running on AWS - are you using EBS snapshots or restic for the volume backup?
2. Could you include the full logs of both backups? (you can put them in a Gist/pastebin/etc and include a link). If that's not possible for some reason, please at least send the error message(s) that you're getting on the second backup.

Wondering if this is a duplicate of #2192?

**Comment by a4nowgh** [comment] 2020-02-12 10:18
Yes, this seems to be a duplicate of #2192.  I'm wondering if PR #2244(https://github.com/vmware-tanzu/velero/pull/2244) will address this issue?

   On Tuesday, February 11, 2020, 3:41:30 PM EST, Steve Kriss <notifications@github.com> wrote:  
 
 
@a4nowgh couple of questions:
   
   - I see you're running on AWS - are you using EBS snapshots or restic for the volume backup?
   - Could you include the full logs of both backups? (you can put them in a Gist/pastebin/etc and include a link). If that's not possible for some reason, please at least send the error message(s) that you're getting on the second backup.

Wondering if this is a duplicate of #2192?

**Comment by a4nowgh** [comment] 2020-02-12 10:27
I'm using restic for the volume backup.

    On Wednesday, February 12, 2020, 5:17:30 AM EST, junkmailatm-github@yahoo.com <junkmailatm-github@yahoo.com> wrote:  
 
  Yes, this seems to be a duplicate of #2192.  I'm wondering if PR #2244(https://github.com/vmware-tanzu/velero/pull/2244) will address this issue?

   On Tuesday, February 11, 2020, 3:41:30 PM EST, Steve Kriss <notifications@github.com> wrote:  
 
 
@a4nowgh couple of questions:
   
   - I see you're running on AWS - are you using EBS snapshots or restic for the volume backup?
   - Could you include the full logs of both backups? (you can put them in a Gist/pastebin/etc and include a link). If that's not possible for some reason, please at least send the error message(s) that you're getting on the second backup.

Wondering if this is a duplicate of #2192?

**Comment by skriss** [comment] 2020-02-12 15:34
I would expect #2244 to fix it, yes. I'll link this issue up to that PR. Hoping to get that fix in for our upcoming release.

**Closed** 2020-02-19 19:01 UTC
Labels: Bug, Duplicate

**Comment by skriss** [comment] 2020-02-26 17:41
xref https://github.com/vmware-tanzu/velero/pull/2244#issuecomment-591446887

@jenting - any ideas on why @a4nowgh is still getting this error with `v1.3.0-beta.2`? I'm not sure off the top of my head. I'm going to try to reproduce as well.

**Comment by skriss** [comment] 2020-02-26 18:01
@a4nowgh did you also update your restic daemonset to use the `beta.2` image?  `kubectl -n velero set image daemonset/restic restic=velero/velero:v1.3.0-beta.2` would do that, if not.

FWIW, I was *not* able to reproduce this using `beta.2`.

**Comment by jenting** [comment] 2020-02-26 20:17
From the log, my first idea is the container image is not `v1.3.0-beta.2`.

@a4nowgh, have you follow the [v1.3.0-beta.2 release note](https://github.com/vmware-tanzu/velero/releases/tag/v1.3.0-beta.2) on upgrading the velero and restic container image?

**Comment by a4nowgh** [comment] 2020-02-27 11:48
Upgrading the restic container image, in additional to the velero container image, resolved my issue.  Thanks very much for the quick response!
