### ISSUE TITLE
Velero backup failure after upgrading to 1.5.2

### ISSUE THREAD

**Issue by davidshare** [vmware-tanzu/velero#3221] opened 2021-01-04 22:21 UTC
**What steps did you take and what happened:**
I upgraded velero version from 1.5.1 to 1.5.2 using the vmware-tanzu helm chart

After the upgrade ran successfully, I get the following errors in the pod.

```
time="2021-01-04T21:56:28Z" level=error msg="Error patching backup location's last-synced time" backupLocation=gcp controller=backup-sync error="backupstoragelocations.velero.io \"gcp\" not found" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_sync_controller.go:311" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*backupSyncController).run" logSource="pkg/controller/backup_sync_controller.go:311"
I0104 21:56:50.681023       1 request.go:621] Throttling request took 1.039360758s, request: GET:https://10.128.128.1:443/apis/internal.autoscaling.k8s.io/v1alpha1?timeout=32s
time="2021-01-04T21:56:58Z" level=error msg="Error patching backup location's last-synced time" backupLocation=default controller=backup-sync error="backupstoragelocations.velero.io \"default\" not found" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_sync_controller.go:311" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*backupSyncController).run" logSource="pkg/controller/backup_sync_controller.go:311"
time="2021-01-04T21:56:58Z" level=error msg="Error patching backup location's last-synced time" backupLocation=gcp controller=backup-sync error="backupstoragelocations.velero.io \"gcp\" not found" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_sync_controller.go:311" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*backupSyncController).run" logSource="pkg/controller/backup_sync_controller.go:311"
```
Velero creates a new backup and it is stuck in the `Inprogress` status.

- I have checked the values.yaml file for velero to be sure it is configured properly and everything seems okay.
- I followed the instructions for the upgrade on velero documentation and installed the crds
- The right permissions are set for the service account file being used.

**What did you expect to happen:**

I expected velero to backup the cluster successfully

**The output of the following commands will help us better understand what's going on**:
github gist with logs and extra information

https://gist.github.com/davidshare/6b355a56f606e1132ddb600551c77cbe

**Anything else you would like to add:**

The values.yaml file

```
initContainers:
   # see https://github.com/vmware-tanzu/velero-plugin-for-gcp
   - name: velero-plugin-for-gcp
     image: velero/velero-plugin-for-gcp:v1.1.0
     imagePullPolicy: IfNotPresent
     volumeMounts:
       - mountPath: /target
         name: plugins

configuration:
  provider: gcp
  backupStorageLocation:
    name: default
    bucket: project-id-backups
    prefix: velero
    config:
      serviceAccount: dev-gke-velero@project-id.iam.gserviceaccount.com

  volumeSnapshotLocation:
    name: gcp

serviceAccount:
  server:
    create: true
    name: velero
    annotations:
      iam.gke.io/gcp-service-account: dev-gke-velero@project-id.iam.gserviceaccount.com

credentials:
  useSecret: false

schedules:
  gcp:
    schedule: "30 9 * * *"
    template:
      storageLocation: gcp
      includeClusterResources: true
      includedNamespaces:
        - '*'
      includedResources:
        - '*'
      snapshotVolumes: true
      ttl: "720h"
```

**Environment:**

GKE - v1.17

**Vote on this issue!**

**Comment by zubron** [comment] 2021-01-05 18:32
Hi @davidshare - sorry you've having problems with this. Did you change any configuration related to the `backupStorageLocation` during the upgrade? The logs are referencing a backup storage location which is not defined in your values.yaml (`gcp`).

Could you please share the full logs from the Velero pod? There may be some additional context which will help us understand what is going on here. Also, can you post the output from `velero backup-locations get` so we can confirm which backup locations exist?

**Comment by davidshare** [comment] 2021-01-05 18:55
Thank you @zubron for looking at this. I changed the backup storage location after the backups failed and I was trying to troubleshoot for what the issue could be. But I reversed that and updated it with the previous one after I realized that it did not solve the issue.

This is a gist with the full logs.

https://gist.github.com/davidshare/3cce98ec190cf2eff800eeb60263dedc

**Comment by davidshare** [comment] 2021-01-05 19:34
The result of `velero backup-locations get`
```
default   gcp        project-id-backups/velero   ReadWrite
gcp       gcp        project-id-backups/velero   ReadWrite
```

**Comment by davidshare** [comment] 2021-01-06 09:28
Hi @zubron - were you able to figure something out. This is still a log in my eye.

**Comment by zubron** [comment] 2021-01-06 13:50
So the `Phase` and `Last Validated` columns are empty? I'm not sure what would cause that. Even if the status `Phase` and `LastValidationTime` are empty, the CLI should print "Unknown" in those columns. :confused: 

I'm going to have to ask you for some more debug information! Could you please provide the output from `kubectl get backupstoragelocations.velero.io -n velero -o yaml`?

**Comment by davidshare** [comment] 2021-01-06 15:12
@zubron - This is the result of the command - `kubectl get backupstoragelocations.velero.io -n velero -o yaml`

```
apiVersion: v1
items:
- apiVersion: velero.io/v1
  kind: BackupStorageLocation
  metadata:
    annotations:
      helm.sh/hook: post-install,post-upgrade
      helm.sh/hook-delete-policy: before-hook-creation
    creationTimestamp: "2021-01-05T18:45:57Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: velero
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: velero
      helm.sh/chart: velero-2.14.4
    name: default
    namespace: velero
    resourceVersion: "xxxxxxxxxx"
    selfLink: /apis/velero.io/v1/namespaces/velero/backupstoragelocations/default
    uid: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx
  spec:
    config:
      serviceAccount: dev-gke-velero@project-id.iam.gserviceaccount.com
    objectStorage:
      bucket: project-id-backups
      prefix: velero
    provider: gcp
- apiVersion: velero.io/v1
  kind: BackupStorageLocation
  metadata:
    annotations:
      helm.sh/hook: post-install,post-upgrade
      helm.sh/hook-delete-policy: before-hook-creation
    creationTimestamp: "2021-01-05T13:48:20Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: velero
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: velero
      helm.sh/chart: velero-2.14.4
    name: gcp
    namespace: velero
    resourceVersion: "334330464"
    selfLink: /apis/velero.io/v1/namespaces/velero/backupstoragelocations/gcp
    uid: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx
  spec:
    config:
      serviceAccount: dev-gke-velero@project-id.iam.gserviceaccount.com
    objectStorage:
      bucket: project-id-backups
      prefix: velero
    provider: gcp
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
  ```

**Comment by zubron** [comment] 2021-01-06 15:41
Thanks for providing the extra info.

I've just checked our Helm charts repository and found another person with the same issue: https://github.com/vmware-tanzu/helm-charts/issues/168#issuecomment-727260191. For this particular user, they were using Flux and to fix the issue disabled the Helm hooks in their chart: https://github.com/vmware-tanzu/helm-charts/issues/168#issuecomment-730208304.

Can you provide details on how you are installing/upgrading the helm chart? Are you using any additional tools to manage it? Thanks!

**Comment by davidshare** [comment] 2021-01-06 15:49
I am not using additional tools, just the helm chart to deploy to an EKS cluster.

**Comment by zubron** [comment] 2021-01-06 23:39
Unfortunately, I haven't been able to reproduce this locally. Can you please share the following:

- The commands you are using to install/upgrade the helm chart
- Output from `velero version` (to check the version of local client being used)

This issue was also reported in #2913. The solution for helm users was to perform the upgrade instructions found here: https://velero.io/docs/v1.5/upgrade-to-1.5/
I know you said you already performed the upgrade instructions but I'd like to verify that the correct version of the client was used to do this.

Thanks for your patience!

**Comment by davidshare** [comment] 2021-01-07 16:34
Thank you @zubron for staying with me on this:


```
velero version

Client:
	Version: v1.4.2
	Git commit: 56a08a4d695d893f0863f697c2f926e27d70c0c5
<error getting server version: timed out waiting for server status request to be processed>
```

The command for installing the chart.

```
helm upgrade vmware-tanzu/velero velero --atomic --timeout 900s --version 2.14.4 --install --namespace velero -f dev.values.yaml -f dev.secrets.yaml --debug
```

**Comment by zubron** [comment] 2021-01-07 16:37
Ah, so in order to perform the upgrade steps to use 1.5 and later, you will need to use the [1.5 version of the client](https://github.com/vmware-tanzu/velero/releases/tag/v1.5.2). Can you please download/install that and then retry the [upgrade steps](https://velero.io/docs/v1.5/upgrade-to-1.5/) again? By using the 1.4 version of the client, you will have installed older versions of the CRDs which will likely have caused this issue.

**Comment by davidshare** [comment] 2021-01-08 14:38
Than you @zubron this was the solution I was looking for. I did not realize the local velero client had to correspond with the version in the chart.

Thank you.

**Comment by zubron** [comment] 2021-01-08 14:56
Glad you got it fixed! Yes, unfortunately the CRDs can't be upgraded with helm so the using the CLI is a necessary part of the process. During the upgrade, you will need to use the same minor version of the CLI as the version you are trying to upgrade to, so any 1.5.* client should be fine.

Since this is now working for you, I'm going to close this issue.

**Closed by zubron** 2021-01-08 14:56 UTC
Labels: Needs info, Needs investigation
