### ISSUE TITLE
Kubecontext flag missing from versions >1.9.5

### ISSUE THREAD

**Issue by gscho** [vmware-tanzu/velero#5896] opened 2023-02-21 20:31 UTC
**What steps did you take and what happened:**

We upgraded velero from v1.9.5 to 1.10.1 and existing processes using the `--kubecontext` flag began failing

```
unknown flag: --kubecontext
```

**What did you expect to happen:**

The flag to exist still.

Looks like it may have been removed inadvertently by https://github.com/vmware-tanzu/velero/pull/5124 specifically this commented out line: https://github.com/vmware-tanzu/velero/pull/5124/files#diff-ba8260b29909b6c7324036b886b8ed4b021d782bd3f8e94e160b5a2a872e6762R100

**Comment by danfengliu** [comment] 2023-02-22 13:57
It will be fixed by PR #5904, and the root cause is described in [comment](https://github.com/vmware-tanzu/velero/pull/5898#issuecomment-1440051601) of PR #5898, it's a break change.

**Closed** 2023-02-23 06:42 UTC
Labels: Bug
