### ISSUE TITLE
CSISnapshotTimeout parameter of backup spec not getting honored in velero-plugin-for-csi while it is getting honored in velero core.

### ISSUE THREAD

**Issue by Shashank1306s** [vmware-tanzu/velero#6261] opened 2023-05-11 10:27 UTC
**What steps did you take and what happened:**

I tried to change the CSISnapshotTimeout to 1 min in the backup CR, but still it waited for default CSI timeout(which is 10min).

**What did you expect to happen:**
The CSISnapshotTimeout should have been honored.

**The following information will help us better understand what's going on**:
Code reference where CSI timeout is set [It is hardcoded as 10 min]: 
[https://github.com/vmware-tanzu/velero-plugin-for-csi/blob/db448f3f3fb030735da686b489e1bf6e23b6ac1c/internal/util/util.go#L163](https://github.com/vmware-tanzu/velero-plugin-for-csi/blob/db448f3f3fb030735da686b489e1bf6e23b6ac1c/internal/util/util.go#L163)

Code reference in the velero core code where CSISnapshotTimeout is set:
[https://github.com/vmware-tanzu/velero/blob/12a14d11e9996688aabd0f23848d8712cc73443b/pkg/controller/backup_controller.go#LL332C6-L332C6](https://github.com/vmware-tanzu/velero/blob/12a14d11e9996688aabd0f23848d8712cc73443b/pkg/controller/backup_controller.go#LL332C6-L332C6)

Usage: [https://github.com/vmware-tanzu/velero/blob/12a14d11e9996688aabd0f23848d8712cc73443b/pkg/controller/backup_controller.go#L657](https://github.com/vmware-tanzu/velero/blob/12a14d11e9996688aabd0f23848d8712cc73443b/pkg/controller/backup_controller.go#L657)

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by dzaninovic** [comment] 2023-05-12 21:21
Here is a pull request with the proposed fix:
https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/175

**Comment by reasonerjt** [comment] 2023-05-15 06:13
@blackpiglet please check the PR and we may want to have that in next patch

**Comment by blackpiglet** [comment] 2023-05-16 12:08
@Shashank1306s 
I'm not sure about this proposal. If we make the CSI plugin also use the setting, the timeout does get shorter in this scenario, but the change will also make the timeout double when the timeout is set to more than 10 minutes.

Ideally, the CSI volume polling logic should be placed in the CSI plugin code, but due to the current BackupItemAction v1 cannot work asynchronously, which makes the multiple CSI volumes that will wait for a very long time. That's why there are two places that have the polling logic.
There is an issue that requires the CSI plugin to adopt the BackupItemAction v2. It's planned for v1.12. When the CSI plugin uses the BIAv2, there is only one polling logic left.
Is this acceptable for your scenario?

**Comment by blackpiglet** [comment] 2023-05-18 08:31
@anshulahuja98 
Thanks for pointing this out. The polling VolumeSnapshotContent's handle logic should be kept.

But I'm not sure whether the polling in the Velero server should be removed. 
That part of the code is used to address issue #4819. I met error case when the snapshot handle was already updated into the VSC status.

**Comment by anshulahuja98** [comment] 2023-05-18 08:37
I am not fully sure of this issue's repro #4819.
Which CSI driver was your cluster using.

If in that CSI driver the VSC is being updated before snapshot completion and also being marked as ready to use. I think the CSI driver impl has some issue.

My understanding is that if we have a snapshothandle along side readytouse true in VSC it is enough to ensure snapshotting completed.

This check is already done in CSI plugin - I am not sure how the core code polling is any different from this.

Can you try to see if you can repro this issue today?

**Comment by blackpiglet** [comment] 2023-05-18 08:55
I cannot remember the Azure CSI driver version. The CSI provisioner version is v2.2.0.

Per the previous testing, adding waiting for VSC status as `ReadyToUse` will increase the waiting time significantly. That's the reason they are separated into two parts. If we cannot put the polling for VSC's status snapshot handle in the async step, maybe the polling for `ReadyToUse` is still needed, and that part should be put into the async step.

**Comment by anshulahuja98** [comment] 2023-05-19 04:55
I don't fully agree with that conclusion. I feel that fundamentally if snapshotHandle is populated, it is very likely that ReadyToUse should be already populated. 
When both are satisfied, only then we can be confident snapshotting is complete and we can run postHooks.

I propose that both the checks be carried on in the CSI plugin and nothing in core code. 

Can we test these scenarios with current state of CSI drivers and ext snapshotter. They have also evolved a bit over time.

Or if we can somehow see logs telemetry of how many times the core code has required to poll more than once(mostly it would always have been completed by then) and no logs would have been pushed in telemetry.

This telemetry can make us confident that second polling is not even needed.

**Comment by blackpiglet** [comment] 2023-05-19 05:56
@anshulahuja98 
In most cases, the polling logic in the Velero server isn't needed, but for some extremely large volumes, the time waiting for ReadyToUse can be longer than expected, and that's the reason the CSI timeout setting is added.
AFAIK, the long waiting period is caused by moving data to OSS after snapshot completion.

**Comment by draghuram** [comment] 2023-05-19 15:56
Based on these:

https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/sidecar-controller/snapshot_controller.go#L42

and

https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/sidecar-controller/snapshot_controller.go#L266

It seems that setting "snapshotHandle" and "readyTouse" fields are two distinct operations and hence, there is a possibility that "snapshotHandle" is present but snapshot is not yet ready for restore. How ever, I agree that CSI plug-in should take care of all CSI related functionality.

**Comment by sseago** [comment] 2023-05-19 17:48
@draghuram So I think everyone is in agreement that having a snapshot handle doesn't imply that the snapshot is ready to use. The question that matters in terms of whether the post hooks can run isn't whether the snapshot is ready to use, though, since post-backup hooks won't attempt to use the snapshot. What matters here is, during the time after snapshot handle is available but before snapshot is ready to use, whether the process creating the snapshot is done with the live volume. i.e. if snapshot is created but just not fully-uploaded, then it doesn't matter what happens to the live volume, as it won't affect the snapshot, so hooks can run, but if the snapshot content is still being generated from the live volume even after snapshot handle is available, then hooks cannot run. What's not clear to me is which of the two situations we're dealing with here.

**Comment by blackpiglet** [comment] 2023-05-21 06:51
@Shashank1306s @anshulahuja98 
Please correct me if I misunderstood this issue.
This issue intends to make the timeout setting more clear. The proposed solution was unifying two polling logics.

The two polling cannot be merged by now, but I agree that moving the CSI snapshot timeout setting to the Velero CSI plugin for polling the snapshot handle creation. 
After the Velero CSI plugin adopted BIA v2, move the polling ReadyToUse logic to the BIA v2 progress checking logic.

@sseago @draghuram
What's your opinion about it?

**Comment by anshulahuja98** [comment] 2023-05-22 04:18
```The two polling cannot be merged by now````
I understand this now, thank you @sseago  / @blackpiglet  for explaining the difference between the two polling logic.
``` but I agree that moving the CSI snapshot timeout setting to the Velero CSI plugin for polling the snapshot handle creation.```
Given that understanding for now I would only request for both the polling to handle the csiSnapshotTimeout.

**Comment by blackpiglet** [comment] 2023-05-22 05:54
@anshulahuja98 
Thanks for your feedback.

The polling of the snapshot handle will honor the `csiSnapshotTimeout` setting.
The polling of `ReadyToUse` will honor the BIA v2's operation timeout setting, because it's supposed to be an async operation. Although they are different timers, users can still control the time setting as their wishes.

**Comment by draghuram** [comment] 2023-05-22 19:40
@sseago Thanks for a very clear explanation of the issue at hand. 

Here is the summary of the issue as I see it after going through the comments few times. Please feel free to correct me if I am wrong:

1. There is a consensus that the polling in CSI plug-in that waits for snapshot handle to be set should honor "csiSnapshotTimeout" setting. This timeout is currently hard-coded to 10 minutes and PR from @dzaninovic addresses this issue. I think that it should be merged. 
2. There is polling in backup controller that waits for "readyToUse" flag to be set. The purpose of this is to make sure that post-hooks can be run. So we need to be really sure that snapshot is decoupled from live volume at this point. I do think that we need to wait for "readyToUse" to be set as there is no other setting that tells us whether snapshot is "decoupled" but still being uploaded. I will post in sig-storage to see if they have any ideas.
3. "readyToUse" polling will remain in place and will use "csiSnapshotTimeout" for now. But once BIA V2 is adopted by CSI plugin, this polling will be moved to CSI plug-in and will honor operation timeouts of BIA V2.

**Comment by draghuram** [comment] 2023-05-23 02:53
As per this comment:

 https://kubernetes.slack.com/archives/C09QZFCE5/p1684790015135739?thread_ts=1684786045.954979&cid=C09QZFCE5

Post-hooks can be run as soon as snapshot handle is available.

**Comment by dzaninovic** [comment] 2023-06-29 15:01
Pull request with the fix was merged.
https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/175

**Closed** 2023-06-30 01:56 UTC
Labels: Area/CSI
