### ISSUE TITLE
Failed to read all source data during backup. PVC backup with Restic

### ISSUE THREAD

**Issue by pavanfhw** [vmware-tanzu/velero#4331] opened 2021-11-10 14:04 UTC
**What steps did you take and what happened:**
Backups are marked as PartiallyFailed after Warning: failed to read all source data during backup\n: exit status 3 is raised during backup (with --use-restic) of a Linstor volume. Linstor storage is using Thin LVM.
This error does not always happen, so I am not sure what causes the read fail. I have around 90 volumes I need to backup, but some volume backup will always fail with this error, not always the same ones. 

**What did you expect to happen:**
I want to understand why this happens, I read in other issues this is because there are empty files in the backup, also that maybe some files are deleted during the Restic backup. For the second option, does Restic not take snapshots of the volume before backing up? 

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

Failed backup log output 
```
time="2021-11-09T17:47:08Z" level=info msg="Skipping snapshot of persistent volume because volume is being backed up with restic." backup=velero/test-label logSource="pkg/backup/item_backupper.go:423" name=pvc-4bd00ee0-6639-49d4-abac-707305fc6746 namespace= persistentVolume=pvc-4bd00ee0-6639-49d4-abac-707305fc6746 resource=persistentvolumes
time="2021-11-09T17:47:37Z" level=info msg="1 errors encountered backup up item" backup=velero/test-label logSource="pkg/backup/backup.go:427" name=abravanew-7d699c9ddd-62d9b
time="2021-11-09T17:47:37Z" level=error msg="Error backing up item" backup=velero/test-label error="pod volume backup failed: error running restic backup, stderr={\"message_type\":\"error\",\"error\":{\"Op\":\"lstat\",\"Path\":\"/host_pods/623bc4d1-4a49-491e-9992-d1ebd43b7b64/volumes/kubernetes.io~csi/pvc-4bd00ee0-6639-49d4-abac-707305fc6746/mount/safebrowsing-updating\",\"Err\":2},\"during\":\"scan\",\"item\":\"/host_pods/623bc4d1-4a49-491e-9992-d1ebd43b7b64/volumes/kubernetes.io~csi/pvc-4bd00ee0-6639-49d4-abac-707305fc6746/mount/safebrowsing-updating\"}\n{\"message_type\":\"error\",\"error\":{\"Op\":\"lstat\",\"Path\":\"safebrowsing-updating\",\"Err\":2},\"during\":\"archival\",\"item\":\"/host_pods/623bc4d1-4a49-491e-9992-d1ebd43b7b64/volumes/kubernetes.io~csi/pvc-4bd00ee0-6639-49d4-abac-707305fc6746/mount/safebrowsing-updating\"}\nWarning: failed to read all source data during backup\n: exit status 3" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:179" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:431" name=abravanew-7d699c9ddd-62d9b
time="2021-11-09T17:47:37Z" level=info msg="Backed up 3 items out of an estimated total of 6 (estimate will change throughout the backup)" backup=velero/test-label logSource="pkg/backup/backup.go:394" name=abravanew-7d699c9ddd-62d9b namespace=whatsgate progress= resource=pods
```

**Environment:**

- Velero version (use `velero version`): 
```
Client:
	Version: v1.6.0
	Git commit: 5bd70fd8eef316d220317245e46dc6016c348dce
Server:
	Version: v1.6.0
```
- Velero features (use `velero client config get features`):  `features: <NOT SET>`
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T19:05:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: Cluster running on bare metal with k3s v1.18.9+k3s1
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from `/etc/os-release`):
```
NAME="k3OS"
VERSION="k3OS v0.11.1"
ID=k3os
ID_LIKE=alpine
PRETTY_NAME="k3OS v0.11.1"
VERSION_ID="v0.11.1"
HOME_URL="https://k3os.io/"
SUPPORT_URL="https://k3os.io/"
BUG_REPORT_URL="https://github.com/rancher/k3os/issues"
ISO_URL="https://github.com/rancher/k3os/releases/download/v0.11.1/k3os-amd64.iso"
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by zubron** [comment] 2021-11-10 21:04
This looks like it is a duplicate of #4072 and it is likely that the file was present during restic's initial scan of the volume but was removed at the point when the file was _actually_ backed up to the restic store. Many users work around this by freezing the file system to ensure that no disk I/O operations are in progress during the backup: https://velero.io/docs/v1.7/backup-hooks/#hook-example-with-fsfreeze

As for your question about snapshotting the volume, this is not how our restic support currently works. Please read more about this in https://github.com/vmware-tanzu/velero/issues/4072#issuecomment-908826417.

I am going to close this in favour of #4072. If you have further comments about this, please add them to that issue. If you think this is not actually a duplicate, we can reopen.

**Closed by zubron** 2021-11-10 21:04 UTC
