### ISSUE TITLE
Way to update credentials for snapshot locations (aws plugin)

### ISSUE THREAD

**Issue by shaunc** [vmware-tanzu/velero#4426] opened 2021-12-03 05:08 UTC
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]

I can update credentials for [backup locations](https://velero.io/docs/v1.6/locations/#create-a-storage-location-that-uses-unique-credentials): 
```
$ velero backup-location set <bsl-name> \
  --credential=<secret-name>=<key-within-secret>
```
The equivalent command fails for snapshot location using aws provider:
```
$ velero snapshot-location set <bsl-name> \
  --credential=<secret-name>=<key-within-secret>
An error occurred: unknown flag: --credential
```

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

The above should work with snapshot locations. Also, documentation should be added to describe the crd manifests -- this would be useful in any case, and would help work around this until the cli addition is added.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.7
- Kubernetes version (use `kubectl version`):  1.17
- Kubernetes installer & version: EKS
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): macos

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by ywk253100** [comment] 2021-12-06 01:34
This isn't supported yet, but it is already in the roadmap https://github.com/vmware-tanzu/velero/issues/2426

**Comment by zubron** [comment] 2022-01-27 22:10
This is a duplicate of https://github.com/vmware-tanzu/velero/issues/4115 so I am closing this issue. If you have any further comments, please add them to the linked issue. Thanks!

**Closed by zubron** 2022-01-27 22:10 UTC
