### ISSUE TITLE
The namespace YAML was skipped when restoring a namespace that doesn't contain service YAML

### ISSUE THREAD

**Issue by Frank51** [vmware-tanzu/velero#4938] opened 2022-05-26 20:12 UTC
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

1. Backup the namespace metadata using velero. The namespace doesn't contain service resource.
2. Restoring the namespace with the copy using velero. Found that the namespace resource was skip on restore time.

**What did you expect to happen:**
The namespace YAML resource should be restored when it was included in "includedResources" of Velero Restore.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
```
- Velero's backup: {
    "metadata": {
       "name": "yelb-new-2022-05-26-11-23-52-yelb-new",
       "creationTimestamp": null
    },
    "spec": {
       "metadata": {},
       "includedNamespaces": [
          "yelb-new"
       ],
       "excludedResources": [
          "persistentvolumeclaims",
          "persistentvolumes"
       ],
       "ttl": "262800h0m0s",
       "hooks": {},
       "storageLocation": "yelb-new-no-svc-irv-vm-90-45-b79da-f465a352e01101c30455b5ef69834a7f.stagings"
    },
    "status": {}
}
```
- `velero backup logs <backupname>`
- https://gist.github.com/Frank51/0e0fe24f299585b3048829addcb364ee
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
```
-  Velero Restore: {
    "metadata": {
       "name": "a9aef1c3-fbd3-5c41-a8ab-06623dc8060b-2022-05-26-11-27-24-yelb-new-restore-no-svc-namespaceonly",
       "creationTimestamp": null
    },
    "spec": {
       "backupName": "yelb-new-2022-05-26-11-23-52-yelb-new",
       "includedResources": [
          "namespace",
          "services",
          "clusterrolebindings",
          "clusterroles",
          "customresourcedefinitions"
       ],
       "namespaceMapping": {
          "yelb-new": "yelb-new-restore-no-svc"
       },
       "restorePVs": false,
       "includeClusterResources": false,
       "hooks": {}
    },
    "status": {}
}
```
- `velero restore logs <restorename>`
- https://gist.github.com/Frank51/bfe2ba86199892d71995f58ea852035e

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by sseago** [comment] 2022-06-08 21:47
Currently on restore, the namespace resource is handled as a special case. Instead of restoring the namespace yaml from the backup, we actually just create a new namespace with the same name. There have been discussions around changing this, but it's been a while, and I'm not sure where that sort of change is on the roadmap right now.

One consequence of this is that if you create a restore plugin that applies only to namespace resources, it will never run.

**Comment by Lyndon-Li** [comment] 2022-06-09 02:11
Yes, this is an expected behavior as the current implementation.
The namespace is not treated as an independent object as others (CR, pod, pv, pvc, etc.). Instead, the namespace is created during restoring one of the other objects. 
In another word, if there is no other resource to be restored, for example, all of them are skipped as the current case, the namespace is not restored.
This behavior is possibly related to the requirement that renaming the namespace during restore. The old-new namespace map is along with the specific resource to be restored, so until the start of restoring the resource, Velero doesn't know what namespace is to be created.

**Comment by Lyndon-Li** [comment] 2022-06-09 02:14
Let me collect the requirements to change this behavior:
1. As @sseago mentioned: if you create a restore plugin that applies only to namespace resources, it will never run
2. @Frank51 Could share us more information of why you want to restore the namespace only, what is its importance?

**Comment by Frank51** [comment] 2022-06-24 22:31
> Let me collect the requirements to change this behavior:
> 
> 1. As @sseago mentioned: if you create a restore plugin that applies only to namespace resources, it will never run
> 2. @Frank51 Could you share us more information of why you want to restore the namespace only? what is its importance?

2. So basically we were backing up a namespace without "service" in it. But when restoring it, we found the behavior of velero is not as expected.  The "namespace" resource is restored as we expected.

**Comment by Lyndon-Li** [comment] 2022-06-27 01:39
@Frank51 It seems that in your current case, it is not a namespace without a service, but a namespace with Nothing (to be restored). Since all resources have been excluded in the namespace, as the current behavior, Velero doesn't restore the namespace alone, because we don't think there is anything useful to restore an empty namespace.
Please explain why restoring an empty namespace alone is useful to you, so that we can change our judgement. Thanks.

**Comment by Lyndon-Li** [comment] 2022-08-29 03:55
I am closing this issue as this is the current behavior of Velero as mentioned above. If we have any requirement that strongly requires a change of this behavior, we can reopen it. Thanks.

**Closed by Lyndon-Li** 2022-08-29 03:55 UTC
Labels: Needs investigation
