### ISSUE TITLE
Tips to speed up restic backup

### ISSUE THREAD

**Issue by hibbert** [vmware-tanzu/velero#2115] opened 2019-12-10 17:39 UTC
[thor-prod-backup-20191209200019-logs.txt](https://github.com/vmware-tanzu/velero/files/3946380/thor-prod-backup-20191209200019-logs.txt)

**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

Our backups are very slow due to lack of concurrency - https://github.com/vmware-tanzu/velero/issues/2078.

Looking for some ideas to help speed this up

**What did you expect to happen:**

Faster backups

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
```
$ velero version
Client:
	Version: v1.2.0
	Git commit: 5d008491bbf681658d3e372da1a9d3a21ca4c03c
Server:
	Version: v1.2.0
```
- Velero features (use `velero client config get features`): 
```
$ velero client config get features
features: <NOT SET>
```
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
EKS
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from `/etc/os-release`):
Amazon Linux 2

**Comment by hibbert** [comment] 2019-12-10 17:40
```velero backup describe``` - https://gist.github.com/hibbert/f814506b7031d29dcac7256c2bbd9f6c

**Comment by hibbert** [comment] 2019-12-10 17:46
The logs also do not seem to report all restic backups that are done:-
````
$ kubectl -n velero logs ds/restic --all-containers=true \| grep "restic backup" \| grep thor-prod-backup-20191209200019
--
Found 8 pods, using pod/restic-n6jls
time="2019-12-09T20:54:53Z" level=debug msg="Ran command=restic backup --repo=s3:s3-us-east-1.amazonaws.com/thor-prod-velero-us-east-1/restic/jenkins-brain --password-file=/tmp/velero-restic-credentials-jenkins-brain505809101 --cache-dir=/scratch/.cache/restic . --tag=volume=jenkins-home --tag=backup=thor-prod-backup-20191209200019 --tag=backup-uid=867cd6c3-1abe-11ea-851d-1227f638c493 --tag=ns=jenkins-brain --tag=pod=jenkins-brain-757c47d54c-7gjkt --tag=pod-uid=57c2e95e-0bc6-11ea-a95d-12d9fbde4cd6 --tag=pvc-uid=d42c36e3-5fb9-11e9-991e-12b46d3678f4 --host=velero --json --parent=1e492102, stdout={\"message_type\":\"summary\",\"files_new\":0,\"files_changed\":60,\"files_unmodified\":23052,\"dirs_new\":0,\"dirs_changed\":0,\"dirs_unmodified\":0,\"data_blobs\":30,\"tree_blobs\":1,\"data_added\":2331112,\"total_files_processed\":23112,\"total_bytes_processed\":5108783981,\"total_duration\":118.289892879,\"snapshot_id\":\"1383e7a2\"}, stderr=" backup=velero/thor-prod-backup-20191209200019 controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:265" name=thor-prod-backup-20191209200019-8lswb namespace=velero
time="2019-12-09T23:09:52Z" level=debug msg="Ran command=restic backup --repo=s3:s3-us-east-1.amazonaws.com/thor-prod-velero-us-east-1/restic/jenkins-delphi --password-file=/tmp/velero-restic-credentials-jenkins-delphi893146568 --cache-dir=/scratch/.cache/restic . --tag=pod=jenkins-delphi-6db9db8c6c-2kk7t --tag=pod-uid=382dde6e-0b21-11ea-a95d-12d9fbde4cd6 --tag=pvc-uid=cf1867ab-982f-11e9-8715-02fc89486110 --tag=volume=jenkins-home --tag=backup=thor-prod-backup-20191209200019 --tag=backup-uid=867cd6c3-1abe-11ea-851d-1227f638c493 --tag=ns=jenkins-delphi --host=velero --json --parent=bed12f70, stdout={\"message_type\":\"summary\",\"files_new\":12685,\"files_changed\":619,\"files_unmodified\":206170,\"dirs_new\":0,\"dirs_changed\":0,\"dirs_unmodified\":0,\"data_blobs\":9296,\"tree_blobs\":1,\"data_added\":50150380,\"total_files_processed\":219474,\"total_bytes_processed\":1677459234,\"total_duration\":1336.814989697,\"snapshot_id\":\"e6e30265\"}, stderr=" backup=velero/thor-prod-backup-20191209200019 controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:265" name=thor-prod-backup-20191209200019-z62w8 namespace=velero
time="2019-12-09T23:35:43Z" level=debug msg="Ran command=restic backup --repo=s3:s3-us-east-1.amazonaws.com/thor-prod-velero-us-east-1/restic/jenkins-helios --password-file=/tmp/velero-restic-credentials-jenkins-helios530199687 --cache-dir=/scratch/.cache/restic . --tag=backup-uid=867cd6c3-1abe-11ea-851d-1227f638c493 --tag=ns=jenkins-helios --tag=pod=jenkins-helios-794c59f859-dvrqt --tag=pod-uid=c966e22c-0b28-11ea-a95d-12d9fbde4cd6 --tag=pvc-uid=084fef7b-b39c-11e9-92c8-1292e5742904 --tag=volume=jenkins-home --tag=backup=thor-prod-backup-20191209200019 --host=velero --json --parent=6a072aa8, stdout={\"message_type\":\"summary\",\"files_new\":432,\"files_changed\":47,\"files_unmodified\":16899,\"dirs_new\":0,\"dirs_changed\":0,\"dirs_unmodified\":0,\"data_blobs\":312,\"tree_blobs\":1,\"data_added\":18681391,\"total_files_processed\":17378,\"total_bytes_processed\":1096600962,\"total_duration\":92.330316419,\"snapshot_id\":\"1f39a65d\"}, stderr=" backup=velero/thor-prod-backup-20191209200019 controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:265" name=thor-prod-backup-20191209200019-mgpjv namespace=velero
time="2019-12-10T06:36:37Z" level=debug msg="Ran command=restic backup --repo=s3:s3-us-east-1.amazonaws.com/thor-prod-velero-us-east-1/restic/jenkins-marketingweb --password-file=/tmp/velero-restic-credentials-jenkins-marketingweb602426426 --cache-dir=/scratch/.cache/restic . --tag=pod-uid=b4ad6ddc-0b12-11ea-a95d-12d9fbde4cd6 --tag=pvc-uid=34c331e9-bd32-11e9-8222-12ec4025b138 --tag=volume=jenkins-home --tag=backup=thor-prod-backup-20191209200019 --tag=backup-uid=867cd6c3-1abe-11ea-851d-1227f638c493 --tag=ns=jenkins-marketingweb --tag=pod=jenkins-marketingweb-6799d54f58-jplpv --host=velero --json --parent=039b277c, stdout={\"message_type\":\"summary\",\"files_new\":0,\"files_changed\":39,\"files_unmodified\":5107,\"dirs_new\":0,\"dirs_changed\":0,\"dirs_unmodified\":0,\"data_blobs\":16,\"tree_blobs\":1,\"data_added\":2377740,\"total_files_processed\":5146,\"total_bytes_processed\":1406311782,\"total_duration\":26.651678089,\"snapshot_id\":\"08375c90\"}, stderr=" backup=velero/thor-prod-backup-20191209200019 controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:265" name=thor-prod-backup-20191209200019-6lqnv namespace=velero
time="2019-12-10T06:44:41Z" level=debug msg="Ran command=restic backup --repo=s3:s3-us-east-1.amazonaws.com/thor-prod-velero-us-east-1/restic/jenkins-mugil --password-file=/tmp/velero-restic-credentials-jenkins-mugil464644689 --cache-dir=/scratch/.cache/restic . --tag=pod-uid=37eacc3f-0b20-11ea-a95d-12d9fbde4cd6 --tag=pvc-uid=a918e974-86b9-11e9-8715-02fc89486110 --tag=volume=jenkins-home --tag=backup=thor-prod-backup-20191209200019 --tag=backup-uid=867cd6c3-1abe-11ea-851d-1227f638c493 --tag=ns=jenkins-mugil --tag=pod=jenkins-mugil-5f84777744-ttfks --host=velero --json --parent=a94a9fbb, stdout={\"message_type\":\"summary\",\"files_new\":0,\"files_changed\":62,\"files_unmodified\":3793,\"dirs_new\":0,\"dirs_changed\":0,\"dirs_unmodified\":0,\"data_blobs\":38,\"tree_blobs\":1,\"data_added\":2431419,\"total_files_processed\":3855,\"total_bytes_processed\":553051246,\"total_duration\":20.664425264,\"snapshot_id\":\"0354cc44\"}, stderr=" backup=velero/thor-prod-backup-20191209200019 controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:265" name=thor-prod-backup-20191209200019-98zk2 namespace=velero
````

**Comment by skriss** [comment] 2019-12-11 20:29
@hibbert looking at the logs I'm seeing the following pods are taking the majority of the backup time:

jenkins-lucas/jenkins-lucas-7b446975c-28kd2 -- ~6.5h
jenkins-voltron/jenkins-voltron-5d4dc9649c-fbr6p -- ~3h
jenkins-dashweb/jenkins-dashweb-594b87cbc7-t8f6t -- ~90m
jenkins-proteus/jenkins-proteus-86f4dfcdfb-jmfb5 -- ~90m

I'm curious how large the volumes are for each of these pods?

Also, have you tried increasing the requests/limits on the restic daemonset pods? What do you have them set at now?

Definitely for a use case like yours where you have a larger # of restic backups, concurrency is going to make a big difference.

**Comment by skriss** [comment] 2019-12-11 21:50
@hibbert I'm also curious about the details of your use case - could you provide some context on why you're using restic? Are you using a storage platform that doesn't have integrated snapshots?

**Comment by hibbert** [comment] 2019-12-12 11:19
Thanks. I'm wandering whereabouts you see the timings in the logs?

Sizes:

```
# du -sh jenkins-lucas-home-pvc-0591b09a-9431-11e9-ac6b-12251819f3ca jenkins-voltron-home-pvc-a7d03d55-8777-11e9-8715-02fc89486110 jenkins-dashweb-home-pvc-c8f33576-e6be-11e9-beca-12c2320ba0f8 jenkins-proteus-home-pvc-1be63f7d-7738-11e9-991e-12b46d3678f4
28.0G	jenkins-lucas-home-pvc-0591b09a-9431-11e9-ac6b-12251819f3ca
10.2G	jenkins-voltron-home-pvc-a7d03d55-8777-11e9-8715-02fc89486110
9.9G	jenkins-dashweb-home-pvc-c8f33576-e6be-11e9-beca-12c2320ba0f8
5.1G	jenkins-proteus-home-pvc-1be63f7d-7738-11e9-991e-12b46d3678f4
```

There are no requests/limits on the restic daemonset pods. The values for the velero deployment are as follows:

```
          resources:
            limits:
              cpu: "1"
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 2Gi
```

We are using restic as our filesystem is EFS which doesn't have integrated snapshots

**Comment by skriss** [comment] 2019-12-12 15:31
I looked at the timestamps in the logs and saw a few big gaps immediately followed by "executing post hooks" for specific pods, so inferred that restic backups were running for those pods during that time.

The time gaps definitely don't match up to what I'd expect for volumes of this size. I'll see if I can reproduce similar perf issues in my own environment.

**Comment by skriss** [comment] 2019-12-12 17:00
FYI, as a baseline i ran a velero backup using restic on a 4.6Gi volume. The initial backup took 4m4sec, and the next backup (no changes to the data) took 19 seconds. So your results are definitely atypical. Now, to see if I can induce performance like you're seeing...

**Comment by skriss** [comment] 2019-12-12 20:58
@hibbert I haven't been able to reproduce this on EKS+EFS. While I'm seeing that restic backups are slower when using a default EFS share than they are on EBS volumes, my results are nowhere near the times you're seeing.

what are the specs for your EFS share (size, bursting vs provisioned throughput, encrypted, etc)? The specs for your cluster nodes would be useful as well.

**Comment by hibbert** [comment] 2019-12-16 19:49
I guess that it would be slower with a higher amount of files/directories/etc

Specs:

Size = 141.8 GiB
Throughput mode = bursting
Encrypted = yes
Lifecycle policy = none
Worker Nodes = 6 X r5.2xlarge, 100GiB gp2 EBS drives, default tenancy

**Comment by carlisia** [comment] 2020-02-05 21:24
Hey @hibbert has your issue been resolved?

**Comment by skriss** [comment] 2020-02-18 18:16
I'm going to close this out, as I'm not sure we have anything else to offer here.

As a closing thought, using provisioned throughput may help with EFS performance, though I recognize this comes at a cost.

**Closed by skriss** 2020-02-18 18:16 UTC
Labels: Investigating, Restic

**Comment by optimus-kart** [comment] 2021-09-30 13:37
Hi all, I am seeing similar issue on my eks setup. did anyone figureout the root cause for this? I am using velero 1.5.2
