### ISSUE TITLE
Error message not logged from plugin

### ISSUE THREAD

**Issue by artificial-aidan** [vmware-tanzu/velero#5205] opened 2022-08-11 22:53 UTC
**What steps did you take and what happened:**
I'm hoping this is just a configuration error, but I burned about half a day digging into it.

The error I had was not having the `kms:Decrypt` https://aws.amazon.com/premiumsupport/knowledge-center/s3-large-file-encryption-kms-key/ on my role being used by the velero aws plugin. But this misconfiguration was incredibly hard to find.

Even with debug logging turned on I would get no more information than the log lines:

```
velero-64b9f75bd4-lngzw[velero] {"backup":"art-system-velero/fast-resource-backup-test-2","cmd":"/plugins/velero-plugin-for-aws","err":"rpc error: code = Unavailable desc = error reading from server: EOF","level":"debug","logSource":"pkg/plugin/clientmgmt/logrus_adapter.go:75","msg":"received EOF, stopping recv loop","pluginName":"stdio","time":"2022-08-11T22:44:45Z"}
velero-64b9f75bd4-lngzw[velero] {"backup":"art-system-velero/fast-resource-backup-test-2","cmd":"/plugins/velero-plugin-for-aws","level":"debug","logSource":"pkg/plugin/clientmgmt/logrus_adapter.go:75","msg":"plugin process exited","path":"/plugins/velero-plugin-for-aws","pid":707,"time":"2022-08-11T22:44:45Z"}
velero-64b9f75bd4-lngzw[velero] {"backup":"art-system-velero/fast-resource-backup-test-2","cmd":"/plugins/velero-plugin-for-aws","level":"debug","logSource":"pkg/plugin/clientmgmt/logrus_adapter.go:75","msg":"plugin exited","time":"2022-08-11T22:44:45Z"}
velero-64b9f75bd4-lngzw[velero] {"controller":"backup","error.message":"rpc error: code = Unknown desc = EOF","key":"art-system-velero/fast-resource-backup-test-2","level":"error","logSource":"pkg/controller/backup_controller.go:298","msg":"backup failed","time":"2022-08-11T22:44:45Z"}
```

And in the backup resource I would get the following status:

```
failureReason: 'rpc error: code = Unknown desc = EOF'
```

To finally get a better handle on the issue I build my own plugin image and added explicit error logging in the plugin. Which finally produced this error:

```
{"backup":"art-system-velero/fast-resource-backup-test-2","bucket":"*******","cmd":"/plugins/velero-plugin-for-aws","key":"resources/default/backups/fast-resource-backup-test-2/fast-resource-backup-test-2.tar.gz","level":"error","logSource":"/go/src/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:351","msg":"error putting object \u0026{%!f(*awserr.baseError=\u0026{MultipartUpload upload multipart failed [0xc00040c940]}) %!f(string=XXXXX.XXXXXXX.XXXXX-)}","pluginName":"velero-plugin-for-aws","time":"2022-08-11T22:44:45Z"}
```

Which led me down the path to solve my problem.

**To be clear this is not a bug report about the failed backup, but that an error returned from a plugin was not logged by velero.**

**Environment:**

- Velero version (use `velero version`): v1.9.0 
- Velero aws version: v1.5.0

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment] 2022-08-15 06:29
@artificial-aidan 
To help me better understand this problem, could you share me the change you made to the plugin code?

Seems for some reason the error handling mechanism of go-plugin is not compatible with the way velero plugin returns the error.

**Comment by artificial-aidan** [comment] 2022-08-15 12:32
I added a log statement.

```
if err != nil {
    log.Error(err)
}
```

**Comment by Lyndon-Li** [comment] 2022-11-15 04:26
We need to judge whether this error should be returned to Velero by plugin or be handled by the plugin.

@artificial-aidan Could you share us the Velero log bundle and the place in the code you added the above log statement?

**Comment by artificial-aidan** [comment] 2022-11-15 05:58
Oh boy. This was a long time ago. I found this looking back through my history.

https://github.com/vmware-tanzu/velero-plugin-for-aws/commit/d75b28e26b6c9a7f5a1bab61745e9c0caaf19bd9

**Comment by reasonerjt** [comment] 2023-01-04 11:12
I double checked and these log messages are expected when you set the `log-level` to `debug`

```
velero-64b9f75bd4-lngzw[velero] {"backup":"art-system-velero/fast-resource-backup-test-2","cmd":"/plugins/velero-plugin-for-aws","err":"rpc error: code = Unavailable desc = error reading from server: EOF","level":"debug","logSource":"pkg/plugin/clientmgmt/logrus_adapter.go:75","msg":"received EOF, stopping recv loop","pluginName":"stdio","time":"2022-08-11T22:44:45Z"}
velero-64b9f75bd4-lngzw[velero] {"backup":"art-system-velero/fast-resource-backup-test-2","cmd":"/plugins/velero-plugin-for-aws","level":"debug","logSource":"pkg/plugin/clientmgmt/logrus_adapter.go:75","msg":"plugin process exited","path":"/plugins/velero-plugin-for-aws","pid":707,"time":"2022-08-11T22:44:45Z"}
velero-64b9f75bd4-lngzw[velero] {"backup":"art-system-velero/fast-resource-backup-test-2","cmd":"/plugins/velero-plugin-for-aws","level":"debug","logSource":"pkg/plugin/clientmgmt/logrus_adapter.go:75","msg":"plugin exited","time":"2022-08-11T22:44:45Z"}
```
This happens when the grpc server representing the plugin exits after the execution of the function.  The meaningful error is the log message printed by the controller.

However, I tried to mock a `multiUploadError` like [this](https://github.com/vmware-tanzu/velero-plugin-for-aws/commit/5dc2d93e0a8fd8df708cd9fa3fa110658f930d14) but the error can be printed successfully in velero process

```
ERRO[0237] backup failed                                 controller=backup error="rpc error: code = Unknown desc = error putting object backups/test-6/velero-backup.json: MultipartUpload: upload multipart failed\n\tupload id: some-uploadID\ncaused by: code-level2: message-level2\ncaused by: the actual error" key=velero/test-6 logSource="pkg/controller/backup_controller.go:298"
```

I also did more test by returning pointer or concrete struct which implements `error interface` and seems the mechanism to pass error from plugin (grpc server) to velero pod (client) works reliably.

I suspect when you see the log 
```
{"controller":"backup","error.message":"rpc error: code = Unknown desc = EOF"....
``` 
the plugin returns an `io.EOF` error rather than a `multiUploadError`

Since I don't discover any obvious problem in the mechanism of error handling in the plugin framework, I'm closing this issue as `not reproducible`, please kindly open a new issue  if you continue seeing this problem in the latest release.

**Closed** 2023-01-04 11:13 UTC
Labels: Area/Plugins, status/not-reproducible
