### ISSUE TITLE
Download PV data with `velero backup download`

### ISSUE THREAD

**Issue by sgielen** [vmware-tanzu/velero#2684] opened 2020-07-02 20:30 UTC
<sub>First of all, thanks for making such a nice application! It took me a bit to get it running on my arm64 cluster because of #2466, and also to build an arm64 version of the velero-plugin-for-aws image -- I don't have any AWS volumes attached to my bare-metal cluster of course, but I think the documentation doesn't specify whether I need it to backup **to** AWS, so I installed it anyway...</sub>

**Describe the problem/challenge you have**
I've just created a backup of my cluster. I use OpenEBS volumes, so I installed the `openebs/velero-plugin-arm64:1.11.0` plugin and created a VolumeSnapshotLocation. This worked according to `velero backup describe --details`, and the volume backup files are visible in my S3 bucket as separate files within the prefix specified!

However, now I'd like to inspect that the backup is complete, so I ran `velero backup download`, but the resulting `.tar.gz` file doesn't contain the volume backup files.

**Describe the solution you'd like**
A `velero backup download --download-pvc-data`, as suggested by #2006 for restic backups, would be great for volume plugins as well.

**Environment:**

- Velero version (use `velero version`): Client & server version 1.4.0
- Kubernetes version (use `kubectl version`): Client version 1.17.4, server version 1.18.3+k3s1
- Kubernetes installer & version: k3os v0.10.0
- Cloud provider or hardware configuration: Bare-metal arm64 cluster of 4 nodes, various Raspberry Pi devices; storage provided by OpenEBS 1.11.0 (arm64)
- OS (e.g. from `/etc/os-release`): k3os v0.10.0

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nrb** [comment] 2020-07-15 22:33
Hi @sgielen - thanks for the feature request!

I think this is definitely a reasonable request, and not quite the same as 2006. Also, given how Velero works, it's unfortunately not going to be a simple thing to add, since right now snapshots made by the snapshot plugins are kind of black boxes to Velero. Restic snapshots are, however, stored in the same bucket.

I'm going to label this and add it for consideration, though, as I think it's something that will be useful to a lot of folks.

**Comment by eleanor-millman** [comment] 2021-05-11 21:27
Closing because duplicate of #1492

**Closed by eleanor-millman** 2021-05-11 21:27 UTC
Labels: Area/CLI, Area/Plugins, Needs Product, Reviewed Q2 2021, Size/L

**Comment by bilbof** [comment] 2024-11-01 14:51
Not sure that this is a duplicate of #1492 (add support for uploading/restoring a local backup)? 

A way to download PVC data seems very useful (e.g. `--download-pvc-data` as described) but isn't described in #1492 AFAICT.

**Comment by kaovilai** [comment] 2024-11-05 23:23
What workflow would be enabled if this is implemented that won't duplicates what velero can do via restore already?

**Comment by kaovilai** [comment] 2024-11-06 15:52
Ok if we are limiting to just kopia it may be more doable. For all PV backup types not so much.

**Comment by sseago** [comment] 2024-11-06 19:05
@kaovilai Although downloading a particular backup's PVCs would probably require essentially running a kopia restore to some local volume. The kopia dir itself will have all backups together in kopia's internal format. I suspect the only way to separate particular backups from  this would be to parse the backup metadata, find the kopia snapshot IDs, then restore those contents to some temporary local storage (assuming the local storage is large enough).
