### ISSUE TITLE
Velero installation failing

### ISSUE THREAD

**Issue by dbebarta** [vmware-tanzu/velero#6369] opened 2023-06-08 04:43 UTC
We tried installing velero in our Kubernetes cluster and getting below error:
```
velero version
An error occurred: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
```
Our kubernetes cluster is running with version  v1.23.15. 
What could be the reason and how can we resolve it ?

**Comment by dbebarta** [comment] 2023-06-08 04:45
Can anyone from velero team please help here

**Comment by blackpiglet** [comment] 2023-06-12 06:28
https://github.com/aws/aws-cli/issues/6920

Just found a similar issue. In that issue, the problem is related to `kubectl` version. It's fixed by update the kubecofig format or downgrade the kubectl version.

**Comment by blackpiglet** [comment] 2023-06-26 03:46
Close for now. If anything needs clarification, feel free to reopen.

**Closed by blackpiglet** 2023-06-26 03:46 UTC
