### ISSUE TITLE
Support for deploying Backup resources to additional namespaces

### ISSUE THREAD

**Issue by marccampbell** [vmware-tanzu/velero#2415] opened 2020-04-10 18:36 UTC
**Describe the problem/challenge you have**
Backup resources only work if they are deployed to the Velero namespace.

**Describe the solution you'd like**
I'd like to be able to deploy `Backup` resources to namespaces other than the velero namespace. My goal would be to create the Backup resource in the same namespace that the off-the-shelf application resides in, so that cleaning up the application can continue to be as easy as "kubectl delete ns". Also this would allow me to use standard, easy kubectl commands to filter backup resources by `kubectl get backups -n my-app`

**Comment by nrb** [comment] 2020-04-10 19:27
To give some background on why Velero is currently implemented this way:

If the `Backup` representation resides in the same namespace it tries to protect, then deleting the namespace will delete all of the backed up data, at least with how Velero's garbage collection works now. Putting the `Backup`s in their own namespaces means that users can accidentally delete a namespace and get it back.

Do you have any suggestions on how we might avoid this when putting Velero backups in the same namespace they're protecting? I'm definitely open to ideas here!

**Comment by skriss** [comment] 2020-04-13 14:47
this appears to be a dupe of https://github.com/vmware-tanzu/velero/issues/1217. Let's continue the discussion there; I'm going to close this one out as a duplicate.

**Closed** 2020-04-13 14:48 UTC
Labels: Duplicate
