### ISSUE TITLE
Pod restore stucked by  restore-wait 

### ISSUE THREAD

**Issue by asd33015** [vmware-tanzu/velero#6489] opened 2023-07-13 05:31 UTC
**What steps did you take and what happened:**

  1. I just make a restore for the Pod resource with existing static PV and PVC, the process is stuck by restore-wait  which shows the bug with `**Not found: /restores/........**`
  2. I found that it would not create the .velero and the file which velero-restore-helper needs to detect.

**What did you expect to happen:**

 Make a restore of the Pod with existing PV/PVC successfully, or remove the initialContainer (restic-wait) for restore with existing static PV/PVC.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

Thanks for the great work!

**Comment by danfengliu** [comment] 2023-07-14 03:33
@asd33015 Could you provide the Velero install and backup command line you're using, and Velero debug bundle after you hit this issue? Please refer to [description](https://github.com/vmware-tanzu/velero/issues/6489#:~:text=If%20you%20are%20using%20velero%20v1.7.0%2B%3A%0APlease%20use%20velero%20debug%20%20%2D%2Dbackup%20%3Cbackupname%3E%20%2D%2Drestore%20%3Crestorename%3E%20to%20generate%20the%20support%20bundle%2C%20and%20attach%20to%20this%20issue%2C%20more%20options%20please%20refer%20to%20velero%20debug%20%2D%2Dhelp) as guidance.

**Comment by Lyndon-Li** [comment] 2023-07-17 07:12
@asd33015 
During pod volume restore, Velero creates a new pod with a PVC only and expect the system to provision a PV. As the current behavior, if the PV cannot provisioned for the PVC, the initialContainer will not complete and the pod volume restore will hang there until the timeout.

If static provision is being used, you need to make sure that by the time of the PVC is created, a PV could be bound to it by any means.

**Comment by quangthe** [comment] 2023-07-19 02:47
I follow the guide here https://velero.io/docs/v1.11/contributions/tencent-config/ and have the same issue. The data is restored but the "done file" never created so that the restore-wait init container keeps running. 

Here is node-agent log
```
time="2023-07-19T02:05:47Z" level=info msg="Setting log-level to INFO"
time="2023-07-19T02:05:47Z" level=info msg="Starting Velero node-agent server v1.11.0 (0da2baa908c88ec3c45da15001f6a4b0bda64ae2-dirty)" logSource="pkg/cmd/cli/nodeagent/server.go:85"
1.689732347243299e+09    INFO    controller-runtime.metrics    Metrics server is starting to listen    {"addr": ":8080"}
time="2023-07-19T02:05:47Z" level=info msg="Starting metric server for node agent at address [:8085]" logSource="pkg/cmd/cli/nodeagent/server.go:175"
time="2023-07-19T02:05:47Z" level=info msg="Starting controllers" logSource="pkg/cmd/cli/nodeagent/server.go:191"
time="2023-07-19T02:05:47Z" level=info msg="Controllers starting..." logSource="pkg/cmd/cli/nodeagent/server.go:227"
1.6897323473449955e+09    INFO    Starting server    {"path": "/metrics", "kind": "metrics", "addr": ":8080"}
1.6897323473470752e+09    INFO    Starting EventSource    {"controller": "podvolumerestore", "controllerGroup": "velero.io", "controllerKind": "PodVolumeRestore", "source": "kind source: *v1.PodVolumeRestore"}
1.6897323473471394e+09    INFO    Starting EventSource    {"controller": "podvolumerestore", "controllerGroup": "velero.io", "controllerKind": "PodVolumeRestore", "source": "kind source: *v1.Pod"}
1.6897323473471463e+09    INFO    Starting Controller    {"controller": "podvolumerestore", "controllerGroup": "velero.io", "controllerKind": "PodVolumeRestore"}
1.6897323473459632e+09    INFO    Starting EventSource    {"controller": "podvolumebackup", "controllerGroup": "velero.io", "controllerKind": "PodVolumeBackup", "source": "kind source: *v1.PodVolumeBackup"}
1.6897323473471754e+09    INFO    Starting Controller    {"controller": "podvolumebackup", "controllerGroup": "velero.io", "controllerKind": "PodVolumeBackup"}
1.6897323474480731e+09    INFO    Starting workers    {"controller": "podvolumebackup", "controllerGroup": "velero.io", "controllerKind": "PodVolumeBackup", "worker count": 1}
1.6897323474482245e+09    INFO    Starting workers    {"controller": "podvolumerestore", "controllerGroup": "velero.io", "controllerKind": "PodVolumeRestore", "worker count": 1}
time="2023-07-19T02:06:03Z" level=info msg="PodVolumeBackup starting" backup=velero/wp controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:92" podvolumebackup=velero/wp-hnhmk
time="2023-07-19T02:06:03Z" level=info msg="PodVolumeBackup starting" backup=velero/wp controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:92" podvolumebackup=velero/wp-mlg9g
time="2023-07-19T02:11:10Z" level=info msg="Restore starting" PodVolumeRestore=velero/wp-20230719091032-rpkps controller=PodVolumeRestore logSource="pkg/controller/pod_volume_restore_controller.go:115" pod=test/wp-mariadb-0 restore=velero/wp-20230719091032
time="2023-07-19T02:11:27Z" level=info msg="Run command=restore, stdout=restoring <Snapshot 5cbe69b0 of [/host_pods/d8c01e32-063f-475c-9359-0f59a78dccde/volumes/kubernetes.io~csi/pvc-bac81303-1393-4aa6-9279-0732388a3126] at 2023-07-18 06:48:39.301882758 +0000 UTC by root@velero> to .\n, stderr=" PodVolumeRestore=velero/wp-20230719091032-rpkps controller=PodVolumeRestore logSource="pkg/uploader/provider/restic.go:184" pod=test/wp-mariadb-0 restore=velero/wp-20230719091032 snapshotID=5cbe69b0 volumePath="/host_pods/0d7bbc52-77dc-4eca-a1f4-6e486ac126ec/volumes/kubernetes.io~csi/pvc-7d5d7b76-de21-4b11-a962-41306ddf62f0"
time="2023-07-19T02:11:27Z" level=info msg="Restore completed" PodVolumeRestore=velero/wp-20230719091032-rpkps controller=PodVolumeRestore logSource="pkg/controller/pod_volume_restore_controller.go:140" pod=test/wp-mariadb-0 restore=velero/wp-20230719091032
time="2023-07-19T02:11:27Z" level=info msg="Restore starting" PodVolumeRestore=velero/wp-20230719091032-kpmps controller=PodVolumeRestore logSource="pkg/controller/pod_volume_restore_controller.go:115" pod=test/wp-wordpress-6dc576fbff-gr8j5 restore=velero/wp-20230719091032
time="2023-07-19T02:11:48Z" level=info msg="Run command=restore, stdout=restoring <Snapshot 83c0625f of [/host_pods/0edbaa34-5504-4bd2-8b27-d4fa971cdf3f/volumes/kubernetes.io~csi/pvc-c94a3684-e8c7-41e2-82d6-3b59ea16a960] at 2023-07-18 06:48:49.863450162 +0000 UTC by root@velero> to .\n, stderr=" PodVolumeRestore=velero/wp-20230719091032-kpmps controller=PodVolumeRestore logSource="pkg/uploader/provider/restic.go:184" pod=test/wp-wordpress-6dc576fbff-gr8j5 restore=velero/wp-20230719091032 snapshotID=83c0625f volumePath="/host_pods/2d9ba05d-e2a9-47da-8278-f38748c09426/volumes/kubernetes.io~csi/pvc-97ca7091-37e9-4ad1-a7d9-2b22e8e40cfe"
time="2023-07-19T02:11:48Z" level=info msg="Restore completed" PodVolumeRestore=velero/wp-20230719091032-kpmps controller=PodVolumeRestore logSource="pkg/controller/pod_volume_restore_controller.go:140" pod=test/wp-wordpress-6dc576fbff-gr8j5 restore=velero/wp-20230719091032
```

**Comment by quangthe** [comment] 2023-07-19 03:58
I found something interesting with `mountPropagation` (HostToContainer) on Tencent TKE.

The node-agent did create the `.velero` dir and sentinel (done file) but the issue is the path.

I launch the debug pod to inspect the path:

```
root@ubuntu:/host_pods/d1fb33af-2814-47a5-93c7-05986d0acbed/volumes/kubernetes.io~csi/pvc-f60da1c7-7099-4cdc-b86b-b3395608e14c# ls -alh
total 20K
drwxr-x--- 4 root root 4.0K Jul 19 03:14 .
drwxr-x--- 3 root root 4.0K Jul 19 03:14 ..
drwxr-xr-x 2 root root 4.0K Jul 19 03:14 .velero
drwxrwsr-x 4 root 1001 4.0K Jul 19 03:49 mount
-rw-r--r-- 1 root root  272 Jul 19 03:06 vol_data.json
```

As you can see, the volume data is actually under the `mount` dir. 

@Lyndon-Li I'm not sure if it's Tencent implemtation way is wrong or the way we handle OnDataPathCompleted need to adapt https://github.com/vmware-tanzu/velero/blob/main/pkg/controller/pod_volume_restore_controller.go#L261

**Comment by Lyndon-Li** [comment] 2023-07-25 06:57
@quangthe 
This is another known issue --- when the PV is unmounted by accident, Velero will restore the data to the host.
This issue should not happen generally.

**Comment by quangthe** [comment] 2023-07-25 07:28
Hi @Lyndon-Li 

Thanks for your info! 

When I do test restore, the data is fully copied to the pv. The podvolumerestore crd also has the status `Completed`. Delete the pod and it can start and regconize the restore data. 

In case of TKE cluster in my above comment, the .velero should be created under the dir `mount/` so that the restore-wait initcontainer can be finished.

**Comment by Lyndon-Li** [comment] 2023-08-10 10:04
@quangthe 
Velero file system restore always creates `.velero` file to the dir where it restore data to.
As what you've mentioned, `.velero` file should go to `mount` dir, then the volume data should also go to the same `mount` dir, if so, the restored pod should not be able to recognize the restored volume data. Otherwise, both the volume data and `.velero` file should be recognized by the pod so the `restore-wait` initcontainer should complete.

Could you share more details of why the `restore-wait` initcontainer didn't complete but the volume data was restored appropriately?

**Comment by blackpiglet** [comment] 2023-08-23 16:40
@quangthe 
What is the version of Velero you are using?
There was some fix to this scenario: #5149. The problem only happens in the CSI migration scenario. The volume's mount point is different for CSI and none for CSI.

**Comment by Lyndon-Li** [comment] 2023-08-25 09:09
@quangthe 
Could you help to confirm and share more info according to comment https://github.com/vmware-tanzu/velero/issues/6489#issuecomment-1672931031?
We discussed locally and still had no clue why the `.velero` file and the restored data are in different path.

**Comment by Lyndon-Li** [comment] 2023-10-24 01:24
Closing this issue since we didn't get the required info update. Feel free to reopen it whenever necessary.

**Closed by Lyndon-Li** 2023-10-24 01:24 UTC
Labels: Needs info, PodVolume
