### ISSUE TITLE
Unable to create VolumeSnapshots

### ISSUE THREAD

**Issue by brovoca** [vmware-tanzu/velero#4801] opened 2022-03-31 15:34 UTC
**What steps did you take and what happened:**

I've re-installed Velero as we want to switch away from Restic (due to many issues) and use snapshots for the time being. I've create a backup from schedule (attached below) which is stuck in the `InProgress` state and no VolumeSnapshots are created.

**What did you expect to happen:**

VolumeSnapshots are created.

**The following information will help us better understand what's going on**:

[bundle-2022-03-31-17-28-42.tar.gz](https://github.com/vmware-tanzu/velero/files/8390946/bundle-2022-03-31-17-28-42.tar.gz)

**Anything else you would like to add:**

- FluxCD HelmRelease with values: [velero-release.yaml](https://github.com/vmware-tanzu/velero/files/8390763/velero-release.txt)
- Ceph FileSystem VolumeSnapshotClass: [ceph-filesystem-vsc.yaml](https://github.com/vmware-tanzu/velero/files/8390833/ceph-filesystem-vsc.txt)
- Ceph Block VolumeSnapshotClass: [ceph-block-vsc.yaml](https://github.com/vmware-tanzu/velero/files/8390834/ceph-block-vsc.txt)
- Jenkins pod that uses Ceph FileSystem (jenkins-home) and Ceph Block (jenkins-cache) PVs: [jenkins-pod.yaml](https://github.com/vmware-tanzu/velero/files/8390856/jenkins-pod.txt).
- Backup schedule for Jenkins: [jenkins-schedule.yaml](https://github.com/vmware-tanzu/velero/files/8390872/jenkins-schedule.txt)

**Environment:**

- Velero version (use `velero version`):

    ```txt
    Client:
        Version: v1.8.1
        Git commit: 18ee078dffd9345df610e0ca9f61b31124e93f50
    Server:
        Version: v1.8.1
    ```

- Velero features (use `velero client config get features`): `features: <NOT SET>`
- Kubernetes version (use `kubectl version`):

    ```txt
    Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"19bca9208454ad7ac76f6fc71b5a2520922e395b", GitTreeState:"clean", BuildDate:"2022-03-10T18:21:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
    ```

- Kubernetes installer & version: AKS
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): N/A

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment] 2022-04-05 17:05
@brovoca 
It seems the velero pod was OOM killed:
```
                        "containerID": "containerd://af9327e5e170840121cfd663d1857951769ee6e2641ecdd21c0563851b93638a",
                        "image": "docker.io/velero/velero:v1.8.1",
                        "imageID": "docker.io/velero/velero@sha256:8d784580931c77892458be8a3b4046ca0c751039c11ea1218d522e9d03cb92cb",
                        "lastState": {
                            "terminated": {
                                "containerID": "containerd://73ef08aba9bd514b240bcadf01e6e191d38c34f950f192b56060f6741ed456f8",
                                "exitCode": 137,
                                "finishedAt": "2022-03-31T15:13:53Z",
                                "reason": "OOMKilled",
                                "startedAt": "2022-03-31T14:45:57Z"
                            }
                        },
```
Do you have a rough estimation like how many resources are selected for the backup?

**Comment by brovoca** [comment] 2022-04-06 07:28
@reasonerjt good catch, I completely missed that. The Jenkins backup job includes ~35 HelmReleases which each contains up to:
- 3x ConfigMaps
- 2x Deployments
- 1x Ingress
- 2x PVCs
- 1x Role
- 1x RoleBinding
- 1x ServiceAccount
- 1x ServiceMonitor
- 3x Services
- 1x Secret (for the HelmRelease itself)

I'll try to increase the memory requests/limits, but perhaps the defaults should be increased?

**Comment by reasonerjt** [comment] 2022-04-06 08:14
@brovoca keep us updated.

Based on the test by @qiuming-best when a backup contains thousands of pods, the velero pod with default mem setting will not be OOM killed.
So it's interesting why in your case velero pod was killed, is it always reproducible?

**Comment by brovoca** [comment] 2022-04-06 10:32
@reasonerjt The snapshot creation is stuck. It has started processing one HelmRelease and created a snapshot of 1x PV (jenkins-cache), but not the second (jenkins-home). It's likely due to the annotation `backup.velero.io/backup-volumes=jenkins-home`. I see this at the end of `velero backup describe jenkins-20220406073714 --details`:

```txt
...
Estimated total items to be backed up:  1552
Items backed up so far:                 0

Resource List:  <backup resource list not found>

Velero-Native Snapshots: <none included>

Restic Backups:
  New:
    jenkins/releasename-scmb-jenkins-68d7dfd98-d6dz8: jenkins-home
```

It seems that `snapshotVolumes: true` isn't respected.

**Comment by brovoca** [comment] 2022-04-08 07:57
I deleted the annotation and VolumeSnapshots were created for all the volumes. However, it has been `InProgress` since, so something else seems to have gotten stuck. I will try to create a schedule that selects only 1x HelmRelease.

**Comment by brovoca** [comment] 2022-04-08 08:08
The backup I just created which only selected 1 HelmRelease `Completed` just fine. Is our schedule too heavy for Velero?

The previous _stuck_ backup was up at 2547 `totalItems`, but never got past 313 `itemsBackedUp`:

```yaml
>>> kubectl get backups -n velero jenkins-20220407145400 -o yaml | grep status: -A1000
status:
  expiration: "2022-05-07T14:54:00Z"
  formatVersion: 1.1.0
  phase: Failed
  progress:
    itemsBackedUp: 313
    totalItems: 2547
  startTimestamp: "2022-04-07T14:54:00Z"
  version: 1
```

> _The `phase: Failed` was set manually by me. It was originally `InProgress` before I edited it and restarted Velero._

**Comment by Lyndon-Li** [comment] 2024-05-20 07:33
Looks like this is some leftover backups after node-agent is oom killed. There are some enhancement around this area in the new release, please try with the newer version under Kopia path.
Closing this issue since there is no update for a long time and feel free to reopen it if it is reproduced.

**Closed by Lyndon-Li** 2024-05-20 07:33 UTC
Labels: Needs info, Needs investigation
