### ISSUE TITLE
Restic doesn't seem to be using the AWS_SHARED_CREDENTIALS_FILE environment variable so fails to create repo

### ISSUE THREAD

**Issue by sazzle2611** [vmware-tanzu/velero#2339] opened 2020-03-11 01:21 UTC
**What steps did you take and what happened:**
Installed velero on kubernetes set to backup to an external minio installation

velero install \
    --provider aws \
    --bucket velero-backups \
    --use-restic \
    --secret-file /root/secrets/credentials-velero  \
    --use-volume-snapshots=false \
    --plugins  velero/velero-plugin-for-aws:v1.0.1 \
    --backup-location-config region="us-east-1",s3ForcePathStyle="true",s3Url=https://minio.mydomain.com

All the pods started fine

Annotated a pod with a persistent volume that I wanted to backup called www

backup.velero.io/backup-volumes: www 

Ran backup

velero backup create mysite-backup01 --selector app=mysite

velero backup describe mysite-backup01 showed this message

Phase:  PartiallyFailed (run `velero backup logs mysite-backup01` for more information)

The logs showed this error message

The request signature we calculated does not match the signature you provided. Check your key and signing method.

**What did you expect to happen:**
I expected the backup to succeed

**Anything else you would like to add:**
The backup had succeeded in connecting to minio and creating the backups path with logs and everything in it but it had failed to create the restic repo. This proves the credentials file was correct otherwise it wouldn't have been able to do that.

velero restic repo get
panic: runtime error: invalid memory address or nil pointer dereference

Sorry I don't know how to display logs and commands properly and I didn't want to will this with lots of text to confuse the issue.

After 2 nights of googling and trying everything then I got to the cause of the problem, what I don't understand is why I couldn't seem to find anyone else with the same issue.

I installed restic binary outside of kubernetes and used the same minio credentials and it successfully created the repo but this was using the main environment variables though and not AWS_SHARED_CREDENTIALS_FILE

I tried to create the repo manually from inside the velero pod, I created a test restic password file and used the same command that it had tried to run during the backup but it still failed with the same message about the request signature not matching.
I then exported the 2 environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY with the same values from the credentials file and ran the command again and it worked.

From this I deleted the velero namespace and ran the install command again but added --dry-run -o yaml > velero.yaml
I then edited velero.yaml and changed the environment variables in the daemonset and deployment to include the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY filed with the same values from my credentials file.

I used kubectl to apply the file and then ran the backup again and it succeeded

**Environment:**

- Velero version (use `velero version`):  v1.3.0
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`):  v1.17.2
- Kubernetes installer & version: kubeadm
- Cloud provider or hardware configuration: on premise
- OS (e.g. from `/etc/os-release`): centos 7

**Comment by skriss** [comment] 2020-03-11 22:06
@sazzle2611 huh, I'm not sure what's causing your error, this is expected to work just fine and I wasn't able to reproduce it using v1.3.

Does your credentials file have just a single profile? I.e. something like the following:

```
[default]
aws_access_key_id = minio
aws_secret_access_key = minio123
```

Is it possible to share the file itself, redacting any actual secret material?

**Comment by sazzle2611** [comment] 2020-03-11 22:15
Hi skriss

It's just the basic file exactly as you've shown
```
[default]
aws_access_key_id: <my-access-key>
aws_secret_access_key: <my-secret-key>
```

It is strange that velero has no problem with this credentials file but restic does. The only think I can think to mention about this file is that my secret key ends with a hash # but I don't see why this should be a problem.

**Comment by sazzle2611** [comment] 2020-03-11 22:16
Just spotted that you have = where I have : 

Could this be a problem?

**Comment by skriss** [comment] 2020-03-11 22:21
Could be, can you try with `=`?

**Comment by skriss** [comment] 2020-03-11 22:22
> It is strange that velero has no problem with this credentials file but restic does.

I do know that Velero will be using the AWS SDK to connect, while restic under the hood uses the minio SDK for all S3 access, so it is two separate libraries that could possibly have discrepancies.

**Comment by sazzle2611** [comment] 2020-03-11 22:35
That does explain why they are working differently, thanks.

I have deleted the velero namespace and reinstalled with velero install and the updated credentials file but I have the same error as before, once again the backups folder got created in minio but no restic.

**Comment by skriss** [comment] 2020-03-12 15:05
@sazzle2611 one other thing you could try is putting the value of the secret key in double quotes.

Beyond this, I'm not really sure what might be the issue with your setup.

**Comment by sazzle2611** [comment] 2020-03-12 15:50
Already tried that but it didn't make a difference.

At least I have a workaround by setting the environment variables directly in the yamls.

Just one last detail incase it's important, the minio it's using is on a separate kubernetes cluster and was installed with helm as part of the gitlab package.

Thanks for your efforts

**Comment by skriss** [comment] 2020-03-16 15:51
I'm going to close this out given that you have a workaround, and I was unable to reproduce. Can reopen as needed if we get further repros.

**Closed by skriss** 2020-03-16 15:51 UTC
Labels: Investigating, Needs info, Restic

**Comment by MarcoMatarazzo** [comment] 2021-06-11 18:58
I am experiencing the same problem with plugin version 1.2.0.

I am available to help with reproducing the issue. 

I would start from: WHERE should the auth data from restic come from? Should the ENV variables be present in the yaml file produced by the installation process?
