### ISSUE TITLE
Support hostpath volumes to be backed up and restored by restic in order to  running / testing / developing in kind cluster.

### ISSUE THREAD

**Issue by VolkerKozlowski** [vmware-tanzu/velero#3053] opened 2020-11-04 15:12 UTC
**Describe the problem/challenge you have**
We are running e2e tests inside of a kind cluster. Kind only provides hostpath mounted volumes provisioned by rancher.io/local-path. 
Unfortunately velero cannot handle to backup and restore such volumes with restic.  

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
Kind kind v0.9.0-alpha
Velero 1.4

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by jppitout** [comment] 2021-01-14 14:44
This would definitely help for training and home labs using Kind clusters :)

**Comment by nrb** [comment] 2021-05-12 16:35
I think this is the same problem as #2767; closing as a duplicate.

**Closed by nrb** 2021-05-12 16:35 UTC
Labels: Duplicate, Reviewed Q2 2021

**Comment by jsanda** [comment] 2022-06-02 21:59
Why was is this considered as a duplicate of #2767? I believe kind stores pod volumes under `/var/lib/kubelet/pods`. 

It doesn't look like there are any labels or annotations added to nodes that would make it easy to identify as part of a kind cluster; however, it would be easy enough to add something.

I am in the same situation as the OP. We use kind extensively for e2e tests. Not being able to use kind for backup/restore will complicate adoption.

**Comment by Lyndon-Li** [comment] 2022-06-06 02:05
@jsanda The current issue as same as issue 2767, is about to support the non-standard pod volume mount path (the standard one is /var/lib/kubelet/pods). If your current issue is the same as these ones, please follow the same doc https://velero.io/docs/main/restic/#:~:text=to%20date%20information.-,Configure,-Restic%20DaemonSet%20spec to solve the problem. Thanks.
