### ISSUE TITLE
Delete Backup-location resource of Velero How?

### ISSUE THREAD

**Issue by thomasbinny1989** [vmware-tanzu/velero#1997] opened 2019-10-25 06:42 UTC
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Im trying to delete a created backup-location which has already been created using 
'velero backup-location create xxxxxx'

**What did you expect to happen:**
I expect a command through which i can delete the backuplocation resource

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
Client:
	Version: v1.1.0
	Git commit: a357f21aec6b39a8244dd23e469cc4519f1fe608
Server:
	Version: v1.1.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"darwin/386"}

Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
Kops Version 1.13.0
- Cloud provider or hardware configuration:
AWS 
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment] 2019-10-25 15:50
Closing as dupe of #1996

**Closed by skriss** 2019-10-25 15:50 UTC
