### ISSUE TITLE
Failed to backup using Restic to NFS

### ISSUE THREAD

**Issue by wcochran53** [vmware-tanzu/velero#2859] opened 2020-08-24 09:43 UTC
**What steps did you take and what happened:**
Hi

I am using velero with the velero/velero-plugin-example configured to backup the object store to nfs (which seems to work by mounting the /tmp/backups  to my nfs hostPath ) and using Restic to backup the PVCs to nfs.   However after annotating my container appropriately to indicate the volume claim,  and running the backup, while the restic repo K8s resource object gets created the restic container fails to create the snapshot.

The error log from the restic container shows
`time="2020-08-24T09:27:17Z" level=error msg="Error running command=restic backup --repo=restic/nginx-example --password-file=/tmp/velero-restic-credentials-nginx-example892170687 --cache-dir=/scratch/.cache/restic . --tag=backup-uid=ad32fef9-83b7-489b-8eb7-f20aea205f54 --tag=ns=nginx-example --tag=pod=nginx-deployment-86c565d654-m72gp --tag=pod-uid=7e5624ef-fdc5-47ce-9945-9a09d18f3fb2 --tag=pvc-uid=983217d9-01e7-4af9-9d61-80cb472bdac0 --tag=volume=nginx-logs --tag=backup=nginx-bu --host=velero --json, stdout=, stderr=Fatal: unable to open config file: Stat: stat restic/nginx-example/config: no such file or directory\nIs there a repository at the following location?\nrestic/nginx-example\n" backup=velero/nginx-bu controller=pod-volume-backup error="unable to find summary in restic backup command output" error.file="/github.com/vmware-tanzu/velero/pkg/restic/exec_commands.go:175" error.function=github.com/vmware-tanzu/velero/pkg/restic.getSummaryLine logSource="pkg/controller/pod_volume_backup_controller.go:283" name=nginx-bu-jf6ff namespace=velero`

It appears as if the restic repository was never initialised/created.

**What did you expect to happen:**

I expected the restic snapshot  to be taken and visible inside the restic container and for this to be then copied to the nfs location

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
`..
time="2020-08-24T09:27:15Z" level=info msg="Initializing restic repository" controller=restic-repository logSource="pkg/controller/restic_repository_controller.go:155" name=nginx-example-default-ptzv8 namespace=velero
time="2020-08-24T09:27:15Z" level=debug msg="Ran restic command" command="restic snapshots --repo=restic/nginx-example --password-file=/tmp/velero-restic-credentials-nginx-example529711110 --cache-dir=/scratch/.cache/restic --last" logSource="pkg/restic/repository_manager.go:291" repository=nginx-example stderr="Fatal: unable to open config file: Stat: stat restic/nginx-example/config: no such file or directory\nIs there a repository at the following location?\nrestic/nginx-example\n" stdout=
time="2020-08-24T09:27:15Z" level=debug msg="Backup has not expired yet, skipping" backup=velero/nginx-bu controller=gc-controller expiration="2020-09-23 09:27:11 +0000 UTC" logSource="pkg/controller/gc_controller.go:127"
time="2020-08-24T09:27:17Z" level=debug msg="Ran restic command" command="restic init --repo=restic/nginx-example --password-file=/tmp/velero-restic-credentials-nginx-example268113837 --cache-dir=/scratch/.cache/restic" logSource="pkg/restic/repository_manager.go:291" repository=nginx-example stderr= stdout="created restic repository e4f217c5b5 at restic/nginx-example\n\nPlease note that knowledge of your password is required to access\nthe repository. Losing your password means that your data is\nirrecoverably lost.\n"
time="2020-08-24T09:27:17Z" level=debug msg="Released lock" backupLocation=default logSource="pkg/restic/repository_ensurer.go:128" volumeNamespace=nginx-example
time="2020-08-24T09:27:17Z" level=debug msg="Executing post hooks" backup=velero/nginx-bu logSource="pkg/backup/item_backupper.go:204" name=nginx-deployment-86c565d654-m72gp namespace=nginx-example resource=pods
time="2020-08-24T09:27:17Z" level=info msg="1 errors encountered backup up item" backup=velero/nginx-bu logSource="pkg/backup/backup.go:444" name=nginx-deployment-86c565d654-m72gp
time="2020-08-24T09:27:17Z" level=error msg="Error backing up item" backup=velero/nginx-bu error="pod volume backup failed: error running restic backup, stderr=Fatal: unable to open config file: Stat: stat restic/nginx-example/config: no such file or directory\nIs there a repository at the following location?\nrestic/nginx-example\n: unable to find summary in restic backup command output" error.file="/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:179" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:448" name=nginx-deployment-86c565d654-m72gp
time="2020-08-24T09:27:17Z" level=info msg="Backed up 32 items out of an estimated total of 626 (estimate will change throughout the backup)" backup=velero/nginx-bu logSource="pkg/backup/backup.go:411" name=nginx-deployment-86c565d654-m72gp namespace=nginx-example progress= resource=pods
..`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`

```
velero backup describe nginx-bu
Name:         nginx-bu
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.18.6
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=18

Phase:  PartiallyFailed (run `velero backup logs nginx-bu` for more information)

Errors:    1
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-08-24 02:27:11 -0700 PDT
Completed:  2020-08-24 02:27:25 -0700 PDT

Expiration:  2020-09-23 02:27:11 -0700 PDT

Total items to be backed up:  624
Items backed up:              624

Velero-Native Snapshots: <none included>

Restic Backups (specify --details for more information):
  Failed:  1
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
`Client:
	Version: v1.4.2
	Git commit: 56a08a4d695d893f0863f697c2f926e27d70c0c5
Server:
	Version: v1.4.2`
- Velero features (use `velero client config get features`):
`features: <NOT SET>`
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:

- Cloud provider or hardware configuration: On prem
- OS (e.g. from `/etc/os-release`):CentOS Linux 7 (Core)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ashish-amarnath** [comment] 2020-08-24 19:24
Identical to https://github.com/vmware-tanzu/velero/issues/2721

**Comment by nrb** [comment] 2020-10-29 16:41
Closing this as a duplicate of #2721; we'll focus on that issue.

**Closed** 2020-10-29 16:42 UTC
Labels: Duplicate, Needs investigation, Restic
