### ISSUE TITLE
No errors with GCP snapshots when quota is reached

### ISSUE THREAD

**Issue by pea-io** [vmware-tanzu/velero#6438] opened 2023-06-29 14:29 UTC
**What steps did you take and what happened:**

We have deployed velero (1.11.0) on our kubernetes cluster on GCP. By default, each GCP project have a snapshot limit to25k.
Once this limit is reached, velero continues to backup and snapshot volumes but nothing happen on the GCP side.
And velero returns no errors.

**What did you expect to happen:**
Velero should fail to snapshot volumes

**Anything else you would like to add:**

Nothing unusual in the logs
```
time="2023-06-29T12:19:25Z" level=info msg="Executing PVCAction" backup=velero/myapp-workspace-20230629121557 cmd=/velero logSource="pkg/backup/backup_pv_action.go:49" pluginName=velero
time="2023-06-29T12:19:25Z" level=info msg="Backing up item" backup=velero/myapp-workspace-20230629121557 logSource="pkg/backup/item_backupper.go:173" name=pvc-f280613e-224f-4d27-aed0-ef33c9f4a9e0 namespace= resource=persistentvolumes
time="2023-06-29T12:19:25Z" level=info msg="Executing takePVSnapshot" backup=velero/myapp-workspace-20230629121557 logSource="pkg/backup/item_backupper.go:457" name=pvc-f280613e-224f-4d27-aed0-ef33c9f4a9e0 namespace= resource=persistentvolumes
time="2023-06-29T12:19:25Z" level=info msg="Got volume ID for persistent volume" backup=velero/myapp-workspace-20230629121557 logSource="pkg/backup/item_backupper.go:537" name=pvc-f280613e-224f-4d27-aed0-ef33c9f4a9e0 namespace= persistentVolume=pvc-f280613e-224f-4d27-aed0-ef33c9f4a9e0 resource=persistentvolumes volumeSnapshotLocation=default
time="2023-06-29T12:19:25Z" level=info msg="Getting volume information" backup=velero/myapp-workspace-20230629121557 logSource="pkg/backup/item_backupper.go:558" name=pvc-f280613e-224f-4d27-aed0-ef33c9f4a9e0 namespace= persistentVolume=pvc-f280613e-224f-4d27-aed0-ef33c9f4a9e0 resource=persistentvolumes volumeID=pvc-f280613e-224f-4d27-aed0-ef33c9f4a9e0
time="2023-06-29T12:19:25Z" level=info msg="Snapshotting persistent volume" backup=velero/myapp-workspace-20230629121557 logSource="pkg/backup/item_backupper.go:564" name=pvc-f280613e-224f-4d27-aed0-ef33c9f4a9e0 namespace= persistentVolume=pvc-f280613e-224f-4d27-aed0-ef33c9f4a9e0 resource=persistentvolumes volumeID=pvc-f280613e-224f-4d27-aed0-ef33c9f4a9e0
time="2023-06-29T12:19:25Z" level=info msg="Backed up 637 items out of an estimated total of 921 (estimate will change throughout the backup)" backup=velero/myapp-workspace-20230629121557 logSource="pkg/backup/backup.go:397" name=claim-myapp-test namespace=myapp progress= resource=persistentvolumeclaims
```

Velero reports nothing:
```
NAME                                  STATUS      ERRORS   WARNINGS   CREATED                          EXPIRES   STORAGE LOCATION   SELECTOR
myapp-workspace-20230629121557   Completed   0        0          2023-06-29 14:16:13 +0200 CEST   91d       default            app.kubernetes.io/name notin (postgresql)
```

velero describe:
```
Name:         myapp-workspace-20230629121557
Namespace:    velero
Labels:       kustomize.toolkit.fluxcd.io/name=velero
              kustomize.toolkit.fluxcd.io/namespace=flux-system
              velero.io/schedule-name=myapp-workspace
              velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.24.12-gke.500
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=24

Phase:  Completed


Namespaces:
  Included:  myapp
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  app.kubernetes.io/name notin (postgresql)

Storage Location:  default

Velero-Native Snapshot PVs:  true

TTL:  2192h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  1h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2023-06-29 14:16:13 +0200 CEST
Completed:  2023-06-29 14:19:28 +0200 CEST

Expiration:  2023-09-28 22:16:13 +0200 CEST

Velero-Native Snapshots:  292 of 292 snapshots completed successfully (specify --details for more information)
```

All the snapshots IDs in the velero describe commands are wrong and doesn't exist on GCP

**Environment:**

- Velero version (use `velero version`): 
```
Client:
	Version: v1.11.0
	Git commit: -
Server:
	Version: v1.11.0
```
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): `features: <NOT SET>`
- Kubernetes installer & version: 
```
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.12-gke.500", GitCommit:"fa2714567d7451b5e32541c10119d1246730c197", GitTreeState:"clean", BuildDate:"2023-03-23T11:35:05Z", GoVersion:"go1.19.7 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GCP

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by 0x113** [comment] 2023-06-29 15:31
I will look into this issue. Can you provide any GCP documentation where they mention a 25k limit? I'm aware that disks can be snapshotted at most once every 10 minutes, but I couldn't find any documentation page on the 25k snapshot limit.

**Comment by pea-io** [comment] 2023-06-29 16:17
I can't find the limit in the documentation too but here is a screenshot of what i have on my quota page on GCP ( [console](https://console.cloud.google.com/apis/api/compute.googleapis.com/quotas) )

![Capture d’écran 2023-06-29 à 18 14 57](https://github.com/vmware-tanzu/velero/assets/101271005/1e861d3f-6b4e-4996-805b-5c82ff114664)

**Comment by 0x113** [comment] 2023-06-30 08:08
Thanks. I see in my project the limit is even lower, as it is 5k. I'll look into that and see what can be done.

**Comment by 0x113** [comment] 2023-07-05 10:31
Just FYI, I have opened a Pull Request for the Velero GCP plugin to check the snapshot limit. PR: https://github.com/vmware-tanzu/velero-plugin-for-gcp/pull/144

**Comment by blackpiglet** [comment] 2023-07-06 02:02
@pea-io @0x113 
Thanks for reporting and working out a fix.

IMO, the GCP SDK used by the GCP plugin should detect the error caused by the project quota limitation.
In normal cases, there is no need to add logic to handle the specific error.

@pea-io 
Could you help to collect the debug bundle to help to find the reason why there is no error reported when the quota limit is hit? The command is `velero debug --backup <backup-name>`.

**Comment by 0x113** [comment] 2023-07-07 11:40
@blackpiglet 

I couldn't find anything in the debug bundle, but I think I know what is wrong. 

As of now, the Velero GCP plugin just calls the `Do` method when trying to create a snapshot, and checks the error there. However, the `Do` method returns two values: operation and an error.

The error is nil, however, the operation is in progress, and might not always be complete. In the case of this issue, the quota limit error is returned for operation, not for the `Do` call. 

I think the Velero plugin should actually wait for the snapshot to finish. Right now it returns right away when the request to create a snapshot is sent. Not when the operation is complete. 

Here's the error present in GCP:
![image](https://github.com/vmware-tanzu/velero/assets/40567093/4d4ab685-19f4-4469-bab3-b12e032143a1)

The PR I raised only handles quota exceeded error, but I think we should make a change to wait for the operation to finish. @blackpiglet, please let me know what you think. I'll be more than happy to update the PR and contribute to Velero.

**Comment by blackpiglet** [comment] 2023-07-08 01:27
@pea-io 
In most cases, waiting for the snapshot operation to complete is not quite time-consuming, but in some extreme cases, it can be unacceptable. The operation time is mainly used to upload the snapshot data into the object storage. If the data size is big enough, it can take more than half an hour to complete. 
If we use the sync mode in this scenario, and there are several large volumes to back up, then the time to complete the backup can be not expected.
There is already an async mode for the plugins, for example, BIA and RIA. I think it's better to use the async mode for the VolumeSnapshotter plugin in this scenario.

**Comment by pea-io** [comment] 2023-07-17 14:38
Hello, 
I understand the issue with a sync mode. Do you have some news about checking at least the quota ?
Regards,

**Comment by 0x113** [comment] 2023-07-18 02:39
> Hello, 
> 
> I understand the issue with a sync mode. Do you have some news about checking at least the quota ?
> 
> Regards,
> 
> 

I opened a Pull Request with changes to check the quota before running the snapshot. It needs to be reviewed by @blackpiglet.

**Comment by blackpiglet** [comment] 2023-08-21 02:23
https://github.com/vmware-tanzu/velero-plugin-for-gcp/pull/144 is merged. This PR can be closed.

**Closed by blackpiglet** 2023-08-21 02:23 UTC
Labels: Area/Cloud/GCP
