### ISSUE TITLE
CRDs update ends with forbidden cannot be set to false

### ISSUE THREAD

**Issue by jprecuch** [vmware-tanzu/velero#2207] opened 2020-01-17 07:57 UTC
Hi.
I was performing update from 1.1 to 1.2 and when I was updating CRDS it didn't for for all. See below: 
`root@aws-jump:~/velero# velero install --crds-only --dry-run -o yaml | kubectl apply -f -
customresourcedefinition.apiextensions.k8s.io/deletebackuprequests.velero.io configured
customresourcedefinition.apiextensions.k8s.io/downloadrequests.velero.io configured
customresourcedefinition.apiextensions.k8s.io/podvolumerestores.velero.io configured
customresourcedefinition.apiextensions.k8s.io/resticrepositories.velero.io configured
customresourcedefinition.apiextensions.k8s.io/serverstatusrequests.velero.io configured
Error from server (Invalid): CustomResourceDefinition.apiextensions.k8s.io "backups.velero.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[hooks].properties[resources].items.properties[labelSelector].properties[matchLabels].additionalProperties: Forbidden: additionalProperties cannot be set to false, spec.validation.openAPIV3Schema.properties[spec].properties[labelSelector].properties[matchLabels].additionalProperties: Forbidden: additionalProperties cannot be set to false]
Error from server (Invalid): CustomResourceDefinition.apiextensions.k8s.io "backupstoragelocations.velero.io" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[config].additionalProperties: Forbidden: additionalProperties cannot be set to false
Error from server (Invalid): CustomResourceDefinition.apiextensions.k8s.io "podvolumebackups.velero.io" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[tags].additionalProperties: Forbidden: additionalProperties cannot be set to false
Error from server (Invalid): CustomResourceDefinition.apiextensions.k8s.io "restores.velero.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[labelSelector].properties[matchLabels].additionalProperties: Forbidden: additionalProperties cannot be set to false, spec.validation.openAPIV3Schema.properties[spec].properties[namespaceMapping].additionalProperties: Forbidden: additionalProperties cannot be set to false]
Error from server (Invalid): CustomResourceDefinition.apiextensions.k8s.io "schedules.velero.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[labelSelector].properties[matchLabels].additionalProperties: Forbidden: additionalProperties cannot be set to false, spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[hooks].properties[resources].items.properties[labelSelector].properties[matchLabels].additionalProperties: Forbidden: additionalProperties cannot be set to false]
Error from server (Invalid): CustomResourceDefinition.apiextensions.k8s.io "volumesnapshotlocations.velero.io" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[config].additionalProperties: Forbidden: additionalProperties cannot be set to false`
My current k8s version
`root@aws-jump:~/velero# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-10T03:03:57Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

Velero started fine but need to know if I need to fix these somehow or it is because we have older version of k8s on server side.

Thanks

**Comment by jprecuch** [comment] 2020-01-17 08:22
I also tried to install it manually on same cluster with fresh 1.2 and ended with 
`CustomResourceDefinition/backups.velero.io: attempting to create resource
An error occurred:

Error installing Velero. Use `kubectl logs deploy/velero -n velero` to check the deploy logs: Error creating resource CustomResourceDefinition/backups.velero.io: CustomResourceDefinition.apiextensions.k8s.io "backups.velero.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[hooks].properties[resources].items.properties[labelSelector].properties[matchLabels].additionalProperties: Forbidden: additionalProperties cannot be set to false, spec.validation.openAPIV3Schema.properties[spec].properties[labelSelector].properties[matchLabels].additionalProperties: Forbidden: additionalProperties cannot be set to false]`

**Comment by nrb** [comment] 2020-01-17 16:56
Hi @jprecuch, this appears to be a duplicate of #2159. I've got a PR open to fix this in #2197.

I'm going to close this issue as a duplicate for now.

**Closed by nrb** 2020-01-17 16:56 UTC
