### ISSUE TITLE
Report metrics for CSI snapshots

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2499] opened 2020-05-05 16:29 UTC
When generating CSI snapshots, we should generate metrics associated with the VolumeSnapshots and VolumeSnapshotContents

This could include:
 
 * number of VolumeSnapshots & VolumeSnapshotContents in a backup
 * total size of on-storage snapshots

This should be in CSI's GA release, but isn't essential for beta support.

**Comment by reasonerjt** [comment] 2022-04-14 12:14
For 1.9, we'll not expose the total size of the snapshot.

Users should be able to get such data from storage directly more easily.

We may consider to add such metric in future based on feedback.

**Comment by blackpiglet** [comment] 2022-04-23 05:10
Met two unusual cases during developing.
* If some VolumeSnapshotContents created by previous backup are left in the cluster, and the backup are already deleted, then a new backup with the same name as previous one is created, the backup's metric cannot work expectedly, because the new backup will include the left VolumeSnapshotContents. Not sure whether this needs fix or expected behavior.
* The VolumeSnapshot attempts are always record as failure in metric. After investigation, the PR needs to be merged to make metric works: https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/100. This is because the VolumeSnapshot BackupItemAction return without checking ReadyToUse as true, so when the metrics code checks the VolumeSnapshot, its status is still not ready. May need to consider whether to use VolumeSnapshot or VolumeSnapshotContent for metric computing.

**Closed** 2022-04-26 02:25 UTC
Labels: Area/CSI, Metrics, Reviewed Q2 2021, CSI plugin - GA - phase1
