### ISSUE TITLE
Why velero try to upload backup even if phase of the backup is failed

### ISSUE THREAD

**Issue by Lighting-wings** [vmware-tanzu/velero#3206] opened 2020-12-24 13:12 UTC
Hello，I can't understand velero's processing logic somewhere. What I mean is not the logic is wrong, but I want to know why you choose to do in that way. Could you explain it to me? Thank you a lot if you spend time to do explanation.

Here are something I can't understand:
1. As shown in the title, why velero try to upload backup even if phase of the backup is failed ?
2. Why can't CSI feature be optional for single backup ? Maybe I want to use restic for one backup and use snapshot for another.
3. Why doesn't velero return error when it can't get `BackStore` in `backupdeletioncontroller` ? I think it will cause panic because of nil pointer. By the way, I met this one time when I restarted velero and offered wrong `sk`. Remaining `deletebackuprequest` is processed by the new velero container.
![image](https://user-images.githubusercontent.com/24741946/103089549-3d3ddd00-4629-11eb-9806-ba361a377dd0.png)

4. I think you provide a retrying mechanism for deleting backup. But why doesn't velero delete the backup in the cluster if backup resource doesn't exist in bucket ? This leads that backup is always in the phase of `Deleting` and the corresponding `deletbackuprequest` is always in the phase of `InProgress`. The `backupdeletioncontroller` will process the `deletbackuprequest` again and again. 
First, we can't  ensure that the users don't delete backups in the bucket manually. 
Second,  we assume the following situation. Two clusters use one bucket for migration and they will have same backups after `backupsynccontroller `works. If one backup expired and deleted by first cluster‘s `backupdeletioncontroller`. Then it will happen to the second cluster.

Now I can't understand the logic above. I think velero is very useful for data protect and application migration. I hope velero be better for users like me.

**Comment by Lighting-wings** [comment] 2020-12-24 13:12
@ncdc @aramprice @carlisia @joonas

**Comment by neujie** [comment] 2020-12-25 03:39
+1
This also bothers me.

**Comment by zubron** [comment] 2021-01-04 18:40
Hi @Lighting-wings - thanks for the questions and feedback. I will answer your questions in turn:

1. Velero stores other information associated with the backup, such as the backup logs, which is why it will upload even if the backup fails. This is intended behaviour. When running `velero backup logs <backupname> the logs are fetched from the BackupStorageLocation.
2. You can specifically choose how volumes are backed up on a per backup basis. For example, if you have Velero installed and are using the CSI plugin, you can opt to instead backup volumes using restic by using the flag `--default-volumes-to-restic` when creating a backup. This will result in Velero opting to use restic instead of the CSI snapshotter. You can also enable restic by default and then opt out on a per backup basis. See https://velero.io/docs/v1.5/restic/#to-back-up
3. Yes, in this case we should probably return the error and prevent the backup deletion from continuing. We append errors to the slice so that all the errors can be reported but in the case where we can't get the backup store, we shouldn't proceed. I will create a separate issue for this.
4. This is a known issue and is being tracked in #2980. A fix has already been merged and will be available in our next 1.5 patch release.

I am going to close this issue but will open a separate one to track point 3. Hopefully these points above answer your questions but feel free to reopen if you have further questions.

**Closed by zubron** 2021-01-04 18:40 UTC

**Comment by Lighting-wings** [comment] 2021-01-08 12:29
Thank you very much for detailed explanation. You're so nice. I still have some doubts with second question. Maybe what I described is not clear enough. In fact, the question is associated with #3078. Now velero uses CSI plugin to complete corresponding operation. So velero will apply CSI snapshotter as long as there is executable file of CSI plugin in the directory of `plugins`. It seems that the feature setting of `EnableCSI` is not useful.

**Comment by zubron** [comment] 2021-01-08 14:18
@Lighting-wings Thanks for sharing a link to the issue. We have some [outstanding issues](https://github.com/vmware-tanzu/velero/labels/CSI) related to CSI integration, including needing to make the language and options clearer. 

My understanding is that you can enable restic by default for _all_ backups by enabling the flag `--default-volumes-to-restic` when running `velero install` or setting that flag on `velero server` in the deployment, or you can enable that on a per backup basis using the same flag with `velero backup create`. This flag will take precedence over any other volume snapshotter or CSI plugin. In this case you could have CSI as the default volume backup option, and enable restic as needed by either setting the `--default-volumes-to-restic` flag when creating the backup. Unfortunately, I don't know if there is currently a way to dynamically enable CSI on a per backup basis as requested in #3078.

Could you share a little more about your use case? Is there a strong need to regularly switch between these two methods?
