### ISSUE TITLE
Persistent Volume with Reclaim Policy Delete gets recreated

### ISSUE THREAD

**Issue by joschi36** [vmware-tanzu/velero#2739] opened 2020-07-21 15:42 UTC
**What steps did you take and what happened:**
We did a backup with Velero and without any form of volume backup (restic/volumesnapshot).
When restoring the PersistentVolume got recreated.

**What did you expect to happen:**
We expected that the manifest of the PersistentVolume gets applied as is with the same meta information.

**The output of the following commands will help us better understand what's going on**:
- `velero restore logs joschi-disaster-test`
```
Getting client for /v1, Kind=PersistentVolume" logSource="pkg/restore/restore.go:746" restore=velero/joschi-disaster-test-2020072117012
Dynamically re-provisioning persistent volume because it doesn't have a snapshot and its reclaim policy is Delete." logSource="pkg/restore/restore.go:933" restore=velero/joschi-disaster-test-2020072117012
Dynamically re-provisioning persistent volume because it doesn't have a snapshot and its reclaim policy is Delete." logSource="pkg/restore/restore.go:933" restore=velero/joschi-disaster-test-2020072117012
Dynamically re-provisioning persistent volume because it doesn't have a snapshot and its reclaim policy is Delete." logSource="pkg/restore/restore.go:933" restore=velero/joschi-disaster-test-2020072117012
Dynamically re-provisioning persistent volume because it doesn't have a snapshot and its reclaim policy is Delete." logSource="pkg/restore/restore.go:933" restore=velero/joschi-disaster-test-2020072117012
Dynamically re-provisioning persistent volume because it doesn't have a snapshot and its reclaim policy is Delete." logSource="pkg/restore/restore.go:933" restore=velero/joschi-disaster-test-2020072117012
Restoring resource 'persistentvolumeclaims' into namespace 'loki'" logSource="pkg/restore/restore.go:702" restore=velero/joschi-disaster-test-2020072117012
Getting client for /v1, Kind=PersistentVolumeClaim" logSource="pkg/restore/restore.go:746" restore=velero/joschi-disaster-test-2020072117012
Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:964" restore=velero/joschi-disaster-test-2020072117012
Executing AddPVFromPVCAction" cmd=/velero logSource="pkg/restore/add_pv_from_pvc_action.go:44" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Adding PV csi-dcb6d759bd as an additional item to restore" cmd=/velero logSource="pkg/restore/add_pv_from_pvc_action.go:66" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Skipping persistentvolumes/csi-dcb6d759bd because it's already been restored." logSource="pkg/restore/restore.go:844" restore=velero/joschi-disaster-test-2020072117012
Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:964" restore=velero/joschi-disaster-test-2020072117012
Executing ChangePVCNodeSelectorAction" cmd=/velero logSource="pkg/restore/change_pvc_node_selector.go:63" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Done executing ChangePVCNodeSelectorAction" cmd=/velero logSource="pkg/restore/change_pvc_node_selector.go:91" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:964" restore=velero/joschi-disaster-test-2020072117012
Executing ChangeStorageClassAction" cmd=/velero logSource="pkg/restore/change_storageclass_action.go:63" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Done executing ChangeStorageClassAction" cmd=/velero logSource="pkg/restore/change_storageclass_action.go:74" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Resetting PersistentVolumeClaim loki/storage-loki-0 for dynamic provisioning" logSource="pkg/restore/restore.go:1037" restore=velero/joschi-disaster-test-2020072117012
Attempting to restore PersistentVolumeClaim: storage-loki-0" logSource="pkg/restore/restore.go:1070" restore=velero/joschi-disaster-test-2020072117012
Restoring resource 'persistentvolumeclaims' into namespace 'monitoring'" logSource="pkg/restore/restore.go:702" restore=velero/joschi-disaster-test-2020072117012
Getting client for /v1, Kind=PersistentVolumeClaim" logSource="pkg/restore/restore.go:746" restore=velero/joschi-disaster-test-2020072117012
Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:964" restore=velero/joschi-disaster-test-2020072117012
Executing AddPVFromPVCAction" cmd=/velero logSource="pkg/restore/add_pv_from_pvc_action.go:44" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Adding PV csi-7aa81280b9 as an additional item to restore" cmd=/velero logSource="pkg/restore/add_pv_from_pvc_action.go:66" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Skipping persistentvolumes/csi-7aa81280b9 because it's already been restored." logSource="pkg/restore/restore.go:844" restore=velero/joschi-disaster-test-2020072117012
Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:964" restore=velero/joschi-disaster-test-2020072117012
Executing ChangePVCNodeSelectorAction" cmd=/velero logSource="pkg/restore/change_pvc_node_selector.go:63" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Done executing ChangePVCNodeSelectorAction" cmd=/velero logSource="pkg/restore/change_pvc_node_selector.go:91" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:964" restore=velero/joschi-disaster-test-2020072117012
Executing ChangeStorageClassAction" cmd=/velero logSource="pkg/restore/change_storageclass_action.go:63" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Done executing ChangeStorageClassAction" cmd=/velero logSource="pkg/restore/change_storageclass_action.go:74" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Resetting PersistentVolumeClaim monitoring/prometheus-grafana-storage for dynamic provisioning" logSource="pkg/restore/restore.go:1037" restore=velero/joschi-disaster-test-2020072117012
Attempting to restore PersistentVolumeClaim: prometheus-grafana-storage" logSource="pkg/restore/restore.go:1070" restore=velero/joschi-disaster-test-2020072117012
Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:964" restore=velero/joschi-disaster-test-2020072117012
Executing AddPVFromPVCAction" cmd=/velero logSource="pkg/restore/add_pv_from_pvc_action.go:44" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Adding PV csi-602da2215a as an additional item to restore" cmd=/velero logSource="pkg/restore/add_pv_from_pvc_action.go:66" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Skipping persistentvolumes/csi-602da2215a because it's already been restored." logSource="pkg/restore/restore.go:844" restore=velero/joschi-disaster-test-2020072117012
Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:964" restore=velero/joschi-disaster-test-2020072117012
Executing ChangePVCNodeSelectorAction" cmd=/velero logSource="pkg/restore/change_pvc_node_selector.go:63" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Done executing ChangePVCNodeSelectorAction" cmd=/velero logSource="pkg/restore/change_pvc_node_selector.go:91" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:964" restore=velero/joschi-disaster-test-2020072117012
Executing ChangeStorageClassAction" cmd=/velero logSource="pkg/restore/change_storageclass_action.go:63" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Done executing ChangeStorageClassAction" cmd=/velero logSource="pkg/restore/change_storageclass_action.go:74" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Resetting PersistentVolumeClaim monitoring/prometheus-k8s-db-prometheus-k8s-0 for dynamic provisioning" logSource="pkg/restore/restore.go:1037" restore=velero/joschi-disaster-test-2020072117012
Attempting to restore PersistentVolumeClaim: prometheus-k8s-db-prometheus-k8s-0" logSource="pkg/restore/restore.go:1070" restore=velero/joschi-disaster-test-2020072117012
Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:964" restore=velero/joschi-disaster-test-2020072117012
Executing AddPVFromPVCAction" cmd=/velero logSource="pkg/restore/add_pv_from_pvc_action.go:44" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Adding PV csi-b53b65bd89 as an additional item to restore" cmd=/velero logSource="pkg/restore/add_pv_from_pvc_action.go:66" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Skipping persistentvolumes/csi-b53b65bd89 because it's already been restored." logSource="pkg/restore/restore.go:844" restore=velero/joschi-disaster-test-2020072117012
Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:964" restore=velero/joschi-disaster-test-2020072117012
Executing ChangePVCNodeSelectorAction" cmd=/velero logSource="pkg/restore/change_pvc_node_selector.go:63" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Done executing ChangePVCNodeSelectorAction" cmd=/velero logSource="pkg/restore/change_pvc_node_selector.go:91" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:964" restore=velero/joschi-disaster-test-2020072117012
Executing ChangeStorageClassAction" cmd=/velero logSource="pkg/restore/change_storageclass_action.go:63" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Resetting PersistentVolumeClaim monitoring/prometheus-k8s-db-prometheus-k8s-1 for dynamic provisioning" logSource="pkg/restore/restore.go:1037" restore=velero/joschi-disaster-test-2020072117012
Attempting to restore PersistentVolumeClaim: prometheus-k8s-db-prometheus-k8s-1" logSource="pkg/restore/restore.go:1070" restore=velero/joschi-disaster-test-2020072117012
Done executing ChangeStorageClassAction" cmd=/velero logSource="pkg/restore/change_storageclass_action.go:74" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Restoring resource 'persistentvolumeclaims' into namespace 'robot-shop'" logSource="pkg/restore/restore.go:702" restore=velero/joschi-disaster-test-2020072117012
Getting client for /v1, Kind=PersistentVolumeClaim" logSource="pkg/restore/restore.go:746" restore=velero/joschi-disaster-test-2020072117012
Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:964" restore=velero/joschi-disaster-test-2020072117012
Executing AddPVFromPVCAction" cmd=/velero logSource="pkg/restore/add_pv_from_pvc_action.go:44" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Adding PV csi-7b017a83e6 as an additional item to restore" cmd=/velero logSource="pkg/restore/add_pv_from_pvc_action.go:66" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Skipping persistentvolumes/csi-7b017a83e6 because it's already been restored." logSource="pkg/restore/restore.go:844" restore=velero/joschi-disaster-test-2020072117012
Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:964" restore=velero/joschi-disaster-test-2020072117012
Executing ChangePVCNodeSelectorAction" cmd=/velero logSource="pkg/restore/change_pvc_node_selector.go:63" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Done executing ChangePVCNodeSelectorAction" cmd=/velero logSource="pkg/restore/change_pvc_node_selector.go:91" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:964" restore=velero/joschi-disaster-test-2020072117012
Executing ChangeStorageClassAction" cmd=/velero logSource="pkg/restore/change_storageclass_action.go:63" pluginName=velero restore=velero/joschi-disaster-test-2020072117012
Resetting PersistentVolumeClaim robot-shop/data-redis-0 for dynamic provisioning" logSource="pkg/restore/restore.go:1037" restore=velero/joschi-disaster-test-2020072117012
Attempting to restore PersistentVolumeClaim: data-redis-0" logSource="pkg/restore/restore.go:1070" restore=velero/joschi-disaster-test-2020072117012
Done executing ChangeStorageClassAction" cmd=/velero logSource="pkg/restore/change_storageclass_action.go:74" pluginName=velero restore=velero/joschi-disaster-test-2020072117012

```

**Anything else you would like to add:**
We can't use the Reclaim Policy Retain as our storage integration ([Dell EMC CSI Isilon](https://github.com/dell/csi-isilon)) will not delete the volumes on the storage system.
My idea would be to define a flag which makes it configurable to choose whether to use the actual logic in https://github.com/vmware-tanzu/velero/blob/f42c63af1b9af445e38f78a7256b1c48ef79c10e/pkg/restore/restore.go#L862-L950 or just to create the PersistentVolume manifest as is (as in the default section https://github.com/vmware-tanzu/velero/blob/f42c63af1b9af445e38f78a7256b1c48ef79c10e/pkg/restore/restore.go#L939-L949).

**Environment:**
- Velero version (use `velero version`):  v1.4.0
- Velero features (use `velero client config get features`): none
- Kubernetes version (use `kubectl version`): v1.16.3-2+f1f3428e8468b6-dirty
- Kubernetes installer & version: Own installation
- Cloud provider or hardware configuration: Own implementation in CloudStack
- OS (e.g. from `/etc/os-release`): CentOS Linux 7

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by joschi36** [comment] 2020-07-29 11:18
Maybe @skriss could have helped here, as he wrote the current logic in https://github.com/vmware-tanzu/velero/blob/main/pkg/restore/restore.go#L939-L949
But as far as I see he isn't maintainer anymore. Do you @nrb know about the current logic?

**Comment by nrb** [comment] 2020-07-29 17:25
@joschi36 Sorry about the delay in response.

I don't think this use case is one we've encountered before, so I need to learn a little more about it.

You're saying you have a PV manifest with no snapshot an a reclaim policy of Delete..is it actually deleted from Kubernetes at restore time? It appears so since Velero is recreating it.

Is this volume also deleted from the Isilon storage system, or is the intention to re-associate with an existing volume in storage at restore time?

**Comment by joschi36** [comment] 2020-07-29 17:40
**Background:**
Our K8s backup/restore plans are discoupled with our volume backup/restore plans.
The storage system we are using is also completely discoupled from K8s
Also, we need to use the Reclaim Policy Delete.

**Expectation:**
The idea is that when an Incident happens (for instance deletion of all server nodes) we want to recreate the cluster and reapply all manifests, also the PV manifests as they were.

**What happens:**
But as Velero does not reapply PVs with the Reclaim Policy Delete and instead dynamically recreates PVs with the PVCs manifests. What we want is that we have the same behavior as the Reclaim Policy Retain, so the PVs manifest gets reapplied with the same manifest without recreating, so same volume gets mounted as before the incident.

**Clarifications:**
The volumes didn't get deleted in the background, just new volumes were created instead of using the already existing ones.

**Solution:**
One Solution would be to have a flag to control this behavior instead of relying on the Reclaim Policy option, which would make sense to me. Maybe I understand something wrong about the current behavior or its decision to behave like this.

Thanks for your help @nrb

**Comment by joschi36** [comment] 2020-08-13 11:18
Hey @nrb can you explain the behavior, because we would be happy to create a PR to extend the current switch with a flag in `velero restore create`.
Something like `--disable-reprovisioning`.

**Comment by nrb** [comment] 2020-08-26 17:43
Sorry for the delay in response.

I think I see the disconnect here - it's this line:

```
Our K8s backup/restore plans are discoupled with our volume backup/restore plans.
The storage system we are using is also completely discoupled from K8s
```

So in most cases where folks are using Velero, the storage is not completely decoupled from Kubernetes such that Velero should completely ignore the PV's reclaim policy.

Velero does not re-apply the PV with a reclaim policy of `Delete` on the assumption that most installations don't want to keep those, otherwise they would have a different reclaim policy such as `Retain`. So, it instead completely re-provisions a fresh PV.

The assumption comes from [these docs](https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/):

> For dynamically provisioned PersistentVolumes, the default reclaim policy is "Delete". This means that a dynamically provisioned volume is automatically deleted when a user deletes the corresponding PersistentVolumeClaim. This automatic behavior might be inappropriate if the volume contains precious data. In that case, it is more appropriate to use the "Retain" policy. With the "Retain" policy, if a user deletes a PersistentVolumeClaim, the corresponding PersistentVolume is not be deleted. Instead, it is moved to the Released phase, where all of its data can be manually recovered.

I'll need to think more about PR #2869 - I don't know that completely removing it makes sense for all cases, but I see why it does in your case, or that a flag disabling it would be a good option for those systems where they don't follow expected behavior exactly as defined.

**Comment by nrb** [comment] 2020-09-02 18:53
@joschi36 I've closed out the PR, but I want to link the [Kubernetes documentation to the `Delete` policy](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#delete) here.

The delete policy is intended to remove the volume from the underlying storage system entirely. If the currently storage system isn't doing that, then it should be using `Retain`.

---

If you're using Velero _only_ for the Kubernetes manifests and managing storage backup completely separately, then this is a use case we'll need to look into separately rather than completely removing the code, because Velero was intended to manage both in concert.

I think the `--disable-reprovisioning` flag can make sense here for this use case as a companion to the `--disable-snapshots` flag, as it would accommodate the de-coupled nature of your setup, which we hadn't really considered before.

**Comment by dsu-igeek** [comment] 2020-10-22 00:54
Closing this, please re-open if there are continuing issues

**Closed by dsu-igeek** 2020-10-22 00:54 UTC
Labels: Needs info
