### ISSUE TITLE
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f

### ISSUE THREAD

**Issue by 13567436138** [vmware-tanzu/velero#6049] opened 2023-03-29 03:45 UTC
**What steps did you take and what happened:**

**What did you expect to happen:**
kubectl logs  -n nginx-example web-2 -c restore-wait

ot found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f
Not found: /restores/www/.velero/470cd690-bcae-45ed-a15f-58d63dbe656f

```
root@cluster2-147:~# velero restore describe nginx-restore --details
Name:         nginx-restore
Namespace:    velero
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"velero.io/v1","kind":"Restore","metadata":{"annotations":{},"name":"nginx-restore","namespace":"velero"},"spec":{"backupName":"nginx-backup","excludedResources":["nodes","events","events.events.k8s.io","backups.velero.io","restores.velero.io","resticrepositories.velero.io","csinodes.storage.k8s.io","volumeattachments.storage.k8s.io","backuprepositories.velero.io"],"includedNamespaces":["*"]}}


Phase:                       PartiallyFailed (run 'velero restore logs nginx-restore' for more information)
Total items to be restored:  34
Items restored:              34

Started:    2023-03-29 11:12:21 +0800 CST
Completed:  2023-03-29 11:13:21 +0800 CST

Warnings:
  Velero:     <none>
  Cluster:  could not restore, CustomResourceDefinition "ciliumendpoints.cilium.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, CustomResourceDefinition "ciliumidentities.cilium.io" already exists. Warning: the in-cluster version is different than the backed-up version.
  Namespaces: <none>

Errors:
  Velero:   pod volume restore failed: error running restore err=exit status 1: exit status 1
  Cluster:    <none>
  Namespaces: <none>

Backup:  nginx-backup

Namespaces:
  Included:  all namespaces found in the backup
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io, csinodes.storage.k8s.io, volumeattachments.storage.k8s.io, backuprepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

restic Restores:
  Failed:
    nginx-example/web-2: www

Existing Resource Policy:   <none>

Preserve Service NodePorts:  auto

```
**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- root@cluster2-147:~# velero version
Client:
	Version: v1.10.2-rc.2
	Git commit: 7416504e3a8fea40f78bbc4cfefc7c642aafc812
Server:
	Version: v1.10.2-rc.2
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- root@cluster2-147:~# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by 13567436138** [comment] 2023-03-31 07:52
yeah,why,why can not find file

**Comment by Lyndon-Li** [comment] 2023-04-06 02:43
The "Not Found" logs in restore-wait init-container indicates that the restore was not completed normally.
From the log, looks like you are using Restic path for file system backup and the Restic command didn't complete normally, its exit code is 1.
This may indicate the Restic process was crashed or killed by kubernetes.

Therefore, to find the cause, please monitor Velero node-agent pod and use `kubectl get event` to check the pod status immediately after the problem is reproduced.

**Comment by pavlovnicola** [comment] 2023-04-10 18:14
Facing exactly same issue. Getting "Not found" while trying to restore.
Backup completed successfully. At least this is what "velero get backup" and "kubectl get backup/jenkins-master-backup-01 -n velero -o yaml" indicate.

Client:
        Version: v1.10.2
Server:
        Version: v1.10.2

Commands used:
# Backup on Cluster A
velero backup create jenkins-master-backup-01 --default-volumes-to-fs-backup=true --include-namespaces jenkins-master
# Restore on Cluster B
velero restore create --from-backup jenkins-master-backup-01 --restore-volumes=true

I used HELM to install velero with a custom values.yaml file. I used a compatible S3 bucket (vast) for the storage. I pasted the contents of values.yaml here: https://pastebin.com/ZHmVpTz1

I would appreciate any help.
Nicola.

**Comment by Lyndon-Li** [comment] 2023-04-11 01:35
@pavlovnicola Could you share below info, so that we can further troubleshoot:
1. Velero log bundle for the problematic restore
2. run `kubectl get podvolumerestore -n velero -o yaml` and share the entire output

**Comment by pavlovnicola** [comment] 2023-04-11 06:35
@Lyndon-Li 

Here are the files requested:
[k-podvolumerestore.yml.txt](https://github.com/vmware-tanzu/velero/files/11197337/k-podvolumerestore.yml.txt)
[velero-restore-logs.txt](https://github.com/vmware-tanzu/velero/files/11197338/velero-restore-logs.txt)

_Note: I have deleted the namespace and tried again the restore but this time I increased the "fs-backup-timeout" to 8 hours instead of 4 and I still get the same results (exit status 1)_

Thanks in advance.

**Comment by Lyndon-Li** [comment] 2023-04-11 06:53
@pavlovnicola 
I see the PVB got the error in 3 hours after it started, it matches the case that restic process was killed. So please also try to increase the memory limit of node-agent pod and see if the problem could be solved:

```
    completionTimestamp: "2023-04-11T00:27:40Z"
    message: 'error running restore err=exit status 1: exit status 1'
    phase: Failedreturn
    startTimestamp: "2023-04-10T21:23:28Z"
```

**Comment by pavlovnicola** [comment] 2023-04-11 18:45
@Lyndon-Li 
I increased the limits on the velero pod as well as on the node agents to 8Gb. I added debug level as well.
Still getting same error.
[k-podvolumerestore.yml.txt](https://github.com/vmware-tanzu/velero/files/11203744/k-podvolumerestore.yml.txt)
[velero-restore-logs-debug.txt](https://github.com/vmware-tanzu/velero/files/11203745/velero-restore-logs-debug.txt)

I could not catch the events :( . But I was tailing the logs from the node-agent:

I was getting a lot of jenkins jobs related errors (since I am migrating Jenkins here):

`UtimesNano: no such file or directory\nignoring error for /jobs/INFRA/jobs/validation/builds/240/build.xml: UtimesNano: no such file or directory\nignoring error for /jobs/INFRA/jobs/validation/builds/240/injectedEnvVars.txt: UtimesNano: no such file or directory\nignoring error for /jobs/INFRA/jobs/validation/builds/240/log: UtimesNano: no such file or directory\nFatal: There were 125379 errors\n\n" PodVolumeRestore=velero/jenkins-master-backup-01-20230411132654-2xfn9 controller=PodVolumeRestore logSource="pkg/uploader/provider/restic.go:184" pod=jenkins-master/jenkins-master-deployment-6bf44f9b75-rls59 restore=velero/jenkins-master-backup-01-20230411132654 snapshotID=a5f1a35b volumePath="/host_pods/a5922406-3c9d-4fd7-a9a1-268946273abe/volumes/kubernetes.io~csi/pvc-b1d4b528-0a44-4847-bf75-6d4de74ba4b4/mount"`

Here are the last few log lines from tailing the node-agent:

[node-agent-logs.txt](https://github.com/vmware-tanzu/velero/files/11203824/node-agent-logs.txt)

**Comment by Lyndon-Li** [comment] 2023-04-12 02:21
`UtimesNano: no such file or directory\nignoring error for /jobs/INFRA/jobs/validation/builds/240/build.xml: UtimesNano: no such file or directory\nignoring error for /jobs/INFRA/jobs/validation/builds/240/injectedEnvVars.txt: UtimesNano: no such file or directory\nignoring error for /jobs/INFRA/jobs/validation/builds/240/log: UtimesNano: no such file or directory\nFatal: There were 125379 errors\n\n" `

The above error that is generated by Restic is the direct cause of the problem. Once the error happens, Velero regards the Restic backup command fails, so make the restore as paritiallyFailed.

Why the error happened for Restic?
Velero runs the Restic backup against the live file system of the PV, there is no snapshot, if the file system changes frequently, it is possible that Restic sees a file during its scan, but cannot find the same file when it wants to back it up.

This problem cannot be solved for file system backup because of its lack of snapshot. In future, Velero will have the snapshot data movement feature, through which, the problem will be solved.

**Comment by pavlovnicola** [comment] 2023-04-13 06:35
@Lyndon-Li 
Thank you for taking time to elaborate on this.

To sum up: this specific problem is related to (restic) backing up a live system. While Velero regards the backup as completed, it fails during restore because of those errors. This issue will be solved in a future release.

Is there an estimation?

**Comment by Lyndon-Li** [comment] 2023-04-13 06:44
@pavlovnicola 
If the storage backs your PV supports CSI and CSI snapshot and you want to back up the PV data to the object store, this case will be supported in Velero v1.12.
If the storage doesn't support CSI snapshot, we need to see if your case is in our radar or not, so please share more info of what is your kubernetes environment is like.

**Comment by pavlovnicola** [comment] 2023-04-13 06:55
@Lyndon-Li 
I would like to migrate an existing K8S cluster with a storage class "kubernetes.io/vsphere-volume" (non-CSI) into a newer cluster that is CSI-enabled (csi.vastdata.com)

**Comment by Lyndon-Li** [comment] 2023-04-13 09:21
@pavlovnicola 
Could you share me more info of your use case? Specifically, some questions as below:
1. Is your source cluster a TKG cluster or a vanilla cluster built on vSphere?
2. What is your target cluster like? Is it a cluster out of vSphere and use vast data as the backend storage?

**Comment by Lyndon-Li** [comment] 2023-06-13 06:20
To sum up, multiple problems have been discussed in this issue:
1. Restic restore command killed/crashed which results in a failed Velero restore. Most probably, restic command was killed due to OOM
2. Restic restore command returns error because the known inconsistent data state of PVB
3. Data movement on non-CSI volumes is requested, but the scenario of why the non-CSI volumes are used is not clear

**Comment by Lyndon-Li** [comment] 2023-06-13 06:22
Closing as there is no further request, feel free to reopen it if necessary.

**Closed by Lyndon-Li** 2023-06-13 06:22 UTC
Labels: Needs info, area/fs-backup

**Comment by rshiva777** [comment] 2023-07-27 05:01
@Lyndon-Li ,

I am facing the same error when i try to restore the namespace having pvc (EFS Storage class). Restore is **PartiallyFailed**

<img width="616" alt="image" src="https://github.com/vmware-tanzu/velero/assets/42074614/ee43ad09-91c1-4ee1-ba05-98f13c918e04">


When i am taking a backup, there is no read/write operations on the PVC, and backup is succesful. But during the restoration itself getting the below error



`time="2023-07-27T04:54:08Z" level=error msg="Velero restore error: pod volume restore failed: error running restore err=exit status 1: exit status 1" logSource="pkg/controller/restore_controller.go:491" restore=velero/newnginx-20230727045358`

**Comment by rshiva777** [comment] 2023-07-27 05:08
I am using velero **v1.11.0**, still the issue persists

**Comment by piyushjain1804** [comment] 2023-09-11 15:10
> kubectl get event -n velero

I was also failing this issue and when i deleted the hanging pod then pod comes backup and i see data is also restored. 
Did you do anything to resolve the issue completely. ?

**Comment by piyushjain1804** [comment] 2023-09-11 15:11
> > kubectl get event -n velero
> 
> I was also failing this issue and when i deleted the hanging pod then pod comes backup and i see data is also restored. Did you do anything to resolve the issue completely. ?
@pavlovnicola
