### ISSUE TITLE
velero hooks doesn't support different yaml quotings

### ISSUE THREAD

**Issue by ThomasSteinbach** [vmware-tanzu/velero#4718] opened 2022-03-04 00:51 UTC
**What steps did you take and what happened:**

Velero allows hook commands to be defined as annotations: https://velero.io/docs/v1.6/backup-hooks/#annotations

For the hook command definition Velero only allows one style of quotings: Outer single quotes with inner double quotes like in the official example:

```
 post.hook.backup.velero.io/command: '["/bin/fsfreeze", "--unfreeze", "/bitnami/postgresql"]'
```

However YAML syntax allows different quoting styles, which aren't processed properly by Velero:

```
 post.hook.backup.velero.io/command: "['/bin/fsfreeze', '--unfreeze', '/bitnami/postgresql']"
 post.hook.backup.velero.io/command: '[''/bin/fsfreeze'', ''--unfreeze'', ''/bitnami/postgresql'']'
```

When generating/processing Kubernetes manifests with tools like cdk8s or FluxCD you can't control the quoting style. If the quoting style differs from the first one, Velero will fail with following error:

```
time="2022-03-03T23:38:55Z" level=error msg="Error executing hook" backup=velero/wikijs-veleroschedule-c8bf5aa0-20220303233853 error="Internal error occurred: error executing command in container: failed to exec in container: failed to start exec \"d92bcbf75217abf53924d9cb01c2b8dbe4ba795f7123eaabce1e41f0b1d571c5\": OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: \"['/bin/fsfreeze', '--freeze', '/mnt/data']\": stat ['/bin/fsfreeze', '--freeze', '/mnt/data']: no such file or directory: unknown" hookPhase=pre hookSource=annotation hookType=exec logSource="internal/hook/item_hook_handler.go:206" name=wikijs-postgresql-0 namespace=wikijs resource=pods
```

**What did you expect to happen:**

Velero hooks should work with any valid YAML quoting style.

**Environment:**

- Velero version (use `velero version`): 1.7.0
- Velero features (use `velero client config get features`): -
- Kubernetes version (use `kubectl version`): 1.22

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment] 2022-03-04 08:15
I think this is probably expected because single quote is not accepted for JSON.

according to 
https://www.json.org/json-en.html
```
A value can be a string in double quotes, or a number, or true or false or null, or an object or an array. These structures can be nested.
```

**Comment by ThomasSteinbach** [comment] 2022-03-04 16:52
@reasonerjt I wrote about Kubernetes manifests written in YAML and **not** JSON.

**Comment by ThomasSteinbach** [comment] 2022-03-04 17:03
### For anyone intrested about a workaround

If you use https://cdk8s.io/ or another generator for your Kubernetes manifests, who prefers to wrap strings into double quotes, you can use following shell command as post processor to toggle double quotes to single quotes and vice versa:

```
find ./dist -type f -name "*.yaml" -exec sed -i '' "/backup.velero.io\/command/y/'\"/\"'/" {} \;
```

This command processes every YAML file in the `./dist` subdirectory and toggles quotes only for lines containing `backup.velero.io`.

An example:

```
# before (what cdk8s will output):
grep "post.hook" ./dist/deployment.yaml
$ post.hook.backup.velero.io/command: "['/bin/fsfreeze', '--unfreeze', '/bitnami/postgresql']"

# toggle quotes
$ find ./dist -type f -name "*.yaml" -exec sed -i '' "/backup.velero.io\/command/y/'\"/\"'/" {} \;

# after (what velero will expect):
$ grep "post.hook" ./dist/deployment.yaml
post.hook.backup.velero.io/command: '["/bin/fsfreeze", "--unfreeze", "/bitnami/postgresql"]'
```

**Comment by reasonerjt** [comment] 2022-03-06 13:26
@ThomasSteinbach 
Thanks for providing the workaround.  
I'm closing this issue as the cause is clear and no further work is needed.
Let me know if we need to re-open this one.

**Comment by ThomasSteinbach** [comment] 2022-03-13 22:46
@reasonerjt yes, please re-open the issue. Further work (a bugfix) is required, because (in my opinion) the bug still persists.

In your first comment you said:

>  single quote is not accepted for JSON

I did not reacted on that comment, because I didn't understand why you referred to JSON documents. And that is beause declarative Kubernetes manifests typically written as YAML documents. For the case of the bug let me refer to the official Velero example of how to define backup hooks in the following YAML document:

https://github.com/vmware-tanzu/velero/blob/v1.6.0/examples/nginx-app/with-pv.yaml#L57

In YAML you also could write that line with following quoting:

```
pre.hook.backup.velero.io/command: "['/sbin/fsfreeze', '--freeze', '/var/log/nginx']"
# or
pre.hook.backup.velero.io/command: '['''/sbin/fsfreeze''', '''--freeze''', '''/var/log/nginx''']'
```

The bug in Velero is, that the backup hook didn't work with either of the two YAML quoting alternatives.

**Comment by reasonerjt** [comment] 2022-03-14 06:51
@ThomasSteinbach 

My point is in the official doc, the value of the field is a valid JSON:
`["/sbin/fsfreeze", "--freeze", "/var/log/nginx"]`
But as for the example you provided, although the quoting is valid in YAML, the  following value is NOT a valid JSON:
`['/sbin/fsfreeze', '--freeze', '/var/log/nginx']`

That's why I think we don't need to fix it in velero.

**Comment by ThomasSteinbach** [comment] 2022-03-14 07:57
Thanks @reasonerjt for your clarification. Now I understand that you mean just the value string after the annotation key must be a parsable JSON list.

The problem is, that the annotation value is still a YAML string and not a JSON string. YAML has it's own rules of which quoting type is used outside/inside and how to represent quotes in quotes. The user doesn't necessarily have control about the quoting style, as tools generating/processing the YAML document, may change quoting to any valid YAML quoting style.

That means enforcing the quoting of the annotation value before passing it to a JSON processor can only be performed at the point, where Velero reads in/parses the Kubernetes YAML manifest. So at some point in the code Velero will read the Kubernetes manifest. At this point Velero will need to ensure the proper JSON style of the backup hook annotation value, before passing it to the JSON logic.

**Comment by reasonerjt** [comment] 2022-03-14 09:09
@ThomasSteinbach 
Thanks for the reply, but I'm not convinced.

Do you mean you pass a string of valid JSON array like: `["element1", "element2"]` to a YAML tool, and the tool will transform it to `['element1', 'element2']`?  If that's the case, this is definitely a bug of the YAML tool, it should treat the JSON string as a whole and should NEVER try to change the quote chars inside the string.

I don't think it's velero's responsibility to parse a malformed JSON, instead, the user or the tool to generate the YAML, should make sure the value of the annotation is valid.

**Comment by ThomasSteinbach** [comment] 2022-03-14 16:43
Hi @reasonerjt ,

one last argument. If that didn't convince you, you can close this issue and I accept the behavior as my personal problem :)

I looked into the Velero code and identified, how the hook annotation is parsed:
https://github.com/vmware-tanzu/velero/blob/v1.8.0/internal/hook/item_hook_handler.go#L302

I mentioned that there the YAML string you get from a Kubernetes pod is "unmarshalled" with a JSON parser and not with a YAML parser. I think this is the issue. You simply cannot assume, that the value of the Kubernetes annotation can be "unmarshalled" with the JSON parser, while it's a (valid) YAML string.

For instance another valid quoting style of YAML would be:

```
pre.hook.backup.velero.io/command: "[\"/bin/sh\", \"-c\", \"/bin/fsfreeze --freeze /mnt/data\"]"
```

Velero currently would parse the string `[\"/bin/sh\", \"-c\", \"/bin/fsfreeze --freeze /mnt/data\"]` as JSON, what might not be correct.

To ensure the velero hook command is correctly parsed, the "JSON" list can either be parsed with a YAML parser.

Or the value must be encoded as Base64 string, such that any YAML processor did not modify the quoting style, and is decoded before putting it into the JSON parser. This approach is obviously not handy.

Does that sound reasonable?

Thanks so far for the discussion.

**Comment by reasonerjt** [comment] 2022-03-15 04:07
@ThomasSteinbach 
I feel there's still a misunderstanding.

Did you see any issues when setting the annotation like this?
```
pre.hook.backup.velero.io/command: "[\"/bin/sh\", \"-c\", \"/bin/fsfreeze --freeze /mnt/data\"]"
```
I tested in my env and I didn't see any issue

**Comment by reasonerjt** [comment] 2022-03-16 06:45
Thanks!

**Closed by reasonerjt** 2022-03-16 06:45 UTC

**Comment by Trashmee** [comment] 2022-11-16 13:25
@ThomasSteinbach, @reasonerjt: I could use some help looking in the right direction here:

This is what I would my velero hook to do - as you can see its working fine within the postgres container. Be aware that `'label'` seems to be mandatory, `"label"` will return an error.
```
1000740000@postgres-db-7964bf6c77-6mlrl:/$ /usr/bin/psql postgresql://postgres:postgres@postgres.as-postgres:5432/postgres -c "SELECT pg_start_backup('label', FALSE, FALSE);"
 pg_start_backup
-----------------
 0/C000028
(1 row) 
```

I've tried a lot of different permutations, most of which are not accepted by `oc annotate`. The ones that are fail in velero, this issue here reported by @reasonerjt seems to explain to me why. 


```
oc annotate pod -l app=postgres -n as-postgres  \
    pre.hook.backup.velero.io/command='["/usr/bin/psql", "postgresql://postgres:postgres@postgres.as-postgres:5432/postgres", "-c", "\"SELECT pg_start_backup(\'label\', FALSE, FALSE);\""]'
```

```
oc annotate pod -l app=postgres -n as-postgres  \
    pre.hook.backup.velero.io/command='["/usr/bin/psql", "postgresql://postgres:postgres@postgres.as-postgres:5432/postgres", "-c", "\"SELECT pg_start_backup('\''label'\'', FALSE, FALSE);\""]'
```

```
oc annotate pod -l app=postgres -n as-postgres  \
    post.hook.backup.velero.io/command: "[\"/usr/bin/psql\", \"postgresql://postgres:postgres@postgres.as-postgres:5432/postgres\", \"-c\", \"\\\"SELECT pg_stop_backup(FALSE)\\\"\"]"
``` 

The most promising was the one that ended up like this in `pod describe`
```
    pre.hook.backup.velero.io/command: '["/usr/bin/psql", "postgresql://postgres:postgres@postgres.as-postgres:5432/postgres",
      "-c", "SELECT pg_start_backup(''label'', FALSE, FALSE);"]'
```
However, in velero the same failed with 
```
Error executing hook" backup=baas/sppbackup-k8s-effebb10-6705-4326-bd40-d9628a359a22 error="command terminated with exit code 1" hookPhase=pre hookSource=annotation hookType=exec logSource="internal/hook/item_hook_handler.go:206" name=postgres-db-7964bf6c77-6mlrl 
```
The command looked kind of okish to me?
```
Exec PreHook Cmd:
/usr/bin/psql postgresql://postgres:postgres@postgres.as-postgres:5432/postgres -c "SELECT pg_start_backup('label', FALSE, FALSE);"
```

Thanks for any kind of idea,
Alex
