### ISSUE TITLE
Cannot use snapshot to backup volumes if specifying "--default-volumes-to-fs-backup" during the installation

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#5533] opened 2022-11-02 07:09 UTC
I install Velero with `--default-volumes-to-fs-backup` option and create a backup with the following command:
`velero backup create test-03 --include-namespaces default --snapshot-volumes --wait`

No snapshot is taken for the volume, the volume is backed up by Restic instead:
```
velero backup describe test-03
Name:         test-03
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.24.6
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=24

Phase:  Completed

Errors:    0
Warnings:  0

Namespaces:
  Included:  default
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  true

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2022-11-02 15:03:13 +0800 CST
Completed:  2022-11-02 15:03:16 +0800 CST

Expiration:  2022-12-02 15:03:13 +0800 CST

Total items to be backed up:  22
Items backed up:              22

Velero-Native Snapshots: <none included>

Restic Backups (specify --details for more information):
  Completed:  1
```

```
kubectl -n velero get backup test-03 -o yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    velero.io/source-cluster-k8s-gitversion: v1.24.6
    velero.io/source-cluster-k8s-major-version: "1"
    velero.io/source-cluster-k8s-minor-version: "24"
  creationTimestamp: "2022-11-02T07:03:13Z"
  generation: 5
  labels:
    velero.io/storage-location: default
  name: test-03
  namespace: velero
  resourceVersion: "2175146"
  uid: 83876b02-80a0-4c37-b622-224fc0aa42ee
spec:
  csiSnapshotTimeout: 10m0s
  defaultVolumesToFsBackup: true
  hooks: {}
  includedNamespaces:
  - default
  metadata: {}
  snapshotVolumes: true
  storageLocation: default
  ttl: 720h0m0s
  volumeSnapshotLocations:
  - default
status:
  completionTimestamp: "2022-11-02T07:03:16Z"
  expiration: "2022-12-02T07:03:13Z"
  formatVersion: 1.1.0
  phase: Completed
  progress:
    itemsBackedUp: 22
    totalItems: 22
  startTimestamp: "2022-11-02T07:03:13Z"
  version: 1
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment] 2022-11-02 10:49
Test with v1.9 and the result is the same.

This looks like to be the expected behavior. The logics are as following:
1. If `default-volumes-to-fs-backup` is set, it means that all volume will be handled by pod volume backup by default
2. Users can set exceptions per volumes by the `backup.velero.io/backup-volumes-excludes` annotation
3. If any volume is excluded by the annotation, Velero falls back on the volume snapshot

Therefore, if default-volumes-to-fs-backup is set and users want to have some volumes backed up by volume snapshot, they should specify the volumes to the `backup.velero.io/backup-volumes-excludes` annotation

**Comment by Lyndon-Li** [comment] 2022-11-02 10:50
Closing this issue since it is the expected behavior.

**Closed** 2022-11-02 10:50 UTC
Labels: Bug
