### ISSUE TITLE
UnauthorizedOperation when attempting snapshot of PV

### ISSUE THREAD

**Issue by geoff-bleakley** [vmware-tanzu/velero#2998] opened 2020-10-09 21:07 UTC
**What steps did you take and what happened:**
Installed velero with AWS plugin and testing namespace backup
  velero backup create <name> --include-namespaces <nsname>
 all namespace resources were backed up to S3, but the PVs (3) did not have snapshots taken.
Error (from log): 

time="2020-10-09T16:03:50Z" level=info msg="Snapshotting persistent volume" backup=velero/vernemq22 logSource="pkg/backup/item_backupper.go:477" name=pvc-2e9fecc0-xxxxxxxxxxx namespace= persistentVolume=pvc-2e9fecc0-9a2c-4af7-9c98-xxxxxxxxxxx resource=persistentvolumes volumeID=vol-05290xxxxxxxxxx
time="2020-10-09T16:03:50Z" level=info msg="1 errors encountered backup up item" backup=velero/vernemq22 logSource="pkg/backup/backup.go:444" name=vernemq-0
time="2020-10-09T16:03:50Z" level=error msg="Error backing up item" backup=velero/vernemq22 error="error taking snapshot of volume: rpc error: code = Unknown desc = UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message

Total items to be backed up:  46
Items backed up:              46

Velero-Native Snapshots:  0 of 3 snapshots completed successfully (specify --details for more information)

**What did you expect to happen?**
PV snapshots taken for 3 PVs.

After the error, I attempted a create-snapshot using the velero AWS credentials and AWSCLI.  A snapshot was created, so I suspect velero. 

**environment:**
kubectl version
client: 1.18
server: 1.18
rancher: 2.4.8
velero:
client: 1.5.1

The velero service account has 'cluster-admin' role.

kubectl describe ClusterRoleBinding velero
Name:         velero
Labels:       component=velero
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  cluster-admin
Subjects:
  Kind            Name    Namespace
  ----            ----    ---------
  ServiceAccount  velero  velero

**Install notes:**
used Helm (keys)

helm install vmware-tanzu/velero --namespace velero \
--set credentials.existingSecret=xxxx-xxxxxxx \
--set configuration.provider=aws \
--set configuration.backupStorageLocation.bucket=xxxxxx \
--set configuration.backupStorageLocation.config.region=xxxxxx \
--set configuration.volumeSnapshotLocation.config.region=xxxxxx \
--set snapshotsEnabled=true \
--set image.repository=velero/velero \
--set image.tag=v1.4.0 \
--set image.pullPolicy=IfNotPresent \
--set initContainers[0].name=velero-plugin-for-aws \
--set initContainers[0].image=velero/velero-plugin-for-aws:v1.1.0 \
--set initContainers[0].volumeMounts[0].mountPath=/target \
--set initContainers[0].volumeMounts[0].name=plugins \
--set nodeSelector.storage=server
--generate-name

Thanks for your assistance.

**Comment by dsu-igeek** [comment] 2020-10-09 22:06
Would you double check the Velero IAM user for all of the permissions listed in the Velero Plugin for AWS README (https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/main/README.md)?  The code that calls the snapshot is pretty simple, however it does create a tag as part of the snapshot, so I'm thinking perhaps you don't have the ec2:CreateTags permission which you wouldn't hit if you just took a snapshot from the CLI without a tag.

**Comment by geoff-bleakley** [comment] 2020-10-12 13:17
Thanks for the reply.  Here is the policy:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeVolumes",
                "ec2:DescribeSnapshots",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:CreateSnapshot",
                "ec2:DeleteSnapshot"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:PutObject",
                "s3:AbortMultipartUpload",
                "s3:ListMultipartUploadParts"
            ],
            "Resource": [
                "arn:aws:s3:::XXX-velero-kubernetes/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::XXX-velero-kubernetes"
            ]
        }
    ]
}

I executed a second create-snapshot from AWSCLI with a tag spec and it was successful.  Other thoughts please?

**Comment by geoff-bleakley** [comment] 2020-10-15 16:49
Hello, i read through volume-snapshotter.go, is that the correct logic?  I notice that our snapshots get a defined set of tags regardless of whether I indicate a snapshot-specific tag.  Is it possible the permission issue is with getting the other tags?

**Comment by geoff-bleakley** [comment] 2020-10-16 14:39
Hello,
I have discovered that the IAM permissions applied to the K8s-rancher worker node role are used for the velero create snapshot.  It appears that the permissions used during velero install are ignored, is that behavior expected?

**Comment by dsu-igeek** [comment] 2020-10-20 06:51
Well, that's not the intended behavior.  We may not be getting what we expect to happen from the AWS SDK, though.  I will investigate the session profile behavior a bit.

**Comment by dsu-igeek** [comment] 2020-10-22 03:47
According to the SDK docs (https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html "Specifying Credentials section) the SDK falls through to using the EC2 instance's IAM role when everything else has failed.  I'm thinking the SDK is running into a problem reading the shared credentials file.  Please upload the full logs (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`

Thanks!

**Comment by geoff-bleakley** [comment] 2020-10-22 13:00
uploaded, thanks.

[backup.log](https://github.com/vmware-tanzu/velero/files/5422941/backup.log)

[deployment.log](https://github.com/vmware-tanzu/velero/files/5422947/deployment.log)
[descBackup.log](https://github.com/vmware-tanzu/velero/files/5422950/descBackup.log)

**Comment by ashish-amarnath** [comment] 2020-10-28 00:47
@geoff-bleakley Looking at the error in the log file, the IAM user that is used by Velero clearly doesn't have permissions to take volumesnapshots.

```
time="2020-10-06T19:53:11Z" level=error msg="Error backing up item" backup=velero/api-infr-backup error="error taking snapshot of volume: rpc error: code = Unknown desc = UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: ZQblDKCEk1uZbAJGYb5ebqX466lwyR8cH_me_BfL0Hcrheol0h38UU1yw3L_O9s6qnOBPvq0IMml0vdN3e9J6s06zxlEIPHSA_W3aO1znkdlMFG-Wv522Pot5bf-CnWhBVYGVHEjVzGfJZa0HYkhQyz_gZgqFwc2oQvBUfn2MwvFJAsPwRGSYYS4nG_diummZW6n7Ekqi-gBu_j1kQYhG4J2Si0XLcAlEDNRqh4ia6LU6toUml0y78oO2Orw9U4iRiIqTEDw9K-XPb6It2Un2AmU_xx6g2BDL4MbSQ_I2WtSbNHcbsGCRbR4MzCerhIA8yAh9o3CPyYz4sz8uDIWP1A4B_8hFducvubV9Fk4FZNXTt5yFXTJHGi048mphrDx00nnsuju0EkUJYjADV7xZ4GMihbNo4uOEWa5itIwRs-Ad48uDIjtG4ZlPqHD_KoXWUF_hUFLZuS7Ql6LGqAvHF4AFgN4rlgDijyZkhlopBjzS3ZAnTmmkjO0tFxt0DCotYO3foHfXhSDm9O9yWha0-ByQljAIE5V-ujhf31cmiw1PhbVn0m4GAkBzk9sablksCMQG0pQmvBWR0RC74rh3OTs1qo7FQ\n\tstatus code: 403, request id: 390dcd82-30d0-4d47-9c0b-0814000e39b6" logSource="pkg/backup/backup.go:448" name=kong-db-0
```

Here is the IAM policy that I use for my dev work on Velero and I can confirm that I can use this to take snapshots of EBS volumes.

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeVolumes",
                "ec2:DescribeSnapshots",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:CreateSnapshot",
                "ec2:DeleteSnapshot"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:PutObject",
                "s3:AbortMultipartUpload",
                "s3:ListMultipartUploadParts"
            ],
            "Resource": [
                "arn:aws:s3:::<BACKUP_STORAGE_LOCATION_BUCKET>/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::<BACKUP_STORAGE_LOCATION_BUCKET>"
            ]
        }
    ]
}
```

I see that in your policy JSON for ec2 permissions you have 
```
"Resource": ""
```
and in the policy JSON that works for me it is set to 
```
            "Resource": "*"
```
This is also the same on our documentation at https://github.com/vmware-tanzu/velero-plugin-for-aws

Can you please update your IAM policy and try this again?
Also suggest confirming that the credentials supplied to Velero are for the correct IAM user.

**Comment by geoff-bleakley** [comment] 2020-10-28 14:01
Thanks for the reply.  The resource entry has been updated to "*".  Here is the rest of my config:
The namespace has a secret containing the key and the secret key.  Does it need the velero user as well?  I assumed that since the objects were saved to s3, the credentials were being used.

**Comment by dsu-igeek** [comment] 2020-11-11 07:54
The secret only needs the AWS info.  Mine looks like this:

---
[default]
aws_access_key_id = <key>
aws_secret_access_key = <secret>
---

I didn't see any errors around the credentials in the logs.  My working theory is that the SDK has silently fallen back to the EC2 instance's IAM role, based on your earlier note.  Does the IAM role for the node allow it access to the S3 bucket?  If not, that would send us in a different direction.

I'd like to double-check the credential that is present in the pod.

FInd the velero pod in the velero namespace (it will be pod/velero-<something>)

Use kubectl describe on it, like this: kubectl describe pod -n velero pod/velero-64d549ffc9-kw2bd

In the output there should be a line like this:

      AWS_SHARED_CREDENTIALS_FILE:     /credentials/cloud

That tells us the path for the credential file.  Dump the credential file and make sure it's present and has the correct stuff in it

kubectl exec -it -n velero velero-64d549ffc9-kw2bd -- cat /credentials/cloud

Double-check the key and secret there and make sure it's correct.
Let us know what the path is that it was looking at.

**Comment by geoff-bleakley** [comment] 2020-11-11 16:50
Thanks for the reply.
Yes, the node's permissions allow S3 GET, PUT, DELETE  
Here is the kubectl output:  AWS_SHARED_CREDENTIALS_FILE:  /credentials/cloud

kubectl exec -it -n velero pod/velero-6c56dd9c45-4cqzs -- cat /credentials/cloud
cat: /credentials/cloud: No such file or directory
command terminated with exit code 1

As I mentioned above in the helm install, i used the set credentials.existingSecret=cloud-credentials.  I thought this would reference the existing secret in rancher, which has the access key and secret access key.  Is it possible when I run a backup from a velero client, the credentials aren't getting found/used?

**Comment by dsu-igeek** [comment] 2020-11-11 17:13
The Velero server is setting the credential profile to point to /credentials/cloud and that file/volume path isn't available in the pod.  The AWS SDK is then silently falling back to the EC2 instance's credentials.

Let's check the secrets you have available in the namespace:

kubectl get secrets -n velero

My AWS setup shows:

NAME                        TYPE                                  DATA   AGE
cloud-credentials           Opaque                                1      4d8h
default-token-797fw         kubernetes.io/service-account-token   3      4d8h
velero-restic-credentials   Opaque                                1      4d8h
velero-token-dkwsn          kubernetes.io/service-account-token   3      4d8h

The secret probably isn't there, we can look at how to create it or reinstall correctly with the helm chart.

**Comment by geoff-bleakley** [comment] 2020-11-11 17:40
Sure.

 kubectl get secrets -n velero
NAME                           TYPE                                  DATA   AGE
cloud-credentials              Opaque                                2      32d
default-token-sg95n            kubernetes.io/service-account-token   3      42d
jfrog                          kubernetes.io/dockerconfigjson        1      42d
sh.helm.release.v1.velero.v1   helm.sh/release.v1                    1      40d
velero-restic-credentials      Opaque                                1      40d
velero-server-token-fmvkq      kubernetes.io/service-account-token   3      40d

**Comment by dsu-igeek** [comment] 2020-11-12 20:00
OK, the secret is present but it's not mounted into the pod even though the environment variables got set to point to it.  Let's see if we can figure out where that is broken.  When I describe my Velero pod in AWS I get:

`kubectl describe -n velero pod/velero-64d549ffc9-659mq `

...
`    Mounts:
      /credentials from cloud-credentials (rw)
`
...
`Volumes:`
...
`  cloud-credentials:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cloud-credentials
    Optional:    false
`

Would you check yours and see if those things have been populated?

**Comment by geoff-bleakley** [comment] 2020-11-13 16:17
sure, here are my results:
kubectl describe -n velero pod/velero-6c56dd9c45-4cqzs
...
mounts: /credentials from cloud-credentials (rw)
...
volumes:
cloud-credentials:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cloud-credentials
    Optional:    false

**Comment by dsu-igeek** [comment] 2020-11-16 23:41
It looks like everything is configured correctly and there's some issue in K8S or Rancher which is preventing the mount of that credential.  You're going to need to debug your pod/worker nodes and figure out why they're not mounting that secret properly.  I'm going to close this for now, please re-open it if you can get the secret to mount and you're still having trouble.

**Closed by dsu-igeek** 2020-11-16 23:41 UTC
Labels: Cloud/AWS, Info Received, Needs investigation
