### ISSUE TITLE
Is there a way we can perform PVC backup without annotating the POD 

### ISSUE THREAD

**Issue by MadhuMahalingappa** [vmware-tanzu/velero#2743] opened 2020-07-22 04:57 UTC
**Describe the problem/challenge you have**
We are trying to backup the PVC in a namespace and performing annotation of POD is looking cumbersome since there are multiple pods running in namespace with different volume attached . Is there a way we can take backup of entire namespace along with PVC.

**Describe the solution you'd like**
Single command to take backup of namespace along with PVC instead of performing annotation.

**Environment:**

- Velero version (use `velero version`): Version: v1.4.0

- Kubernetes version (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2+45a4ac4", GitCommit:"45a4ac4", GitTreeState:"clean", BuildDate:"2020-06-29T06:31:08Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
- Cloud provider or hardware configuration: VMware 
- OS (e.g. from `/etc/os-release`): Linux Core OS

**Comment by nrb** [comment] 2020-07-22 17:44
I'm assuming you're running with restic, as using a VolumeSnapshotter plugin does not require any annotation.

In v1.5.0, our next release, there will be a new option to backup all attached PVs with restic automatically rather than individually via annotation. We are hoping to have this released in late August or early September.

I'm going to close this issue as a duplicate of #1871, but let me know if this isn't want you were looking for.

**Closed by nrb** 2020-07-22 17:44 UTC
Labels: Duplicate, Restic

**Comment by MadhuMahalingappa** [comment] 2020-07-23 13:00
@nrb    Thank you very much for the update ,Can you please help me with any reference documentation for using VolumeSnapshotter plugin to take PVC backup .

**Comment by ashish-amarnath** [comment] 2020-08-04 18:51
You can find all of our docs at https://velero.io. PTAL!
