### ISSUE TITLE
velero make full snapshot of azure managed disk everytime

### ISSUE THREAD

**Issue by NickSu86** [vmware-tanzu/velero#2446] opened 2020-04-20 08:29 UTC
I have created a schedule job and the deployments, configmap, services work quite good, but I found the pv snapshot is already in full backup not incremental, as some of our PV is TB large, and we need to back it up every day, which consumes us very large space for backup.

**What did you expect to happen:**
The volume snapshot could be incremental rather than full backup every time

**Environment:**

- Velero version (use `velero version`): 1.3.2
- Velero features (use `velero client config get features`):  features: <NOT SET>
- Kubernetes version (use `kubectl version`): Openshift v3.11
- Kubernetes installer & version: 
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): Redhat

**Comment by skriss** [comment] 2020-04-20 14:13
hey @NickSu86 we already have an open feature request in the Azure plugin repo for this - see https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/issues/25. I'm going to close this issue out as a duplicate, but please follow along there.

**Closed** 2020-04-21 14:39 UTC
Labels: Duplicate

**Comment by antonmatsiuk** [comment] 2021-03-29 07:28
@skriss could you check the status of this? Azure plugin issue tracker doesn't exist any more, and it seems like the problem is still not solved

**Comment by smmaster** [comment] 2022-03-19 08:47
Any update regarding this feature?
