### ISSUE TITLE
Restic not working with AWS IAM-backed service accounts

### ISSUE THREAD

**Issue by hibbert** [vmware-tanzu/velero#2457] opened 2020-04-24 20:43 UTC
**What steps did you take and what happened:**

Have set this up taking into account https://github.com/vmware-tanzu/velero-plugin-for-aws/issues/17

**What did you expect to happen:**

Restic backups would be okay

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

```
time="2020-04-24T20:21:57Z" level=error msg="Error backing up item" backup=velero/240420-3 error="pod volume backup failed: error running restic backup, stderr=Fatal: unable to open config file: Stat: Access Denied.\nIs there a repository at the following location?\ns3:s3-us-east-1.amazonaws.com/thor-dev-velero-us-east-1/restic/jenkins-ops\n: unable to find summary in restic backup command output" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:182" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" group=v1 logSource="pkg/backup/resource_backupper.go:287" name=jenkins-ops-6dff69687b-r5wzv namespace= resource=pods
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
```
$ velero version
Client:
	Version: v1.2.0
	Git commit: 5d008491bbf681658d3e372da1a9d3a21ca4c03c
Server:
	Version: v1.3.1
```
- Velero features (use `velero client config get features`): 
```
$ velero client config get features
features: <NOT SET>
```
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
EKS
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
Amazon Linux 2

**Comment by hibbert** [comment] 2020-05-05 17:31
@ashish-amarnath @skriss Any update on this?

**Comment by skriss** [comment] 2020-05-05 18:57
Is this a dupe of https://github.com/vmware-tanzu/velero/issues/2198?

From looking at the previous issue, I believe this was a limitation in restic itself.

**Comment by hibbert** [comment] 2020-05-12 18:53
Yes it's a duplicate. I can see an issue open for it https://github.com/restic/restic/issues/2703, I've had a go at a PR for this https://github.com/restic/restic/pull/2733. Hopefully this or something similar will be in a future version of restic which can be used in velero

**Comment by skriss** [comment] 2020-05-12 22:24
if a new version of restic that includes the fix gets released, we'll be sure to update for the next Velero release.

**Comment by skriss** [comment] 2020-06-03 21:03
I'm going to close this out as it's not actionable on the velero side right now. If/when a new restic release comes out with a fix, we'll upgrade our dependency.

**Closed by skriss** 2020-06-03 21:03 UTC
Labels: Restic
