### ISSUE TITLE
[velero-plugin-for-gcp] Add support for multiple credentials

### ISSUE THREAD

**Issue by zubron** [vmware-tanzu/velero#3430] opened 2021-02-08 22:15 UTC
**Describe the solution you'd like**
As part of #3304, we will be enabling users to specify a credential to use for a given `BackupStorageLocation` or `VolumeSnapshotLocation` rather than relying solely on the `cloud-credentials` secret created by Velero.

Currently, the path to the `cloud-credentials` secret is made available to GCP plugin through the environment variable `GOOGLE_APPLICATION_CREDENTIALS` which the GCP Go library will look for and use if set.

To support multiple credentials, Velero will now set an additional field in the `config` for a BSL with the key `credentialsFile`. The value of this entry will be a file path which will contain the contents of the user specified credential.

When initialising the `ObjectStore` plugin, the GCP plugin will need to check the config for the `credentialsFile` key, and if set, create the GCP session using this file to load credentials from.

**Comment by stmcginnis** [comment] 2021-02-11 14:35
Is this a duplicate of https://github.com/vmware-tanzu/velero/issues/3304

**Closed** 2021-03-06 01:06 UTC
Labels: Area/Cloud/GCP, P1 - Important, release-blocker
