### ISSUE TITLE
Backups disappear after updating or deleting a schedule

### ISSUE THREAD

**Issue by brovoca** [vmware-tanzu/velero#4528] opened 2022-01-13 12:23 UTC
**What steps did you take and what happened:**
I'm installing Velero using the Helm chart and I wanted to maintain my schedules inside of the values.yaml. However, when a schedule in the values.yaml has been edited and the helm release upgraded, the schedules get replaced (rather than modified) causing Velero to go nuts and loose track of previous backups. The backups disappear from the `velero get backups` list, but still exist in Azure.

... however; it seems that Velero is glitching out a bit, because I can see "vanished" backups re-appear sometimes when I'm running `watch velero get backups`. If I run `watch --interval 0.1 velero backup describe velero-jenkins-20220113115159` it will give me `An error occurred: backups.velero.io "velero-jenkins-20220113115159" not found` most of the time, but sometimes it will actually return the details of the backup. Very inconsistent.

**What did you expect to happen:**

Existing backups related to a schedule should remain visible after replacing a schedule.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

Unable to do so:

```sh
~ >>> velero debug  --backup velero-jenkins-20220113115159
An error occurred: backups.velero.io "velero-jenkins-20220113115159" not found
```

**Anything else you would like to add:**

It obviously finds the backups in Azure and attempts to pull them in, which explains the re-appearance.

```log
time="2022-01-13T12:42:56Z" level=info msg="Found 18 backups in the backup location that do not exist in the cluster and need to be synced" backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:204"
time="2022-01-13T12:42:56Z" level=info msg="Attempting to sync backup into cluster" backup=velero-jenkins-20220112103805 backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2022-01-13T12:42:57Z" level=info msg="Successfully synced backup into cluster" backup=velero-jenkins-20220112103805 backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2022-01-13T12:42:57Z" level=info msg="Attempting to sync backup into cluster" backup=velero-monitoring-20220113103526 backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2022-01-13T12:42:57Z" level=info msg="Successfully synced backup into cluster" backup=velero-monitoring-20220113103526 backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
time="2022-01-13T12:42:57Z" level=info msg="Attempting to sync backup into cluster" backup=velero-jenkins-20220113103525 backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
time="2022-01-13T12:42:57Z" level=info msg="Successfully synced backup into cluster" backup=velero-jenkins-20220113103525 backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
```

**Environment:**

- Velero version (use `velero version`): 

```txt
Client:
        Version: v1.7.0
        Git commit: 9e52260568430ecb77ac38a677ce74267a8c2176
Server:
        Version: v1.7.1
```

- Velero features (use `velero client config get features`): 

```txt
features: <NOT SET>
```

- Kubernetes version (use `kubectl version`):

```txt
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"802eff1fe87ad2dd737ebbe891f30500b88beb00", GitTreeState:"clean", BuildDate:"2021-11-15T08:35:41Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes installer & version: AKS v1.21.2
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): N/A

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by brovoca** [comment] 2022-01-13 13:34
Not sure why I got an notification about this failed action: https://github.com/vmware-tanzu/velero/actions/runs/1692652513

**Comment by blackpiglet** [comment] 2022-01-14 11:29
I think this is related to #4093 
What is the version of Velero helm chart you are using?

I think this is caused by backup created from schedule is set with owner reference to the schedule. When schedule is deleted, all backups set owner to the schedule are GC by Kubernetes automatically. As a temporary solution, you can reference to this reply #4093 (comment) .

Please set useOwnerReferencesInBackup to false in helm value.yaml when you deploy Velero in new environment.

**Comment by brovoca** [comment] 2022-01-14 13:13
I'm using chart version 2.27.3. It's likely that it's related, as I'm using useOwnerReferencesInBackup.

**Comment by blackpiglet** [comment] 2022-01-16 11:29
@jenting 
Hi, could we set `useOwnerReferencesInBackup`'s default value to false in Velero Helm chart?
The reference between schedule and backups could cause some misleading in Velero use cases.

**Comment by jenting** [comment] 2022-01-16 11:38
I think yes.
Please help file the PR, thank you.

**Comment by reasonerjt** [comment] 2022-01-18 01:11
@blackpiglet let's double-check to make sure this issue only exists in helm-chart

**Comment by blackpiglet** [comment] 2022-01-18 03:38
This is a common issue. reference between schedule and backup can be set up by this command:
`velero schedule create --use-owner-references-in-backup`

Recent issues are mostly triggered by Helm chart, because the helm chart's default schedule setting in value.yaml set `useOwnerReferencesInBackup` to true.

I think we also should consider what we should do about the owner reference in the future release. The original PR is #3127 
PR author's motivation is:
"I use argo to manage my applications. When using the velero chart and configuring the schedules, the backups created are "linked" to the main application. For this reason, the application's situation changes to OutOfSync, but if the backup is linked to the schedule, the situation remains Synced."

**Comment by blackpiglet** [comment] 2022-03-02 01:41
Fixed by
https://github.com/vmware-tanzu/velero/pull/4660
https://github.com/vmware-tanzu/helm-charts/pull/346

**Closed by blackpiglet** 2022-03-02 01:41 UTC
Labels: Helm
