### ISSUE TITLE
Restic restore failed Lchown: operation not permitted

### ISSUE THREAD

**Issue by sikishen** [vmware-tanzu/velero#5963] opened 2023-03-07 09:18 UTC
**What steps did you take and what happened:**
I want to test cluster resource migration from k8s cluster v1.17.5 to k8s cluster v1.22.17
so i made backup on v1.17.5
`velero backup create vastdata-nginx-example-namespace --include-namespaces nginx-example --snapshot-volumes --ttl 180h --volume-snapshot-locations=vast1.me-corp.lan -w`
and when run velero restore on v1.22.17
`velero restore create --from-backup vastdata-nginx-example-namespace --restore-volumes=true -w`
but getting error
`stdout=restoring <Snapshot 2507e775 of [/host_pods/32b7bc45-ee2b-4123-b454-0119f759b525/volumes/kubernetes.io~csi/pvc-65ec1eb5-b62d-4cc8-9913-d46838826d71/mount] at 2023-03-06 07:55:01.285036425 +0000 UTC by root@velero> to .
, stderr=ignoring error for /access.log: Lchown: lchown /host_pods/f2445658-807f-4baa-bb0d-aa03803ce007/volumes/kubernetes.io~csi/pvc-4f79ec5e-6b63-4f81-a4d3-de68063d06ef/mount/access.log: operation not permitted
ignoring error for /error.log: Lchown: lchown /host_pods/f2445658-807f-4baa-bb0d-aa03803ce007/volumes/kubernetes.io~csi/pvc-4f79ec5e-6b63-4f81-a4d3-de68063d06ef/mount/error.log: operation not permitted
ignoring error for /test-file3.txt: Lchown: lchown /host_pods/f2445658-807f-4baa-bb0d-aa03803ce007/volumes/kubernetes.io~csi/pvc-4f79ec5e-6b63-4f81-a4d3-de68063d06ef/mount/test-file3.txt: operation not permitted
`

**What did you expect to happen:**
should migrate resource and persistentvolume to new cluster as expected.

**The following information will help us better understand what's going on**:
```
vastdata-nginx-example-namespace-20230307103201   vastdata-nginx-example-namespace   PartiallyFailed   2023-03-07 10:32:01 +0200 IST   2023-03-07 10:32:16 +0200 IST   1        0          2023-03-07 10:32:01 +0200 IST   <none>
```
```
Errors:
  Velero:  pod volume restore failed: error restoring volume: error running restic restore, cmd=restic restore --repo=s3:http://vast1.me-corp.lan/tmc-migration/velero/restic/nginx-example --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic 2507e775 --target=., stdout=restoring <Snapshot 2507e775 of [/host_pods/32b7bc45-ee2b-4123-b454-0119f759b525/volumes/kubernetes.io~csi/pvc-65ec1eb5-b62d-4cc8-9913-d46838826d71/mount] at 2023-03-06 07:55:01.285036425 +0000 UTC by root@velero> to .
, stderr=ignoring error for /access.log: Lchown: lchown /host_pods/f2445658-807f-4baa-bb0d-aa03803ce007/volumes/kubernetes.io~csi/pvc-4f79ec5e-6b63-4f81-a4d3-de68063d06ef/mount/access.log: operation not permitted
ignoring error for /error.log: Lchown: lchown /host_pods/f2445658-807f-4baa-bb0d-aa03803ce007/volumes/kubernetes.io~csi/pvc-4f79ec5e-6b63-4f81-a4d3-de68063d06ef/mount/error.log: operation not permitted
ignoring error for /test-file3.txt: Lchown: lchown /host_pods/f2445658-807f-4baa-bb0d-aa03803ce007/volumes/kubernetes.io~csi/pvc-4f79ec5e-6b63-4f81-a4d3-de68063d06ef/mount/test-file3.txt: operation not permitted
Fatal: There were 3 errors
```

**Anything else you would like to add:**

I tried velero v1.10, no good
I tried changing velero-restic-restore-helper  configMaps secCtxRunAsUser: to 0 and 65535, no good

**Environment:**

- Velero version (use `velero version`): 
Client:
        Version: v1.7.1
        Git commit: 4729274d07eae7e788233d5c995d7f45f40c9c61
Server:
        Version: v1.7.2
- Velero features (use `velero client config get features`): 
features: <NOT SET>
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2022-12-08T11:47:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2022-12-08T11:42:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
bare-metal
- OS (e.g. from `/etc/os-release`):
ubuntu

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment] 2023-03-08 02:26
It's dup of https://github.com/vmware-tanzu/velero/issues/5403

**Comment by sikishen** [comment] 2023-03-08 03:03
Thanks for replying,

I have two kinds of bare-metal storage clusters, vastdata and vSphere vsan, non of them are on the cloud according to https://github.com/vmware-tanzu/velero/issues/5403.

**Comment by Lyndon-Li** [comment] 2023-03-09 01:15
@sikishen Let's work on this issue in two ways:
1. Workaround: As you see in #5403 , the Kopia path in v1.10 has integrated with `IgnorePermissionErrors` flag, so any permission error like the the current one will be solved, it doesn't only work with cloud storage. Hopefully, with this workaround, you could get successful backups very soon (merely, the files with permission errors will be skipped from the restore).
2. Find root cause: let's find the root cause of why the lchown problem happened in your env. We need some more information and may take some time to troubleshoot.

**Comment by Lyndon-Li** [comment] 2023-03-09 02:08
@sikishen 
For point 2 mentioned above, to find the root cause, let me ask some information:
1. Does the lchown error happens for some of the files under the `mount` folder only or for all the files?
2. Is the `root_squash` enabled on the NFS server side for the export root or for the problematic files/dirs?
3. Is the `no_root_squash` specified explicitly on the NFS server side for the export root?
4. Please share us the `uid+gid` of the **restored folder** `/host_pods/f2445658-807f-4baa-bb0d-aa03803ce007/volumes/kubernetes.io~csi/pvc-4f79ec5e-6b63-4f81-a4d3-de68063d06ef/mount/`
5. Please also share us the `uid+gid` of the  problematic files in the **source PV** (it should be a similar path to /host_pods/<pod ID>/volumes/kubernetes.io~csi/<source PVC ID>/mount/), just one of them is enough, for example, access.log

If you don't want to share us 4 and 5, please do it yourself and see if the two `uid+gid` are the same, if not, please share what the different is like.

**Comment by sikishen** [comment] 2023-03-09 09:54
@Lyndon-Li thank you for your detail response.

for Option 1: I tried with velero v1.10, but since we have an old k8s cluster 1.17, I only install velero v1.7 for compatibility and creating backups(using restric), and new cluster using velero v1.10 to restore still volume won't restore

for Option 2:
1. Does the lchown error happens for some of the files under the mount folder only or for all the files?
every file
2. not using NFS
3. not using NFS
4. Please share us the uid+gid of the restored folder /host_pods/f2445658-807f-4baa-bb0d-aa03803ce007/volumes/kubernetes.io~csi/pvc-4f79ec5e-6b63-4f81-a4d3-de68063d06ef/mount/
```
ls -l /var/lib/kubelet/pods/9414040f-4171-4b79-9fc1-a64de9d007fc/volumes/kubernetes.io~csi/pvc-cf5caa38-38db-49c8-89f1-45ef6ece0ccf/mount/
total 513
-rw-r--r-- 1 nobody nogroup    558 Mar  6 09:01 access.log
```
5. Please also share us the uid+gid of the problematic files in the source PV (it should be a similar path to /host_pods//volumes/kubernetes.io~csi//mount/), just one of them is enough, for example, access.log
```
ls -l /var/lib/kubelet/pods/876734a7-aaf6-45c3-8e67-005a3e38d8ce/volumes/kubernetes.io~csi/pvc-4621a010-2587-4c4c-afd1-d02d311a451c/mount/
total 4
-rw-r--r-- 1 root root 558 Mar  8 05:07 access.log
```

actually since I'm testing migration, I also tested disaster recovery using the same storage, and it aws fine in the same cluster(v1.17)

**Comment by sikishen** [comment] 2023-03-09 15:12
Hi @Lyndon-Li,
I found the issue, we are running on NFS protocol actually, and we had a whitelist for no_root_squash, we won't fix this if you didn't pointed out NFS service.
Br,
Siki.

**Comment by ywk253100** [comment] 2023-03-14 06:03
@sikishen I suppose the issue can be fixed by updating the configuration of your NFS service according to the comments.
I'm closing this issue and feel free to reopen it.

**Closed by ywk253100** 2023-03-14 06:03 UTC
Labels: Restic
