### ISSUE TITLE
Extend Restic support to backup CSI volume snapshots to S3 location

### ISSUE THREAD

**Issue by jagdishkumbhare** [vmware-tanzu/velero#4685] opened 2022-02-22 04:38 UTC
**Describe the problem/challenge you have**
With K8s Volume snapshot feature for CSI supported storage, actual volume snapshot is stored locally in same storage, It is not backed up to remote location (s3) where resources information is backed up.
This is fine with AWS, GCE, or Azure but with other storage solutions like ceph, snapshot are not available outside cluster. To make it truely disaster proof, we need snapshot to be stored remotely.

**Describe the solution you'd like**
We can use restic to take volume snapshot to s3 location as its done for any other non-csi volume.
Steps when creating backup:
1. Take volume snapshot with supported CSI plugin.
2. Create temp PV/PVC from volume snapshot and mount it.
3. Backup temp PV/PVC using restic (as its being done when backing volume using restic)
4. Delete temp PV/PVC 

Steps when restoring from backup:
1. If volume snapshot is present locally, restore PV/PVC from volume snapshot. (existing behavior)
2. If no volume snapshot is found locally, create volume using restic backup from s3 (as its being done when using restic)
3. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):1.17
- Kubernetes version (use `kubectl version`):1.23
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by gman0** [comment] 2022-02-22 13:05
I believe this is a duplicate of https://github.com/vmware-tanzu/velero/issues/3544 ?

**Comment by ywk253100** [comment] 2022-02-23 01:58
Yes, it's a dup, I'm closing this one

**Closed by ywk253100** 2022-02-23 01:58 UTC
