### ISSUE TITLE
sock file fails backup with velero v.1.12 datamover: data path backup failed: Failed to run kopia backup: Error when processing     mysql.sock: unknown or unsupported entry type

### ISSUE THREAD

**Issue by weshayutin** [vmware-tanzu/velero#6736] opened 2023-08-31 18:24 UTC
**What steps did you take and what happened:**

I would assume any application with sock file would probably hit this issue if the sock file is located on the mounted volume being backed up with datamover.     In this case this mariadb locates the sock file in the working dir, where the  standard maria container does not have the sock file in the working dir.   This issue is specific to sock files and highlighted with this specific image registry.redhat.io/rhel8/mariadb-105:latest

Using the included mariadb template...
1.  `velero backup create mysql-persistent-rhel8-fs-1 --include-namespaces maria --default-volumes-to-fs-backup=true`  PASSES
2.  `velero backup create mysql-persistent-rhel8-dm-1 --include-namespaces maria --snapshot-move-data=true` FAILS

## error:
data path backup failed: Failed to run kopia backup: Error when processing
    mysql.sock: unknown or unsupported entry type

## mariadb template to test with:
```
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    name: mariadb-port
  clusterIP: None
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-sts
spec:
  serviceName: "mariadb-service"
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: registry.redhat.io/rhel8/mariadb-105:latest
        ports:
        - containerPort: 3306
          name: mariadb-port
        env:
        # Using Secrets
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/mysql/
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 300M
```

## dataupload failed cr
```
apiVersion: velero.io/v2alpha1
kind: DataUpload
metadata:
  creationTimestamp: "2023-08-31T17:59:43Z"
  finalizers:
  - velero.io/data-upload-download-finalizer
  generateName: mysql-persistent-rhel8-dm-1-
  generation: 6
  labels:
    velero.io/accepted-by: ip-10-0-204-67.us-west-2.compute.internal
    velero.io/async-operation-id: du-11b4a6cd-4d60-438b-8f4c-9802c7e3513f.e8b46894-834c-4c363a3c2
    velero.io/backup-name: mysql-persistent-rhel8-dm-1
    velero.io/backup-uid: 11b4a6cd-4d60-438b-8f4c-9802c7e3513f
    velero.io/pvc-uid: e8b46894-834c-4c37-ae3c-d67954f7b6f9
  name: mysql-persistent-rhel8-dm-1-6d86q
  namespace: openshift-adp
  ownerReferences:
  - apiVersion: velero.io/v1
    controller: true
    kind: Backup
    name: mysql-persistent-rhel8-dm-1
    uid: 11b4a6cd-4d60-438b-8f4c-9802c7e3513f
  resourceVersion: "39027554"
  uid: 60c8bf9b-081f-4cf0-bb0d-d3f22d2b4dd6
spec:
  backupStorageLocation: velero-sample-1
  csiSnapshot:
    snapshotClass: ""
    storageClass: gp3-csi
    volumeSnapshot: velero-datadir-mariadb-sts-0-cvb57
  operationTimeout: 10m0s
  snapshotType: CSI
  sourceNamespace: maria
  sourcePVC: datadir-mariadb-sts-0
status:
  completionTimestamp: "2023-08-31T18:00:30Z"
  message: 'data path backup failed: Failed to run kopia backup: Error when processing
    mysql.sock: unknown or unsupported entry type'
  node: ip-10-0-181-147.us-west-2.compute.internal
  phase: Failed
  progress:
    totalBytes: 36308935
  startTimestamp: "2023-08-31T17:59:43Z"

```

**What did you expect to happen:**
* datamover should skip or ignore the .sock file 

**The following information will help us better understand what's going on**:

```
Name:         mysql-persistent-rhel8-dm-1
Namespace:    openshift-adp
Labels:       velero.io/storage-location=velero-sample-1
Annotations:  velero.io/resource-timeout=10m0s
              velero.io/source-cluster-k8s-gitversion=v1.26.6+73ac561
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=26

Phase:  PartiallyFailed (run `velero backup logs mysql-persistent-rhel8-dm-1` for more information)


Errors:
  Velero:     <none>
  Cluster:    <none>
  Namespaces: <none>

Namespaces:
  Included:  maria
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  velero-sample-1

Velero-Native Snapshot PVs:  auto
Snapshot Move Data:          true
Data Mover:                  velero

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  4h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2023-08-31 17:59:33 +0000 UTC
Completed:  2023-08-31 18:00:39 +0000 UTC

Expiration:  2023-09-30 17:59:33 +0000 UTC

Total items to be backed up:  90
Items backed up:              90

Backup Item Operations:
  Operation for persistentvolumeclaims maria/datadir-mariadb-sts-0:
    Backup Item Action Plugin:  velero.io/csi-pvc-backupper
    Operation ID:               du-11b4a6cd-4d60-438b-8f4c-9802c7e3513f.e8b46894-834c-4c363a3c2
    Items to Update:
                           datauploads.velero.io openshift-adp/mysql-persistent-rhel8-dm-1-6d86q
    Phase:                 Failed
    Operation Error:       data path backup failed: Failed to run kopia backup: Error when processing mysql.sock: unknown or unsupported entry type
    Progress:              0 of 36308935 complete (Bytes)
    Progress description:  Failed
    Created:               2023-08-31 17:59:43 +0000 UTC
    Started:               2023-08-31 17:59:43 +0000 UTC
    Updated:               2023-08-31 18:00:30 +0000 UTC
Resource List:
  apiextensions.k8s.io/v1/CustomResourceDefinition:
    - clusterserviceversions.operators.coreos.com
  apps/v1/ControllerRevision:
    - maria/mariadb-sts-78599786c
  apps/v1/StatefulSet:
    - maria/mariadb-sts
  authorization.openshift.io/v1/RoleBinding:
    - maria/openshift-pipelines-edit
    - maria/pipelines-scc-rolebinding
    - maria/system:deployers
    - maria/system:image-builders
    - maria/system:image-pullers
  discovery.k8s.io/v1/EndpointSlice:
    - maria/mariadb-service-kkphk
  operators.coreos.com/v1alpha1/ClusterServiceVersion:
    - maria/openshift-pipelines-operator-rh.v1.11.1
  rbac.authorization.k8s.io/v1/ClusterRole:
    - openshift-pipelines-clusterinterceptors
  rbac.authorization.k8s.io/v1/ClusterRoleBinding:
    - openshift-pipelines-clusterinterceptors
  rbac.authorization.k8s.io/v1/RoleBinding:
    - maria/openshift-pipelines-edit
    - maria/pipelines-scc-rolebinding
    - maria/system:deployers
    - maria/system:image-builders
    - maria/system:image-pullers
  v1/ConfigMap:
    - maria/config-service-cabundle
    - maria/config-trusted-cabundle
    - maria/kube-root-ca.crt
    - maria/openshift-service-ca.crt
  v1/Endpoints:
    - maria/mariadb-service
  v1/Event:
    - maria/datadir-mariadb-sts-0.178088b1885bd825
    - maria/datadir-mariadb-sts-0.178088b18aa21721
    - maria/datadir-mariadb-sts-0.178088b18aa2c1f3
    - maria/datadir-mariadb-sts-0.178088b250518b2b
    - maria/mariadb-sts-0.178088b2791bd934
    - maria/mariadb-sts-0.178088b37a4cef79
    - maria/mariadb-sts-0.178088b3fb59d102
    - maria/mariadb-sts-0.178088b3fe93472f
    - maria/mariadb-sts-0.178088b431fcbc19
    - maria/mariadb-sts-0.178088b43af614f6
    - maria/mariadb-sts-0.178088b43d10e465
    - maria/mariadb-sts-0.178088b484db86f2
    - maria/mariadb-sts-0.178088b4d0cf7b67
    - maria/mariadb-sts-0.178088b88b288585
    - maria/mariadb-sts-0.178088bf33775311
    - maria/mariadb-sts-0.17808901535ba556
    - maria/mariadb-sts-0.17808902583d3fe7
    - maria/mariadb-sts-0.178089043d29e322
    - maria/mariadb-sts-0.178089043f482ba0
    - maria/mariadb-sts-0.1780890473bca09b
    - maria/mariadb-sts-0.178089047d3b941a
    - maria/mariadb-sts-0.178089047eeb2d3d
    - maria/mariadb-sts-0.17808904f1e10814
    - maria/mariadb-sts-0.1780890534b1bd2d
    - maria/mariadb-sts-0.17808908a877765d
    - maria/mariadb-sts-0.1780890f3d3e13f4
    - maria/mariadb-sts-0.178089278a5d31e5
    - maria/mariadb-sts-0.178089288ce9fb01
    - maria/mariadb-sts-0.1780892a48c5ff90
    - maria/mariadb-sts-0.1780892a4bae2df4
    - maria/mariadb-sts-0.1780892a6c1591a9
    - maria/mariadb-sts-0.1780892a750dba11
    - maria/mariadb-sts-0.1780892a768c6046
    - maria/mariadb-sts-0.1780892abb15a782
    - maria/mariadb-sts-0.1780892ad3c03066
    - maria/mariadb-sts-0.1780892d9c7b859c
    - maria/mariadb-sts-0.178089333c05c0e2
    - maria/mariadb-sts-0.1780893d6fd776c2
    - maria/mariadb-sts-0.17808941a4221d4b
    - maria/mariadb-sts-0.178089443e9c2edb
    - maria/mariadb-sts-0.17808944ad7e0767
    - maria/mariadb-sts-0.17808944b046fa29
    - maria/mariadb-sts-0.17808944d1019aa3
    - maria/mariadb-sts-0.17808944d98c8248
    - maria/mariadb-sts-0.17808944db32222c
    - maria/mariadb-sts.178088b188639860
    - maria/mariadb-sts.178088b18984616e
    - maria/mariadb-sts.1780890152c1b6b0
    - maria/mariadb-sts.178089278579db8c
    - maria/mariadb-sts.17808941a3a48bf9
  v1/Namespace:
    - maria
  v1/PersistentVolume:
    - pvc-e8b46894-834c-4c37-ae3c-d67954f7b6f9
  v1/PersistentVolumeClaim:
    - maria/datadir-mariadb-sts-0
  v1/Pod:
    - maria/mariadb-sts-0
  v1/Secret:
    - maria/builder-dockercfg-bjdjq
    - maria/builder-token-n2wtn
    - maria/default-dockercfg-t9nsl
    - maria/default-token-ghwl8
    - maria/deployer-dockercfg-bnx7w
    - maria/deployer-token-gdtv2
    - maria/mariadb-secret
    - maria/pipeline-dockercfg-mnpgd
    - maria/pipeline-token-n8gt4
  v1/Service:
    - maria/mariadb-service
  v1/ServiceAccount:
    - maria/builder
    - maria/default
    - maria/deployer
    - maria/pipeline

Velero-Native Snapshots: <none included>
```
* log file: https://termbin.com/krd0

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by kaovilai** [comment] 2023-08-31 18:39
This should also apply to kopia in general? Or just data mover?

**Comment by sseago** [comment] 2023-08-31 19:07
Looks like kopia fsb results in the same error. The success above was with restic.

**Comment by sseago** [comment] 2023-08-31 19:07
Restic automatically excludes socket files. It looks like we need to invoke kopia with a similar exclusion.

**Comment by weshayutin** [comment] 2023-08-31 19:09
> Looks like kopia fsb results in the same error. The success above was with restic.

yes sir.. sorry about that, and thank you for double checking.

**Comment by sseago** [comment] 2023-08-31 19:10
Note that we can't exclude files by name -- for example if you use the image `mysql:8.0` then the monted volume does not have a sock file, there's a symlink to the sock file in a local dir, so we want to back up the symlink but if the actual file on the  filesystem is a sock file, then we want to exclude that

**Comment by sseago** [comment] 2023-08-31 19:20
And it looks like the ignore files feature in kopia is filename-based, so we can't use that for ignoring sock files. One other possibility is to look more carefully at kopia error output and ignore sock file errors. Kopia just couldn't back it up, which is fine, it just means the  file is skipped, no need to mark the backup failed when we probably wanted to ignore that file anyway.

**Comment by sseago** [comment] 2023-08-31 20:03
@draghuram Restic skips socket files already, so restic doesn't fail in this way, but with kopia, socket files trigger an error. There's also this kopia issue recently opened to explicitly ignore socket file errors: https://github.com/kopia/kopia/issues/2796

But if you have something that works in CloudCasa, maybe you could submit a similar change to velero to do something similar.

**Comment by sseago** [comment] 2023-08-31 21:33
Right, I think we're all referring to kopia. I meant that if you made a change to the way you're using kopia in CloudCasa to handle this, maybe we could apply a similar change within Velero, since it doesn't look like there's much traction on the upstream kopia issues to handle this internally.

**Comment by Lyndon-Li** [comment] 2023-09-01 02:19
The `IgnoreUnknownTypes` policy set by #5786 should work for all ErrUnknown(unknown or unsupported entry type) errors as the [Kopia code here](https://github.com/kopia/kopia/blob/1320f0c8e856ec856ad0b82c52ceed5483a5196d/snapshot/snapshotfs/upload.go#L910C4-L910C18). 
And from the original issue #5684, the problematic file is also a socket file, so it means #5786  should have fixed the problem.

Let's check why this doesn't work in Velero now, maybe there is a regression issue after data path refactor in 1.12.

**Comment by qiuming-best** [comment] 2023-09-01 08:11
@weshayutin thanks for your report, I've reproduced your errors, and now I've fixed

reproduced error:
<img width="2047" alt="image" src="https://github.com/vmware-tanzu/velero/assets/8985337/52f733b8-c4c3-4598-887c-58d5a36e3d05">
fixed:
<img width="1835" alt="image" src="https://github.com/vmware-tanzu/velero/assets/8985337/11794335-863a-4637-b779-3c92e5670e75">

**Comment by weshayutin** [comment] 2023-09-01 13:21
@qiuming-best thank you!

**Comment by sseago** [comment] 2023-09-01 15:05
@qiuming-best Thank you. I've verified your fix with both datamover and kopia FSB in my env with the latest release-1.12 branch updates.

**Comment by Lyndon-Li** [comment] 2023-09-04 01:29
Thanks all! Let me close this issue.

**Closed by Lyndon-Li** 2023-09-04 01:29 UTC
Labels: area/datamover, area/fs-backup, target/1.12-rc.2
