### ISSUE TITLE
Create backup with cli specifying a volume-snapshot-location always adds all available locations and causes an error

### ISSUE THREAD

**Issue by jasmdk** [vmware-tanzu/velero#4828] opened 2022-04-13 11:43 UTC
**What steps did you take and what happened:**
I have two sets of backup-storage-location and volume-snapshot-location
When I create a backup using velero cli that specifies exactly one volume snapshot location, however the resulting backup resource lists both volume snapshot locations. Backups are created, but reports the backup as PartiallyFailed with an error message about the surplus volume snapshot location failed during authentication.

**What did you expect to happen:**
I expected the resulting Backup resource to look like the dry-run (-o yaml) with only the requested volume snapshot location being referenced.

**The following information will help us better understand what's going on**:
Dry-run
`velero backup create nginx-backup-csi --storage-location default --include-namespaces nginx-example --snapshot-volumes --volume-snapshot-locations default -o yaml`
Result:
```
apiVersion: velero.io/v1
kind: Backup
metadata:
  creationTimestamp: null
  name: nginx-backup-csi
  namespace: velero
spec:
  hooks: {}
  includedNamespaces:
  - nginx-example
  metadata: {}
  snapshotVolumes: true
  storageLocation: default
  ttl: 720h0m0s
  volumeSnapshotLocations:
  - default
status: {}
```
And the Backup resource as produced without "-o yaml":
```
apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    velero.io/source-cluster-k8s-gitversion: v1.20.12
    velero.io/source-cluster-k8s-major-version: "1"
    velero.io/source-cluster-k8s-minor-version: "20"
  creationTimestamp: "2022-04-13T11:15:50Z"
  generation: 5
  labels:
    velero.io/storage-location: default
  name: nginx-backup-csi
  namespace: velero
  resourceVersion: "17732027"
  uid: 337d0728-7489-48e9-b590-dc78c317020c
spec:
  defaultVolumesToRestic: false
  hooks: {}
  includedNamespaces:
  - nginx-example
  metadata: {}
  snapshotVolumes: true
  storageLocation: default
  ttl: 720h0m0s
  volumeSnapshotLocations:
  - recovery
  - default
status:
  completionTimestamp: "2022-04-13T11:16:06Z"
  errors: 1
  expiration: "2022-05-13T11:15:50Z"
  formatVersion: 1.1.0
  phase: PartiallyFailed
  progress:
    itemsBackedUp: 40
    totalItems: 40
  startTimestamp: "2022-04-13T11:15:50Z"
  version: 1
  warnings: 1
```
As shown, the "recovery" volume-snapshot-location is added to the list even though it was not referenced and it produced an error: 
`time="2022-04-13T11:16:01Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/nginx-backup-csi error="rpc error: code = Unknown desc = error getting authorizer from environment: failed to get oauth token from MSI: MSI not available" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/volume_snapshotter.go:135" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:446" name=pvc-ccd2c1e3-fefc-4c75-be6d-22019f708ec9 namespace= persistentVolume=pvc-ccd2c1e3-fefc-4c75-be6d-22019f708ec9 resource=persistentvolumes volumeSnapshotLocation=recovery`

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 
[bundle-2022-04-13-13-33-45.tar.gz](https://github.com/vmware-tanzu/velero/files/8481068/bundle-2022-04-13-13-33-45.tar.gz)

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.8.1
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`): 1.20.12
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by jasmdk** [comment] 2022-04-13 12:02
Actually it seems like it is not the cli, but Velero that somehow adds the provider even when I create the backup using plain YAML

**Comment by qiuming-best** [comment] 2022-04-18 06:45
@jasmdk How do you set up your velero and execute backup command? Because I could not reproduce it currently.

**Comment by Lyndon-Li** [comment] 2024-05-20 07:29
Closing this issue as there is no update for long time, please retry with the latest release and feel free to reopen this issue if it reproduced.

**Closed by Lyndon-Li** 2024-05-20 07:29 UTC
Labels: Area/Cloud/Azure
