### ISSUE TITLE
The velero restore delete command does not delete restore log and result files from BSL

### ISSUE THREAD

**Issue by codegold79** [vmware-tanzu/velero#4087] opened 2021-08-31 22:09 UTC
**What steps did you take and what happened:**

* Step 1: I installed Velero 1.6.3 using `velero install` on Kind using K8s version 1.21.1.

```bash
velero install \
	  --features=EnableAPIGroupVersions \
	  --provider aws \
	  --plugins velero/velero-plugin-for-aws:v1.2.0 \
	  --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://192.168.0.121:9000 \
	  --use-volume-snapshots=false \
	  --bucket velero \
	  --secret-file ~/Documents/credentials-minio-tkgs
```

* Step 2: Run a Velero restore using an existing backup file.

```bash
velero restore create --from-backup test1
```

* Step 3: Verify velero recognizes a new restore object and it is in Minio BSL

```bash
$ velero restore 
NAME                   BACKUP   STATUS      STARTED                         COMPLETED                       ERRORS   WARNINGS   CREATED                         SELECTOR
test1-20210831133951   test1    Completed   2021-08-31 13:39:51 -0700 PDT   2021-08-31 13:40:34 -0700 PDT   0        23         2021-08-31 13:39:51 -0700 PDT   <none>
```

![minio-restore](https://user-images.githubusercontent.com/17328443/131581133-ad41b80b-75fc-44a8-97ff-10bbcd829102.png)

* Step 4: Run velero restore delete command

```bash
$ velero restore delete test1-20210831133951
Are you sure you want to continue (Y/N)? y
Restore "test1-20210831133951" deleted
```

* Step 5: Check restore has been removed

I was able to see that `velero restore get` returned nothing. However,  the results and log files still remain in Minio.

**What did you expect to happen:**
I expect when I go into my MinIO BSL server, I no longer see the directory named after the restore and its contents (log and result files).

**The output of the following commands will help us better understand what's going on**:

- `kubectl logs deployment/velero -n velero`: [velero-deploy.log](https://github.com/vmware-tanzu/velero/files/7087008/velero-deploy.log)
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`: NOT RELEVANT
- `velero backup logs <backupname>`: NOT RELEVANT
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`: NO LONGER ACCESSIBLE WITH VELERO COMMAND
- `velero restore logs <restorename>`: NO LONGER ACCESSIBLE WITH VELERO COMMAND

Although the restore describe and logs are no longer accessible using Velero commands, these files still remain in Minio restores directory: 
- [restore-test1-20210831133951-logs.gz](https://github.com/vmware-tanzu/velero/files/7087024/restore-test1-20210831133951-logs.gz)
- [restore-test1-20210831133951-results.gz](https://github.com/vmware-tanzu/velero/files/7087025/restore-test1-20210831133951-results.gz)

**Anything else you would like to add:**

According to [Velero documentation](https://velero.io/docs/v1.6/restore-reference/#what-happens-when-user-removes-restore-objects), the `velero restore delete` command should do the following:

> Deleting with velero restore delete. This command will delete the custom resource representing it, along with its individual log and results files. But, it will not delete any objects that were created by it from your cluster.

**Environment:**

- Velero version (use `velero version`): 1.6.3
- Velero features (use `velero client config get features`): enable api groups
- Kubernetes version (use `kubectl version`): 1.21.1
- Kubernetes installer & version: ???
- Cloud provider or hardware configuration: Kind
- OS (e.g. from `/etc/os-release`): Mac OS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by zubron** [comment] 2021-08-31 22:34
Thanks for highlighting this, @codegold79! It looks like this is a duplicate of https://github.com/vmware-tanzu/velero/issues/2697. As pointed out in https://github.com/vmware-tanzu/velero/issues/2697#issuecomment-665264222, we don't reconcile the deletion of restore objects. The restores are only deleted if backups referencing those restores are deleted. It's not clear if this is intentional or not :confused:

I'm going to close this. If you have any other comments, please add them to #2697. Thanks :)

**Closed by zubron** 2021-08-31 22:34 UTC

**Comment by codegold79** [comment] 2021-08-31 22:51
Thanks @zubron -- I promise I did a search of issues but I completely missed this one. Oops!
