### ISSUE TITLE
Velero and MinIO on vSphere 7 with Tanzu

### ISSUE THREAD

**Issue by kurthv** [vmware-tanzu/velero#3108] opened 2020-11-24 07:40 UTC
First of all I have to admit, that I am pretty new to Kubernetes, but I did manage to setup my own lab environment including:
- 4x Nested ESXi hosts running vSphere 7 Update 1
- Tanzu Basic 
- 3-node Supervisor Cluster

I was also able to deploy my first K8s application with PVCs (the wordpress example from kubernetes.io).

Now I wanted to setup Velero in combination with MinIO for backup & recovery.
Therefore I tried to follow the 'Evaluation Install' steps described in the official Velero documentation.

Unfortuantely I don't get to the point, where I can install Velero itself, because I am already failing to install MiniIO.
Here are the results:

`kurthv@slax:~/k8s-examples/velero$ kubectl apply -f examples/minio/00-minio-deployment.yaml`
`deployment.apps/minio created`
`service/minio created`
`job.batch/minio-setup created`
`kurthv@slax:~/k8s-examples/velero$ kubectl get pods`
`NAME                     READY   STATUS             RESTARTS   AGE`
`minio-7b4ff54f67-7ncdm   0/1     CrashLoopBackOff   1          22s`
`kurthv@slax:~/k8s-examples/velero$ kubectl get deployments`
`NAME    READY   UP-TO-DATE   AVAILABLE   AGE`
`minio   0/1     1            0           32s`

Here is what it looks like in vCenter: https://ibb.co/j8QkCXM

I have no idea, where I have to check what's going wrong here.
Did anyone manage to setup Velero and MinIO on vSphere 7 with Tanzu?

Help is much appreciated!

Greetings from Germany :-)

**Comment by dsu-igeek** [comment] 2020-11-24 19:45
This is outside of Velero, so we may not be able to resolve this, but I'll try to help you out here.  The first thing to figure out is why the pod is crashing.

Try
`kubectl get logs -p minio-7b4ff54f67-7ncdm`

That should get you the previous (before the pod crashed) logs.

**Comment by kurthv** [comment] 2020-11-25 09:35
It seems there is a problem with the PVCs/disks:

kurthv@slax:~/k8s-examples/velero$ kubectl get pods
NAME                     READY   STATUS             RESTARTS   AGE
minio-7b4ff54f67-fw629   0/1     CrashLoopBackOff   4          3m51s
minio-setup-fm6kh        1/1     Running            4          3m51s

kurthv@slax:~/k8s-examples/velero$ kubectl logs --previous minio-7b4ff54f67-fw629
ERROR Unable to initialize backend: Unable to write to the backend
      > Please ensure MinIO binary has write permissions for the backend
      HINT:
        The disk size is less than 900MiB threshold

kurthv@slax:~/k8s-examples/velero$ kubectl logs -p minio-setup-fm6kh
mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "http://minio:9000/probe-bucket-sign-qviumvbks9n4/?location=": dial tcp 10.96.0.44:9000: i/o timeout.

**Comment by nrb** [comment] 2020-12-07 23:26
@kurthv This is working as intended [per the minio team](https://github.com/minio/minio/issues/6528) - you need disks larger than 900MiB to get started.

We can update our documentation to specify this minimum.

**Comment by a-mccarthy** [comment] 2021-02-19 17:03
@carlisia and @dsu-igeek is this issue closed by thee merged PR? I can't tell so i wanted to check, thanks! :)

**Comment by dsu-igeek** [comment] 2021-03-05 23:53
Yes, this should be closed with that additional info.

**Closed by dsu-igeek** 2021-03-05 23:53 UTC
Labels: Area/Documentation
