### ISSUE TITLE
Support multiple selectors ("OR" logic) when creating a backup

### ISSUE THREAD

**Issue by tcdowney** [vmware-tanzu/velero#3072] opened 2020-11-12 01:00 UTC
**Describe the problem/challenge you have**
I have a usecase where I'd like to take a targeted backup of several components, but they are not consistently labeled. One is labeled with `app: postgres` and the other with `app.kubernetes.io/name: cf-api-controllers`.

Since a single Kubernetes label selector only supports logical `AND`s of different labels, I have to change the labels on one of the Pods to get this to work. In this case I have control of the `cf-api-controllers` Deployment so I labeled it with `app: cf-api-controllers` as a workaround, but it would be nice if Velero supported a logical `OR` for cases where I didn't have the ability to change the Deployment.

**Describe the solution you'd like**
One option would be to support multiple `--selector` flags. For example:

```console
velero create backup "${backup_name}" \
       --include-namespaces cf-system,cf-db \
       --selector 'app in (postgres)' \
       --selector 'app.kubernetes.io/name in (cf-api-controllers)' \
       --wait
```

**Environment:**
I don't think environment matters much here, but will include some anyway:

- Velero version (use `velero version`):
```
Client:
	Version: v1.5.2
	Git commit: -
Server:
	Version: v1.3.2
```

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-14T11:09:22Z", GoVersion:"go1.14.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-gke.1504", GitCommit:"17061f5bd4ee34f72c9281d49f94b4f3ac31ac25", GitTreeState:"clean", BuildDate:"2020-10-19T17:00:22Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes installer & version: GKE
- Cloud provider or hardware configuration: GKE
- OS (e.g. from `/etc/os-release`): OS X

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nrb** [comment] 2021-05-12 16:40
I think this is a duplicate of #1508, closing this and updating that title.

**Closed by nrb** 2021-05-12 16:40 UTC
Labels: Area/CLI, Enhancement/User, Reviewed Q2 2021
