### ISSUE TITLE
Allow for namespace selectors 

### ISSUE THREAD

**Issue by dhananjaysathe** [vmware-tanzu/velero#503] opened 2018-05-18 11:48 UTC
In a usecase where one has dynamic namespaces being created through a higher order api and it would like to back these up on schedule - it can be cumbersome to do so with namespace names . 

It would be more natural and declarative to just label them and use that as a selector . 
Esp relevant to the  he `ark schedule` feature as you cant create a new BackupSpec each time. 
In the normal backup case one could write an api abstraction that gathers a list of namespace names and then calls the backup api with a slice.

**Comment by ncdc** [comment] 2018-05-22 01:00
cc @jbeda @dhanmm

**Comment by rosskukulinski** [comment] 2018-06-13 21:02
Hi @dhananjaysathe - could you provide a little more context regarding your dynamic namespaces?  I'm curious about what's being used to create your namespaces.

**Comment by dhananjaysathe** [comment] 2018-08-07 08:47
hi @rosskukulinski we use kube as a provisioning layer for dynamic workloads. Each workload gets put into its own isolated name-space. So what i would want to do is take backups of a particular users workloads and allow him to restore them to a point in time. SO instead of specifying exact namespace names i would use lables and selectors to map to a backup job/schedule.

**Comment by rosskukulinski** [comment] 2018-08-08 15:54
Cool! Thanks for the additional context @dhananjaysathe.  We're in the planning process for the next few releases as well as the road to 1.0.  Once I have a better understanding of if/when this might be worked on, I'll let you know.

Also, we're happy to take contributions if you or anyone else has some time.  We love mentoring/on-boarding folks to the project!

**Comment by skriss** [comment] 2020-04-29 18:55
closing this out as a dupe of #2477.

**Closed by skriss** 2020-04-29 18:55 UTC
Labels: Breaking change, Enhancement/User, Needs Product
