### ISSUE TITLE
FIPS go compliant crypto for velero

### ISSUE THREAD

**Issue by jprecuch** [vmware-tanzu/velero#5284] opened 2022-09-05 10:21 UTC
**Describe the problem/challenge you have**
It seems based on our research tha velero is not using FIPS compliant crypto at the moment.
https://github.com/vmware-tanzu/velero/blob/main/Dockerfile#L14

Would it be possible to start using FIPS compliant go crypto instead by default for velero?
It should be simple change like example:
```
FROM  --platform=$BUILDPLATFORM us-docker.pkg.dev/google.com/api-project-999119582588/go-boringcrypto/golang:1.17.11b7 as builder-env
```

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by qiuming-best** [comment] 2022-09-06 02:04
@jprecuch Thanks for your help. Currently, I'm not familiar with FIPS-compliant crypto

So what's the benefit of using FIPS-compliant crypto for velero?

And using `go-boringcrypto/golang:1.17.11b7` as the base image to build images that will be FIPS compliant, is that right?

Thanks

**Comment by jprecuch** [comment] 2022-09-08 09:55
Thanks @qiuming-best . More information about FIPS can be found here https://www.encryptionconsulting.com/education-center/what-is-fips/ . It brings extra security.

For the base image yes, that should be enough, however it should be checked what is latest version of boringcrypto to be used.

**Comment by reasonerjt** [comment] 2022-09-20 11:34
Thanks @jprecuch

So far I don't see strong requirement to release a FIPs compliant velero as part of each release.

I'll put this in the backlog, in the short term, I'd suggest you customize the image downstream so you have the FIPS compliant velero.

We may re-evaluate when we see more requirements like this in the community.

**Comment by kaovilai** [comment] 2024-11-20 02:29
Closing as dupe of #7649

**Closed by kaovilai** 2024-11-20 02:29 UTC
Labels: Needs investigation, kind/requirement
