### ISSUE TITLE
No results channel found for pod 

### ISSUE THREAD

**Issue by Dannhausen** [vmware-tanzu/velero#7829] opened 2024-05-27 08:05 UTC
**What steps did you take and what happened:**
In our logs we see daily error messages like (on dev stage and production stage as well)

"No results channel found for pod namespace/pod to send pod volume backup velero/lmc-dev-20240526030058-sdpb2 on" logSource="pkg/podvolume/backupper.go:135"

The backup is running fine. But we would like to know, why we get those messages.

**What did you expect to happen:**
No error messages

**Environment:**

- Velero version (use `velero version`):
Client:
        Version: v1.11.1
Server:
        Version: v1.13.2
- Velero features (use `velero client config get features`):  features: <NOT SET>
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.15+vmware.1"

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by kaovilai** [comment] 2024-05-29 17:33
Code came from 
https://github.com/vmware-tanzu/velero/blob/33633d8a027ad5d97bf2565fe125df6fbabcfe94/pkg/podvolume/restorer.go#L72-L117

Looks like there's something that Updated the PodVolumeRestore object prior to RestorePodVolumes function being executed.

**Comment by kaovilai** [comment] 2024-05-29 17:34
If [RestorePodVolumes](https://github.com/vmware-tanzu/velero/blob/33633d8a027ad5d97bf2565fe125df6fbabcfe94/pkg/podvolume/restorer.go#L119) was called before PVR getting updated, this error shouldn't appear.

**Comment by Dannhausen** [comment] 2024-06-13 04:30
Thanks for your time. I forgot to say that those error messages don´t appear during the backup progress.
So our backup is running at 5:00 AM, those error messages appear for example at 4:00 pm.

**Comment by Dannhausen** [comment] 2024-06-19 04:46
Any new thoughts? Or can i just ignore this messages?

**Comment by blackpiglet** [comment] 2024-06-21 08:11
Is it possible that the Velero server pod restarted during the PodVolume backup process?

**Comment by Dannhausen** [comment] 2024-06-21 08:23
Nope.
Backup runs at 5:00 AM and needs about 10-15 minutes.
Those messages appears in the log files troughout the day like:
time="2024-06-19T16:16:58Z" level=error msg="No results channel found for pod lmc/psql-lmc-2 to send pod volume backup velero/lmc-prod-backup-20240619030053-f8bqq on" logSource="pkg/podvolume/backupper.go:135"

At this time there is no Backup progress active.

**Comment by blackpiglet** [comment] 2024-06-21 09:17
Thanks for the update.
Could you help to collect the debug bundle by running `velero debug` CLI?

**Comment by Dannhausen** [comment] 2024-06-21 09:34
[velero-bundle.zip](https://github.com/user-attachments/files/15925666/velero-bundle.zip)
i´ve deleted some areas with internal informations

**Comment by Dannhausen** [comment] 2024-06-21 10:14
[velero-bundle.zip](https://github.com/user-attachments/files/15926169/velero-bundle.zip)
some parts were deleted because of nonofficial informations

**Comment by blackpiglet** [comment] 2024-06-24 02:12
Checked the uploaded bundles, but I didn't find the reported error information.
I did find some PVB failed due to Velero node-agent restart.
```
            "status": {
                "completionTimestamp": "2024-06-13T03:01:13Z",
                "message": "get a podvolumebackup with status \"InProgress\" during the server starting, mark it as \"Failed\"",
                "phase": "Failed",
                "progress": {},
                "startTimestamp": "2024-06-13T03:01:04Z"
            }
```

**Comment by Dannhausen** [comment] 2024-06-24 04:26
there was a node restart and after this the error didnt appeared till the velero debug command. i will provide you with a log file if it happens again.

And for the failed PVB. We had a partiallyfailed backup this day, correct. I did a manually backup and it worked. Every scheduled backup after this date was fine.

**Comment by Dannhausen** [comment] 2024-06-27 04:18
[velero_log_nochannelfound.txt](https://github.com/user-attachments/files/16007858/velero_log_nochannelfound.txt)

search for timestamp 2024-06-26T15:19:01

**Comment by blackpiglet** [comment] 2024-06-27 05:29
It seems an empty file.

**Comment by reasonerjt** [comment] 2024-08-28 08:49
Move out of v1.15 b/c we cannot reproduce this issue and pending for more info from the author.

**Comment by Dannhausen** [comment] 2024-08-28 11:11
[velero_log_nochannelfound.txt](https://github.com/user-attachments/files/16782490/velero_log_nochannelfound.txt)
sorry for the delay :/

**Comment by blackpiglet** [comment] 2024-08-28 16:38
Not sure why the PodVolumeBackups are still updated after Backup completion.

But I think this is already fixed in v1.14.0. 
Could you please have a try with v1.14.1?

**Comment by Dannhausen** [comment] 2024-08-29 04:20
Got this error messages with 1.14.1. Did an update to 1.14.1 with helm chart version 7.1.5. 
i keep an eye on it

**Comment by blackpiglet** [comment] 2024-08-29 05:20
> [velero_log_nochannelfound.txt](https://github.com/user-attachments/files/16782490/velero_log_nochannelfound.txt) sorry for the delay :/

The provided log is collected from v1.13.2.

From the v1.14.0 code, I think the EventHandler was already deleted on PVB reaching a final phase.
https://github.com/vmware-tanzu/velero/blob/2fc6300f2239f250b40b0488c35feae59520f2d3/pkg/podvolume/backupper.go#L307-L312

**Comment by Dannhausen** [comment] 2024-08-29 06:23
ah right, my fault. different stages. i´ll do the update tomorrow on this stage

**Comment by Dannhausen** [comment] 2024-09-03 03:54
Looks good. No more messages with "No results channel found..."
Thx :)

**Closed** 2024-09-03 05:26 UTC
Labels: Needs info, Needs reproduction, PodVolume
