### ISSUE TITLE
Current BackupStorageLocations available/unavailable/unknown: 0/0/1

### ISSUE THREAD

**Issue by MGlants** [vmware-tanzu/velero#4985] opened 2022-06-10 14:12 UTC
**What steps did you take and what happened:**
level=error msg="Current BackupStorageLocations available/unavailable/unknown: 0/0/1)" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:172"

**What did you expect to happen:**
S3 working fine

[bundle-2022-06-10-17-07-06.tar.gz](https://github.com/vmware-tanzu/velero/files/8879565/bundle-2022-06-10-17-07-06.tar.gz)

**Environment:**

- Velero version (use `velero version`): 
  c3a32a116ff69164930e796495b5ce1985a34cc6-dirty
- Velero features (use `velero client config get features`): 
  NOT SET
- Kubernetes version (use `kubectl version`):
  1.23.7
- Kubernetes installer & version:
  Talos

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment] 2022-06-13 05:41
I see this chunk in the code

```
time="2022-06-10T17:05:31+03:00" level=error msg="Current BackupStorageLocations available/unavailable/unknown: 0/0/1)" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:172"
time="2022-06-10T17:06:31+03:00" level=info msg="Validating BackupStorageLocation" backup-storage-location=backup/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:130"
time="2022-06-10T17:06:31+03:00" level=info msg="BackupStorageLocations is valid, marking as available" backup-storage-location=backup/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:115"
```
it seems the controller tries to mark the bsl as available but still can't find the status correctly.

@MGlants It seems you compiled the code in `main` branch, could you confirm?  We have been changing the `status` back and forth on the main branch.  There may be inconsistency in your env between the controller code and the CRD.

I suggest you double check with a fresh install of the RC build which will be available in next couple of days.  And let us know the result.

**Comment by MGlants** [comment] 2022-06-13 20:15
Really into it, because with v1.8.1 i have `"The 'EnableCSI' feature flag was specified, but CSI API group [snapshot.storage.k8s.io/v1beta1] was not found`

**Comment by blackpiglet** [comment] 2022-06-14 01:59
@MGlants 
I think this is related to how snapshotter controller is installed. Please check whether there is a v1beta1 version of snapshot.storage.k8s.io in cluster.
Velero v1.8.1 still doesn't upgrade the snapshot client version to v1 yet.
I also suggest to uninstall Velero, and install Velero's main branch from scratch.

**Comment by blackpiglet** [comment] 2022-06-17 01:43
@MGlants 
Is Velero uninstalled and installed again, or update the Velero image to rc.1?

I suggest to uninstall Velero first: `velero uninstall --force`
Then download v1.9.0-rc.1 Velero command line from https://github.com/vmware-tanzu/velero/releases/tag/v1.9.0-rc.1
In the end, use the downloaded v1.9.0-rc.1 Velero comand line binary to install Velero again. 

This is due to Velero CRD changed a lot lately. Image updating is not enough to make it work.

**Comment by blackpiglet** [comment] 2022-06-21 07:24
Close it by now.
I can also reproduce this in environment, and it can be resolved by installing from scratch.

**Closed by blackpiglet** 2022-06-21 07:24 UTC
Labels: Needs info

**Comment by MGlants** [comment] 2022-06-21 23:56
finally managed it - upgrade crds job failed due to wrong image

**Comment by solankivikasinno** [comment] 2023-02-07 20:11
I was getting the same error  

level=error msg="Current BackupStorageLocations available/unavailable/unknown: 0/0/1)" controller=backup-storage-location 

and checked for all possible solution from my end .What actually works for me is below



i resolved this by updating the secrets as backupStorgaelocation was unavailable 
it means it was not able to access the bucket in my case as cloud credential was first empty and than when i recreated that it was wrong key with no permission on bucket
i fixed by creating the secrets again with correct key

we have four secrets in velero namespace
`cloud-credentials         Opaque                                
default-token-xwj9z       kubernetes.io/service-account-token   
velero-repo-credentials   Opaque                              =
velero-token-sxl4r        kubernetes.io/service-account-token  

in my cloud credential there was no key , so i recreated secret manually with a file having credentials with default profile 
for examaple .  Below is the content of a file secrets.txt

[default]
aws_access_key_id = your_access_key
aws_secret_access_key = your secret_key

use  this to create your opaque secrets .

kubectl create secret generic  cloud-credentials  --from-file=secrets.txt

This resolved my issue
