### ISSUE TITLE
Not found reported by "restic-wait" during restore.

### ISSUE THREAD

**Issue by junjie9021** [vmware-tanzu/velero#7314] opened 2024-01-12 09:47 UTC
velero version 1.9.0

k8s version 1.22 -> 1.26, unable to recover data
![image](https://github.com/vmware-tanzu/velero/assets/71370818/2bad83b7-fe02-425e-8777-840118c8f601)

k8s version 1.22 -> 1.22 is normal
![image](https://github.com/vmware-tanzu/velero/assets/71370818/f30a4c03-a0ae-446e-9a67-98d3e5e7cabc)

**Comment by reasonerjt** [comment] 2024-01-15 07:27
It's likely on v1.26 the restore of data is not complete.
Please provide the debug bundle of the restore on v1.26.

Additionally, the `CSIMigration` flag may impact the path of the target volume, 
@blackpiglet please link the known issue.

**Comment by junjie9021** [comment] 2024-01-15 08:28
> It's likely on v1.26 the restore of data is not complete. Please provide the debug bundle of the restore on v1.26.
> 
> Additionally, the `CSIMigration` flag may impact the path of the target volume, @blackpiglet please link the known issue.

![image](https://github.com/vmware-tanzu/velero/assets/71370818/a8156433-5ab6-415f-9767-e322dee6bd78)

**Comment by blackpiglet** [comment] 2024-01-17 05:37
@junjie9021 
https://github.com/vmware-tanzu/velero/issues/5149
Please check this issue for the CSI migration issue fixed in v1.9. 
The problem is that in v1.9, Velero didn't check the PV's migrated annotation to determine whether the PV is provisioned by CSI or by the in-tree volume plugin.

The two ways mount the volume in different directories in the pod.

Could you tell us the k8s environment provider?
Some cloud providers turned on the CSI migration feature gate by default on the k8s v1.26 cluster, but the feature is not enabled by default on v1.22.

If that is the case, you need to upgrade the Velero version at least to v1.9.6.

**Comment by junjie9021** [comment] 2024-01-17 07:18
> CSI

tks for your help, after upgrading the client to version 1.9.6, the issue was resolved and cross cluster recovery was normal.

**Comment by blackpiglet** [comment] 2024-01-17 07:32
Great. I will close this issue for now.

**Closed by blackpiglet** 2024-01-17 07:32 UTC
Labels: Needs info, area/fs-backup
