### ISSUE TITLE
Restore is not working with Amazon EFS volumes

### ISSUE THREAD

**Issue by ruzickap** [vmware-tanzu/velero#3729] opened 2021-04-25 05:10 UTC
**What steps did you take and what happened:**
I would like to backup+restore namespace which contains [Amazon EFS CSI dynamically provisioned volume](https://aws.amazon.com/blogs/containers/introducing-efs-csi-dynamic-provisioning/).

Backup is working fine, but restore part ends with "lchown" + "operation not permitted" errors: 

```
stderr=ignoring error for /out.txt: Lchown: lchown /host_pods/7fd99083-163a-46e4-81b0-0ebd4c3d0413/volumes/kubernetes.io~csi/pvc-9e83fe12-c0ec-48b5-b180-cf7997a0e7e4/mount/out.txt: operation not permitted\nFatal: There were 1 errors\n\n: exit status 1"
```

Test example:

Install [Amazon EFS CSI Driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver):
(you need to have EFS provisioned and have (`FileSystemId` = `${EFS_FS_ID}`)

```bash
helm repo add aws-efs-csi-driver https://kubernetes-sigs.github.io/aws-efs-csi-driver/
helm install --version 1.2.2 --namespace kube-system --values - aws-efs-csi-driver aws-efs-csi-driver/aws-efs-csi-driver << EOF
serviceAccount:
  controller:
    create: false
storageClasses:
- name: efs-dynamic-sc
  parameters:
    provisioningMode: efs-ap
    fileSystemId: "${EFS_FS_ID}"
    directoryPerms: "700"
    basePath: "/dynamic_provisioning"
EOF
```

Install Velero:

```bash
helm repo add vmware-tanzu https://vmware-tanzu.github.io/helm-charts
helm upgrade --version 2.19.1 --namespace velero --create-namespace --values - velero vmware-tanzu/velero << EOF
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.2.0
    imagePullPolicy: Always
    volumeMounts:
      - mountPath: /target
        name: plugins
  - name: velero-plugin-for-csi
    image: velero/velero-plugin-for-csi:v0.1.2
    imagePullPolicy: Always
    volumeMounts:
      - mountPath: /target
        name: plugins
configuration:
  provider: aws
  backupStorageLocation:
    bucket: ${CLUSTER_FQDN}
    prefix: velero
    config:
      region: ${AWS_DEFAULT_REGION}
  volumeSnapshotLocation:
    name: aws
    config:
      region: ${AWS_DEFAULT_REGION}
serviceAccount:
  server:
    create: false
    name: velero
credentials:
  useSecret: false
deployRestic: true
EOF
```

Create test namespace `backup-test` with pod and PVC:

```
kubectl apply -f - << EOF
apiVersion: v1
kind: Namespace
metadata:
  name: backup-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-backup-test-pv
  namespace: backup-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-dynamic-sc
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-app
  namespace: backup-test
spec:
  containers:
  - name: app
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-backup-test-pv
EOF
```

Run backup of "backup-test" namespace:

```bash
velero backup create backup-test --default-volumes-to-restic --ttl 24h --include-namespaces=backup-test
```

Check the backups:

```bash
velero get backups

NAME          STATUS      ERRORS   WARNINGS   CREATED                          EXPIRES   STORAGE LOCATION   SELECTOR
backup-test   Completed   0        0          2021-04-24 12:02:10 +0200 CEST   23h       default            <none>
```

Remove "backup-test" namespace:

```bash
kubectl delete namespace backup-test
```

Restore the object in the "backup-test" namespace:

```bash
velero restore create restore-backup-test --from-backup backup-test --include-namespaces backup-test
```

Get the logs:

```bash
velero restore logs restore-backup-test


time="2021-04-25T05:00:26Z" level=info msg="starting restore" logSource="pkg/controller/restore_controller.go:465" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Starting restore of backup velero/backup-test" logSource="pkg/restore/restore.go:383" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Skipping restore of resource because it cannot be resolved via discovery" logSource="pkg/restore/restore.go:1584" resource=volumesnapshotclass.snapshot.storage.k8s.io restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Skipping restore of resource because it cannot be resolved via discovery" logSource="pkg/restore/restore.go:1584" resource=volumesnapshotcontents.snapshot.storage.k8s.io restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Skipping restore of resource because it cannot be resolved via discovery" logSource="pkg/restore/restore.go:1584" resource=volumesnapshots.snapshot.storage.k8s.io restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Skipping resource persistentvolumes because it's cluster-scoped and only specific namespaces are included in the restore" logSource="pkg/restore/restore.go:1639" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Resource 'persistentvolumeclaims' will be restored into namespace 'backup-test'" logSource="pkg/restore/restore.go:1671" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Resource 'secrets' will be restored into namespace 'backup-test'" logSource="pkg/restore/restore.go:1671" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Resource 'serviceaccounts' will be restored into namespace 'backup-test'" logSource="pkg/restore/restore.go:1671" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Resource 'pods' will be restored into namespace 'backup-test'" logSource="pkg/restore/restore.go:1671" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Skipping restore of resource because it cannot be resolved via discovery" logSource="pkg/restore/restore.go:1584" resource=clusters.cluster.x-k8s.io restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Skipping restore of resource because it cannot be resolved via discovery" logSource="pkg/restore/restore.go:1584" resource=clusterresourcesets.addons.cluster.x-k8s.io restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Skipping restore of resource because the restore spec excludes it" logSource="pkg/restore/restore.go:1601" resource=events restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Getting client for /v1, Kind=PersistentVolumeClaim" logSource="pkg/restore/restore.go:811" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:1061" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Executing AddPVFromPVCAction" cmd=/velero logSource="pkg/restore/add_pv_from_pvc_action.go:44" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Adding PV pvc-e81214c4-cbdf-4a94-b1a5-510211c2a714 as an additional item to restore" cmd=/velero logSource="pkg/restore/add_pv_from_pvc_action.go:66" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Getting client for /v1, Kind=PersistentVolume" logSource="pkg/restore/restore.go:811" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Dynamically re-provisioning persistent volume because it has a restic backup to be restored." logSource="pkg/restore/restore.go:1020" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:1061" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Executing ChangePVCNodeSelectorAction" cmd=/velero logSource="pkg/restore/change_pvc_node_selector.go:65" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Done executing ChangePVCNodeSelectorAction" cmd=/velero logSource="pkg/restore/change_pvc_node_selector.go:93" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:1061" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Executing ChangeStorageClassAction" cmd=/velero logSource="pkg/restore/change_storageclass_action.go:65" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Done executing ChangeStorageClassAction" cmd=/velero logSource="pkg/restore/change_storageclass_action.go:76" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:1061" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Starting PVCRestoreItemAction for PVC backup-test/efs-backup-test-pv" cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/restore/pvc_action.go:96" pluginName=velero-plugin-for-csi restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Skipping PVCRestoreItemAction for PVC backup-test/efs-backup-test-pv, PVC does not have a CSI volumesnapshot." cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/restore/pvc_action.go:102" pluginName=velero-plugin-for-csi restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Resetting PersistentVolumeClaim backup-test/efs-backup-test-pv for dynamic provisioning" logSource="pkg/restore/restore.go:1140" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Attempting to restore PersistentVolumeClaim: efs-backup-test-pv" logSource="pkg/restore/restore.go:1166" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Getting client for /v1, Kind=Secret" logSource="pkg/restore/restore.go:811" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Attempting to restore Secret: default-token-w27v9" logSource="pkg/restore/restore.go:1166" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Getting client for /v1, Kind=ServiceAccount" logSource="pkg/restore/restore.go:811" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Executing item action for serviceaccounts" logSource="pkg/restore/restore.go:1061" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Executing ServiceAccountAction" cmd=/velero logSource="pkg/restore/service_account_action.go:47" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Done executing ServiceAccountAction" cmd=/velero logSource="pkg/restore/service_account_action.go:78" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Attempting to restore ServiceAccount: default" logSource="pkg/restore/restore.go:1166" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Getting client for /v1, Kind=Pod" logSource="pkg/restore/restore.go:811" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Executing item action for pods" logSource="pkg/restore/restore.go:1061" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Executing AddPVCFromPodAction" cmd=/velero logSource="pkg/restore/add_pvc_from_pod_action.go:44" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Adding PVC backup-test/efs-backup-test-pv as an additional item to restore" cmd=/velero logSource="pkg/restore/add_pvc_from_pod_action.go:58" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Skipping persistentvolumeclaims/backup-test/efs-backup-test-pv because it's already been restored." logSource="pkg/restore/restore.go:919" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Executing item action for pods" logSource="pkg/restore/restore.go:1061" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Executing InitRestoreHookPodAction" cmd=/velero logSource="pkg/restore/init_restorehook_pod_action.go:49" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Pod backup-test/test-app has no init.hook.restore.velero.io/container-image annotation, no initRestoreHook in annotation" cmd=/velero logSource="internal/hook/item_hook_handler.go:350" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Handling InitRestoreHooks from RestoreSpec" cmd=/velero logSource="internal/hook/item_hook_handler.go:138" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Returning pod backup-test/test-app with 0 init container(s)" cmd=/velero logSource="internal/hook/item_hook_handler.go:157" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Returning from InitRestoreHookPodAction" cmd=/velero logSource="pkg/restore/init_restorehook_pod_action.go:57" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Executing item action for pods" logSource="pkg/restore/restore.go:1061" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Executing item action for pods" logSource="pkg/restore/restore.go:1061" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Executing ResticRestoreAction" cmd=/velero logSource="pkg/restore/restic_restore_action.go:71" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Restic backups for pod found" cmd=/velero logSource="pkg/restore/restic_restore_action.go:106" pluginName=velero pod=backup-test/test-app restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Using image \"velero/velero-restic-restore-helper:v1.6.0\"" cmd=/velero logSource="pkg/restore/restic_restore_action.go:117" pluginName=velero pod=backup-test/test-app restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Done executing ResticRestoreAction" cmd=/velero logSource="pkg/restore/restic_restore_action.go:175" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Attempting to restore Pod: test-app" logSource="pkg/restore/restore.go:1166" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Waiting for all restic restores to complete" logSource="pkg/restore/restore.go:575" restore=velero/restore-backup-test
time="2021-04-25T05:00:37Z" level=error msg="unable to successfully complete restic restores of pod's volumes" error="pod volume restore failed: error restoring volume: error running restic restore, cmd=restic restore --repo=s3:s3-eu-central-1.amazonaws.com/kube1.k8s.mylabs.dev/velero/restic/backup-test --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic d4f55967 --target=., stdout=restoring <Snapshot d4f55967 of [/host_pods/afcce7b7-b463-4181-acc3-dc5c93e6f8d8/volumes/kubernetes.io~csi/pvc-e81214c4-cbdf-4a94-b1a5-510211c2a714/mount] at 2021-04-24 10:02:13.146253889 +0000 UTC by root@velero> to .\n, stderr=ignoring error for /out.txt: Lchown: lchown /host_pods/7fd99083-163a-46e4-81b0-0ebd4c3d0413/volumes/kubernetes.io~csi/pvc-9e83fe12-c0ec-48b5-b180-cf7997a0e7e4/mount/out.txt: operation not permitted\nFatal: There were 1 errors\n\n: exit status 1" logSource="pkg/restore/restore.go:1358" restore=velero/restore-backup-test
time="2021-04-25T05:00:37Z" level=info msg="Done waiting for all restic restores to complete" logSource="pkg/restore/restore.go:591" restore=velero/restore-backup-test
time="2021-04-25T05:00:37Z" level=info msg="Waiting for all post-restore-exec hooks to complete" logSource="pkg/restore/restore.go:595" restore=velero/restore-backup-test
time="2021-04-25T05:00:37Z" level=info msg="Done waiting for all post-restore exec hooks to complete" logSource="pkg/restore/restore.go:603" restore=velero/restore-backup-test
time="2021-04-25T05:00:37Z" level=info msg="restore completed" logSource="pkg/controller/restore_controller.go:480" restore=velero/restore-backup-test
```

```
kubectl logs deployment/velero -n velero
...
...
...
time="2021-04-25T05:00:26Z" level=info msg="Pod backup-test/test-app has no init.hook.restore.velero.io/container-image annotation, no initRestoreHook in annotation" cmd=/velero logSource="internal/hook/item_hook_handler.go:350" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Handling InitRestoreHooks from RestoreSpec" cmd=/velero logSource="internal/hook/item_hook_handler.go:138" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Returning pod backup-test/test-app with 0 init container(s)" cmd=/velero logSource="internal/hook/item_hook_handler.go:157" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Returning from InitRestoreHookPodAction" cmd=/velero logSource="pkg/restore/init_restorehook_pod_action.go:57" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Executing item action for pods" logSource="pkg/restore/restore.go:1061" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Executing item action for pods" logSource="pkg/restore/restore.go:1061" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Executing ResticRestoreAction" cmd=/velero logSource="pkg/restore/restic_restore_action.go:71" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Restic backups for pod found" cmd=/velero logSource="pkg/restore/restic_restore_action.go:106" pluginName=velero pod=backup-test/test-app restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Using image \"velero/velero-restic-restore-helper:v1.6.0\"" cmd=/velero logSource="pkg/restore/restic_restore_action.go:117" pluginName=velero pod=backup-test/test-app restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Done executing ResticRestoreAction" cmd=/velero logSource="pkg/restore/restic_restore_action.go:175" pluginName=velero restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Attempting to restore Pod: test-app" logSource="pkg/restore/restore.go:1166" restore=velero/restore-backup-test
time="2021-04-25T05:00:26Z" level=info msg="Waiting for all restic restores to complete" logSource="pkg/restore/restore.go:575" restore=velero/restore-backup-test
time="2021-04-25T05:00:37Z" level=error msg="unable to successfully complete restic restores of pod's volumes" error="pod volume restore failed: error restoring volume: error running restic restore, cmd=restic restore --repo=s3:s3-eu-central-1.amazonaws.com/kube1.k8s.mylabs.dev/velero/restic/backup-test --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic d4f55967 --target=., stdout=restoring <Snapshot d4f55967 of [/host_pods/afcce7b7-b463-4181-acc3-dc5c93e6f8d8/volumes/kubernetes.io~csi/pvc-e81214c4-cbdf-4a94-b1a5-510211c2a714/mount] at 2021-04-24 10:02:13.146253889 +0000 UTC by root@velero> to .\n, stderr=ignoring error for /out.txt: Lchown: lchown /host_pods/7fd99083-163a-46e4-81b0-0ebd4c3d0413/volumes/kubernetes.io~csi/pvc-9e83fe12-c0ec-48b5-b180-cf7997a0e7e4/mount/out.txt: operation not permitted\nFatal: There were 1 errors\n\n: exit status 1" logSource="pkg/restore/restore.go:1358" restore=velero/restore-backup-test
time="2021-04-25T05:00:37Z" level=info msg="Done waiting for all restic restores to complete" logSource="pkg/restore/restore.go:591" restore=velero/restore-backup-test
time="2021-04-25T05:00:37Z" level=info msg="Waiting for all post-restore-exec hooks to complete" logSource="pkg/restore/restore.go:595" restore=velero/restore-backup-test
time="2021-04-25T05:00:37Z" level=info msg="Done waiting for all post-restore exec hooks to complete" logSource="pkg/restore/restore.go:603" restore=velero/restore-backup-test
time="2021-04-25T05:00:37Z" level=info msg="restore completed" logSource="pkg/controller/restore_controller.go:480" restore=velero/restore-backup-test
time="2021-04-25T05:01:12Z" level=info msg="Validating backup storage location" backup-storage-location=default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:114"
time="2021-04-25T05:01:12Z" level=info msg="Backup storage location valid, marking as available" backup-storage-location=default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:121"
time="2021-04-25T05:01:26Z" level=info msg="Checking for expired DeleteBackupRequests" controller=backup-deletion logSource="pkg/controller/backup_deletion_controller.go:596"
time="2021-04-25T05:01:26Z" level=info msg="Done checking for expired DeleteBackupRequests" controller=backup-deletion logSource="pkg/controller/backup_deletion_controller.go:624"
I0425 05:01:51.135081       1 request.go:645] Throttling request took 1.04551807s, request: GET:https://10.100.0.1:443/apis/node.k8s.io/v1beta1?timeout=32s
```

```
velero restore describe restore-backup-test

Name:         restore-backup-test
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:                       PartiallyFailed (run 'velero restore logs restore-backup-test' for more information)
Total items to be restored:  6
Items restored:              6

Started:    2021-04-25 07:00:25 +0200 CEST
Completed:  2021-04-25 07:00:37 +0200 CEST

Errors:
  Velero:  pod volume restore failed: error restoring volume: error running restic restore, cmd=restic restore --repo=s3:s3-eu-central-1.amazonaws.com/kube1.k8s.mylabs.dev/velero/restic/backup-test --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic d4f55967 --target=., stdout=restoring <Snapshot d4f55967 of [/host_pods/afcce7b7-b463-4181-acc3-dc5c93e6f8d8/volumes/kubernetes.io~csi/pvc-e81214c4-cbdf-4a94-b1a5-510211c2a714/mount] at 2021-04-24 10:02:13.146253889 +0000 UTC by root@velero> to .
, stderr=ignoring error for /out.txt: Lchown: lchown /host_pods/7fd99083-163a-46e4-81b0-0ebd4c3d0413/volumes/kubernetes.io~csi/pvc-9e83fe12-c0ec-48b5-b180-cf7997a0e7e4/mount/out.txt: operation not permitted
Fatal: There were 1 errors

: exit status 1
  Cluster:    <none>
  Namespaces: <none>

Backup:  backup-test

Namespaces:
  Included:  backup-test
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

Restic Restores (specify --details for more information):
  Failed:  1

Preserve Service NodePorts:  auto
```

**Environment:**

- Velero version (use `velero version`): `Client: Version: v1.6.0` | `Server: Version: v1.6.0`
- Velero features (use `velero client config get features`): `features: <NOT SET>`
- Kubernetes version (use `kubectl version`): `v1.21.0`
- Kubernetes installer & version: `v1.19.8-eks-96780e`
- Cloud provider or hardware configuration: Amazon EKS
- OS (e.g. from `/etc/os-release`): AmazonLinux2

**Comment by nrb** [comment] 2021-05-12 19:10
We have EFS issues tracked in #2958, I'm gonna close this as a duplicate.

**Closed by nrb** 2021-05-12 19:10 UTC
Labels: Bug, Duplicate, Reviewed Q2 2021

**Comment by ruzickap** [comment] 2021-05-13 04:37
I'm fine to have this issue closed, but the issue described here is different from what is in #2958.

In this case the "velero restore" can successfully create PVC - the part which is failing is restic restore to NFS (EFS).

Here are some details captured after failed `velero restore create restore-backup-test --from-backup backup-test --include-namespaces backup-test`

```bash
### The PVC was successfully created by velero
$ kubectl get pvc -n backup-test
NAME                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     AGE
efs-backup-test-pv   Bound    pvc-0289df43-6b28-4b95-a208-c9d3b5554910   1Gi        RWX            efs-dynamic-sc   8h


### Velero can not restore the data
$ kubectl describe all -n backup-test
Name:         test-app
Namespace:    backup-test
Priority:     0
Node:         ip-192-168-27-239.eu-central-1.compute.internal/192.168.27.239
Start Time:   Wed, 12 May 2021 22:15:51 +0200
Labels:       velero.io/backup-name=backup-test
              velero.io/restore-name=restore-backup-test
Annotations:  cni.projectcalico.org/podIP: 172.16.88.23/32
              cni.projectcalico.org/podIPs: 172.16.88.23/32
              kubernetes.io/psp: eks.privileged
Status:       Pending
IP:           172.16.88.23
IPs:
  IP:  172.16.88.23
Init Containers:
  restic-wait:
    Container ID:  docker://21db4bae22f64437066720d2982e5f8b0c0791e6ddccaf5f8c6ce40171d83653
    Image:         velero/velero-restic-restore-helper:v1.6.0
    Image ID:      docker-pullable://velero/velero-restic-restore-helper@sha256:bc903cfe6de2cbdfa4a73166539476c75a85dc99a0915b25902d8d0c6718ba0a
    Port:          <none>
    Host Port:     <none>
    Command:
      /velero-restic-restore-helper
    Args:
      f94a940b-5523-4555-8b33-6c13bbd2ac67
    State:          Running
      Started:      Wed, 12 May 2021 22:15:58 +0200
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  128Mi
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment:
      POD_NAMESPACE:  backup-test (v1:metadata.namespace)
      POD_NAME:       test-app (v1:metadata.name)
    Mounts:
      /restores/persistent-storage from persistent-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-r4nrz (ro)
Containers:
  app:
    Container ID:
    Image:         alpine
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
      while true; do date >> /data/out.txt; sleep 5; done
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  128Mi
    Requests:
      cpu:        250m
      memory:     64Mi
    Environment:  <none>
    Mounts:
      /data from persistent-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-r4nrz (ro)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  persistent-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  efs-backup-test-pv
    ReadOnly:   false
  default-token-r4nrz:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-r4nrz
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:          <none>


###
$ kubectl logs -n backup-test test-app --all-containers | tail
Error from server (BadRequest): container "app" in pod "test-app" is waiting to start: PodInitializing
Not found: /restores/persistent-storage/.velero/f94a940b-5523-4555-8b33-6c13bbd2ac67
```

I agree that it's related to "EFS restore issues" and it doesn't make sense to have two duplicated issues.

**Comment by mrad-bilel** [comment] 2021-06-30 14:10
Any update on this issue

**Comment by aboyanov** [comment] 2021-08-09 20:53
Any updates here? I've got exactly the same case. The backup is successful, but the restore is failing with the same error:

`level=error msg="unable to successfully complete restic restores of pod's volumes" error="pod volume restore failed: error restoring volume: error running restic restore, cmd=restic restore --repo=s3:s3-us-east-1.amazonaws.com/eks-backup-infra-delivery-lab/infra-delivery-lab/restic/efs-test --password-file=/tmp/credentials/kube-system/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic6bccfa00 --target=., stdout=restoring <Snapshot 6bccfa00 of [/host_pods/cdf3dca0-d2e6-4127-843f-1c0ec3da3940/volumes/kubernetes.io~csi/pvc-d03c133f-1d3b-4a8f-bf92-e8a032cb21a4/mount] at 2021-08
-09 19:50:45.457306829 +0000 UTC by root@velero> to .\n, stderr=ignoring error for /alex-3.txt: Lchown: lchown /host_pods/cdc7c97d-f35d-43ab-a0f4-16e8781637c8/volumes/kubernetes.io~csi/pvc-f40bb58e-9e12-4538-b325-
35e537ea3a3f/mount/alex-3.txt: operation not permitted\nignoring error for /out: Lchown: lchown /host_pods/cdc7c97d-f35d-43ab-a0f4-16e8781637c8/volumes/kubernetes.io~csi/pvc-f40bb58e-9e12-4538-b325-35e537ea3a3f/mount/out: operation not permitted\nFatal: There were 2 errors\n\n: exit status 1" logSource="pkg/restore/restore.go:1438" restore=kube-system/efs7-20210809225719`

**Comment by sazecis** [comment] 2021-12-01 11:41
I would also like to request a re-open of this ticket. It is different then the one at: https://github.com/vmware-tanzu/velero/issues/2958. There the problem is with the PV creation, which can be worked around if I create the PVs manually but this problem after that.
The issue with lchown actually is within restic, so maybe the ticket should go there and not for velero. Which one do you suggest?
In restic the error occurs when the root@velero user tries to restore the metadata. During this it tries to modify the owner of the restored dir to the new owner. But the problem with this is that EFS by default has does not allow lchown: https://docs.aws.amazon.com/efs/latest/ug/accessing-fs-nfs-permissions.html.

In restic there are already exception to not to call chown for widows os and for non root user.

What could be done and actually could remove further problems to introduce a parameter/switch in both velero and restic to turn of chown for restoring metadata.

Hope that this helps.
Thanks,
Csaba

**Comment by sazecis** [comment] 2021-12-03 11:42
The workaround for me was that I changed the runAsUser of the restic daemonset to a non root value.
Edit daemonset: `k edit daemonset/restic -n velero`
search for runAsUser and change it to e.g. 1001. 

With this the restic won't try to lchown the restored metadata.

Restore now to efs storageclass works almost like a charm. Almost because https://github.com/vmware-tanzu/velero/issues/2958 it still blocks to automatically create PV but the workaround there is to create the PVC beforehand, which creates the PVs and then do restore the POD which also restores the volumes.
