### ISSUE TITLE
Multi-goroutine backup/restore

### ISSUE THREAD

**Issue by Gus6324** [vmware-tanzu/velero#8079] opened 2024-08-03 12:40 UTC
### problem/challenge

The current `BackupWithResolvers` function in Velero processes backup items sequentially. This serial processing can be a performance bottleneck, especially for large Kubernetes clusters with many resources. It results in longer backup times, which can impact the overall efficiency and reliability of backup operations in large-scale environments.

### Solution proposal

Modify the `BackupWithResolvers` function to process backup items concurrently using goroutines. This will involve:

1. Creating a worker pool to manage the concurrent processing of backup items.
2. Using channels to communicate between the main backup loop and the worker goroutines.

### Environment:

- Velero version (use `velero version`): v1.14.0
- Kubernetes version (use `kubectl version`): v1.29
- Kubernetes installer & version: kubeadm 1.29
- Cloud provider: AWS,Azure,GCP
- OS: Ubuntu 20.04

### Vote on this issue!

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- 👍 for "The project would be better with this feature added"
- 👎 for "This feature will not enhance the project in a meaningful way"

**Comment by kaovilai** [comment] 2024-08-05 02:42
Close as dupe of https://github.com/vmware-tanzu/velero/issues/7900 ?

**Closed** 2024-08-05 02:49 UTC
