### ISSUE TITLE
kopia backup failed when data generated using dd ,exit on "dd_file: ConcatenateObjects is not supported"

### ISSUE THREAD

**Issue by TzahiAshkenazi** [vmware-tanzu/velero#6880] opened 2023-09-27 09:42 UTC
**What steps did you take and what happened:**
Running kopia backup .
create SN with single file created using "dd"  with the flowing parameters:
```
 expected_capacity:  '1.1T' 
 bs: '1M'
 count : '1048576'
 pv_size: '1100Gi'
  sc : 'ocs-storagecluster-ceph-rbd'
```

disk usage from the pod: 
```
(app-root) bash-4.2$ du -sh /opt/mounts/mnt1
1.1T	/opt/mounts/mnt1
```

main error : 
```
Error when processing dd_file: ConcatenateObjects is not supported
```

Backup CR failed exit on : "PartiallyFailed"

the error : 
```
[root@f07-h27-000-r640 velero]# ./velero   backup describe  dd-test-1tb-velero-1-12 -nvelero-1-12
Name:         dd-test-1tb-velero-1-12
Namespace:    velero-1-12
Labels:       velero.io/storage-location=default
Annotations:  velero.io/resource-timeout=10m0s
              velero.io/source-cluster-k8s-gitversion=v1.24.14+38b1413
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=24

Phase:  PartiallyFailed (run `velero backup logs dd-test-1tb-velero-1-12` for more information)


Errors:
  Velero:    name: /deploy-perf-datagen-2-3-0-9-rbd-0-765bc566f5-hcw76 error: /pod volume backup failed: data path backup failed: Failed to run kopia backup: Error when processing dd_file: ConcatenateObjects is not supported
  Cluster:    <none>
  Namespaces: <none>

Namespaces:
  Included:  perf-datagen-case4-rbd
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  false
Snapshot Move Data:          auto
Data Mover:                  velero

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  4h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2023-09-27 08:25:07 +0000 UTC
Completed:  2023-09-27 08:32:03 +0000 UTC

Expiration:  2023-10-27 08:25:07 +0000 UTC

Total items to be backed up:  26
Items backed up:              26

Velero-Native Snapshots: <none included>

kopia Backups (specify --details for more information):
  Failed:  1

```

**What did you expect to happen:**
backup CR will complete successfully

**Anything else you would like to add:**
tested on both  velero images : 

```
velero/velero:release-1.12-dev
velero/velero:v1.12.0
```

**Environment:**
Version: velero/velero:v1.12.0

features:

Kubernetes version : Kustomize Version: v4.5.4

Kubernetes installer & version:

Cloud provider or hardware configuration:
OCP running over BM servers
3 masters & 12 workers nodes

OS (e.g. from /etc/os-release):

NAME="Red Hat Enterprise Linux CoreOS"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION="411.86.202306021408-0"
VERSION_ID="4.11"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 411.86.202306021408-0 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::coreos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://docs.openshift.com/container-platform/4.11/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.11"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.11"
OPENSHIFT_VERSION="4.11"
RHEL_VERSION="8.6"
OSTREE_VERSION="411.86.202306021408-0"

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
[dd_issue_kopia.tar.gz](https://github.com/vmware-tanzu/velero/files/12737088/dd_issue_kopia.tar.gz)

**Comment by weshayutin** [comment] 2023-09-27 12:02
FYI: https://github.com/vmware-tanzu/velero/blame/c3ec7b71c56dbd0440fb48a0232d8cd8e9b38567/pkg/uploader/kopia/shim.go#L240

**Comment by anshulahuja98** [comment] 2023-09-28 04:48
I also hit the same issue with CSI datamover.
initiall there was a file a.txt of 16KB
I increased the file to 19GB
After that backup went to partial fail with error
data path backup failed: Failed to run kopia backup: Error when processing a.txt: ConcatenateObjects is not supported

**Comment by anshulahuja98** [comment] 2023-09-28 04:53
Further repro
I renamed a.txt to b.txt
Still seeing same issue.

**Comment by anshulahuja98** [comment] 2023-09-28 05:06
time="2023-09-28T05:04:31Z" level=error msg="Error when processing c.txt: ConcatenateObjects is not supported" controller=dataupload dataupload=velero/backup8-jpgst logSource="pkg/uploader/kopia/progress.go:86" parentSnapshot= path="/host_pods/7022914a-68e8-4198-b92c-134073c6aaf9/volumes/kubernetes.io~csi/pvc-585eea55-68d2-4484-b3f8-3ec4de43cc94/mount" realSource=default/azurediskpvc
time="2023-09-28T05:04:31Z" level=info msg="Created snapshot with root kde22185bf051c8821b8a9a99df697252 and ID 1875335d3eb91f14dd117530e8c0d9a9 in 1m39s" controller=dataupload dataupload=velero/backup8-jpgst logSource="pkg/uploader/kopia/snapshot.go:267" parentSnapshot= path="/host_pods/7022914a-68e8-4198-b92c-134073c6aaf9/volumes/kubernetes.io~csi/pvc-585eea55-68d2-4484-b3f8-3ec4de43cc94/mount" realSource=default/azurediskpvc
time="2023-09-28T05:04:31Z" level=error msg="Async fs backup data path failed" dataupload=backup8-jpgst error="Failed to run kopia backup: Error when processing c.txt: ConcatenateObjects is not supported" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/uploader/kopia/snapshot.go:286" error.function=github.com/vmware-tanzu/velero/pkg/uploader/kopia.reportSnapshotStatus logSource="pkg/controller/data_upload_controller.go:399"
time="2023-09-28T05:04:31Z" level=info msg="Action finished" controller=dataupload dataupload=velero/backup8-jpgst logSource="pkg/uploader/provider/kopia.go:91"
time="2023-09-28T05:04:31Z" level=warning msg="Failed to patch dataupload with err Failed to run kopia backup: Error when processing c.txt: ConcatenateObjects is not supported" dataupload=backup8-jpgst error="Failed to run kopia backup: Error when processing c.txt: ConcatenateObjects is not supported" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/uploader/kopia/snapshot.go:286" error.function=github.com/vmware-tanzu/velero/pkg/uploader/kopia.reportSnapshotStatus logSource="pkg/controller/data_upload_controller.go:406"
time="2023-09-28T05:04:31Z" level=info msg="Reconcile backup8-jpgst" controller=dataupload dataupload=velero/backup8-jpgst logSource="pkg/controller/data_upload_controller.go:113"
time="2023-09-28T05:04:31Z" level=info msg="Reconcile backup8-jpgst" controller=dataupload dataupload=velero/backup8-jpgst logSource="pkg/controller/data_upload_controller.go:113"
time="2023-09-28T05:04:31Z" level=info msg="FileSystemBR is closed" controller=dataupload dataupload=velero/backup8-jpgst logSource="pkg/datapath/file_system.go:129" user=backup8-jpgst

**Comment by Lyndon-Li** [comment] 2023-09-28 06:19
The cause of this issue is that Velero's policy was not correctly set to Kopia, as a result, the default policy was used. By the default policy, files that are larger than 2GB will go to the ConcatenateObjects operation which is not supported by Velero unified repo API.

**Comment by anshulahuja98** [comment] 2023-09-28 06:32
I see, will try out again with the build once your changes are checked in.
Thanks for the quick fix!

**Closed** 2023-09-28 07:17 UTC
Labels: target/1.10.4, target/1.11.2, target/1.12.1, area/fs-uploader

**Comment by TzahiAshkenazi** [comment] 2023-10-01 07:48
F.Y.I
this bug reproduce also with python data generator ( not dd)
created 100 files each file size is 10GB total capacity is TB 
```
[root@f07-h27-000-r640 velero]# ./velero  backup describe backup-kopia-pvc-util-2-4-1-9-rbd-100f-10gb-1001g  -nvelero-1-12
Name:         backup-kopia-pvc-util-2-4-1-9-rbd-100f-10gb-1001g
Namespace:    velero-1-12
Labels:       velero.io/storage-location=default
Annotations:  velero.io/resource-timeout=10m0s
              velero.io/source-cluster-k8s-gitversion=v1.24.14+38b1413
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=24

Phase:  PartiallyFailed (run `velero backup logs backup-kopia-pvc-util-2-4-1-9-rbd-100f-10gb-1001g` for more information)


Errors:
  Velero:   name: /deploy-perf-datagen-2-4-1-9-rbd-0-787b875769-b5626 error: /pod volume backup failed: data path backup failed: Failed to run kopia backup: Error when processing python/my-dir-name-0/my-random-file-0.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-1.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-10.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-11.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-12.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-13.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-14.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-15.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-16.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-17.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-18.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-19.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-2.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-20.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-21.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-22.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-23.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-24.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-25.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-26.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-27.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-28.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-29.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-3.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-30.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-31.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-32.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-33.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-34.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-35.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-36.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-37.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-38.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-39.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-4.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-40.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-41.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-42.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-43.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-44.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-45.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-46.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-47.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-48.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-49.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-5.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-50.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-51.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-52.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-53.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-54.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-55.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-56.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-57.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-58.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-59.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-6.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-60.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-61.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-62.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-63.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-64.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-65.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-66.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-67.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-68.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-69.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-7.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-70.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-71.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-72.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-73.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-74.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-75.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-76.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-77.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-78.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-79.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-8.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-80.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-81.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-82.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-83.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-84.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-85.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-86.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-87.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-88.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-89.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-9.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-90.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-91.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-92.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-93.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-94.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-95.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-96.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-97.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-98.data: ConcatenateObjects is not supported
Error when processing python/my-dir-name-0/my-random-file-99.data: ConcatenateObjects is not supported
  Cluster:    <none>
  Namespaces: <none>

Namespaces:
  Included:  perf-datagen-case3-rbd
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  false
Snapshot Move Data:          auto
Data Mover:                  velero

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  4h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2023-09-28 14:42:52 +0000 UTC
Completed:  2023-09-28 15:01:50 +0000 UTC

Expiration:  2023-10-28 14:42:52 +0000 UTC

Total items to be backed up:  39
Items backed up:              39

Velero-Native Snapshots: <none included>

kopia Backups (specify --details for more information):
  Failed:  1

```

**Comment by pseymournutanix** [comment] 2023-10-21 08:30
Tested 1.12.1-rc.1 and this seems resolved although for one of mine I am seeing these warnings/errors issued 

```
 time="2023-10-21T02:26:53Z" level=warning msg="volume var-files is declared in pod argocd/argocd-repo-server-b865cd5db-92s5l but not mounted by any container, skipping" backup=velero/dre-services-beta-daily-fs-20231021020035 logSource="pkg/podvolume/backupper.go:284" name=argocd-repo-server-b865cd5db-92s5l namespace=argocd resource=pods
time="2023-10-21T04:38:55Z" level=error msg="Error backing up item" backup=velero/dre-services-beta-daily-fs-20231021020035 error="pod volume backup failed: data path backup failed: Failed to run kopia backup: Error when processing mount/main/builds: no such file or directory\nError when processing mount/main/devtools: no such file or directory\nError when processing mount/main/minerva_nvm/minerva: no such file or directory" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podvolume/backupper.go:324" error.function="github.com/vmware-tanzu/velero/pkg/podvolume.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:448" name=eulabeia-5d459bb656-d5qcb
```
