### ISSUE TITLE
Incremental Backup

### ISSUE THREAD

**Issue by adarshyadav15** [vmware-tanzu/velero#3798] opened 2021-05-13 14:31 UTC
I am not sure if Velero has incremental backup with schedules or not. If velero supports incremental backup then I am not able to do it instead it is taking full backup everytime. Thank you for any help in this case.

**Comment by eleanor-millman** [comment] 2021-05-13 21:42
Incremental backup is not currently a Velero feature. It is something that may end up on the roadmap since it is very useful, but it is not planned for the next couple releases.

**Comment by dsu-igeek** [comment] 2021-05-14 19:59
Velero backs up a number of different things.

For the Kubernetes resources, we always back up all of the resources.  This is a fairly small amount of data and it's very difficult to figure out what has changed so this will probably remain a full backup.

For PV data, it depends on the method and platform.  For Restic based backups, Restic essentially does an incremental backup of data.  With volume snapshot plugins it depends on the platform.

@adarshyadav15 What are you seeing as "full backup" behavior?

**Comment by adarshyadav15** [comment] 2021-05-18 07:40
@dsu-igeek  with full backup, what I meant was that I was trying to backup a demo application called nginx and each backup that occurred due to schedule was backing up the entire application each time. But since you already mentioned that velero does not has an incremental backup , I think that`s why the complete application was being backed up each time.

**Comment by zubron** [comment] 2021-07-09 15:46
Thanks for your question here, @adarshyadav15! I'm going to close this as this is working as intended. We don't do incremental backups of the Kubernetes resources and as @dsu-igeek mentioned, incremental backup of volumes is platform dependent.

**Closed by zubron** 2021-07-09 15:46 UTC
Labels: Needs info, Support
