### ISSUE TITLE
Restoration is failing while taking restore for Istio service mesh app.

### ISSUE THREAD

**Issue by rahulgit1988** [vmware-tanzu/velero#2653] opened 2020-06-19 08:55 UTC
**What steps did you take and what happened:**
1- I have some app running on OCP enviorment, Istio service mesh is deployed and side car is injected in each conatiner.
NAME                                  READY   STATUS    RESTARTS   AGE
pod/details-v1-c4cf9fdc8-tksh7        2/2     Running   0          2d
pod/productpage-v1-654b899dbd-2dg6j   2/2     Running   0          2d
pod/ratings-v1-79c78dc7f8-4rnms       2/2     Running   0          2d
pod/reviews-v1-78469854c4-4r8ht       2/2     Running   0          2d
pod/reviews-v2-784796fb4-8x6x8        2/2     Running   0          2d
pod/reviews-v3-894bc755d-vt54l        2/2     Running   0          2d

Deployment:
deployment.apps/details-v1       1/1     1            1           3d
deployment.apps/productpage-v1   1/1     1            1           3d
deployment.apps/ratings-v1       1/1     1            1           3d
deployment.apps/reviews-v1       1/1     1            1           3d
deployment.apps/reviews-v2       1/1     1            1           3d
deployment.apps/reviews-v3       1/1     1            1           3d

2- While taking backup of one of app using --selector, backup become successfufl, 

[core@host ~]$ velero create backup app-productpage-v1 --selector app=productpage-v1

Backup logs are patsed below:

time="2020-06-19T08:18:04Z" level=info msg="Backing up group" backup=velero/app-productpage-v1 group=snapshot.storage.k8s.io/v1beta1 logSource="pkg/backup/group_backupper.go:101"
time="2020-06-19T08:18:04Z" level=info msg="Backing up resource" backup=velero/app-productpage-v1 group=snapshot.storage.k8s.io/v1beta1 logSource="pkg/backup/resource_backupper.go:105" resource=volumesnapshotcontents
time="2020-06-19T08:18:04Z" level=info msg="Listing items" backup=velero/app-productpage-v1 group=snapshot.storage.k8s.io/v1beta1 logSource="pkg/backup/resource_backupper.go:226" namespace= resource=volumesnapshotcontents
time="2020-06-19T08:18:04Z" level=info msg="Retrieved 0 items" backup=velero/app-productpage-v1 group=snapshot.storage.k8s.io/v1beta1 logSource="pkg/backup/resource_backupper.go:240" namespace= resource=volumesnapshotcontents
time="2020-06-19T08:18:04Z" level=info msg="Backing up resource" backup=velero/app-productpage-v1 group=snapshot.storage.k8s.io/v1beta1 logSource="pkg/backup/resource_backupper.go:105" resource=volumesnapshots
time="2020-06-19T08:18:04Z" level=info msg="Listing items" backup=velero/app-productpage-v1 group=snapshot.storage.k8s.io/v1beta1 logSource="pkg/backup/resource_backupper.go:226" namespace= resource=volumesnapshots
time="2020-06-19T08:18:04Z" level=info msg="Retrieved 0 items" backup=velero/app-productpage-v1 group=snapshot.storage.k8s.io/v1beta1 logSource="pkg/backup/resource_backupper.go:240" namespace= resource=volumesnapshots
time="2020-06-19T08:18:04Z" level=info msg="Backing up resource" backup=velero/app-productpage-v1 group=snapshot.storage.k8s.io/v1beta1 logSource="pkg/backup/resource_backupper.go:105" resource=volumesnapshotclasses
time="2020-06-19T08:18:04Z" level=info msg="Listing items" backup=velero/app-productpage-v1 group=snapshot.storage.k8s.io/v1beta1 logSource="pkg/backup/resource_backupper.go:226" namespace= resource=volumesnapshotclasses
time="2020-06-19T08:18:04Z" level=info msg="Retrieved 0 items" backup=velero/app-productpage-v1 group=snapshot.storage.k8s.io/v1beta1 logSource="pkg/backup/resource_backupper.go:240" namespace= resource=volumesnapshotclasses
time="2020-06-19T08:18:04Z" level=info msg="Backing up group" backup=velero/app-productpage-v1 group=extensions/v1beta1 logSource="pkg/backup/group_backupper.go:101"
time="2020-06-19T08:18:04Z" level=info msg="Backing up resource" backup=velero/app-productpage-v1 group=extensions/v1beta1 logSource="pkg/backup/resource_backupper.go:105" resource=ingresses
time="2020-06-19T08:18:04Z" level=info msg="Listing items" backup=velero/app-productpage-v1 group=extensions/v1beta1 logSource="pkg/backup/resource_backupper.go:226" namespace= resource=ingresses
time="2020-06-19T08:18:04Z" level=info msg="Retrieved 0 items" backup=velero/app-productpage-v1 group=extensions/v1beta1 logSource="pkg/backup/resource_backupper.go:240" namespace= resource=ingresses

3- For DR purpose, intensonaly deleted, the deployment of `deployment.apps/productpage-v1

[core@host ~]$ oc delete deployment productpage-v1 -n new-hook
deployment.apps "productpage-v1" deleted
[core@host ~]$ oc get deployment -n new-hook
NAME         READY   UP-TO-DATE   AVAILABLE   AGE
details-v1   1/1     1            1           3d1h
ratings-v1   1/1     1            1           3d1h
reviews-v1   1/1     1            1           3d1h
reviews-v2   1/1     1            1           3d1h
reviews-v3   1/1     1            1           3d1h

While restoring the backup there is problem, Phase: is empty and restore is not initiated/completed. 

[core@host-~]$ velero restore create app-productpage-restore --from-backup app-productpage-v1  --wait
Restore request "app-productpage-restore" submitted successfully.
Waiting for restore to complete. You may safely press ctrl-c to stop waiting - your restore will continue in the background.
Restore completed with status: . You may check for more information using the commands `velero restore describe app-productpage-restore` and `velero restore logs app-productpage-restore`.

Reattaempt:
[core@host ~]$ velero restore create app-productpage-restore --from-backup app-productpage-v1

[core@host- ~]$ velero restore describe app-productpage-restore
Name:         app-productpage-restore
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:

Backup:  app-productpage-v1

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

**What did you expect to happen:**
Restore should be initiated and successfull.

**The output of the following commands will help us better understand what's going on**:
[core@host-192-168-75-38 ~]$ velero restore create app-productpage-restore --from-backup app-productpage-v1
Restore request "app-productpage-restore" submitted successfully.
Run `velero restore describe app-productpage-restore` or `velero restore logs app-productpage-restore` for more details.
[core@host- ~]$ velero restore describe app-productpage-restore
Name:         app-productpage-restore
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:

Backup:  app-productpage-v1

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto
[core@host- ~]$ velero restore logs app-productpage-restore
Restore "app-productpage-restore" does not exist.
[core@host- ~]$

**Anything else you would like to add:**
** Some additional Questions **

1- Is there any wahy to take specific custome resources OR CRDS backup through velero and restore them
for example : Istio service mesh cuctome resurces (Virtualservice, gateway, Destination rules, etc..)
2- What if i need to take backup of specific custom resources (my own CRDs), is there any way in velero, i know that taking that backup of namespace/poject/cluster these resources included, but i want to take backup restore of specific CRDs.

**Environment:**

- Velero version (use `velero version`): 1.3.2
- Velero features (use `velero client config get features`): backup, restore, --selector
- Kubernetes version (use `kubectl version`): latest
- OS (e.g. from `/etc/os-release`): core os

**Comment by ashish-amarnath** [comment] 2020-06-19 22:53
@rahulgit1988 I don't see any error messages in the logs you shared and it is not clear what is the failure you are seeing.
To answer your question though, it is possible to backup and restore custom CRDs using Velero.
Velero uses the Kubernetes discovery API to become aware of the types installed in the cluster during both backup and recovery.

**Comment by rahulgit1988** [comment] 2020-06-22 05:35
In restoration, phase: value is empty

**Comment by rahulgit1988** [comment] 2020-06-22 06:47
> @rahulgit1988 I don't see any error messages in the logs you shared and it is not clear what is the failure you are seeing.
> To answer your question though, it is possible to backup and restore custom CRDs using Velero.
> Velero uses the Kubernetes discovery API to become aware of the types installed in the cluster during both backup and recovery.

I want it for specific Custom Resource, Not for entire namespace contaning the CRDs

**Comment by ashish-amarnath** [comment] 2020-07-30 17:45
@rahulgit1988 Yes, you can include specific resources that you intend to backup. You can use the `includedResources` in the BackupSpec https://velero.io/docs/v1.4/api-types/backup/ to indicate all the resources that should be included in the backup.

**Comment by nrb** [comment] 2020-08-11 18:34
@rahulgit1988 You didn't provide the whole path to the `phase` field, but I'm going to guess that it's somewhere in the `status`.

Right now, Velero clears the `status` field of any object on restore. There's an open request in #1687 to change this behavior, which I think this may be a duplicate of. Is that accurate?

**Comment by dsu-igeek** [comment] 2020-10-22 00:53
Closing this, please re-open if there are still open questions.

**Closed by dsu-igeek** 2020-10-22 00:53 UTC
Labels: Needs info, Question
