### ISSUE TITLE
Verify logrus hooks don't have race conditions

### ISSUE THREAD

**Issue by ncdc** [vmware-tanzu/velero#599] opened 2018-06-25 15:16 UTC
Check to make sure that multiple goroutines logging messages don't have race conditions, especially with the log location hook.

**Comment by skriss** [comment] 2019-04-17 15:26
The version of logrus we're currently using does have a concurrency bug around multiple goroutines logging to the same `*logrus.Entry` and using hooks that mutate the data in the entry.  It *appears* to be fixed in a later version of logrus - doing more testing now.

**Comment by skriss** [comment] 2019-04-17 16:26
Nope, looks like there's still an issue, although some adjacent fixes have been made. Filed an issue: https://github.com/sirupsen/logrus/issues/953

Here's my test that reproduces this issue (intermittently):

```go
func TestLogging(t *testing.T) {
	logger := DefaultLogger(logrus.InfoLevel)
	// logger.ReportCaller = true

	log := logger.WithField("foo", "bar")

	var wg sync.WaitGroup
	for i := 0; i < 10; i++ {
		go func(i int) {
			wg.Add(1)
			defer wg.Done()

			switch i {
			case 0:
				log.Infof("Here %d", i)
				// log.WithField("i", i).Infof("Here %d", i)
			case 1:
				log.Infof("Here %d", i)
				// log.WithField("i", i).Infof("Here %d", i)
			case 2:
				log.Infof("Here %d", i)
				// log.WithField("i", i).Infof("Here %d", i)
			case 3:
				log.Infof("Here %d", i)
				// log.WithField("i", i).Infof("Here %d", i)
			case 4:
				log.Infof("Here %d", i)
				// log.WithField("i", i).Infof("Here %d", i)
			case 5:
				log.Infof("Here %d", i)
				// log.WithField("i", i).Infof("Here %d", i)
			case 6:
				log.Infof("Here %d", i)
				// log.WithField("i", i).Infof("Here %d", i)
			case 7:
				log.Infof("Here %d", i)
				// log.WithField("i", i).Infof("Here %d", i)
			case 8:
				log.Infof("Here %d", i)
				// log.WithField("i", i).Infof("Here %d", i)
			case 9:
				log.Infof("Here %d", i)
				// log.WithField("i", i).Infof("Here %d", i)
			}
		}(i)
	}

	wg.Wait()
	<-time.After(100 * time.Millisecond)
}
```

**Comment by skriss** [comment] 2019-04-17 16:27
Somewhat related, newer versions of logrus have built-in support for capturing log locations, which we should switch to. That code doesn't seem to be impacted by this race condition. It won't totally solve the issue for us, though, as we have other mutating hooks.

**Comment by skriss** [comment] 2019-06-12 15:23
Moving this back to "New Issues" as there's no active work being done on it. We should follow up on the upstream bug if/when this becomes critical.

**Closed** 2021-05-03 20:57 UTC
Labels: Enhancement/Dev, P2 - Long-term important
